### ISSUE TITLE
pb-assembly falcon does not run with slurm

### ISSUE THREAD

**Issue by roblehmann** [PacificBiosciences/pbbioconda#10]
**Operating system**
CentOS Linux release 7.3.1611

**Package name**
pb-assembly installed today via anaconda

**Describe the bug**
I am trying to configure falcon for slurm, but keep getting the error message: `TypeError: object.__init__() takes no parameters` -  see below

**Error message**
```
[INFO] starting job Job(jobid='Pe1c6df12cc584e', cmd='/bin/bash run.sh', rundir='/home/lehmanr/melpacbio/0-assembly/newFalcon/0-rawreads/build', options={'JOB_QUEUE': 'batch', 'pwatcher_type': '', 'use_tmpdir': False, 'MB': 4000, 'job_type': 'slurm', 'submit': 'sbatch  \\\n-p ${JOB_QUEUE}     \\\n--job-name=${JOB_NAME}      \\\n-o "${JOB_STDOUT}"  \\\n-e "${JOB_STDERR}"  \\\n--cpus-per-task ${NPROC}    \\\n--mem ${MB}    \\\n--time ${time} \\\n--nodes 1 --ntasks 1 \\\n"${JOB_SCRIPT}"', 'NPROC': 1, 'njobs': '32'}) w/ job_type=SLURM
Traceback (most recent call last):
  File "/home/lehmanr/.conda/envs/denovo_asm/bin/fc_run.py", line 11, in <module>
    load_entry_point('falcon-kit==1.2.2', 'console_scripts', 'fc_run.py')()
  File "/home/lehmanr/.conda/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 724, in main
    main1(argv[0], args.config, args.logger)
  File "/home/lehmanr/.conda/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 76, in main1
    input_fofn_fn=input_fofn_fn,
  File "/home/lehmanr/.conda/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 242, in run
    dist=Dist(NPROC=4, MB=4000, job_dict=config['job.step.da']),
  File "/home/lehmanr/.conda/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/pype.py", line 106, in gen_parallel_tasks
    wf.refreshTargets()
  File "/home/lehmanr/.conda/envs/denovo_asm/lib/python2.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 277, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/home/lehmanr/.conda/envs/denovo_asm/lib/python2.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 316, in _refreshTargets
    unsubmitted = set(self.tq.enque(to_submit)) # In theory, this traps exceptions.
  File "/home/lehmanr/.conda/envs/denovo_asm/lib/python2.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 152, in enque
    result = self.watcher.run(**watcher_args)
  File "/home/lehmanr/.conda/envs/denovo_asm/lib/python2.7/site-packages/pwatcher/fs_based.py", line 650, in run
    return cmd_run(self.state, jobids, job_type, job_defaults_dict)
  File "/home/lehmanr/.conda/envs/denovo_asm/lib/python2.7/site-packages/pwatcher/fs_based.py", line 453, in cmd_run
    bjob = MetaJobSlurm(mjob)
  File "/home/lehmanr/.conda/envs/denovo_asm/lib/python2.7/site-packages/pwatcher/fs_based.py", line 398, in __init__
    super(MetaJobSlurm, self).__init__(mjob)
TypeError: object.__init__() takes no parameters
```

**To Reproduce**
My relevant fc_run.cfg:

```
[job.defaults]
job_type=slurm
pwatcher_type=
JOB_QUEUE=batch
MB=32768
NPROC=6
njobs=32
time=08:00:00
submit = sbatch  \
  -p ${JOB_QUEUE}     \
  --job-name=${JOB_NAME}      \
  -o "${JOB_STDOUT}"  \
  -e "${JOB_STDERR}"  \
  --cpus-per-task ${NPROC}    \
  --mem ${MB}    \
  --time ${time} \
  --nodes 1 --ntasks 1 \
  "${JOB_SCRIPT}"
```

**Comment by gconcepcion** [comment]
Hi Rob,

You should set `pwatcher_type=blocking`
The default value of `fs_based` is sometimes difficult to debug and can be problematic w/ high latency file systems.

See this page for reference:
https://github.com/PacificBiosciences/pypeFLOW/wiki/configuration

**Comment by gconcepcion** [comment]
Is there anything in the stderr here:
`0-rawreads/tan-split/run-*.stderr`?

I have no experience with Slurm, but did you try using `srun` instead of `sbatch` as described in the pypeFLOW wiki [here](https://github.com/PacificBiosciences/pypeFLOW/wiki/configuration)?

**Comment by roblehmann** [comment]
Great, using `pwatcher_type=blocking` and srun together works! However, I just realized that the problem was not our cluster but the configuration with which each job gets submitted. As you can see in the log below, the values for MB and NPROC are correctly configured in the parameter dictionary, but the assembled job submission string has the default values in it: 
--cpus-per-task=1  --mem-per-cpu=4000M 

I suppose I could hard code the parameters in the submission string, but that wouldn't be very elegant.

```
[INFO]In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.blocking' from '/home/lehmanr/.conda/envs/denovo_asm/lib/python2.7/site-packages/pwatcher/blocking.pyc'>
[INFO]job_type='slurm', (default)job_defaults={'JOB_QUEUE': 'batch', 'pwatcher_type': 'blocking', 'use_tmpdir': False, 'MB': '32768', 'time': '08:00:00', 'job_type': 'slurm', 'submit': 'srun --wait=0  \\\n-p ${JOB_QUEUE}     \\\n--job-name=${JOB_NAME}      \\\n-o "${JOB_STDOUT}"  \\\n-e "${JOB_STDERR}"  \\\n--cpus-per-task=${NPROC}    \\\n--mem-per-cpu=${MB}M    \\\n--time ${time} \\\n--nodes 1 --ntasks 1 \\\n"${JOB_SCRIPT}"', 'NPROC': '6', 'njobs': '32'}, use_tmpdir=False, squash=False, job_name_style=0
[INFO]Setting max_jobs to 32; was None
[INFO]Num unsatisfied: 2, graph: 2
[INFO]About to submit: Node(0-rawreads/build)
[INFO]Popen: 'srun --wait=0  \
-p batch     \
--job-name=Pe1c6df12cc584e      \
-o "/home/lehmanr/melpacbio/0-assembly/newFalcon/0-rawreads/build/run-Pe1c6df12cc584e.bash.stdout"  \
-e "/home/lehmanr/melpacbio/0-assembly/newFalcon/0-rawreads/build/run-Pe1c6df12cc584e.bash.stderr"  \
--cpus-per-task=1    \
--mem-per-cpu=4000M    \
--time 08:00:00 \
--nodes 1 --ntasks 1 \
"/home/lehmanr/.conda/envs/denovo_asm/lib/python2.7/site-packages/pwatcher/mains/job_start.sh"'
```

**Comment by gconcepcion** [comment]
Yes, the first step building the database is hard coded to `MB=4000M` and `NPROC=1` because this step is just a DB building step and shouldn't really need a resource re-configuration.

Let us know if you find otherwise. The rest of the pipeline should be picking up the parameters appropriately.

**Comment by zrlewis** [comment]
@roblehmann 

Would you be able to post your full `.cfg` script that worked for you on your SLURM system?

Thanks in advance! Zack
