### ISSUE TITLE
Crash during build stage

### ISSUE THREAD

**Issue by asrivathsan** [PacificBiosciences/pbbioconda#105]
Hi, 

I just started running falcon on a mammalian genome. I am using the human genome cfg file as the template. The run started off fine but it right after the first step (I installed it today using Conda environment)
```py
[INFO](slept for another 500.0s -- another 50 loop iterations)
[ERROR]Task Node(0-rawreads/build) failed with exit-code=1
[ERROR]Some tasks are recently_done but not satisfied: set([Node(0-rawreads/build)])
[ERROR]ready: set([])
        submitted: set([])
[ERROR]Noop. We cannot kill blocked threads. Hopefully, everything will die on SIGTERM.
Traceback (most recent call last):
  File "/home/asrivathsan/.conda/envs/denovo_asm/bin/fc_run", line 11, in <module>
    load_entry_point('falcon-kit==1.2.6', 'console_scripts', 'fc_run')()
  File "/home/asrivathsan/.conda/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 726, in main
    main1(argv[0], args.config, args.logger)
  File "/home/asrivathsan/.conda/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 76, in main1
    input_fofn_fn=input_fofn_fn,
  File "/home/asrivathsan/.conda/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 242, in run
    dist=Dist(NPROC=4, MB=4000, job_dict=config['job.step.da']),
  File "/home/asrivathsan/.conda/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/pype.py", line 106, in gen_parallel_tasks
    wf.refreshTargets()
  File "/home/asrivathsan/.local/lib/python2.7/site-packages/pypeflow-2.1.1-py2.7.egg/pypeflow/simple_pwatcher_bridge.py", line 278, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/home/asrivathsan/.local/lib/python2.7/site-packages/pypeflow-2.1.1-py2.7.egg/pypeflow/simple_pwatcher_bridge.py", line 362, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: set([Node(0-rawreads/build)])
```
I noted that the error messages are usually in respective build directory, but I can't seem to note any error there. I am attaching it here.

[run-P0f9090629c8e2e.bash.stderr.txt](https://github.com/PacificBiosciences/pbbioconda/files/2952050/run-P0f9090629c8e2e.bash.stderr.txt)

**Comment by pb-cdunn** [comment]
You will need to run the task yourself and observe the result. It seems to crash on
```
DBdust  raw_reads
```
You might be able to debug that yourself somehow. You could try `DBshow raw_reads` or `DBdump -rh raw_reads`. Or `cat raw_reads.db` or `input.fofn`.

We run something like this:
```sh
while read fn; do  cat  ${fn} | python -m falcon_kit.mains.fasta_filter ${zmw_whitelist_option} streamed-internal-median - | fasta2DB -v raw_reads -i${fn##*/}; done < my.input.fofn
+ read fn
+ cat ../../data/greg200k-sv2/subreads1.fasta
+ python -m falcon_kit.mains.fasta_filter streamed-internal-median -
+ fasta2DB -v raw_reads -isubreads1.fasta

```
But in your `stderr`, I see this:
```
+ read fn
+ cat ../../test/m54077_180418_080904.fasta
+ python -m falcon_kit.mains.fasta_filter streamed-median -
+ fasta2DB -v raw_reads -im54077_180418_080904.fasta
falcon-kit 1.2.6
pypeflow 2.1.1
INFO:root:Counting bytes from "None"
INFO:root:        #1 count=          8,521 
INFO:root:        #2 count=         20,565 
Adding 'm54077_180418_080904.fasta.fasta' ...
...
```
Why does it say `.fasta.fasta`? You'll need to debug that yourself, unfortunately.

 In the meantime, what is the output of `conda list`? The problem could be a wrong version of some software component (though we have never seen this before), possibly `fasta2DB`. Try `which fasta2DB`. It should come from **pb-dazzler**:
```
pb-assembly               0.0.4                    py27_6    bioconda
pb-dazzler                0.0.0                h470a237_0    bioconda
pb-falcon                 0.2.6            py27hc0aa232_3    bioconda
```

**Comment by asrivathsan** [comment]
Thanks for the reply,

I tried DBshow raw_reads and looked at the resulting output, it seems to be reading fine... I will try to see what else I can do but meanwhile sharing the rest:

"which fasta2DB" output is

~/.conda/envs/denovo_asm/bin/fasta2DB

and Conda list output is attached.
 
Could I know how pb-dazzler is associated with fasta2DB in path?

[condalist.txt](https://github.com/PacificBiosciences/pbbioconda/files/2954856/condalist.txt)

**Comment by asrivathsan** [comment]
Hi I changed a few things, I recalled the fasta using dextractor and in .cfg files tried both pa_DBdust_option=... and pa_DBdust_option=true

Now I get the following error message, thanks for looking into this.:

Usage: DBdust [-b] [-w<int(64)>] [-t<double(2.)>] [-m<int(10)>] <path:db|dam>

      -w: DUST algorithm window size.
      -t: DUST algorithm threshold.
      -m: Record only low-complexity intervals >= this size.
      -b: Take into account base composition bias.
[WARNING]Call 'bash -vex build_db.sh' returned 256.
Traceback (most recent call last):
  File "/home/asrivathsan/.conda/envs/denovo_asm/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/asrivathsan/.conda/envs/denovo_asm/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/asrivathsan/.conda/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/mains/dazzler.py", line 1443, in <module>
    main()
  File "/home/asrivathsan/.conda/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/mains/dazzler.py", line 1439, in main
    args.func(args)
  File "/home/asrivathsan/.conda/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/mains/dazzler.py", line 985, in cmd_build
    build_db(ours, args.input_fofn_fn, args.db_fn, args.length_cutoff_fn)
  File "/home/asrivathsan/.conda/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/mains/dazzler.py", line 167, in build_db
    io.syscall('bash -vex {}'.format(script_fn))
  File "/home/asrivathsan/.local/lib/python2.7/site-packages/pypeflow-2.1.1-py2.7.egg/pypeflow/io.py", line 29, in syscall
    raise Exception(msg)
Exception: Call 'bash -vex build_db.sh' returned 256.
2019-03-12 20:01:14,436 - root - WARNING - Call '/bin/bash user_script.sh' returned 256.
2019-03-12 20:01:14,437 - root - WARNING - CD: '/mnt/projects/asrivathsan/test/0-rawreads/build' -> '/mnt/projects/asrivathsan/test/reads/build'
2019-03-12 20:01:14,438 - root - WARNING - CD: '/mnt/projects/asrivathsan/test/0-rawreads/build' -> '/mnt/projects/asrivathsan/test/0-rawreads/build'
2019-03-12 20:01:14,439 - root - CRITICAL - Error in /home/asrivathsan/.local/lib/python2.7/site-packages/pypeflow-2.1.1-py2.7.egg/pypeflow/do_task.py with args="{'json_fn': '/mnt/projects/asrivathsan/test/0-rawreads/build/task.json',\n 'timeout': 30,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/home/asrivathsan/.conda/envs/denovo_asm/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/asrivathsan/.conda/envs/denovo_asm/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/asrivathsan/.local/lib/python2.7/site-packages/pypeflow-2.1.1-py2.7.egg/pypeflow/do_task.py", line 267, in <module>
    main()
  File "/home/asrivathsan/.local/lib/python2.7/site-packages/pypeflow-2.1.1-py2.7.egg/pypeflow/do_task.py", line 259, in main
    run(**vars(parsed_args))
  File "/home/asrivathsan/.local/lib/python2.7/site-packages/pypeflow-2.1.1-py2.7.egg/pypeflow/do_task.py", line 253, in run
    run_cfg_in_tmpdir(cfg, tmpdir, '.')
  File "/home/asrivathsan/.local/lib/python2.7/site-packages/pypeflow-2.1.1-py2.7.egg/pypeflow/do_task.py", line 228, in run_cfg_in_tmpdir
    run_bash(bash_template, myinputs, myoutputs, parameters)
  File "/home/asrivathsan/.local/lib/python2.7/site-packages/pypeflow-2.1.1-py2.7.egg/pypeflow/do_task.py", line 187, in run_bash
    util.system(cmd)
  File "/home/asrivathsan/.local/lib/python2.7/site-packages/pypeflow-2.1.1-py2.7.egg/pypeflow/io.py", line 29, in syscall
    raise Exception(msg)
Exception: Call '/bin/bash user_script.sh' returned 256.
pwd) (If you see -terminal database is inaccessible- you are using the python bin-wrapper, so you will not get diagnostic info. No big deal. This process is crashing anyway.)"
pwd) (If you see -terminal database is inaccessible- you are using the python bin-wrapper, so you will not get diagnostic info. No big deal. This process is crashing anyway.)
pwd

**Comment by pb-cdunn** [comment]
```
Could not extract name and version from: 'avro             1.8.2'
...
```
I don't know what's going on with those warnings. I never see that.

```
pb-assembly               0.0.4                    py27_6    bioconda
pb-dazzler                0.0.0                h470a237_0    bioconda
pb-falcon                 0.2.6            py27hc0aa232_3    bioconda
```
That seems fine.
```
% which fasta2DB
~/.conda/envs/denovo_asm/bin/fasta2DB
```
That seems fine too. Still mysterious.

> Hi I changed a few things, I recalled the fasta using dextractor ...

Could you explain? It could be helpful for other users.

> pa_DBdust_option=... and pa_DBdust_option=true

Those are options passed along to `DBdust`, not booleans.
