### ISSUE TITLE
fc_run ERROR: CRITICAL - Error in ...

### ISSUE THREAD

**Issue by xiaoyezao** [PacificBiosciences/pbbioconda#111]
**Operating system**
Red Hat Enterprise Linux Server release 6.5 (Santiago)

**Package name**
pb_assembly

**Conda environment**
falcon-kit 1.2.6; pypeflow 2.1.1

**Describe the bug**
I run fc_run with the example data from [https://github.com/PacificBiosciences/pb-assembly] in a cluster . The cfg file is:
[fc_run_200kb.cfg.txt](https://github.com/PacificBiosciences/pbbioconda/files/2973880/fc_run_200kb.cfg.txt)

I got the error message in the stderr file: 

**Error message**
```
pypeflow 2.1.1
pypeflow 2.1.1
    raise Exception(msg)
Exception: Call 'bash -vex build_db.sh' returned 256.
2019-03-16 15:04:37,109 - root - WARNING - Call '/bin/bash user_script.sh' returned 256.
2019-03-16 15:04:37,109 - root - WARNING - CD: '/BIGDATA1/wbgcas_tfeng_1/project/pb_assembly_test/result/0-rawreads/build' -> '/BIGDATA1/wbgcas_tfeng_1/project/pb_assembly_test/result/0-rawreads/build'
2019-03-16 15:04:37,109 - root - WARNING - CD: '/BIGDATA1/wbgcas_tfeng_1/project/pb_assembly_test/result/0-rawreads/build' -> '/BIGDATA1/wbgcas_tfeng_1/project/pb_assembly_test/result/0-rawreads/build'
2019-03-16 15:04:37,109 - root - CRITICAL - Error in /BIGDATA1/app/anaconda2/5.0.1-gcc-4.8.5/lib/python2.7/site-packages/pypeflow/do_task.py with args="{'json_fn': '/BIGDATA1/wbgcas_tfeng_1/project/pb_assembly_test/result/0-rawreads/build/task.json',\n 'timeout': 30,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/BIGDATA1/app/anaconda2/5.0.1-gcc-4.8.5/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/BIGDATA1/app/anaconda2/5.0.1-gcc-4.8.5/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/BIGDATA1/app/anaconda2/5.0.1-gcc-4.8.5/lib/python2.7/site-packages/pypeflow/do_task.py", line 267, in <module>
    main()
  File "/BIGDATA1/app/anaconda2/5.0.1-gcc-4.8.5/lib/python2.7/site-packages/pypeflow/do_task.py", line 259, in main
    run(**vars(parsed_args))
  File "/BIGDATA1/app/anaconda2/5.0.1-gcc-4.8.5/lib/python2.7/site-packages/pypeflow/do_task.py", line 253, in run
    run_cfg_in_tmpdir(cfg, tmpdir, '.')
  File "/BIGDATA1/app/anaconda2/5.0.1-gcc-4.8.5/lib/python2.7/site-packages/pypeflow/do_task.py", line 228, in run_cfg_in_tmpdir
    run_bash(bash_template, myinputs, myoutputs, parameters)
  File "/BIGDATA1/app/anaconda2/5.0.1-gcc-4.8.5/lib/python2.7/site-packages/pypeflow/do_task.py", line 187, in run_bash
    util.system(cmd)
  File "/BIGDATA1/app/anaconda2/5.0.1-gcc-4.8.5/lib/python2.7/site-packages/pypeflow/io.py", line 29, in syscall
    raise Exception(msg)
```
How can I fix this?

Thanks

**Comment by pb-cdunn** [comment]
For some reason, your `stderr` does not have all the stack-traces we would need. Go into `0-rawreads/build/` and run `bash -vex user_script.sh`.  Hopefully, that will help you debug this. 

Since the first task is failing, you're probably missing the conda env's `bin` from your environment on the remote machine. To fix that, you need to learn the proper flag for submitting the job and passing along the environment. (If that's impossible on your system, we can show you a hidden flag to run custom bash code in each remote job.)

**Comment by xiaoyezao** [comment]
> For some reason, your `stderr` does not have all the stack-traces we would need. Go into `0-rawreads/build/` and run `bash -vex user_script.sh`. Hopefully, that will help you debug this.
> 
> Since the first task is failing, you're probably missing the conda env's `bin` from your environment on the remote machine. To fix that, you need to learn the proper flag for submitting the job and passing along the environment. (If that's impossible on your system, we can show you a hidden flag to run custom bash code in each remote job.)

Hi, thanks for your reply.

This is the complete stderr file:
[Uploading run-P6fb1b878b6327d.bash.stderr.txt…]()

and this the output of "bash -vex user_script.sh"
[bash -vex user_script.sh.txt](https://github.com/PacificBiosciences/pbbioconda/files/2975261/bash.-vex.user_script.sh.txt)

I have no idea what's going wrong from this.

How do I know wehther I am missing the conda env's 'bin'?  In our cluster, the pb_assembly package was installed by the administrator. I just load the package by "module load" command.

**Comment by pb-cdunn** [comment]
> How do I know whehther I am missing the conda env's 'bin'?

Hard to say. It worked when you ran it manually, so it's possible. But I think the problem is something else.

```
fasta2DB: [WARNING] Could not delete temporary file subreads1.fasta
```
That's odd. But stranger is this:
```
+ read fn
+ fasta2DB -v raw_reads -isubreads2.fasta
+ python -m falcon_kit.mains.fasta_filter pass -
+ cat /BIGDATA1/wbgcas_tfeng_1/project/pb_assembly_test/fasta/subreads2.fasta
fasta2DB: raw_reads.db is corrupted, read failed
```
The mixed lines of stderr indicate that multiple procs are running. They seem to be writing into the DB simultaneously.

This task is not parallel, and it has no "units of work". So something very strange is going on...

I see repetition even at the top of your stderr, e.g. setting our bash variables. So I think your job has been submitted as multiple jobs piped into the same stderr.

This is a problem either with your job submission system or with your "submit" line.
```
submit = srun --wait=0 -p ${JOB_QUEUE} -J ${JOB_NAME} -o ${JOB_STDOUT} -e ${JOB_STDERR} --mem-per-cpu=${MB}M --cpus-per-task=${NPROC} ${JOB_SCRIPT}
```
You will need to talk to your sysadmin. This does not appear to be a Falcon bug at all.
