### ISSUE TITLE
pb-assembly failing/stalling in cns-runs

### ISSUE THREAD

**Issue by Ashleyfarlow** [PacificBiosciences/pbbioconda#113]
I'm trying to assembly at ~40x human genome (pacbio reads) and pb-assemble is hitting an error and stalling (the job has not exited for some reason despite no activity and clear errors in the log) and the cns-runs stage. 

The tail of the log points to an error with cns-runs:
```
[INFO]Num satisfied in this iteration: 1
[INFO]Num still unsatisfied: 410
[INFO]About to submit: Node(0-rawreads/cns-runs/cns_00111)
[INFO]Popen: '/bin/bash -C /short/te53/af3298/miniconda3/lib/python2.7/site-packages/pwatcher/mains/job_start.sh >| /g/data1a/te53/longread.assembly/falcon.assembly/ELD103313/local.2/0-rawreads/cns-runs/cns_00111/run-P3017f7ec493978.bash.stdout 2>| /g/data1a/te53/longread.assembly/falcon.assembly/ELD103313/local.2/0-rawreads/cns-runs/cns_00111/run-P3017f7ec493978.bash.stderr'
[INFO](slept for another 3.7s -- another 11 loop iterations)
[INFO](slept for another 12.6s -- another 12 loop iterations)
[INFO](slept for another 29.9s -- another 13 loop iterations)
[INFO](slept for another 51.1s -- another 14 loop iterations)
[INFO](slept for another 76.5s -- another 15 loop iterations)
[INFO](slept for another 106.4s -- another 16 loop iterations)
[INFO](slept for another 141.1s -- another 17 loop iterations)
[INFO](slept for another 176.5s -- another 18 loop iterations)
[INFO](slept for another 190.0s -- another 19 loop iterations)
[INFO](slept for another 200.0s -- another 20 loop iterations)
[INFO](slept for another 210.0s -- another 21 loop iterations)
[INFO](slept for another 220.0s -- another 22 loop iterations)
[INFO](slept for another 230.0s -- another 23 loop iterations)
[INFO](slept for another 240.0s -- another 24 loop iterations)
[ERROR]Task Node(0-rawreads/cns-runs/cns_00085) failed with exit-code=1
[ERROR]Some tasks are recently_done but not satisfied: set([Node(0-rawreads/cns-runs/cns_00085)])
```
The problem appears might be at `INFO:root:Started a worker in 327293 from parent 323084` because this and subsequent processes are getting killed. 0-rawreads/cns-runs/cns_00085/run-Pbb823f5c6fdae4.bash.stderr
```
[323679]starting get_consensus_without_trim(<list(54 elem), '01992071', <4, 8, 200, 0.7, 1000, 50, 10, 0>>)
[323679]maxrss:    14672
[323681]starting get_consensus_without_trim(<list(49 elem), '01992072', <4, 8, 200, 0.7, 1000, 50, 10, 0>>)
[323681]maxrss:    14672
[323684]starting get_consensus_without_trim(<list(200 elem), '01992076', <4, 8, 200, 0.7, 1000, 50, 10, 0>>)
[323684]maxrss:    14620
INFO:root:Started a worker in 327290 from parent 323084
[327290]starting get_consensus_without_trim(<list(19 elem), '01992079', <4, 8, 200, 0.7, 1000, 50, 10, 0>>)
[327290]maxrss:  9169696
INFO:root:Started a worker in 327291 from parent 323084
[327291]starting get_consensus_without_trim(<list(26 elem), '01992080', <4, 8, 200, 0.7, 1000, 50, 10, 0>>)
[327291]maxrss:  9170324
INFO:root:Started a worker in 327293 from parent 323084
[327293]starting get_consensus_without_trim(<list(25 elem), '01992081', <4, 8, 200, 0.7, 1000, 50, 10, 0>>)
[327293]maxrss:  9169972
INFO:root:Started a worker in 327296 from parent 323084
[327296]starting get_consensus_without_trim(<list(45 elem), '01992082', <4, 8, 200, 0.7, 1000, 50, 10, 0>>)
[327296]maxrss:  9169100
run_consensus.sh: line 6: 323083 Done                    LA4Falcon -H$CUTOFF -of raw_reads.db /g/data1a/te53/longread.assembly/falcon.assembly/ELD103313/local.2/0-rawreads/cns-split/cns-symlinks/cns_00085/merged.cns_00085.las
     323084 Killed                  | python -m falcon_kit.mains.consensus --output-multi --min-idt 0.70 --min-cov 4 --max-n-read 200 --n-core=32 >|consensus.cns_00085.fasta.tmp
WARNING:root:Call 'bash -vex run_consensus.sh' returned 35072.
Traceback (most recent call last):
  File "/short/te53/af3298/miniconda3/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/short/te53/af3298/miniconda3/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/short/te53/af3298/miniconda3/lib/python2.7/site-packages/falcon_kit/mains/consensus_task.py", line 197, in <module>
    main()
  File "/short/te53/af3298/miniconda3/lib/python2.7/site-packages/falcon_kit/mains/consensus_task.py", line 193, in main
    run(**vars(args))
  File "/short/te53/af3298/miniconda3/lib/python2.7/site-packages/falcon_kit/mains/consensus_task.py", line 148, in run
    io.syscall('bash -vex {}'.format(script_fn))
  File "/short/te53/af3298/miniconda3/lib/python2.7/site-packages/pypeflow/io.py", line 29, in syscall
    raise Exception(msg)
Exception: Call 'bash -vex run_consensus.sh' returned 35072.
WARNING:root:Call '/bin/bash user_script.sh' returned 256.
WARNING:root:CD: 'uow-00' -> '/g/data1a/te53/longread.assembly/falcon.assembly/ELD103313/local.2/0-rawreads/cns-runs/cns_00085'
```
I'm running in local mode on a PBSpro HPC. fc_run.local.cfg:
```
#### Input
[General]
input_fofn=input.fofn
input_type=raw
pa_DBdust_option=
pa_fasta_filter_option=streamed-median
target=assembly
skip_checks=False
LA4Falcon_preload=false

#### Data Partitioning
pa_DBsplit_option=-x500 -s400
ovlp_DBsplit_option=-s400

#### Repeat Masking
pa_HPCTANmask_option=
#no-op repmask param set
pa_REPmask_code=0,300;0,300;0,300

####Pre-assembly
length_cutoff=5000 
pa_HPCdaligner_option=-v -B128 -M16
pa_daligner_option= -k18 -e0.75 -l5000 -h256 -w8 -s100
falcon_sense_option=--output-multi --min-idt 0.70 --min-cov 4 --max-n-read 200
falcon_sense_greedy=False

####Pread overlapping
ovlp_HPCdaligner_option=-v -B128 -M16
ovlp_daligner_option=-k24 -e.92 -6000 -h600 -s100

####Final Assembly
length_cutoff_pr=10000
overlap_filtering_setting=--max-diff 100 --max-cov 100 --min-cov 2
fc_ovlp_to_graph_option=

[job.defaults]
pwatcher_type = blocking
job_type=local
submit = /bin/bash -C ${CMD} >| ${STDOUT_FILE} 2>| ${STDERR_FILE}
njobs=32

[job.step.da]
NPROC=32
MB=16000
njobs=32
[job.step.la]
NPROC=32
MB=16000
njobs=32
[job.step.cns]
NPROC=32
MB=16000
njobs=32
[job.step.pda]
NPROC=32
MB=16000
njobs=32
[job.step.pla]
NPROC=32
MB=16000
njobs=32
[job.step.asm]
NPROC=32
MB=512000
njobs=1
```

**Comment by pb-cdunn** [comment]
"killed" typically means out-of-memory. You might have to use smaller blocks.

But try to investigate that specific task first. Go into the directory of a failed run and find the `LA4Falcon` command. Then run that yourself and see how much memory it consumes and how long it takes.
