### ISSUE TITLE
Falcon fails in 0-rawreads/tan-runs/

### ISSUE THREAD

**Issue by mycecilia** [PacificBiosciences/pbbioconda#125]
I tried falcon multiple times and always failed in 0-rawreads/tan-runs step. When I used only a small proportion of the real data, some of the tan-runs succeeded but still failed eventually on other chunks.

Any help is greatly appreciated!

This is the error file from 0-rawreads/tan-runs/tan_013 [run-P2d88a2c0762e02.bash.stderr.txt](https://github.com/PacificBiosciences/pbbioconda/files/3070267/run-P2d88a2c0762e02.bash.stderr.txt) I was able replicate the error by running bash user_script.sh in the tmp/pypetmp/0-rawreads/tan-runs/tan_013 folder. Error started at

```
LAsort ./datander.41989/raw_reads.56.T@.las
LAmerge TAN.raw_reads.56.las ./datander.41989/raw_reads.56.T@.S.las
LAcheck raw_reads TAN.raw_reads.53.las TAN.raw_reads.54.las TAN.raw_reads.55.las TAN.raw_reads.56.las
+ LAcheck raw_reads TAN.raw_reads.53.las TAN.raw_reads.54.las TAN.raw_reads.55.las TAN.raw_reads.56.las
[WARNING]Call 'bash -vex run_datander.sh' returned 256.
Traceback (most recent call last):
  File "/software/anaconda2/5.0.1/lssc0-linux/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/software/anaconda2/5.0.1/lssc0-linux/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/afs/genomecenter.ucdavis.edu/software/anaconda2/5.0.1/lssc0-linux/lib/python2.7/site-packages/falcon_kit/mains/dazzler.py", line 1443, in <module>
    main()
  File "/afs/genomecenter.ucdavis.edu/software/anaconda2/5.0.1/lssc0-linux/lib/python2.7/site-packages/falcon_kit/mains/dazzler.py", line 1439, in main
    args.func(args)
  File "/afs/genomecenter.ucdavis.edu/software/anaconda2/5.0.1/lssc0-linux/lib/python2.7/site-packages/falcon_kit/mains/dazzler.py", line 990, in cmd_tan_apply
    tan_apply(args.db_fn, args.script_fn, args.job_done_fn)
  File "/afs/genomecenter.ucdavis.edu/software/anaconda2/5.0.1/lssc0-linux/lib/python2.7/site-packages/falcon_kit/mains/dazzler.py", line 355, in tan_apply
    io.syscall('bash -vex {}'.format(os.path.basename(script_fn)))
  File "/software/anaconda2/5.0.1/lssc0-linux/lib/python2.7/site-packages/pypeflow/io.py", line 29, in syscall
    raise Exception(msg)
Exception: Call 'bash -vex run_datander.sh' returned 256.

```

It seems all the input files are in place. build/, run-split/ and run-chunks/ were done successfully. I don't know how to proceed from here. 

my cfg file:
```
[General]
input_fofn = input.fofn
input_type = raw 

pa_fasta_filter_option=pass
pa_DBsplit_option = -a -x500 -s200
ovlp_DBsplit_option = -a -x500 -s200

ovlp_HPCTANmask_option = 
pa_REPmask_code = 0,300;0,300;0,300

genome_size = 800000000
seed_coverage = 60
length_cutoff = -1
length_cutoff_pr = 1500

pa_HPCdaligner_option = -v -B4 -M16
pa_daligner_option =  -e.70 -l1000 -s1000  

falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --local_match_count_threshold 2 --max_n_read 200 --n_core 6
falcon_sense_skip_contained = False

ovlp_HPCdaligner_option = -v -B4 -M32 
ovlp_daligner_option = -h60 -e.96 -l500 -s1000

overlap_filtering_setting = --max_diff 100 --max_cov 100 --min_cov 20 --bestn 10
[job.defaults]
njobs = 12
use_tmpdir = ./tmp
stop_all_jobs_on_failure = true
job_type = slurm
job_type = string
pwatcher_type = blocking

submit = srun -J ${JOB_ID} -o ${JOB_STDOUT} -e ${JOB_STDERR} --time=10:00:00 --mem=100g --cpus-per-task=${NPROC} --partition=production ${JOB_SCRIPT}

[job.step.da]
NPROC=8
[job.step.la]
NPROC=8
[job.step.cns]
NPROC=12
[job.step.pda]
NPROC=8
[job.step.pla]
NPROC=8
[job.step.asm]
NPROC=24
```

**Comment by pb-cdunn** [comment]
Typically, this is due to out-of-memory.

Try
```
cd -rawreads/tan-runs/tan_013/
bash -vex user_script.sh
```
If that works, try to watch peak memory while you run. Then adjust pypeflow settings. Or if it fails, maybe you can debug there.

**Comment by mycecilia** [comment]
I ran 0-rawreads/tan-runs/tan_013/user_script.sh as you advised. It failed and gave the same error message.

```
LAsort ./datander.36587/raw_reads.56.T@.las
LAmerge TAN.raw_reads.56.las ./datander.36587/raw_reads.56.T@.S.las
LAcheck raw_reads TAN.raw_reads.53.las TAN.raw_reads.54.las TAN.raw_reads.55.las TAN.raw_reads.56.las
+ LAcheck raw_reads TAN.raw_reads.53.las TAN.raw_reads.54.las TAN.raw_reads.55.las TAN.raw_reads.56.las
[WARNING]Call 'bash -vex run_datander.sh' returned 256.
Traceback (most recent call last):
  File "/software/anaconda2/5.0.1/lssc0-linux/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/software/anaconda2/5.0.1/lssc0-linux/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/afs/genomecenter.ucdavis.edu/software/anaconda2/5.0.1/lssc0-linux/lib/python2.7/site-packages/falcon_kit/mains/dazzler.py", line 1443, in <module>
    main()
  File "/afs/genomecenter.ucdavis.edu/software/anaconda2/5.0.1/lssc0-linux/lib/python2.7/site-packages/falcon_kit/mains/dazzler.py", line 1439, in main
    args.func(args)
  File "/afs/genomecenter.ucdavis.edu/software/anaconda2/5.0.1/lssc0-linux/lib/python2.7/site-packages/falcon_kit/mains/dazzler.py", line 990, in cmd_tan_apply
    tan_apply(args.db_fn, args.script_fn, args.job_done_fn)
  File "/afs/genomecenter.ucdavis.edu/software/anaconda2/5.0.1/lssc0-linux/lib/python2.7/site-packages/falcon_kit/mains/dazzler.py", line 355, in tan_apply
    io.syscall('bash -vex {}'.format(os.path.basename(script_fn)))
  File "/software/anaconda2/5.0.1/lssc0-linux/lib/python2.7/site-packages/pypeflow/io.py", line 29, in syscall
    raise Exception(msg)
Exception: Call 'bash -vex run_datander.sh' returned 256.
WARNING:root:Call '/bin/bash user_script.sh' returned 256.
WARNING:root:CD: 'uow-00' -> '/share/vandeynzelab/scratch/Shiyu/Fonio_Assembly/Temporary_data/Falcon/tmp/shyche/pypetmp/share/vandeynzelab/scratch/Shiyu/Fonio_Assembly/Temporary_data/Falcon/0-rawreads/tan-runs/tan_013'
Traceback (most recent call last):
  File "/software/anaconda2/5.0.1/lssc0-linux/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/software/anaconda2/5.0.1/lssc0-linux/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/afs/genomecenter.ucdavis.edu/software/anaconda2/5.0.1/lssc0-linux/lib/python2.7/site-packages/falcon_kit/mains/generic_run_units_of_work.py", line 117, in <module>
    main()
  File "/afs/genomecenter.ucdavis.edu/software/anaconda2/5.0.1/lssc0-linux/lib/python2.7/site-packages/falcon_kit/mains/generic_run_units_of_work.py", line 113, in main
    run(**vars(args))
  File "/afs/genomecenter.ucdavis.edu/software/anaconda2/5.0.1/lssc0-linux/lib/python2.7/site-packages/falcon_kit/mains/generic_run_units_of_work.py", line 66, in run
    pypeflow.do_task.run_bash(script, inputs, outputs, params)
  File "/software/anaconda2/5.0.1/lssc0-linux/lib/python2.7/site-packages/pypeflow/do_task.py", line 187, in run_bash
    util.system(cmd)
  File "/software/anaconda2/5.0.1/lssc0-linux/lib/python2.7/site-packages/pypeflow/io.py", line 29, in syscall
    raise Exception(msg)
Exception: Call '/bin/bash user_script.sh' returned 256.
```
The peak memory use before it died was around 7g.

**Comment by pb-cdunn** [comment]
It looks like `LAcheck` failed. That's not actually our code, but let's try to figure out if that's the problem anywyay. If you `cd` into the "uow" run directory, you can run `LAcheck` directly. Just type that whole line (after `+`) into your shell. If that crashes, Gene Myers will definitely want a failing testcase. Hopefully it's not too much data to send him. Let's see.

**Comment by pb-cdunn** [comment]
LAcheck raw_reads TAN.raw_reads.53.las TAN.raw_reads.54.las TAN.raw_reads.55.las TAN.raw_reads.56.las

Also try to learn the file sizes of those `.las` files. (They might be symlinked.) And also of the `.raw_reads.*` database files.

**Comment by mycecilia** [comment]
I ran `LAcheck raw_reads TAN.raw_reads.53.las TAN.raw_reads.54.las TAN.raw_reads.55.las TAN.raw_reads.56.las -v`. Error output as following:
```
  TAN.raw_reads.53: Duplicate LAs (1034526 vs 1034526)
  TAN.raw_reads.53: Not OK, see stderr
  TAN.raw_reads.54: Duplicate LAs (1068337 vs 1068337)
  TAN.raw_reads.54: Not OK, see stderr
  TAN.raw_reads.55: Duplicate LAs (1090695 vs 1090695)
  TAN.raw_reads.55: Not OK, see stderr
  TAN.raw_reads.56: Duplicate LAs (1110284 vs 1110284)
  TAN.raw_reads.56: Not OK, see stderr
``` 
I'm not sure which stderr to check. 
The file sizes are 
```
18G  ./0-rawreads/build/.raw_reads.bps
53M ./0-rawreads/build/.raw_reads.dust.anno
253M ./0-rawreads/build/.raw_reads.dust.data
262M ./0-rawreads/build/.raw_reads.idx

658K ./temp/0-rawreads/tan-runs/tan_013/uow-00/TAN.raw_reads.53.las
648K ./temp/0-rawreads/tan-runs/tan_013/uow-00/TAN.raw_reads.54.las
524K ./temp/0-rawreads/tan-runs/tan_013/uow-00/TAN.raw_reads.55.las
686K ./temp/0-rawreads/tan-runs/tan_013/uow-00/TAN.raw_reads.56.las
```

**Comment by pb-cdunn** [comment]
There used to be a bug in DALIGNER which caused similar LAcheck failures. My guess is that you are not using our version of DALIGNER. Please post `conda list`.

**Comment by mycecilia** [comment]
`conda list`
```
# packages in environment at /software/anaconda2/5.0.1/lssc0-linux:
#
# Name                    Version                   Build  Channel
falcon-kit                1.2.6                    pypi_0    pypi
falcon-phase              1.0.0                    pypi_0    pypi
falcon-unzip              1.1.7                    pypi_0    pypi

```

**Comment by mycecilia** [comment]
Also
```
pb-assembly               0.0.4                    py27_5    bioconda
pb-dazzler                0.0.0                h470a237_0    bioconda
pb-falcon                 0.2.6            py27hc0aa232_3    bioconda
pbalign                   0.3.1                    py27_0    bioconda
pbbam                     0.18.0               h6678c95_4    bioconda
pbccs                     3.3.0                         0    bioconda
pbcommand                 1.1.1            py27h24bf2e0_1    bioconda
pbcopper                  0.4.2                h02d93b8_0    bioconda
pbcore                    1.5.1                    py27_1    bioconda
pbcoretools               0.2.4                    py27_1    bioconda
pbmm2                     0.8.1                ha87ae23_0    bioconda
```

**Comment by pb-cdunn** [comment]
```
pb-dazzler                0.0.0                h470a237_0    bioconda
```
That should be fine. Maybe you have `LAcheck` or `daligner` in your `$PATH` from elsewhere. Let's see:
```sh
which daligner
which LAcheck
```

**Comment by mycecilia** [comment]
I use a falcon module installed by my system administrator.  
```
$ which daligner
/software/falcon/2018.31.08/lssc0-linux/bin/daligner
$ which LAcheck
/software/falcon/2018.31.08/lssc0-linux/bin/LAcheck
```

**Comment by pb-cdunn** [comment]
Is that the same path as the Bioconda tools? Or could those be old versions?
```
which samtools
which python
which nucmer
```

**Comment by mycecilia** [comment]
```
$ which samtools
/software/anaconda2/5.0.1/lssc0-linux/bin/samtools
$ which python
/software/anaconda2/5.0.1/lssc0-linux/bin/python
$ which nucmer
/software/anaconda2/5.0.1/lssc0-linux/bin/nucmer

```

LAcheck and daligner are not from the path /software/anaconda2/5.0.1/. Does it mean that I'm not using the versions from bioconda? I did find fc_run in `/software/anaconda2/5.0.1/lssc0-linux/bin/`, but when I run `which fc_run`, the path is `/software/falcon/2018.31.08/lssc0-linux/bin/fc_run`.

**Comment by pb-cdunn** [comment]
> Does it mean that I'm not using the versions from bioconda?

Correct.

**Comment by mycecilia** [comment]
Hi, it took me a while to finally figure out which one is the latest bioconda pb-assembly. I still can't run through the tan-run step but with slightly different/better problem. 

Here are the versions I used:
```
# packages in environment at /share/vandeynzelab/local/conda_envs/my_pb_env_conda3:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                py37_1003    conda-forge
avro-python2              1.8.2                      py_1    bioconda
bcftools                  1.9                  ha228f0b_4    bioconda
bedtools                  2.28.0               hdf88d34_0    bioconda
blasr                     5.3.3                h707fff8_0    bioconda
blasr_libcpp              5.3.3                h707fff8_0    bioconda
bwa                       0.7.17               h84994c4_5    bioconda
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
certifi                   2019.3.9                 py37_0    conda-forge
cffi                      1.12.3           py37h8022711_0    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
cryptography              2.6.1            py37h72c5cf5_0    conda-forge
curl                      7.64.1               hf8cf82a_0    conda-forge
cython                    0.29.7           py37he1b5a44_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
falcon-kit                1.4.2                    pypi_0    pypi
falcon-phase              1.1.0                    pypi_0    pypi
falcon-unzip              1.3.1                    pypi_0    pypi
future                    0.17.1                py37_1000    conda-forge
h5py                      2.9.0           nompi_py37hf008753_1102    conda-forge
hdf5                      1.10.4          nompi_h3c11f04_1106    conda-forge
htslib                    1.9                  ha228f0b_7    bioconda
idna                      2.8                   py37_1000    conda-forge
iso8601                   0.1.12                     py_1    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
libblas                   3.8.0                9_openblas    conda-forge
libcblas                  3.8.0                9_openblas    conda-forge
libcurl                   7.64.1               hda55be3_0    conda-forge
libdeflate                1.0                  h14c3975_1    bioconda
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran-ng            7.3.0                hdf63c60_0  
liblapack                 3.8.0                9_openblas    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              8.2.0                hdf63c60_1  
linecache2                1.0.0                      py_1    conda-forge
minimap2                  2.17                 h84994c4_0    bioconda
mummer4                   4.0.0beta2      pl526hf484d3e_4    bioconda
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.3                        py_0    conda-forge
nim-falcon                0.0.0                         0    bioconda
numpy                     1.16.3           py37he5ce36f_0    conda-forge
openblas                  0.3.6                h6e990d7_2    conda-forge
openssl                   1.1.1b               h14c3975_1    conda-forge
pb-assembly               0.0.6                    py37_5    bioconda
pb-dazzler                0.0.0                h470a237_0    bioconda
pb-falcon                 0.3.1            py37hc0aa232_0    bioconda
pbbam                     0.23.0               h88345a9_0    bioconda
pbcopper                  0.4.2                h3f2a3d2_1    bioconda
pbgcpp                    0.0.1                         0    bioconda
pbmm2                     1.0.0                ha888412_0    bioconda
perl                      5.26.2            h516909a_1006    conda-forge
pip                       19.1                     py37_0    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pysam                     0.15.2           py37h4b7d16d_3    bioconda
pysocks                   1.7.0                    py37_0    conda-forge
python                    3.7.3                h5b0a415_0    conda-forge
python-edlib              1.2.4            py37h6bb024c_0    bioconda
python-intervaltree       3.0.2                      py_0    bioconda
python-msgpack            0.6.1            py37h6bb024c_0    bioconda
python-sortedcontainers   2.1.0                      py_0    bioconda
pytz                      2019.1                     py_0    conda-forge
racon                     1.3.2                he860b03_1    bioconda
readline                  7.0               hf8c457e_1001    conda-forge
requests                  2.21.0                py37_1000    conda-forge
samtools                  1.9                 h8571acd_11    bioconda
setuptools                41.0.1                   py37_0    conda-forge
six                       1.12.0                py37_1000    conda-forge
sqlite                    3.26.0            h67949de_1001    conda-forge
tk                        8.6.9             h84994c4_1001    conda-forge
traceback2                1.4.0                    py37_0  
unittest2                 1.1.0                    py37_0  
urllib3                   1.24.3                   py37_0    conda-forge
wheel                     0.33.4                   py37_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
```

All the tan-run/run_### jobs exit with error. They look like the same error as I got before. But when I ran `bash -vex run_datander.sh`, it went through without any error. 

Then I try the command inside user_script.sh 
`python3 -m falcon_kit.mains.dazzler --config=/share/vandeynzelab/scratch/Shiyu/Fonio_Assembly/Temporary_data/Falcon/General_config.json --db=/share/vandeynzelab/scratch/Shiyu/Fonio_Assembly/Temporary_data/Falcon/0-rawreads/build/raw_reads.db  tan-apply --script=../../../../../../../../../../../../../../0-rawreads/tan-split/tan-scripts/tan_000/run_datander.sh --job-done=job.done` 
it gave me the error I saw from .err file, which is:
```
LAsort ./datander.59443/raw_reads.4.T@.las
LAmerge TAN.raw_reads.4.las ./datander.59443/raw_reads.4.T@.S.las
LAcheck raw_reads TAN.raw_reads.1.las TAN.raw_reads.2.las TAN.raw_reads.3.las TAN.raw_reads.4.las
+ LAcheck raw_reads TAN.raw_reads.1.las TAN.raw_reads.2.las TAN.raw_reads.3.las TAN.raw_reads.4.las
[WARNING]Call 'bash -vex run_datander.sh' returned 256.
Traceback (most recent call last):
  File "/share/vandeynzelab/local/conda_envs/my_pb_env_conda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/share/vandeynzelab/local/conda_envs/my_pb_env_conda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/share/vandeynzelab/local/conda_envs/my_pb_env_conda3/lib/python3.7/site-packages/falcon_kit/mains/dazzler.py", line 1531, in <module>
    main()
  File "/share/vandeynzelab/local/conda_envs/my_pb_env_conda3/lib/python3.7/site-packages/falcon_kit/mains/dazzler.py", line 1527, in main
    args.func(args)
  File "/share/vandeynzelab/local/conda_envs/my_pb_env_conda3/lib/python3.7/site-packages/falcon_kit/mains/dazzler.py", line 1056, in cmd_tan_apply
    tan_apply(args.db_fn, args.script_fn, args.job_done_fn)
  File "/share/vandeynzelab/local/conda_envs/my_pb_env_conda3/lib/python3.7/site-packages/falcon_kit/mains/dazzler.py", line 394, in tan_apply
    io.syscall('bash -vex {}'.format(os.path.basename(script_fn)))
  File "/share/vandeynzelab/local/conda_envs/my_pb_env_conda3/lib/python3.7/site-packages/pypeflow/io.py", line 27, in syscall
    raise Exception(msg)
Exception: Call 'bash -vex run_datander.sh' returned 256.

```

I also tried to run LAsort, LAmerge and LAcheck separately with success. 
I'm really puzzled here. Any help is greatly appreciated.

Shiyu

**Comment by pb-cdunn** [comment]
When others have seen a crash in tan-masking, it is usually out-of-memory. If you adjust your config, hopefully you can reduce the memory required per job, or increase the memory requested from the machines you use.

The way to debug this is to go into the run-directory of the failing task and run the task yourself. You can try `bash user_script.sh` for a start. Observe the process to see how much memory it actually uses. Good luck!
