### ISSUE TITLE
installing genomicconsensus does not work

### ISSUE THREAD

**Issue by nmmsv** [PacificBiosciences/pbbioconda#126]
**Operating system**
```
NAME="CentOS Linux"
VERSION="7 (Core)"
```

**Package name**
trying to install any version of `genomicconsensus` version 2.3.3 which requires `pbcommand` (automatically installs v1.1.1).

**Conda environment**
```
# packages in environment at /storage/nmmsv/packages/anaconda2/envs/arrow3:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                py27_1003    conda-forge
avro-python2              1.8.2                      py_1    bioconda
bcftools                  1.9                  ha228f0b_3    bioconda
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
certifi                   2019.3.9                 py27_0    conda-forge
cffi                      1.12.2           py27hf0e25f4_1    conda-forge
chardet                   3.0.4                 py27_1003    conda-forge
cryptography              2.6.1            py27h72c5cf5_0    conda-forge
curl                      7.64.1               hf8cf82a_0    conda-forge
cython                    0.29.6           py27hf484d3e_0    conda-forge
enum34                    1.1.6                 py27_1001    conda-forge
genomicconsensus          2.3.3                    py27_0    bioconda
h5py                      2.9.0           nompi_py27hf008753_1102    conda-forge
hdf5                      1.10.4          nompi_h3c11f04_1106    conda-forge
htslib                    1.9                  ha228f0b_7    bioconda
idna                      2.8                   py27_1000    conda-forge
ipaddress                 1.0.22                     py_1    conda-forge
iso8601                   0.1.12                     py_1    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
libblas                   3.8.0                4_openblas    conda-forge
libcblas                  3.8.0                4_openblas    conda-forge
libcurl                   7.64.1               hda55be3_0    conda-forge
libdeflate                1.0                  h14c3975_1    bioconda
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran-ng            7.3.0                hdf63c60_0  
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              8.2.0                hdf63c60_1  
linecache2                1.0.0                      py_1    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.16.2           py27h7fc5cc3_0    conda-forge
openblas                  0.3.5             h9ac9557_1001    conda-forge
openssl                   1.1.1b               h14c3975_1    conda-forge
pbcommand                 1.1.1                    py27_2    bioconda
pbcore                    1.7.1                    py27_0    bioconda
pip                       19.0.3                   py27_0    conda-forge
pycparser                 2.19                     py27_1    conda-forge
pyopenssl                 19.0.0                   py27_0    conda-forge
pysam                     0.15.2           py27h4b7d16d_3    bioconda
pysocks                   1.6.8                 py27_1002    conda-forge
python                    2.7.15            h721da81_1008    conda-forge
python-consensuscore      1.1.1            py27h3f2a3d2_3    bioconda
python-consensuscore2     3.4.1                    py27_0    bioconda
pytz                      2019.1                     py_0    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
requests                  2.21.0                py27_1000    conda-forge
samtools                  1.9                 h8571acd_11    bioconda
setuptools                41.0.0                   py27_0    conda-forge
six                       1.12.0                py27_1000    conda-forge
sqlite                    3.26.0            h67949de_1001    conda-forge
tk                        8.6.9             h84994c4_1001    conda-forge
traceback2                1.4.0                    py27_0    conda-forge
unittest2                 1.1.0                      py_0    conda-forge
urllib3                   1.24.1                py27_1000    conda-forge
wheel                     0.33.1                   py27_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
```

**Describe the bug**
I'm trying to install `genomicconsensus` to run arrow. Installing package from bioconda automatically install `pbcommand` v1.1.1. However, there is the following error (attached in the next section) when I try to run quiver.
I have tried using old versions of `pbcommand`, but installing `genomicconsensus` will force and upgrade of `pbcommand`.

**Error message**
```
(arrow3) [nmmsv@snorlax pbcommand-0.2.17]$ quiver
Traceback (most recent call last):
  File "/storage/nmmsv/packages/anaconda2/envs/arrow3/bin/variantCaller", line 3, in <module>
    from GenomicConsensus.main import main
  File "/storage/nmmsv/packages/anaconda2/lib/python2.7/site-packages/GenomicConsensus/main.py", line 12, in <module>
    from pbcommand.utils import setup_log, Constants as LogFormats
ImportError: cannot import name Constants
```

**To Reproduce**
install `genomicconsensus` on a fresh conda environment (python 2.7)

**Expected behavior**
the software to run.

**Comment by pb-dseifert** [comment]
Could it be that you have mixed envs? it seems like GenomicConsensus is installed in a different env
