### ISSUE TITLE
pbalign Error loading chemistry mapping xml

### ISSUE THREAD

**Issue by ptranvan** [PacificBiosciences/pbbioconda#129]
Hi,

I got weird error by running this command (last version of pbalign installed via bioconda). Any solution ? Thanks

`pbalign --nproc 20 fasta/file.fasta contigs.fasta pbalign/output.sam `

```
Traceback (most recent call last):
  File "/scratch/beegfs/monthly/ptranvan/Software/anaconda_2/bin/pbalign", line 11, in <module>
    load_entry_point('pbalign==0.3.2', 'console_scripts', 'pbalign')()
  File "/scratch/beegfs/monthly/ptranvan/Software/anaconda_2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/scratch/beegfs/monthly/ptranvan/Software/anaconda_2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/scratch/beegfs/monthly/ptranvan/Software/anaconda_2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/scratch/beegfs/monthly/ptranvan/Software/anaconda_2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/scratch/beegfs/monthly/ptranvan/Software/anaconda_2/lib/python2.7/site-packages/pbalign/pbalignrunner.py", line 53, in <module>
    from pbcore.io import (AlignmentSet, ConsensusAlignmentSet)
  File "lib/python2.7/site-packages/pbcore/io/__init__.py", line 3, in <module>
  File "lib/python2.7/site-packages/pbcore/io/BasH5IO.py", line 23, in <module>
  File "lib/python2.7/site-packages/pbcore/chemistry/__init__.py", line 3, in <module>
  File "lib/python2.7/site-packages/pbcore/chemistry/chemistry.py", line 41, in <module>
  File "lib/python2.7/site-packages/pbcore/chemistry/chemistry.py", line 32, in _loadBarcodeMappings
  File "lib/python2.7/site-packages/pbcore/chemistry/chemistry.py", line 28, in _loadBarcodeMappingsFromFile
pbcore.chemistry.chemistry.ChemistryLookupError: Error loading chemistry mapping xml
```

**Comment by ylipacbio** [comment]
We are deprecating pbalign, please use pbmm2 instead.


If you have to use pbalign for some reason, two issues here:
(1) pbcore python environemnt seems to be contaminated. From bioconda pbalign path switch to system pbcore path, e.g., `File "/scratch/beegfs/monthly/ptranvan/Software/anaconda_2/lib/python2.7/site-packages/pkg_resources/__init__.py` --> `File "lib/python2.7/site-packages/pbcore/chemistry/chemistry.py"`

2) You may have specified system `SMRT_CHEMISTRY_BUNDLE_DIR` and it is not pointing to the right directory. Check `$SMRT_CHEMISTRY_BUNDLE_DIR/chemistry.xml`.
