### ISSUE TITLE
A different error with code: [ERROR]Task Node(0-rawreads/build) failed with exit-code=1

### ISSUE THREAD

**Issue by WTarabidopsis** [PacificBiosciences/pbbioconda#131]
**Operating system**
CentOS 6.5

**Package name**
pb-assembly

**Conda environment**
[conda_list.txt](https://github.com/PacificBiosciences/pbbioconda/files/3084994/conda_list.txt)

**Describe the bug**
Recently, when I was testing the pb-assembly with the human data (SRR7615963), an err "[ERROR]Task Node(0-rawreads/build) failed with exit-code=1" always came out. I checked the running information, .stderr and .stdout file and have no idea what happened. I searched the issues page and no one has reported an err like this.
Here is the running information, the .cfg file, the conda list, the .stderr and .stdout files. Please help me figure it out, this problem has confused me for a few days.

The software went well when the 200kb and F1_bull_test_data were given. I'm not sure if there is something wrong with the input fasta file. I downloaded SRR7615963.sra from NCBI and converted it into fasta file for assembly. Is there something I missed?

Thanks in advance.
Yuxin

**Error message**
[run information.txt](https://github.com/PacificBiosciences/pbbioconda/files/3085009/run.information.txt)

[run-P7b511a055fa96b.bash.stdout.txt](https://github.com/PacificBiosciences/pbbioconda/files/3085010/run-P7b511a055fa96b.bash.stdout.txt)

[run-P7b511a055fa96b.bash.stderr.txt](https://github.com/PacificBiosciences/pbbioconda/files/3085006/run-P7b511a055fa96b.bash.stderr.txt)

[fc_run_human.local.cfg.txt](https://github.com/PacificBiosciences/pbbioconda/files/3085014/fc_run_human.local.cfg.txt)

**Comment by pb-cdunn** [comment]
```python
while read fn; do  zcat  ${fn} | python -m falcon_kit.mains.fasta_filter ${zmw_whitelist_option} streamed-median - | fasta2DB -v raw_reads -i${fn##*/}; done < my.input.fofn
+ read fn
+ zcat /vol1/agis/huangsanwen_group/jiayuxin/11_falcon_test/03_human_test/01_data/SRR7615963.fasta.gz
+ python -m falcon_kit.mains.fasta_filter streamed-median -
+ fasta2DB -v raw_reads -iSRR7615963.fasta.gz
falcon-kit 1.2.6
pypeflow 2.1.1
INFO:root:Counting bytes from "None"
INFO:root:        #1 count=            779 
Traceback (most recent call last):
  File "/public/agis/huangsanwen_group/jiayuxin/07_softwares/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/public/agis/huangsanwen_group/jiayuxin/07_softwares/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/public/agis/huangsanwen_group/jiayuxin/07_softwares/anaconda2/lib/python2.7/site-packages/falcon_kit/mains/fasta_filter.py", line 357, in <module>
    main(sys.argv)          # pragma: no cover
  File "/public/agis/huangsanwen_group/jiayuxin/07_softwares/anaconda2/lib/python2.7/site-packages/falcon_kit/mains/fasta_filter.py", line 354, in main
    args.func(args)
  File "/public/agis/huangsanwen_group/jiayuxin/07_softwares/anaconda2/lib/python2.7/site-packages/falcon_kit/mains/fasta_filter.py", line 267, in cmd_run_streamed_median_filter
    run_streamed_median_filter(fp_in, sys.stdout, whitelist_set)
  File "/public/agis/huangsanwen_group/jiayuxin/07_softwares/anaconda2/lib/python2.7/site-packages/falcon_kit/mains/fasta_filter.py", line 147, in run_streamed_median_filter
    write_streamed(fp_out, yield_zmwtuple_func, zmw_filter_func)
  File "/public/agis/huangsanwen_group/jiayuxin/07_softwares/anaconda2/lib/python2.7/site-packages/falcon_kit/mains/fasta_filter.py", line 138, in write_streamed
    for zmw_id, zmw_subreads in itertools.groupby(yield_zmwtuple_func(store_record=True), lambda x: x.zmw_id):
  File "/public/agis/huangsanwen_group/jiayuxin/07_softwares/anaconda2/lib/python2.7/site-packages/falcon_kit/mains/fasta_filter.py", line 127, in yield_zmwtuple
    for (record, tokens) in yield_record_and_tokenized_headers(whitelist_set, records):
  File "/public/agis/huangsanwen_group/jiayuxin/07_softwares/anaconda2/lib/python2.7/site-packages/falcon_kit/mains/fasta_filter.py", line 48, in yield_record_and_tokenized_headers
    tokens = tokenize_header(record.name)
  File "/public/agis/huangsanwen_group/jiayuxin/07_softwares/anaconda2/lib/python2.7/site-packages/falcon_kit/mains/fasta_filter.py", line 36, in tokenize_header
    movie_name, zmw_id, subread_pos = rid.split('/')
ValueError: need more than 1 value to unpack
```
This typically occurs when the input fasta is invalid. It could be fastq, or it could be CCS reads (which we will support soon), or it could be missing PacBio-style headers. Could you post a sample header?

In the meantime, we will make the error message more clear.

**Comment by WTarabidopsis** [comment]
Thank you for the quick reply, here are the headers of some fasta reads: 

>SRR7615963.1 1 length=742
>SRR7615963.2 2 length=1872
>SRR7615963.3 3 length=371
>SRR7615963.4 4 length=21278
>SRR7615963.5 5 length=64650
>SRR7615963.6 6 length=792
>SRR7615963.7 7 length=2212
>SRR7615963.8 8 length=12969
>SRR7615963.9 9 length=20161
>SRR7615963.10 10 length=28814
>SRR7615963.11 11 length=45463
>SRR7615963.12 12 length=285
>SRR7615963.13 13 length=64935
>SRR7615963.14 14 length=27547
>SRR7615963.15 15 length=49263
>SRR7615963.16 16 length=46174
>SRR7615963.17 17 length=8813
>SRR7615963.18 18 length=3819
>SRR7615963.19 19 length=44310
>SRR7615963.20 20 length=29232

**Comment by pb-cdunn** [comment]
In github-flavored markdown, you can use triple backticks above and below the text to display verbatim with a monospace font.

Anyway, yes, this is bad data for Falcon. The headers need to have the form
```
>SRR123/9999/0_456
```
where `9999` is the Pacbio zmw number, and `0_456` is the start and end of the subread along the raw read of the insert. You could try to modify the headers.

**Comment by WTarabidopsis** [comment]
Thanks again, I will try to fix it.
Yuxin
