### ISSUE TITLE
Error when merging .subreadset.xml files in IsoSeq3.1

### ISSUE THREAD

**Issue by alissawilliams** [PacificBiosciences/pbbioconda#132]
I am following the commands at https://github.com/PacificBiosciences/IsoSeq3/blob/master/README_v3.1.md. I have two **movies and merged the .flnc.bam files with no issue using the command: 
dataset create --type TranscriptSet merged.flnc.xml m54138_190117_075027.flnc.bam m54138_190118_192656.flnc.bam** 

However, I cannot get the .subreadset.xml to merge. I used the command:
**dataset create --type SubreadSet merged.subreadset.xml m54138_190117_075027.subreadset.xml m54138_190118_192656.subreadset.xml** 

and got an error:
Including unresolved file: m54138_190117_075027.sts.xml
Including unresolved file: m54138_190117_075027.adapters.fasta
Including unresolved file: m54138_190117_075027.scraps.bam
Including unresolved file: m54138_190117_075027.scraps.bam.pbi
Including unresolved file: m54138_190118_192656.sts.xml
Including unresolved file: m54138_190118_192656.adapters.fasta
Including unresolved file: m54138_190118_192656.scraps.bam
Including unresolved file: m54138_190118_192656.scraps.bam.pbi
Resource m54138_190118_192656.sts.xml not found
Traceback (most recent call last):
  File "/projects/amwill@colostate.edu/anaconda2/lib/python2.7/site-packages/pbcommand/cli/core.py", line 138, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/projects/amwill@colostate.edu/anaconda2/lib/python2.7/site-packages/pbcoretools/dataset.py", line 59, in run
    return args.func(args)
  File "/projects/amwill@colostate.edu/anaconda2/lib/python2.7/site-packages/pbcoretools/DataSetEntryPoints.py", line 62, in createXml
    generateIndices=args.generateIndices)
  File "/projects/amwill@colostate.edu/anaconda2/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2705, in __init__
    super(SubreadSet, self).__init__(*files, **kwargs)
  File "/projects/amwill@colostate.edu/anaconda2/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 1994, in __init__
    super(ReadSet, self).__init__(*files, **kwargs)
  File "/projects/amwill@colostate.edu/anaconda2/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 386, in __init__
    self._modResources(_fileExists)
  File "/projects/amwill@colostate.edu/anaconda2/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 1252, in _modResources
    func(item)
  File "/projects/amwill@colostate.edu/anaconda2/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 255, in _fileExists
    raise InvalidDataSetIOError("Resource {f} not found".format(f=fname))
**InvalidDataSetIOError: Resource m54138_190118_192656.sts.xml not found**

I am not sure how to fix this issue.

**Comment by armintoepfer** [comment]
Looks like you are missing the stats xml file. Try this:
```
dataset create --type SubreadSet merged.subreadset.xml m54138_190117_075027.subreads.bam m54138_190118_192656.subreads.bam
```

**Comment by alissawilliams** [comment]
That worked, thank you so much!! I had been struggling with it for a while!
