### ISSUE TITLE
pbmm2 M5 field still missing with latest version

### ISSUE THREAD

**Issue by mycecilia** [PacificBiosciences/pbbioconda#141]
**Operating system**
Ubuntu 16.04.6 LTS (GNU/Linux 4.15.0-46-generic x86_64)

**Package name**
`pbmm2                     1.0.0                ha888412_0    bioconda `
Have you updated to the latest version `conda update package`?
Yes
Have you updated the complete env by running `conda update --all`? 
Yes
Have you ensured that your channel priorities are set up according to the bioconda recommendations at https://bioconda.github.io/#set-up-channels?
Yes

**Conda environment**
```
# packages in environment at /home/shyche/.conda/envs/my_pb_env:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                py27_1003    conda-forge
avro-python2              1.8.2                      py_1    bioconda
bcftools                  1.9                  ha228f0b_3    bioconda
blasr                     5.3.3                h707fff8_0    bioconda
blasr_libcpp              5.3.3                h707fff8_0    bioconda
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
certifi                   2019.3.9                 py27_0    conda-forge
cffi                      1.12.3           py27h8022711_0    conda-forge
chardet                   3.0.4                 py27_1003    conda-forge
cryptography              2.6.1            py27h72c5cf5_0    conda-forge
curl                      7.64.1               hf8cf82a_0    conda-forge
cython                    0.29.7           py27he1b5a44_0    conda-forge
enum34                    1.1.6                 py27_1001    conda-forge
h5py                      2.9.0           nompi_py27hf008753_1102    conda-forge
hdf5                      1.10.4          nompi_h3c11f04_1106    conda-forge
htslib                    1.9                  h4da6232_3    bioconda
idna                      2.8                   py27_1000    conda-forge
ipaddress                 1.0.22                     py_1    conda-forge
iso8601                   0.1.12                     py_1    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
libblas                   3.8.0                7_openblas    conda-forge
libcblas                  3.8.0                7_openblas    conda-forge
libcurl                   7.64.1               hda55be3_0    conda-forge
libdeflate                1.0                  h14c3975_1    bioconda
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran-ng            7.3.0                hdf63c60_0  
liblapack                 3.8.0                7_openblas    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              8.2.0                hdf63c60_1  
linecache2                1.0.0                      py_1    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.16.3           py27he5ce36f_0    conda-forge
openblas                  0.3.5             h9ac9557_1001    conda-forge
openssl                   1.1.1b               h14c3975_1    conda-forge
pbalign                   0.3.2                    py27_0    bioconda
pbbam                     0.23.0               h88345a9_0    bioconda
pbcommand                 1.1.1                    py27_2    bioconda
pbcopper                  0.4.2                h3f2a3d2_1    bioconda
pbcore                    1.7.1                    py27_0    bioconda
pbmm2                     1.0.0                ha888412_0    bioconda
pip                       19.1                     py27_0    conda-forge
pycparser                 2.19                     py27_1    conda-forge
pyopenssl                 19.0.0                   py27_0    conda-forge
pysam                     0.15.2           py27h4b7d16d_3    bioconda
pysocks                   1.6.8                 py27_1002    conda-forge
python                    2.7.15            h721da81_1008    conda-forge
pytz                      2019.1                     py_0    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
requests                  2.21.0                py27_1000    conda-forge
samtools                  1.9                 h8571acd_11    bioconda
setuptools                41.0.1                   py27_0    conda-forge
six                       1.12.0                py27_1000    conda-forge
sqlite                    3.26.0            h67949de_1001    conda-forge
tk                        8.6.9             h84994c4_1001    conda-forge
traceback2                1.4.0                    py27_0    conda-forge
unittest2                 1.1.0                      py_0    conda-forge
urllib3                   1.24.2                   py27_0    conda-forge
wheel                     0.33.1                   py27_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
```

**Describe the bug**
I successfully used bax2bam to convert PacBio bax.h5 files to bam files, then ran `pbmm2 align --sort -j 8 -J 4 Ref.fasta subreads.bam aligned.bam`. 
However, I got error when running `variantCaller -j8 --algorithm=arrow -r Ref.fasta -o ${OutputPrefix}.fasta -o ${OutputPrefix}.fastq -o ${OutputPrefix}.gff aligned.bam`. So I traced back to pbmm2 bam output, and found no M5 info in the header. In [this closed issue](https://github.com/PacificBiosciences/pbbioconda/issues/58), the same error occurred but updating the package didn't result in generating M5 information for me. Should I have used Ref.mmi file in pbmm2 align command? Could you give an example that could result in the compatible bam file with arrow? Thank you.

**my bam header looks like this**
```
@HD	VN:1.6	SO:coordinate	pb:3.0.5
@SQ	SN:tig00000003	LN:38460
@SQ	SN:tig00000007	LN:23023
@SQ	SN:tig00000009	LN:21162
@SQ	SN:tig00000011	LN:49756
@SQ	SN:tig00000012	LN:26938
@SQ	SN:tig00000013	LN:37345
@SQ	SN:tig00000014	LN:37656
@SQ	SN:tig00000016	LN:46426
@SQ	SN:tig00000017	LN:22036
......
@RG	ID:fdd7b040	PL:PACBIO	DS:READTYPE=SUBREAD;DeletionQV=dq;DeletionTag=dt;InsertionQV=iq;MergeQV=mq;SubstitutionQV=sq;Ipd:CodecV1=ip;PulseWidth:CodecV1=pw;BINDINGKIT=100372700;SEQUENCINGKIT=100612400;BASECALLERVERSION=2.3.0.4.187002;FRAMERATEHZ=75.000000	PU:m180221_165701_42145_c101251512550000001823310509221810_s1_p0	SM:UnnamedSample	PM:RS
@PG	ID:bax2bam-0.0.8	PN:bax2bam	VN:0.0.8	DS:bax2bam converts the legacy PacBio basecall format (bax.h5) into the BAM basecall format.	CL:bax2bam /share/vandeynzelab/scratch/share/Fonio/data/FN_01/180218_528/D1/D01_1_Primary/Analysis_Results/m180221_165701_42145_c101251512550000001823310509221810_s1_p0.1.bax.h5 /share/vandeynzelab/scratch/share/Fonio/data/FN_01/180218_528/D1/D01_1_Primary/Analysis_Results/m180221_165701_42145_c101251512550000001823310509221810_s1_p0.2.bax.h5 /share/vandeynzelab/scratch/share/Fonio/data/FN_01/180218_528/D1/D01_1_Primary/Analysis_Results/m180221_165701_42145_c101251512550000001823310509221810_s1_p0.3.bax.h5 
@PG	ID:pbmm2	PN:pbmm2	VN:1.0.0 (commit 1.0.0)	CL:pbmm2 align --sort -j 8 -J 4 /share/vandeynzelab/scratch/Shiyu/Fonio_Assembly/data/FN_CANU_20190101.contigs.fasta /share/vandeynzelab/scratch/Shiyu/Fonio_Assembly/Temporary_data/HDF5_Convert/subreads.bam /share/vandeynzelab/scratch/Shiyu/Fonio_Assembly/Temporary_data/Polish/FN_CANU_1kb.aligned.bam
```

**Error message**
```
'M5'
Traceback (most recent call last):
  File "/software/falcon/2018.31.08/lssc0-linux/lib/python2.7/site-packages/pbcommand/cli/core.py", line 138, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/software/anaconda2/5.0.1/lssc0-linux/lib/python2.7/site-packages/GenomicConsensus/main.py", line 340, in args_runner
    return tr.main()
  File "/software/anaconda2/5.0.1/lssc0-linux/lib/python2.7/site-packages/GenomicConsensus/main.py", line 258, in main
    with AlignmentSet(options.inputFilename) as peekFile:
  File "/software/falcon/2018.31.08/lssc0-linux/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2720, in __init__
    super(AlignmentSet, self).__init__(*files, **kwargs)
  File "/software/falcon/2018.31.08/lssc0-linux/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 1984, in __init__
    super(ReadSet, self).__init__(*files, **kwargs)
  File "/software/falcon/2018.31.08/lssc0-linux/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 461, in __init__
    self.updateCounts()
  File "/software/falcon/2018.31.08/lssc0-linux/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2538, in updateCounts
    self.assertIndexed()
  File "/software/falcon/2018.31.08/lssc0-linux/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2368, in assertIndexed
    self._assertIndexed((IndexedBamReader, CmpH5Reader))
  File "/software/falcon/2018.31.08/lssc0-linux/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 1941, in _assertIndexed
    self._openFiles()
  File "/software/falcon/2018.31.08/lssc0-linux/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2065, in _openFiles
    resource = IndexedBamReader(location)
  File "/software/falcon/2018.31.08/lssc0-linux/lib/python2.7/site-packages/pbcore/io/align/BamIO.py", line 373, in __init__
    super(IndexedBamReader, self).__init__(fname, referenceFastaFname)
  File "/software/falcon/2018.31.08/lssc0-linux/lib/python2.7/site-packages/pbcore/io/align/BamIO.py", line 181, in __init__
    self._loadReferenceInfo()
  File "/software/falcon/2018.31.08/lssc0-linux/lib/python2.7/site-packages/pbcore/io/align/BamIO.py", line 49, in _loadReferenceInfo
    refMD5s    = [r["M5"] for r in refRecords]
KeyError: 'M5'
```

**Comment by armintoepfer** [comment]
You need genomicconsensus from bioconda. Not sure which version you are using.

**Comment by pb-dseifert** [comment]
that looks like an ancient falcon installation. pbcore has been updated around that time, and it's unlikely that falcon will have included that.

**Comment by armintoepfer** [comment]
^ what he said.

**Comment by xiaoyezao** [comment]
Hi mycecilia,
I found the pbmm2 from package pbsv do not generate M5 field. Try to use the one implemented in pb-assembly. The resulted bam file can be used for arrow.

**Comment by armintoepfer** [comment]
Just use the latest genomicconsensus from bioconda!
