### ISSUE TITLE
fc_phase.py TypeError: gen_parallel_tasks() got multiple values for keyword argument 'run_dict'

### ISSUE THREAD

**Issue by changhan1110** [PacificBiosciences/pbbioconda#153]
I am trying to run fc_phase tutorial but I got this error. I tried to fix the bug with config files but I didn't work well. 
I will be grateful if you help me to understand the error and how to fix it.
Thanks in advance.

```
falcon-phase 1.0.0
falcon-kit 1.3.0
pypeflow 2.2.0
[INFO]Setup logging from file "None".
[ERROR]job.defaults.submit is not set; pwatcher_type=fs_based; but job_type is not set. Maybe try "job_type=local" first.
[INFO]Using config=
falcon-phase 1.0.0
falcon-kit 1.3.0
pypeflow 2.2.0
[INFO]Setup logging from file "None".
[INFO]Using config=
{'General': {},
 'Phase': {'cns_h_ctg_fasta': './4-polish/cns-output/cns_h_ctg.fasta',
           'cns_p_ctg_fasta': './4-polish/cns-output/cns_p_ctg.fasta',
           'enzyme': '"GATC"',
           'iterations': '10000000',
           'min_aln_len': '5000',
           'output_format': 'pseudohap',
           'reads_1': '/BiO/Research/Project1/KOGIC-KOREF_v2_PacBio-Genome-2018-11/Workspace/changhan/falcon_tutorial/F1_bull_test_data/F1_bull_test.HiC_R1.fastq.gz',
           'reads_2': '/BiO/Research/Project1/KOGIC-KOREF_v2_PacBio-Genome-2018-11/Workspace/changhan/falcon_tutorial/F1_bull_test_data/F1_bull_test.HiC_R2.fastq.gz'},
 'job.defaults': {'JOB_QUEUE': 'all.q@tiger',
                  'MB': '3200',
                  'NPROC': '2',
                  'job_type': 'sge',
                  'njobs': '100',
                  'pwatcher_type': 'blocking',
                  'submit': 'qsub -S /bin/bash -sync y -V  \\\n-q ${JOB_QUEUE}     \\\n-N ${JOB_NAME}        \\\n-o "${JOB_STDOUT}" \\\n-e "${JOB_STDERR}" \\\n-pe smp ${NPROC}    \\\n"${JOB_SCRIPT}"',
                  'use_tmpdir': False},
 'job.step.phase.alignment': {},
 'job.step.phase.placement': {}}
[INFO]PATH=/BiO/Access/changhan/anaconda3/envs/denovo_asm/bin:/BiO/Access/changhan/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/BiO/BioTools/root5.34.26/bin:/opt/SSM/SuperDoctor5
[INFO]$('which which')
/usr/bin/which
[INFO]$('which samtools')
/BiO/Access/changhan/anaconda3/envs/denovo_asm/bin/samtools
[INFO]$('which nucmer')
/BiO/Access/changhan/anaconda3/envs/denovo_asm/bin/nucmer
[INFO]$('which show-coords')
/BiO/Access/changhan/anaconda3/envs/denovo_asm/bin/show-coords
[INFO]$('which delta-filter')
/BiO/Access/changhan/anaconda3/envs/denovo_asm/bin/delta-filter
[INFO]$('which bwa')
/BiO/Access/changhan/anaconda3/envs/denovo_asm/bin/bwa
[INFO]$('which bedtools')
/BiO/Access/changhan/anaconda3/envs/denovo_asm/bin/bedtools
[INFO]$ nucmer --version >
[INFO]nucmer ['4', '0', '0beta2'] is >= 4.0.0
[INFO]$ bwa mem >
[INFO]$ show-coords -h >
[INFO]$ delta-filter -h >
[INFO]$('bedtools --version')
bedtools v2.28.0
[INFO]$ samtools >
[INFO]samtools ['1', '9'] is >= 1.3
[INFO]In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.fs_based' from '/BiO/Access/changhan/anaconda3/envs/denovo_asm/lib/python2.7/site-packages/pwatcher/fs_based.pyc'>
[INFO]job_type='local', (default)job_defaults={'pwatcher_type': 'fs_based', 'use_tmpdir': False, 'MB': '3200', 'job_type': 'local', 'NPROC': '2', 'njobs': '100'}, use_tmpdir=False, squash=False, job_name_style=0
[INFO]Setting max_jobs to 100; was None
[INFO]This is where FALCON-Phase workflow should be initialized and run.
Traceback (most recent call last):
  File "/BiO/Access/changhan/anaconda3/envs/denovo_asm/bin/fc_phase.py", line 11, in <module>
    load_entry_point('falcon-phase==1.0.0', 'console_scripts', 'fc_phase.py')()
  File "/BiO/Access/changhan/anaconda3/envs/denovo_asm/lib/python2.7/site-packages/falcon_phase/mains/start_falcon_phase.py", line 26, in main
    falcon_phase.run(**vars(args))
  File "/BiO/Access/changhan/anaconda3/envs/denovo_asm/lib/python2.7/site-packages/falcon_phase/falcon_phase.py", line 70, in run
    falcon_phase_all(config)
  File "/BiO/Access/changhan/anaconda3/envs/denovo_asm/lib/python2.7/site-packages/falcon_phase/falcon_phase.py", line 21, in falcon_phase_all
    tasks_falcon_phase.run_workflow(wf, config, rule_writer)
  File "/BiO/Access/changhan/anaconda3/envs/denovo_asm/lib/python2.7/site-packages/falcon_phase/tasks/tasks_falcon_phase.py", line 322, in run_workflow
    min_aln_len, default_nproc, config, rule_writer)
  File "/BiO/Access/changhan/anaconda3/envs/denovo_asm/lib/python2.7/site-packages/falcon_phase/tasks/tasks_falcon_phase.py", line 267, in add_placement_as_parallel_tasks
    job_dict=config['job.step.phase.placement'],
TypeError: gen_parallel_tasks() got multiple values for keyword argument 'run_dict'
```

**Operating system**
Ubuntu 14.04.1

**Package name**
falcon_phase
```
falcon-phase 1.0.0
falcon-kit 1.3.0
pypeflow 2.2.0
```
 Have you updated to the latest version `conda update package`? Yes
 Have you updated the complete env by running `conda update --all`? Yes
 Have you ensured that your channel priorities are set up according to the bioconda recommendations at https://bioconda.github.io/#set-up-channels? Yes

**Conda environment**
```# packages in environment at /BiO/Access/changhan/anaconda3/envs/denovo_asm:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py27_0  
avro-python2              1.8.2                      py_1    bioconda
bcftools                  1.9                  ha228f0b_3    bioconda
bedtools                  2.28.0               hdf88d34_0    bioconda
blas                      1.0                         mkl  
blasr                     5.3.3                h707fff8_0    bioconda
blasr_libcpp              5.3.3                h707fff8_0    bioconda
bwa                       0.7.17               h84994c4_5    bioconda
bzip2                     1.0.6                h14c3975_5  
ca-certificates           2019.1.23                     0  
certifi                   2019.3.9                 py27_0  
cffi                      1.12.3           py27h2e261b9_0  
chardet                   3.0.4                    py27_1  
cryptography              2.6.1            py27h1ba5d50_0  
curl                      7.64.1               hbc83047_0  
cython                    0.29.7           py27he6710b0_0  
decorator                 4.4.0                    py27_1  
enum34                    1.1.6                    py27_1  
falcon-kit                1.3.0                    pypi_0    pypi
falcon-phase              1.0.0                    pypi_0    pypi
falcon-unzip              1.2.0                    pypi_0    pypi
future                    0.17.1                   py27_0  
h5py                      2.9.0            py27h7918eee_0  
hdf5                      1.10.4               hb1b8bf9_0  
htslib                    1.9                  ha228f0b_7    bioconda
idna                      2.8                      py27_0  
intel-openmp              2019.3                      199  
ipaddress                 1.0.22                   py27_0  
iso8601                   0.1.12                   py27_1  
krb5                      1.16.1               h173b8e3_7  
libcurl                   7.64.1               h20c2e04_0  
libdeflate                1.0                  h14c3975_1    bioconda
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran-ng            7.3.0                hdf63c60_0  
libssh2                   1.8.2                h1ba5d50_0  
libstdcxx-ng              8.2.0                hdf63c60_1  
linecache2                1.0.0                    py27_0  
minimap2                  2.16                 h84994c4_1    bioconda
mkl                       2019.3                      199  
mkl_fft                   1.0.10           py27ha843d7b_0  
mkl_random                1.0.2            py27hd81dba3_0  
mummer4                   4.0.0beta2      pl526hf484d3e_4    bioconda
ncurses                   6.1                  he6710b0_1  
networkx                  2.2                      py27_1  
nim-falcon                0.0.0                         0    bioconda
numpy                     1.16.3           py27h7e9f1db_0  
numpy-base                1.16.3           py27hde5b4d6_0  
openssl                   1.1.1b               h7b6447c_1  
pb-assembly               0.0.5                    py27_2    bioconda
pb-dazzler                0.0.0                h470a237_0    bioconda
pb-falcon                 0.2.7            py27hc0aa232_1    bioconda
pbalign                   0.3.2                    py27_0    bioconda
pbbam                     0.23.0               h88345a9_0    bioconda
pbcommand                 1.1.1                    py27_2    bioconda
pbcopper                  0.4.2                h3f2a3d2_1    bioconda
pbcore                    1.7.1                    py27_0    bioconda
pbgcpp                    0.0.1                         0    bioconda
pbmm2                     1.0.0                ha888412_0    bioconda
perl                      5.26.2               h14c3975_0  
pip                       19.1                     py27_0  
pycparser                 2.19                     py27_0  
pyopenssl                 19.0.0                   py27_0  
pysam                     0.15.2           py27h4b7d16d_3    bioconda
pysocks                   1.6.8                    py27_0  
python                    2.7.16               h9bab390_0  
python-edlib              1.2.3.post1      py27h470a237_0    bioconda
python-intervaltree       3.0.2                      py_0    bioconda
python-msgpack            0.5.6            py27h470a237_0    bioconda
python-sortedcontainers   2.1.0                      py_0    bioconda
pytz                      2019.1                     py_0  
racon                     1.3.2                he860b03_1    bioconda
readline                  7.0                  h7b6447c_5  
requests                  2.21.0                   py27_0  
samtools                  1.9                 h8571acd_11    bioconda
setuptools                41.0.0                   py27_0  
six                       1.12.0                   py27_0  
sqlite                    3.28.0               h7b6447c_0  
tk                        8.6.8                hbc83047_0  
traceback2                1.4.0                    py27_0  
unittest2                 1.1.0                    py27_0  
urllib3                   1.24.2                   py27_0  
wheel                     0.33.1                   py27_0  
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3```
**Describe the bug**
A clear and concise description of what the bug is.

**Error message**
Paste the error message / stack.

**To Reproduce**
Steps to reproduce the behavior. Providing a minimal test dataset on which we can reproduce the behavior will generally lead to quicker turnaround time!

**Expected behavior**
A clear and concise description of what you expected to happen.

**Comment by pb-cdunn** [comment]
Not sure of the problem, but it's definitely old code. Try `conda update --all` first. (You might want to do that in a fresh env, to avoid over-writing whatever you have if important.)

**Comment by changhan1110** [comment]
I made a new environment to run it. It works well now! Thank you very much.

**Comment by bgbrink** [comment]
I am re-opening this issue, because I have the exact same problem, even though I created a brand new environment.

```
[INFO]This is where FALCON-Phase workflow should be initialized and run.
Traceback (most recent call last):
  File "/home/bbrink/.conda/envs/falcon_assembler/bin/fc_phase.py", line 11, in <module>
    load_entry_point('falcon-phase==1.0.0', 'console_scripts', 'fc_phase.py')()
  File "/home/bbrink/.conda/envs/falcon_assembler/lib/python2.7/site-packages/falcon_phase/mains/start_falcon_phase.py", line 26, in main
    falcon_phase.run(**vars(args))
  File "/home/bbrink/.conda/envs/falcon_assembler/lib/python2.7/site-packages/falcon_phase/falcon_phase.py", line 70, in run
    falcon_phase_all(config)
  File "/home/bbrink/.conda/envs/falcon_assembler/lib/python2.7/site-packages/falcon_phase/falcon_phase.py", line 21, in falcon_phase_all
    tasks_falcon_phase.run_workflow(wf, config, rule_writer)
  File "/home/bbrink/.conda/envs/falcon_assembler/lib/python2.7/site-packages/falcon_phase/tasks/tasks_falcon_phase.py", line 322, in run_workflow
    min_aln_len, default_nproc, config, rule_writer)
  File "/home/bbrink/.conda/envs/falcon_assembler/lib/python2.7/site-packages/falcon_phase/tasks/tasks_falcon_phase.py", line 267, in add_placement_as_parallel_tasks
    job_dict=config['job.step.phase.placement'],
TypeError: gen_parallel_tasks() got multiple values for keyword argument 'run_dict'
```

Conda environment:
```
conda list
# packages in environment at /home/bbrink/.conda/envs/falcon_assembler:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
asn1crypto                1.0.1                    py27_0    conda-forge
avro-python2              1.9.0                      py_0    bioconda
bcftools                  1.9                  h68d8f2e_7    bioconda
bedtools                  2.29.0               h6ed99ea_1    bioconda
blasr                     5.3.3                h018d624_1    bioconda
blasr_libcpp              5.3.3                h018d624_1    bioconda
bwa                       0.7.17               hed695b0_6    bioconda
bzip2                     1.0.8                h516909a_1    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
certifi                   2019.9.11                py27_0    conda-forge
cffi                      1.12.3           py27h8022711_0    conda-forge
chardet                   3.0.4                 py27_1003    conda-forge
cryptography              2.7              py27h72c5cf5_0    conda-forge
curl                      7.65.3               hf8cf82a_0    conda-forge
cython                    0.29.13          py27he1b5a44_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
enum34                    1.1.6                 py27_1001    conda-forge
falcon-kit                1.3.0                    pypi_0    pypi
falcon-phase              1.0.0                    pypi_0    pypi
falcon-unzip              1.2.0                    pypi_0    pypi
future                    0.17.1                py27_1000    conda-forge
gsl                       2.5                  h294904e_1    conda-forge
h5py                      2.10.0          nompi_py27h513d04c_100    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1103    conda-forge
htslib                    1.9                  h4da6232_3    bioconda
idna                      2.8                   py27_1000    conda-forge
ipaddress                 1.0.22                     py_1    conda-forge
iso8601                   0.1.12                     py_1    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
libblas                   3.8.0               13_openblas    conda-forge
libcblas                  3.8.0               13_openblas    conda-forge
libcurl                   7.65.3               hda55be3_0    conda-forge
libdeflate                1.3                  h516909a_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
liblapack                 3.8.0               13_openblas    conda-forge
libopenblas               0.3.7                h6e990d7_1    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
linecache2                1.0.0                      py_1    conda-forge
minimap2                  2.17                 h84994c4_0    bioconda
mummer4                   4.0.0beta2      pl526hf484d3e_4    bioconda
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.2                        py_1    conda-forge
nim-falcon                0.0.1                h2f8a211_0    bioconda
numpy                     1.16.4           py27h95a1406_0    conda-forge
openssl                   1.1.1c               h516909a_0    conda-forge
pb-assembly               0.0.5                    py27_2    bioconda
pb-dazzler                0.0.1                h516909a_0    bioconda
pb-falcon                 0.2.7            py27hc0aa232_1    bioconda
pbalign                   0.3.1                    py27_2    bioconda
pbbam                     1.0.6                hc16d5b3_1    bioconda
pbcommand                 1.1.1                    py27_2    bioconda
pbcopper                  1.3.0                h3e4de3e_0    bioconda
pbcore                    1.6.5                    py27_0    bioconda
pbgcpp                    1.0.0                         0    bioconda
pbmm2                     1.1.0                hfb76ee0_0    bioconda
pcre                      8.41              hf484d3e_1003    conda-forge
perl                      5.26.2            h516909a_1006    conda-forge
pip                       19.2.3                   py27_0    conda-forge
pycparser                 2.19                     py27_1    conda-forge
pyopenssl                 19.0.0                   py27_0    conda-forge
pysam                     0.15.0.1         py27hdfb72b2_1    bioconda
pysocks                   1.7.1                    py27_0    conda-forge
python                    2.7.15            h5a48372_1009    conda-forge
python-edlib              1.3.4            py27hc9558a2_0    bioconda
python-intervaltree       3.0.2                      py_0    bioconda
python-msgpack            0.6.1            py27h6bb024c_0    bioconda
python-sortedcontainers   2.1.0                      py_0    bioconda
pytz                      2019.3                     py_0    conda-forge
racon                     1.4.7                he513fc3_0    bioconda
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.22.0                   py27_1    conda-forge
samtools                  1.9                 h10a08f8_12    bioconda
setuptools                41.4.0                   py27_0    conda-forge
six                       1.12.0                py27_1000    conda-forge
sqlite                    3.30.0               hcee41ef_0    conda-forge
tk                        8.6.9             hed695b0_1003    conda-forge
traceback2                1.4.0                    py27_0    conda-forge
unittest2                 1.1.0                      py_0    conda-forge
urllib3                   1.25.6                   py27_0    conda-forge
wheel                     0.33.6                   py27_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge

```
