### ISSUE TITLE
falcon-phase unzip style output broken

### ISSUE THREAD

**Issue by mcshane** [PacificBiosciences/pbbioconda#158]
Not sure if this is the right place to post this, but... Generating `unzip` style output using Falcon-phase with pb-assembly 0.0.6 am getting the following error:

```python -m falcon_phase.mains.emit_haplotigs ../phasing/phased.txt ../prep-emit/BC.bed ../prep-emit/p_h_ctg.fa bedtools unzip
+ python -m falcon_phase.mains.emit_haplotigs ../phasing/phased.txt ../prep-emit/BC.bed ../prep-emit/p_h_ctg.fa bedtools unzip
falcon-phase 1.1.0
Traceback (most recent call last):
  File "/software/vertres/installs/miniconda3/envs/pb-assembly-0.0.6/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/software/vertres/installs/miniconda3/envs/pb-assembly-0.0.6/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/software/vertres/installs/miniconda3/envs/pb-assembly-0.0.6/lib/python3.7/site-packages/falcon_phase/mains/emit_haplotigs.py", line 292, in <module>
    main(sys.argv)
  File "/software/vertres/installs/miniconda3/envs/pb-assembly-0.0.6/lib/python3.7/site-packages/falcon_phase/mains/emit_haplotigs.py", line 289, in main
    run(prog, phase_file, BC_bed_file, unzip_asm_file, bedtools_path, output_format)
  File "/software/vertres/installs/miniconda3/envs/pb-assembly-0.0.6/lib/python3.7/site-packages/falcon_phase/mains/emit_haplotigs.py", line 92, in run
    makeBED(BC_bed_file, output_format);
  File "/software/vertres/installs/miniconda3/envs/pb-assembly-0.0.6/lib/python3.7/site-packages/falcon_phase/mains/emit_haplotigs.py", line 279, in makeBED
    func(BC, ZERO, ONE)
  File "/software/vertres/installs/miniconda3/envs/pb-assembly-0.0.6/lib/python3.7/site-packages/falcon_phase/mains/emit_haplotigs.py", line 228, in _makeBED_unzip
    array0[3], array1[3] = array1[3], array0[3]
IndexError: list index out of range
```

Digging into the code, the below appears to fix this and I now get identical output to the original perl script (https://github.com/phasegenomics/FALCON-Phase/blob/unzip_style_output/bin/emit_haplotigs.pl)

```--- emit_haplotigs_orig.py      2019-06-17 17:58:10.000000000 +0100
+++ ./emit_haplotigs.py 2019-06-17 20:03:24.000000000 +0100
@@ -202,19 +202,19 @@
                if tup:
                        if tup.phase == 0:
                                zero_entry = '{}\t{}'.format(line, primaryID)
-                               contig_ID_A = tup.pair.split(':-')
+                               contig_ID_A = tup.pair.replace('-',':').split(':')
                                haplotigID = contig_ID_A[0]
                                contig_ID_A.append(haplotigID)
-                               one_entry = '\n'.join(contig_ID_A)
+                               one_entry = '\t'.join(contig_ID_A)
                        else:
                                one_entry = '{}\t{}'.format(line, primaryID)
-                               contig_ID_A = tup.pair.split(':-')
+                               contig_ID_A = tup.pair.replace('-',':').split(':')
                                haplotigID = contig_ID_A[0]
                                contig_ID_A.append(haplotigID)
-                               zero_entry = '\n'.join(contig_ID_A)
+                               zero_entry = '\t'.join(contig_ID_A)
                else: # collapsed haplotype
-                       zero_entry = '{}\t{}.collapsed'.format(line, primaryID)
-                       one_entry = '{}\t{}.collapsed'.format(line, primaryID)
+                       zero_entry = '{}\t{}collapsed'.format(line, primaryID)
+                       one_entry = '{}\t{}collapsed'.format(line, primaryID)
                if (primaryID != oldPID and oldPID != 'first'): # new primary
                                if (switch2(''.join(zero_bed), ''.join(one_bed))): # 0 phase most resembles original primary contig
                                        zero_bed, one_bed = one_bed, zero_bed```

**Comment by zeeev** [comment]
Hi Shane,

Would you mind sharing the inputs to the `emit_haplotigs` python script? I'll dig into the issue a bit more.

**Comment by mcshane** [comment]
Thanks @zeeev. See the links below. I think it is simply that the python re-write of `emit_haplotigs` packaged in Falcon is broken for this particular output mode.
```
s3://genomeark/species/Taeniopygia_guttata/bTaeGut2/assembly_cambridge/intermediates/falcon_phase/BC.bed
s3://genomeark/species/Taeniopygia_guttata/bTaeGut2/assembly_cambridge/intermediates/falcon_phase/p_h_ctg.fa
s3://genomeark/species/Taeniopygia_guttata/bTaeGut2/assembly_cambridge/intermediates/falcon_phase/phased.txt```

**Comment by zeeev** [comment]
Hi @mcshane,

We've tested the changes you proposed (thanks to: @skingan). Your modifications were correct for both output modes. We will update the release going forward.

Thanks for reporting the issue.
