### ISSUE TITLE
Unzip error saying ccs read has 2 regions

### ISSUE THREAD

**Issue by aclum** [PacificBiosciences/pbbioconda#160]
Hi,
I'm trying to get unzip to run on some Sequel II CCS and I'm getting the following error. The read appears to be formatted correctly and only appears on the input file once so I'm not sure what the error means.
```
[INFO 55322 MainThread 2019-06-29 00:42:27] [Proto] Read m64021_190323_205424/174656266/ccs has 2 regions.

        #grabs the names of all the CCS reads that associate with this primary contig.
        grep -w 000008F ../../../sorting/rid_to_cgt.txt > rid_to_ctg.txt
+ grep -w 000008F ../../../sorting/rid_to_cgt.txt

        #converts the CCS read names into DAZDB read ids.
        python -m falcon_unzip.mains.db_to_ccs_id --lookup ../../../readnames/readname_lookup.txt --rid-to-phase rid_to_phase.tmp --rid-to-ctg rid_to_ctg.txt --output rid_to_phase --ctg 000008F
+ python -m falcon_unzip.mains.db_to_ccs_id --lookup ../../../readnames/readname_lookup.txt --rid-to-phase rid_to_phase.tmp --rid-to-ctg rid_to_ctg.txt --output rid_to_phase --ctg 000008F
falcon-unzip 1.2.0 (pip thinks "falcon-unzip 1.2.0")
```
```py
Traceback (most recent call last):
  File "/projectb/sandbox/gaag/aclum/pb_falcon_conda_cori/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/projectb/sandbox/gaag/aclum/pb_falcon_conda_cori/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/global/projectb/sandbox/gaag/aclum/pb_falcon_conda_cori/lib/python2.7/site-packages/falcon_unzip/mains/db_to_ccs_id.py", line 77, in <module>
    main()
  File "/global/projectb/sandbox/gaag/aclum/pb_falcon_conda_cori/lib/python2.7/site-packages/falcon_unzip/mains/db_to_ccs_id.py", line 73, in main
    run(**vars(args))
  File "/global/projectb/sandbox/gaag/aclum/pb_falcon_conda_cori/lib/python2.7/site-packages/falcon_unzip/mains/db_to_ccs_id.py", line 34, in run
    out.write("%s %s %s %s\n" % (nameLookup[lc[0]], ctg, -1, 0))
KeyError: 'm64021_190323_205424/154862766/ccs'
```
```
2019-06-28 17:42:32,105 - root - WARNING - Call '/bin/bash user_script.sh' returned 256.
2019-06-28 17:42:32,105 - root - INFO - CD: '/global/projectb/scratch/aclum/sequel_II/PB1179/falcon_preads/3-unzip/0-phasing/000008F/uow-fake' -> '/global/projectb/scratch/aclum/sequel_II/PB1179/
falcon_preads/3-unzip/0-phasing/000008F/uow-fake'
2019-06-28 17:42:32,107 - root - INFO - CD: '/global/projectb/scratch/aclum/sequel_II/PB1179/falcon_preads/3-unzip/0-phasing/000008F/uow-fake' -> '/global/projectb/scratch/aclum/sequel_II/PB1179/
falcon_preads/3-unzip/0-phasing/000008F/uow-fake'
2019-06-28 17:42:32,108 - root - CRITICAL - Error in /global/projectb/sandbox/gaag/aclum/pb_falcon_conda_cori/lib/python2.7/site-packages/pypeflow/do_task.py with args="{'json_fn': '/global/proje
ctb/scratch/aclum/sequel_II/PB1179/falcon_preads/3-unzip/0-phasing/000008F/uow-fake/task.json',\n 'timeout': 30,\n 'tmpdir': None}"
```
```py
Traceback (most recent call last):
  File "/projectb/sandbox/gaag/aclum/pb_falcon_conda_cori/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/projectb/sandbox/gaag/aclum/pb_falcon_conda_cori/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/global/projectb/sandbox/gaag/aclum/pb_falcon_conda_cori/lib/python2.7/site-packages/pypeflow/do_task.py", line 281, in <module>
    main()
  File "/global/projectb/sandbox/gaag/aclum/pb_falcon_conda_cori/lib/python2.7/site-packages/pypeflow/do_task.py", line 273, in main
    run(**vars(parsed_args))
  File "/global/projectb/sandbox/gaag/aclum/pb_falcon_conda_cori/lib/python2.7/site-packages/pypeflow/do_task.py", line 267, in run
    run_cfg_in_tmpdir(cfg, tmpdir, '.')
  File "/global/projectb/sandbox/gaag/aclum/pb_falcon_conda_cori/lib/python2.7/site-packages/pypeflow/do_task.py", line 242, in run_cfg_in_tmpdir
    run_bash(bash_template, myinputs, myoutputs, parameters)
  File "/global/projectb/sandbox/gaag/aclum/pb_falcon_conda_cori/lib/python2.7/site-packages/pypeflow/do_task.py", line 201, in run_bash
    util.system(cmd)
  File "/projectb/sandbox/gaag/aclum/pb_falcon_conda_cori/lib/python2.7/site-packages/pypeflow/io.py", line 29, in syscall
    raise Exception(msg)
Exception: Call '/bin/bash user_script.sh' returned 256.
```

**Comment by zeeev** [comment]
Hi @aclum,

Can you tell me what version of the code you're using and how are you calling the code?

**Comment by aclum** [comment]
falcon-unzip 1.2.0 (pip thinks "falcon-unzip 1.2.0")
falcon-kit 1.3.0
pypeflow 2.2.0

**Comment by zeeev** [comment]
Are all the FALCON input reads also passed to FALCON-Unzip? Did you filter the reads in any way?

**Comment by aclum** [comment]
I used the same input file for both FALCON and FALCON-Unzip

**Comment by aclum** [comment]
Is there are recommendation for how to proceed here?

**Comment by zeeev** [comment]
Hi @aclum,

Apologies for the late reply. I've found the source of the issue you've described. I'm working on a fix, which should be done soon. Thank you for your patience.

**Comment by aclum** [comment]
Great. We are looking forward to the fix.

**Comment by zeeev** [comment]
Hi @aclum,

We are in the process of finalizing the new release. I'll be running validity tests tomorrow, but if you're comfortable with Conda feel free to try out the release candidate. 

https://github.com/bioconda/bioconda-recipes/pull/16736

**Comment by aclum** [comment]
I was able to get my dataset to complete with the new version of the code. Thanks!

**Comment by zeeev** [comment]
Glad to hear the good news. Thank you for reporting the issue.
