### ISSUE TITLE
Step, 3-unzip/reads, is deleting all the Fasta files with the reads.

### ISSUE THREAD

**Issue by bruc** [PacificBiosciences/pbbioconda#177]
**Operating system**
Redhat Enterprise 6

**Package name**
Falcon_unzip is the package. I did an update on July 24 and started my assembly after getting the 200K test case completed.

**Conda environment**
```
# packages in environment at /db/congenomics/local6/binaries/pbbioconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
asn1crypto                0.24.0                py37_1003    conda-forge
bcftools                  1.9                  ha228f0b_4    bioconda
beautifulsoup4            4.8.0                    py37_0    conda-forge
bedtools                  2.28.0               hdf88d34_0    bioconda
blasr                     5.3.3                h707fff8_0    bioconda
blasr_libcpp              5.3.3                h707fff8_0    bioconda
bwa                       0.7.17               h84994c4_5    bioconda
bzip2                     1.0.8                h516909a_0    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
certifi                   2019.6.16                py37_1    conda-forge
cffi                      1.12.3           py37h8022711_0    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
conda                     4.7.10                   py37_0    conda-forge
conda-build               3.18.9                   py37_0    conda-forge
conda-package-handling    1.3.11                   py37_0    conda-forge
cryptography              2.7              py37h72c5cf5_0    conda-forge
curl                      7.65.3               hf8cf82a_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
falcon-kit                1.4.2                    pypi_0    pypi
falcon-phase              1.1.0                    pypi_0    pypi
falcon-unzip              1.3.3                    pypi_0    pypi
filelock                  3.0.10                     py_0    conda-forge
future                    0.17.1                py37_1000    conda-forge
glob2                     0.7                        py_0    conda-forge
hdf5                      1.10.4          nompi_h3c11f04_1106    conda-forge
htslib                    1.9                  ha228f0b_7    bioconda
icu                       64.2                 he1b5a44_0    conda-forge
idna                      2.8                   py37_1000    conda-forge
jinja2                    2.10.1                     py_0    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
libarchive                3.3.3             hb44662c_1005    conda-forge
libblas                   3.8.0               10_openblas    conda-forge
libcblas                  3.8.0               10_openblas    conda-forge
libcurl                   7.65.3               hda55be3_0    conda-forge
libdeflate                1.0                  h14c3975_1    bioconda
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libiconv                  1.15              h516909a_1005    conda-forge
liblapack                 3.8.0               10_openblas    conda-forge
liblief                   0.9.0                hf8a498c_1    conda-forge
libopenblas               0.3.6                h6e990d7_5    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
libxml2                   2.9.9                hee79883_2    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
lzo                       2.10              h14c3975_1000    conda-forge
markupsafe                1.1.1            py37h14c3975_0    conda-forge
minimap2                  2.17                 h84994c4_0    bioconda
mummer4                   4.0.0beta2      pl526hf484d3e_4    bioconda
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.3                        py_0    conda-forge
nim-falcon                0.0.0                         0    bioconda
numpy                     1.16.4           py37h95a1406_0    conda-forge
openblas                  0.3.6                h6e990d7_5    conda-forge
openssl                   1.1.1c               h516909a_0    conda-forge
patchelf                  0.10                 he1b5a44_0    conda-forge
pb-assembly               0.0.6                    py37_5    bioconda
pb-dazzler                0.0.0                h470a237_0    bioconda
pb-falcon                 0.3.3            py37hc0aa232_0    bioconda
pbbam                     0.23.0               h88345a9_0    bioconda
pbcopper                  0.4.2                h3f2a3d2_1    bioconda
pbgcpp                    0.0.1                         0    bioconda
pbmm2                     1.0.0                ha888412_0    bioconda
perl                      5.26.2            h516909a_1006    conda-forge
pip                       19.2.1                   py37_0    conda-forge
pkginfo                   1.5.0.1                    py_0    conda-forge
psutil                    5.6.3            py37h516909a_0    conda-forge
py-lief                   0.9.0            py37he1b5a44_1    conda-forge
pycosat                   0.6.3           py37h14c3975_1001    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pysam                     0.15.2           py37h4b7d16d_3    bioconda
pysocks                   1.7.0                    py37_0    conda-forge
python                    3.7.3                h0371630_0  
python-edlib              1.2.4.post1      py37h6bb024c_0    bioconda
python-intervaltree       3.0.2                      py_0    bioconda
python-libarchive-c       2.8                   py37_1004    conda-forge
python-msgpack            0.6.1            py37h6bb024c_0    bioconda
python-sortedcontainers   2.1.0                      py_0    bioconda
pytz                      2019.1                     py_0    conda-forge
pyyaml                    5.1.1            py37h516909a_0    conda-forge
racon                     1.4.0                he860b03_0    bioconda
readline                  7.0               hf8c457e_1001    conda-forge
requests                  2.22.0                   py37_1    conda-forge
ruamel_yaml               0.15.71         py37h14c3975_1000    conda-forge
samtools                  1.9                 h8571acd_11    bioconda
setuptools                41.0.1                   py37_0    conda-forge
six                       1.12.0                py37_1000    conda-forge
soupsieve                 1.9.2                    py37_0    conda-forge
sqlite                    3.29.0               h7b6447c_0  
tk                        8.6.9             hed695b0_1002    conda-forge
tqdm                      4.32.2                     py_0    conda-forge
urllib3                   1.25.3                   py37_0    conda-forge
wheel                     0.33.4                   py37_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.1.7             h14c3975_1001    conda-forge
zlib                      1.2.11            h516909a_1005    conda-forge
zstd                      1.4.0                h3b9ef0a_0    conda-forge
```
 

**Describe the bug**
It appears that the step, 3-unzip/reads, is deleting all the Fasta files with the reads. The Fasta files with reads were placed in the top level working directory (where the 0-rawreads, 1-preads_ovl, etc. directories are written). In this step, the command,
```
python3 -m falcon_unzip.mains.pr_ctg_track --n-core=$ncore --db=../../1-preads_ovl/build/preads.db --las-fofn=../../1-preads_ovl/las-merge-combine/las_fofn.json --output=pread_to_contigs
 ```
completes normally, but the following command, 
```
python3 -m falcon_unzip.mains.fetch_reads --p-ctg=../../2-asm-falcon/p_ctg.fa --fofn=../../input.fofn --ctg-list=ctg_list
```
dies with a missing file error, and the Fasta files with the reads are now missing.

**Error message**

Please note that I have redacted the name of the genome.

```
[83996]'LA4Falcon -mo ../../1-preads_ovl/build/preads.db /clscratch/bruccro2/XXXX_genome/fc_unzip_try11/1-preads_ovl/las-merge-gathered/../las-merge-runs/m_00687/uow-00/preads.98.las'
[83996]maxrss:  3988048
[83996]finished run_tr_stage1('../../1-preads_ovl/build/preads.db', /clscratch/bruccro2/XXXX_genome/fc_unzip_try11/1-preads_ovl/las-merge-gathered/../las-merge-runs/m_0...(125), 2500, 40, dict(1818347 elem))
[83996]starting run_tr_stage1('../../1-preads_ovl/build/preads.db', /clscratch/bruccro2/XXXX_genome/fc_unzip_try11/1-preads_ovl/las-merge-gathered/../las-merge-runs/m_0...(125), 2500, 40, dict(1818347 elem))
[83996]maxrss:  3988048
[83996]'LA4Falcon -mo ../../1-preads_ovl/build/preads.db /clscratch/bruccro2/XXXX_genome/fc_unzip_try11/1-preads_ovl/las-merge-gathered/../las-merge-runs/m_00688/uow-00/preads.99.las'
[83996]maxrss:  3988048
[83996]finished run_tr_stage1('../../1-preads_ovl/build/preads.db', /clscratch/bruccro2/XXXX_genome/fc_unzip_try11/1-preads_ovl/las-merge-gathered/../las-merge-runs/m_0...(125), 2500, 40, dict(1818347 elem))
[83806]preparing tr_stage1
[83806]maxrss:    22400
[83806]len(pid_to_ctg) == 1818347
[83806]finished track_reads
# Those outputs are used only by fetch_reads.
python3 -m falcon_unzip.mains.fetch_reads --p-ctg=../../2-asm-falcon/p_ctg.fa --fofn=../../input.fofn --ctg-list=ctg_list
+ python3 -m falcon_unzip.mains.fetch_reads --p-ctg=../../2-asm-falcon/p_ctg.fa --fofn=../../input.fofn --ctg-list=ctg_list
falcon-unzip 1.3.3 (pip thinks "falcon-unzip 1.3.3")
falcon-kit 1.4.2
pypeflow 2.3.0
[INFO 2019-08-20 23:18:05,720 GMT] Counting 10,463,405,250 bytes from
  "/clscratch/bruccro2/XXXX_genome/fc_unzip_try11/2-asm-falcon/p_ctg.fa"
[INFO 2019-08-20 23:18:05,983 GMT]         #1 count=      4,430,274   0.04% 
[INFO 2019-08-20 23:18:06,431 GMT]         #3 count=     12,884,228   0.12% 
[INFO 2019-08-20 23:18:07,402 GMT]         #6 count=     24,535,658   0.23% 
[INFO 2019-08-20 23:18:09,216 GMT]        #13 count=     45,057,407   0.43% 
[INFO 2019-08-20 23:18:12,438 GMT]        #25 count=     81,889,955   0.78% 
[INFO 2019-08-20 23:18:17,910 GMT]        #51 count=    153,896,643   1.47% 
[INFO 2019-08-20 23:18:29,858 GMT]       #110 count=    297,387,615   2.84% 
[INFO 2019-08-20 23:18:55,196 GMT]       #259 count=    580,945,179   5.55% 
[INFO 2019-08-20 23:19:47,287 GMT]       #618 count=  1,148,472,331  10.98% 
[INFO 2019-08-20 23:21:30,932 GMT]     #1,478 count=  2,195,817,129  20.99% 
[INFO 2019-08-20 23:23:25,430 GMT]     #2,564 count=  3,242,178,877  30.99% 
[INFO 2019-08-20 23:25:32,192 GMT]     #3,911 count=  4,288,983,120  40.99% 
[INFO 2019-08-20 23:27:51,300 GMT]     #5,582 count=  5,335,474,001  50.99% 
[INFO 2019-08-20 23:30:31,087 GMT]     #7,687 count=  6,381,942,923  60.99% 
[INFO 2019-08-20 23:33:31,024 GMT]    #10,457 count=  7,428,324,919  70.99% 
[INFO 2019-08-20 23:37:18,711 GMT]    #14,384 count=  8,474,864,270  81.00% 
[INFO 2019-08-20 23:43:31,686 GMT]    #21,386 count=  9,521,279,241  91.00% 
Traceback (most recent call last):
  File "/db/congenomics/local6/binaries/pbbioconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/db/congenomics/local6/binaries/pbbioconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/db/congenomics/local6/binaries/pbbioconda3/lib/python3.7/site-packages/falcon_unzip/mains/fetch_reads.py", line 189, in <module>
    main()
  File "/db/congenomics/local6/binaries/pbbioconda3/lib/python3.7/site-packages/falcon_unzip/mains/fetch_reads.py", line 185, in main
    fetch_ref_and_reads(**vars(args))
  File "/db/congenomics/local6/binaries/pbbioconda3/lib/python3.7/site-packages/falcon_unzip/mains/fetch_reads.py", line 108, in fetch_ref_and_reads
    with open_fasta_reader(r_fn) as read_fa_file:
  File "/db/congenomics/local6/binaries/pbbioconda3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/db/congenomics/local6/binaries/pbbioconda3/lib/python3.7/site-packages/falcon_kit/FastaReader.py", line 232, in open_fasta_reader
    ofs = open(filename, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/clscratch/bruccro2/XXXX_genome/fc_unzip_try11/m54049_180330_232143.fasta'
2019-08-20 19:56:12,771 - root - WARNING - Call '/bin/bash user_script.sh' returned 256.
2019-08-20 19:56:12,772 - root - INFO - CD: '/clscratch/bruccro2/XXXX_genome/fc_unzip_try11/3-unzip/reads' -> '/clscratch/bruccro2/XXXX_genome/fc_unzip_try11/3-unzip/reads'
2019-08-20 19:56:12,772 - root - INFO - CD: '/clscratch/bruccro2/XXXX_genome/fc_unzip_try11/3-unzip/reads' -> '/clscratch/bruccro2/XXXX_genome/fc_unzip_try11/3-unzip/reads'
2019-08-20 19:56:12,772 - root - CRITICAL - Error in /db/congenomics/local6/binaries/pbbioconda3/lib/python3.7/site-packages/pypeflow/do_task.py with args="{'json_fn': '/clscratch/bruccro2/XXXX_genome/fc_unzip_try11/3-unzip/reads/task.json',\n 'timeout': 30,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/db/congenomics/local6/binaries/pbbioconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/db/congenomics/local6/binaries/pbbioconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/db/congenomics/local6/binaries/pbbioconda3/lib/python3.7/site-packages/pypeflow/do_task.py", line 280, in <module>
    main()
  File "/db/congenomics/local6/binaries/pbbioconda3/lib/python3.7/site-packages/pypeflow/do_task.py", line 272, in main
    run(**vars(parsed_args))
  File "/db/congenomics/local6/binaries/pbbioconda3/lib/python3.7/site-packages/pypeflow/do_task.py", line 266, in run
    run_cfg_in_tmpdir(cfg, tmpdir, '.')
  File "/db/congenomics/local6/binaries/pbbioconda3/lib/python3.7/site-packages/pypeflow/do_task.py", line 241, in run_cfg_in_tmpdir
    run_bash(bash_template, myinputs, myoutputs, parameters)
  File "/db/congenomics/local6/binaries/pbbioconda3/lib/python3.7/site-packages/pypeflow/do_task.py", line 200, in run_bash
    util.system(cmd)
  File "/db/congenomics/local6/binaries/pbbioconda3/lib/python3.7/site-packages/pypeflow/io.py", line 27, in syscall
    raise Exception(msg)
Exception: Call '/bin/bash user_script.sh' returned 256.
+++ pwd
++ echo 'FAILURE. Running top in /clscratch/bruccro2/XXXX_genome/fc_unzip_try11/3-unzip/reads (If you see -terminal database is inaccessible- you are using the python bin-wrapper, so you will not get diagnostic info. No big deal. This process is crashing anyway.)'
++ rm -f top.txt
++ which python
++ which top
++ env -u LD_LIBRARY_PATH top -b -n 1
++ env -u LD_LIBRARY_PATH top -b -n 1
++ pstree -apl

real	1704m54.615sA clear and concise description of what you expected to happen
user	1957m37.643s
sys	215m12.180s
+ finish
+ echo 'finish code: 1'
```
Paste the error message / stack.

**To Reproduce**
I've reproduced this problem once. The data is confidential, but could be shared under a non-disclosure agreement. 

**Expected behavior**
The Unzip part should finish successfully.

**Comment by pb-cdunn** [comment]
This might be caused by a relative path somewhere. Try to find out what bit of code is looking for `/clscratch/bruccro2/XXXX_genome/fc_unzip_try11/m54049_180330_232143.fasta`. You can look in `3-unzip/reads/user_script.sh`

**Comment by pb-cdunn** [comment]
Oh, btw, your versions look old. E.g.
`pb-falcon                 0.3.3`
We're at `pb-falcon-0.3.4`. Try `conda update --all`

**Comment by bruc** [comment]
I did -- couldn't find anything. I reloaded the fasta files, and modified the user_script.sh to just run the failed step. It's running now -- I'll see if it finishes.

I don't want to update the run now -- I started it just after I installed the latest code as it was at the end of July. It's taking a long time. Wouldn't it be a bad idea to update the code in the middle of a run?

**Comment by bruc** [comment]
I place the Fasta files in /clscratch/bruccro2/XXXX_genome/fc_unzip_try11 and Falcon unzip creates its 5 directories in the same location. The fasta files are there when I issue the fc_unzip.py command, but when the fc_unzip.py command fails, all the fasta files are deleted. The .fasta file was present.

I'm getting a core dump from fc_unzip.py reproducibly on this run, although it takes over a week to hit the problem. I will open another issue once I have more information.

**Comment by pb-cdunn** [comment]
I can't imagine what would delete fasta files. We usually keep everything (except .las files), to a fault! Maybe a 3p tool is deleting it.

I suggest creating a completely separate directory for a fasta file, and make the file r-only and the directory rx-only. (Double-check by trying to over-write and delete the file.) Then look for a stack-trace when something tries to delete it.

**Comment by bruc** [comment]
I wasn't able to follow your suggestion above because the output directories for Falcon Unzip were also the location of the fasta files, but I did make the fasta files readonly, and now Falcon Unzip successfully entered the 3 phase. There were no errors. So, this problem is not reproducible now.

I'll watch for it in the future.

**Comment by bruc** [comment]
One more thought -- Python core dumped prior to the deletion of the files. Could the deletion have come from pypeflow?
