### ISSUE TITLE
[ERROR]Task Node(0-rawreads/build) failed with exit-code=1

### ISSUE THREAD

**Issue by gbdias** [PacificBiosciences/pbbioconda#18]
**Operating system**
CentOS 6.5

**Package name**
pb-assembly

**Describe the bug**
PB-assembly on a very small E. coli dataset is failing with exit code 1 and some error messages.

**Error message**
```
falcon-kit 1.2.3
pypeflow 2.1.0
[INFO]Setup logging from file "None".
[INFO]$ lfs setstripe -c 12 /lustre1/gd98309/funzip/ecoli3 >
[WARNING]'lfs setstripe -c 12 /lustre1/gd98309/funzip/ecoli3' failed to produce any output.
[INFO]Lustre filesystem detected. This lfs stripe (12) should propagate to subdirs of '/lustre1/gd98309/funzip/eco
li3'.
[INFO]fc_run started with configuration fc_run.cfg
[WARNING]Unexpected keys in input config: set(['ovlp_HPCTANmask_option'])
[INFO]cfg=
{
  "General": {
    "LA4Falcon_preload": false,
    "avoid_text_file_busy": true,
    "bestn": 12,
    "dazcon": false,
    "falcon_sense_greedy": false,
    "falcon_sense_option": "--output-multi --min-idt 0.70 --min-cov 2 --max-n-read 400",
    "falcon_sense_skip_contained": false,
    "fc_ovlp_to_graph_option": " --min-len 1000",
    "genome_size": "4600000",
    "input_fofn": "input.fofn",
    "input_type": "raw",
    "length_cutoff": "-1",
    "length_cutoff_pr": "1000",
    "overlap_filtering_setting": "--max-diff 100 --max-cov 100 --min-cov 2",
    "ovlp_DBsplit_option": "-x500 -s200",
    "ovlp_HPCTANmask_option": "-l500",
    "ovlp_HPCdaligner_option": "-v -B128 -M24",
    "ovlp_daligner_option": "-e.93 -l2500 -k24 -h1024 -w6 -s100",
    "pa_DBdust_option": "True",
    "pa_DBsplit_option": "-x500 -s200",
    "pa_HPCTANmask_option": "",
    "pa_HPCdaligner_option": "-v -B128 -M24",
    "pa_REPmask_code": "0,300;0,300;0,300",
    "pa_daligner_option": "-e.8 -l2000 -k18 -h480  -w8 -s100",
    "pa_dazcon_option": "-j 4 -x -l 500",
    "pa_fasta_filter_option": "pass",
    "seed_coverage": "20",
    "skip_checks": true,
    "target": "assembly"
  },
  "job.defaults": {
    "JOB_QUEUE": "default",
    "MB": "32768",
    "NPROC": "8",
    "job_type": "local",
    "njobs": "32",
    "pwatcher_type": "blocking",
    "submit": "qsub -S /bin/bash -sync y -V  \\\n-q ${JOB_QUEUE}     \\\n-N ${JOB_NAME}      \\\n-o \"${JOB_STDOUT
}\"  \\\n-e \"${JOB_STDERR}\"  \\\n-pe smp ${NPROC}    \\\n-l h_vmem=${MB}M    \\\n\"${JOB_SCRIPT}\"",
    "use_tmpdir": false
  },
  "job.step.asm": {
    "MB": "32768",
    "NPROC": "4",
    "njobs": "3"
  },
  "job.step.cns": {
    "MB": "49152",
    "NPROC": "4",
    "njobs": "2"
  },
  "job.step.da": {},
  "job.step.la": {},
  "job.step.pda": {},
  "job.step.pla": {}
}
[INFO]In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.blocking' from '/home/gd98309/.conda/envs/falcond
a/lib/python2.7/site-packages/pwatcher/blocking.pyc'>
[INFO]job_type='local', (default)job_defaults={'JOB_QUEUE': 'default', 'pwatcher_type': 'blocking', 'use_tmpdir': 
False, 'MB': '32768', 'job_type': 'local', 'submit': 'qsub -S /bin/bash -sync y -V  \\\n-q ${JOB_QUEUE}     \\\n-N
 ${JOB_NAME}      \\\n-o "${JOB_STDOUT}"  \\\n-e "${JOB_STDERR}"  \\\n-pe smp ${NPROC}    \\\n-l h_vmem=${MB}M    
\\\n"${JOB_SCRIPT}"', 'NPROC': '8', 'njobs': '32'}, use_tmpdir=False, squash=False, job_name_style=0
[INFO]Setting max_jobs to 32; was None
[INFO]Num unsatisfied: 2, graph: 2
[INFO]About to submit: Node(0-rawreads/build)
[INFO]Popen: 'qsub -S /bin/bash -sync y -V  \
-q default     \
-N Pa93d51772c1627      \
-o "/lustre1/gd98309/funzip/ecoli3/0-rawreads/build/run-Pa93d51772c1627.bash.stdout"  \
-e "/lustre1/gd98309/funzip/ecoli3/0-rawreads/build/run-Pa93d51772c1627.bash.stderr"  \
-pe smp 1    \
-l h_vmem=4000M    \
"/home/gd98309/.conda/envs/falconda/lib/python2.7/site-packages/pwatcher/mains/job_start.sh"'
[INFO](slept for another 0.0s -- another 1 loop iterations)
qsub: script file 'y' cannot be loaded - No such file or directory
[ERROR]Task Node(0-rawreads/build) failed with exit-code=1
[ERROR]Some tasks are recently_done but not satisfied: set([Node(0-rawreads/build)])
[ERROR]ready: set([])
	submitted: set([])
[ERROR]Noop. We cannot kill blocked threads. Hopefully, everything will die on SIGTERM.
Traceback (most recent call last):
  File "/home/gd98309/.conda/envs/falconda/bin/fc_run", line 11, in <module>
    load_entry_point('falcon-kit==1.2.3', 'console_scripts', 'fc_run')()
  File "/home/gd98309/.conda/envs/falconda/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 726, in mai
n
    main1(argv[0], args.config, args.logger)
  File "/home/gd98309/.conda/envs/falconda/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 76, in main
1
    input_fofn_fn=input_fofn_fn,
  File "/home/gd98309/.conda/envs/falconda/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 242, in run
    dist=Dist(NPROC=4, MB=4000, job_dict=config['job.step.da']),
  File "/home/gd98309/.conda/envs/falconda/lib/python2.7/site-packages/falcon_kit/pype.py", line 106, in gen_paral
lel_tasks
    wf.refreshTargets()
  File "/home/gd98309/.conda/envs/falconda/lib/python2.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 2
77, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/home/gd98309/.conda/envs/falconda/lib/python2.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 3
61, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: set([Node(0-rawreads/build)])
```

**To Reproduce**
- I am using this E. coli test dataset:
https://github.com/PacificBiosciences/DevNet/wiki/E.-coli-Bacterial-Assembly

- I am only using one of the subreads fasta file.

Here is my script:

```
ml Miniconda3
source activate /home/gd98309/.conda/envs/falconda

cd $OUTDIR

fc_run fc_run.cfg &> falcon-$PBS_JOBID.log

source deactivate
ml unload Miniconda3
```

**Comment by armintoepfer** [comment]
Thank you, we'll look into it.

**Comment by gconcepcion** [comment]
Hi @gbdias 

Your run is failing in the initial step during the building of the read database.

The actual error would be found here:
`0-rawreads/build/run-*.bash.stderr`

Were you successful running the test example here?
https://github.com/PacificBiosciences/pb-assembly#example-data-set

It's generally better to ensure the test dataset works prior to running your own data to rule out installation problems.

**Comment by gbdias** [comment]
Hi guys,
Thanks a lot for the quick reply.

- I suspect this has to do with resource allocation.
- I just ran the test dataset with the same script but with the test cfg file from the FALCON-examples repo and it completed both Falcon and Unzip.

- Test cfg file from the greg run:
```
[General]
#sge_option_da =
#sge_option_la =
#sge_option_pda =
#sge_option_pla =
#sge_option_cns =
#sge_option_fc =
#pwatcher_type = blocking
#job_type = string
#job_queue = bash -C ${CMD} >| ${STDOUT_FILE} 2>| ${STDERR_FILE}

# list of files of the initial bas.h5 files
input_fofn = input.fofn
#input_fofn = preads.fofn

input_type = raw
#input_type = preads

#openending = True

# The length cutoff used for seed reads used for initial mapping
length_cutoff = 1000
genome_size = 200000
#seed_coverage = 60

# The length cutoff used for seed reads usef for pre-assembly
length_cutoff_pr = 1

#pa_REPmask_code = 1,300;0,300;0,300
pa_daligner_option   = -e.8 -l3200 -k18 -h480  -w8 -s100
ovlp_daligner_option = -e.9 -l2500 -k24 -h1024 -w6 -s100
pa_HPCdaligner_option   =  -v -B128 -M24
ovlp_HPCdaligner_option =  -v -B128 -M24
#pa_HPCTANmask_option = -k18 -h480 -w8 -e.8 -s100
#pa_HPCREPmask_option = -k18 -h480 -w8 -e.8 -s100

pa_DBsplit_option = -a -x500 -s4
ovlp_DBsplit_option = -s100

falcon_sense_option = --output-multi --min-cov-aln 4 --min-idt 0.70 --min-cov 4 --max-n-read 200 --n-core 8
falcon_sense_skip_contained = False

overlap_filtering_setting = --max-diff 120 --max-cov 120 --min-cov 2 --n-core 8
#dazcon = 1

[job.defaults]
job_type = local

#use_tmpdir = /scratch
pwatcher_type = blocking
job_type = string
submit = bash -C ${CMD} >| ${STDOUT_FILE} 2>| ${STDERR_FILE}
#job_queue = bash -C ${CMD}
# By dropping STD*_FILE, we see all output on the console.
# That helps debugging in TravisCI/Bamboo.

NPROC=4
#njobs=1
[job.step.da]
[job.step.pda]
[job.step.la]
#NPROC=1
[job.step.pla]
#NPROC=1
[job.step.cns]
#njobs=1
NPROC=8
[job.step.asm]
NPROC=32
```

- My cfg file for E. coli
```
#### Input
[General]
input_fofn=input.fofn
input_type=raw
pa_DBdust_option=True
pa_fasta_filter_option=pass
target=assembly
skip_checks=True
LA4Falcon_preload=false

#### Data Partitioning
pa_DBsplit_option=-x500 -s200
ovlp_DBsplit_option=-x500 -s200

#### Repeat Masking
pa_HPCTANmask_option=
pa_REPmask_code=0,300;0,300;0,300

####Pre-assembly
genome_size=4600000
seed_coverage=20
length_cutoff=-1 
pa_HPCdaligner_option=-v -B128 -M24
pa_daligner_option=-e.8 -l2000 -k18 -h480  -w8 -s100
falcon_sense_option=--output-multi --min-idt 0.70 --min-cov 2 --max-n-read 400
falcon_sense_greedy=False

####Pread overlapping
ovlp_daligner_option=-e.93 -l2500 -k24 -h1024 -w6 -s100
ovlp_HPCdaligner_option=-v -B128 -M24

####Final Assembly
overlap_filtering_setting=--max-diff 100 --max-cov 100 --min-cov 2
fc_ovlp_to_graph_option=
length_cutoff_pr=1000

[job.defaults]
job_type=local
pwatcher_type=blocking
JOB_QUEUE=default
MB=32768
NPROC=8
njobs=32
submit = qsub -S /bin/bash -sync y -V  \
  -q ${JOB_QUEUE}     \
  -N ${JOB_NAME}      \
  -o "${JOB_STDOUT}"  \
  -e "${JOB_STDERR}"  \
  -pe smp ${NPROC}    \
  -l h_vmem=${MB}M    \
  "${JOB_SCRIPT}"

[job.step.da]
# NPROC=4
# MB=32768
# njobs=240
[job.step.la]
# NPROC=4
# MB=32768
# njobs=240
[job.step.cns]
NPROC=4
MB=49152
njobs=2
[job.step.pda]
# NPROC=4
# MB=32768
# njobs=240
[job.step.pla]
# NPROC=4
# MB=32768
# njobs=240
[job.step.asm]
NPROC=4
MB=32768
njobs=3
```

- I am having a hard time figuring out how should I scale it up on a bigger machine, but in local mode (not sge). Do you guys have any recommendation on how to do this?

Thanks,
Guilherme

**Comment by gconcepcion** [comment]
@gbdias 
Ahh- the `greg200k-sv2` run was in local mode, your ecoli job was run in `sge` mode.
I missed this line in your first post:
`qsub: script file 'y' cannot be loaded - No such file or directory`

Something is going wrong w/ your submit.

The `qsub` string *appears* correct in the `all.log`. 

Can you post the contents of your `fc_run.cfg`?

**Comment by gbdias** [comment]
Hi Greg,

My `fc_run.cfg` is the last one I just posted. I though it was in local mode cause I used the `job_type = local` flag.
Do I also need the `job_type = string` and `submit = bash -C ${CMD} >| ${STDOUT_FILE} 2>| ${STDERR_FILE}` for local mode?

**Comment by gconcepcion** [comment]
@gbdias Ahh.

The `greg200k-sv2` example was run in local mode w/ a local mode `submit` string.
You ran the ecoli job in `local` mode w/ an `sge` submit string.

For local mode, you need to run w/ the local mode submit line:
`bash -C ${CMD} >| ${STDOUT_FILE} 2>| ${STDERR_FILE}`
See also the **Job Distribution** section here:
https://github.com/PacificBiosciences/pb-assembly#configuration

**Comment by gbdias** [comment]
Okie dokie.
I will fix this and try again!
Thanks

**Comment by gbdias** [comment]
- It worked this time!
Thanks a lot guys

Guilherme

**Comment by wuxiaopei0509** [comment]
I have the similar problem at 0-rawreads/cns-runs stage and I check the run-Pec6a2970c36c74.bash.stderr .I found the job was killed nonarbitrary;the error info as follows:
2019-09-27 14:12:07,314 - root - CRITICAL - Error in /data/wuxiaopei/conda/envs/dujuan_denovo_pb-assembly0.0.4/lib/python2.7/site-packages/pypeflow/do_task.py with args="{'json_fn': '/1data/wuxiaopei/zhejiangdaxue_dujuan/Falcon_assembly/0-rawreads/cns-runs/cns_00043/task.json',\n 'timeout': 30,\n 'tmpdir': None}"
Could y help me with it? Thanks a lot.

**Comment by pb-cdunn** [comment]
Hmmm. If there is nothing in stderr, my best guess is that your job-distributor killed it for exceeding some resource limits.
