### ISSUE TITLE
Falcon Unzip CCS Python SyntaxError: more than 255 arguments

### ISSUE THREAD

**Issue by EdHarry** [PacificBiosciences/pbbioconda#187]
**Operating system**
Linux

**Package name**
falcon-unzip 1.3.4

**Conda environment**
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
bcftools                  1.8                  h4da6232_3    bioconda
bedtools                  2.26.0                        0    bioconda
blasr                     5.3.3                h018d624_1    bioconda
blasr_libcpp              5.3.3                h018d624_1    bioconda
bwa                       0.7.17               hed695b0_6    bioconda
bzip2                     1.0.8                h516909a_0    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
certifi                   2019.6.16                py36_1    conda-forge
clang                     8.0.1                hc9558a2_0    conda-forge
curl                      7.65.3               hf8cf82a_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
falcon-kit                1.4.4                    pypi_0    pypi
falcon-phase              1.1.0                    pypi_0    pypi
falcon-unzip              1.3.4                    pypi_0    pypi
future                    0.17.1                py36_1000    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1103    conda-forge
htslib                    1.9                  h4da6232_3    bioconda
krb5                      1.16.3            h05b26f9_1001    conda-forge
libblas                   3.8.0               12_openblas    conda-forge
libcblas                  3.8.0               12_openblas    conda-forge
libcurl                   7.65.3               hda55be3_0    conda-forge
libcxx                    8.0.1                         0    conda-forge
libcxxabi                 8.0.1                         0    conda-forge
libdeflate                1.3                  h516909a_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
liblapack                 3.8.0               12_openblas    conda-forge
libllvm8                  8.0.1                hc9558a2_0    conda-forge
libopenblas               0.3.7                h6e990d7_1    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
minimap2                  2.17                 h84994c4_0    bioconda
mummer4                   4.0.0beta2      pl526hf484d3e_4    bioconda
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.3                        py_0    conda-forge
nim-falcon                0.0.1                h2f8a211_0    bioconda
numpy                     1.17.1           py36h95a1406_0    conda-forge
openssl                   1.1.1c               h516909a_0    conda-forge
pb-assembly               0.0.6                    py36_5    bioconda
pb-dazzler                0.0.1                h516909a_0    bioconda
pb-falcon                 0.3.4            py36hed50d52_0    bioconda
pbbam                     1.0.6                hc16d5b3_1    bioconda
pbcopper                  1.3.0                h3e4de3e_0    bioconda
pbgcpp                    0.0.1                         0    bioconda
pbmm2                     1.1.0                hfb76ee0_0    bioconda
pcre                      8.41              hf484d3e_1003    conda-forge
perl                      5.26.2            h516909a_1006    conda-forge
pip                       19.2.3                   py36_0    conda-forge
pysam                     0.11.2.2                 py36_1    bioconda
python                    3.6.7             h357f687_1005    conda-forge
python-edlib              1.3.4            py36hc9558a2_0    bioconda
python-intervaltree       3.0.2                      py_0    bioconda
python-msgpack            0.6.1            py36h6bb024c_0    bioconda
python-sortedcontainers   2.1.0                      py_0    bioconda
racon                     1.4.3                he513fc3_0    bioconda
readline                  8.0                  hf8c457e_0    conda-forge
samtools                  1.6                  h244ad75_4    bioconda
setuptools                41.2.0                   py36_0    conda-forge
sqlite                    3.29.0               hcee41ef_1    conda-forge
tk                        8.6.9             hed695b0_1002    conda-forge
wheel                     0.33.6                   py36_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h516909a_1005    conda-forge
```

**Describe the bug**
fc_unzip.py fails with the error: "SyntaxError: more than 255 arguments"

**Error message**
```
2019-09-05 08:01:09,714 - fc_run:199 - ERROR - Error for run(target=ccs, config_fn=fc_unzip, logging_config_fn=None)
Traceback (most recent call last):
  File "/nfs/users/nfs_e/eh15/anaconda3/envs/Falcon/lib/python3.6/site-packages/falcon_unzip/unzip.py", line 195, in run
    run_logged(target, config_fn)
  File "/nfs/users/nfs_e/eh15/anaconda3/envs/Falcon/lib/python3.6/site-packages/falcon_unzip/unzip.py", line 181, in run_logged
    ccs_all(config, unzip_config_fn)
  File "/nfs/users/nfs_e/eh15/anaconda3/envs/Falcon/lib/python3.6/site-packages/falcon_unzip/unzip.py", line 42, in ccs_all
    tasks_ccs.run_workflow(wf, config, unzip_config_fn)
  File "/nfs/users/nfs_e/eh15/anaconda3/envs/Falcon/lib/python3.6/site-packages/falcon_unzip/tasks/ccs.py", line 392, in run_workflow
    dist=dist_local,
  File "/nfs/users/nfs_e/eh15/anaconda3/envs/Falcon/lib/python3.6/site-packages/falcon_kit/pype.py", line 59, in wrap_gen_task
    pt = pype_gen_task(script, inputs, outputs, params, dist)
  File "/nfs/users/nfs_e/eh15/anaconda3/envs/Falcon/lib/python3.6/site-packages/pypeflow/tasks.py", line 60, in gen_task
    validate_dict(inputs)
  File "/nfs/users/nfs_e/eh15/anaconda3/envs/Falcon/lib/python3.6/site-packages/pypeflow/tasks.py", line 56, in validate_dict
    collections.namedtuple('validate', list(mydict.keys()))
  File "/nfs/users/nfs_e/eh15/anaconda3/envs/Falcon/lib/python3.6/collections/__init__.py", line 429, in namedtuple
    exec(class_definition, namespace)
  File "<string>", line 12
SyntaxError: more than 255 arguments
```
[all.log.zip](https://github.com/PacificBiosciences/pbbioconda/files/3578186/all.log.zip)

**Comment by pb-cdunn** [comment]
I didn't realize that was a problem. However, [python3.7 allows it](https://stackoverflow.com/questions/26766076/pass-more-than-255-arguments-to-a-function).
```
python                    3.6.7
```
We actually stopped supporting py3.6 as of, well, today I think. We _could_ add that back. I dropped it only because `bioconda-utils build` was failing for me locally with no discernible error exception py3.6, but I _think_ we could add it back. If absolutely needed, please re-open and let us know.
