### ISSUE TITLE
RuntimeError "dictionary changed size during iteration" in 2-asm-falcon

### ISSUE THREAD

**Issue by changhan1110** [PacificBiosciences/pbbioconda#190]
**Operating system**
Ubuntu 14.04.2 LTS

**Package name**
Which package / tool is causing the problem? Which version are you using, use `tool --version`. Have you updated to the latest version `conda update package`? Have you updated the complete env by running `conda update --all`? Have you ensured that your channel priorities are set up according to the bioconda recommendations at https://bioconda.github.io/#set-up-channels?

**Conda environment**
```
bedtools                  2.28.0               hdf88d34_0    bioconda
blas                      1.0                         mkl  
blasr                     5.3.3                h707fff8_0    bioconda
blasr_libcpp              5.3.3                h707fff8_0    bioconda
bwa                       0.7.17               h84994c4_5    bioconda
bzip2                     1.0.6                h14c3975_5  
ca-certificates           2019.1.23                     0  
certifi                   2019.3.9                 py37_0  
curl                      7.64.1               hbc83047_0  
decorator                 4.4.0                    py37_1  
falcon-kit                1.4.1                    pypi_0    pypi
falcon-phase              1.1.0                    pypi_0    pypi
falcon-unzip              1.3.0                    pypi_0    pypi
future                    0.17.1                   py37_0  
hdf5                      1.10.4               hb1b8bf9_0  
htslib                    1.9                  ha228f0b_7    bioconda
intel-openmp              2019.3                      199  
krb5                      1.16.1               h173b8e3_7  
libcurl                   7.64.1               h20c2e04_0  
libdeflate                1.0                  h14c3975_1    bioconda
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran-ng            7.3.0                hdf63c60_0  
libssh2                   1.8.2                h1ba5d50_0  
libstdcxx-ng              8.2.0                hdf63c60_1  
minimap2                  2.17                 h84994c4_0    bioconda
mkl                       2019.3                      199  
mkl_fft                   1.0.12           py37ha843d7b_0  
mkl_random                1.0.2            py37hd81dba3_0  
mummer4                   4.0.0beta2      pl526hf484d3e_4    bioconda
ncurses                   6.1                  he6710b0_1  
networkx                  2.3                        py_0  
nim-falcon                0.0.0                         0    bioconda
numpy                     1.16.3           py37h7e9f1db_0  
numpy-base                1.16.3           py37hde5b4d6_0  
openssl                   1.1.1b               h7b6447c_1  
pb-assembly               0.0.6                    py37_5    bioconda
pb-dazzler                0.0.0                h470a237_0    bioconda
pb-falcon                 0.3.0            py37hc0aa232_1    bioconda
pbbam                     0.23.0               h88345a9_0    bioconda
pbcopper                  0.4.2                h3f2a3d2_1    bioconda
pbgcpp                    0.0.1                         0    bioconda
pbmm2                     1.0.0                ha888412_0    bioconda
perl                      5.26.2               h14c3975_0  
pip                       19.1                     py37_0  
python                    3.7.3                h0371630_0  
python-edlib              1.2.4            py37h6bb024c_0    bioconda
python-intervaltree       3.0.2                      py_0    bioconda
python-msgpack            0.6.1            py37h6bb024c_0    bioconda
python-sortedcontainers   2.1.0                      py_0    bioconda
racon                     1.3.2                he860b03_1    bioconda
readline                  7.0                  h7b6447c_5  
samtools                  1.9                 h8571acd_11    bioconda
setuptools                41.0.1                   py37_0  
sqlite                    3.28.0               h7b6447c_0  
tk                        8.6.8                hbc83047_0  
wheel                     0.33.1                   py37_0  
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3
```
**Describe the bug**

**Error message**
Paste the error message / stack.
```
[22153]finished ovlp_filter

real    81m51.822s
user    319m41.531s
sys     26m12.786s

ln -sf ../1-preads_ovl/db2falcon/preads4falcon.fasta ./preads4falcon.fasta
+ ln -sf ../1-preads_ovl/db2falcon/preads4falcon.fasta ./preads4falcon.fasta

# Given preads.ovl,
# write sg_edges_list, c_path, utg_data, ctg_paths.
time python3 -m falcon_kit.mains.ovlp_to_graph  --min-len 10000 --overlap-file preads.ovl >| fc_ovlp_to_graph.log
+ python3 -m falcon_kit.mains.ovlp_to_graph --min-len 10000 --overlap-file preads.ovl
falcon-kit 1.4.1
Traceback (most recent call last):
  File "/BiO/Access/changhan/miniconda2/envs/denovo_asm/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/BiO/Access/changhan/miniconda2/envs/denovo_asm/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/BiO/Access/changhan/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/falcon_kit/mains/ovlp_to_graph.py", line 1600, in <module>
    main(sys.argv)
  File "/BiO/Access/changhan/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/falcon_kit/mains/ovlp_to_graph.py", line 1596, in main
    ovlp_to_graph(args)
  File "/BiO/Access/changhan/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/falcon_kit/mains/ovlp_to_graph.py", line 1418, in ovlp_to_graph
    ug2 = identify_spurs(ug, u_edge_data, 50000)
  File "/BiO/Access/changhan/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/falcon_kit/mains/ovlp_to_graph.py", line 1207, in identify_spurs
    for s, t, v in ug2.out_edges(v1, keys=True):
  File "/BiO/Access/changhan/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/networkx/classes/reportviews.py", line 806, in <genexpr>
    for nbr, kd in nbrs.items() for k, dd in kd.items())
RuntimeError: dictionary changed size during iteration
2019-09-10 16:01:49,400 - root - WARNING - Call '/bin/bash user_script.sh' returned 256.
2019-09-10 16:01:49,401 - root - INFO - CD: '/BiO/Research/Project1/KOGIC-KOREF_v2_PacBio-Genome-2018-11/Workspace/falcon_koref_93x_daligner_threads-4_dbblocksize-400/2-asm-falcon' -> '/BiO/Research/Project1/KOGIC-KOREF_v2_PacBio-Genome-2018-11/Workspace/falcon_koref_93x_daligner_threads-4_dbblocksize-400/2-asm-falcon'
2019-09-10 16:01:49,401 - root - INFO - CD: '/BiO/Research/Project1/KOGIC-KOREF_v2_PacBio-Genome-2018-11/Workspace/falcon_koref_93x_daligner_threads-4_dbblocksize-400/2-asm-falcon' -> '/BiO/Research/Project1/KOGIC-KOREF_v2_PacBio-Genome-2018-11/Workspace/falcon_koref_93x_daligner_threads-4_dbblocksize-400/2-asm-falcon'
2019-09-10 16:01:49,401 - root - CRITICAL - Error in /BiO/Access/changhan/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/pypeflow/do_task.py with args="{'json_fn': '/BiO/Research/Project1/KOGIC-KOREF_v2_PacBio-Genome-2018-11/Workspace/falcon_koref_93x_daligner_threads-4_dbblocksize-400/2-asm-falcon/task.json',\n 'timeout': 30,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/BiO/Access/changhan/miniconda2/envs/denovo_asm/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/BiO/Access/changhan/miniconda2/envs/denovo_asm/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/BiO/Access/changhan/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/pypeflow/do_task.py", line 280, in <module>
    main()
  File "/BiO/Access/changhan/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/pypeflow/do_task.py", line 272, in main
    run(**vars(parsed_args))
  File "/BiO/Access/changhan/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/pypeflow/do_task.py", line 266, in run
    run_cfg_in_tmpdir(cfg, tmpdir, '.')
  File "/BiO/Access/changhan/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/pypeflow/do_task.py", line 241, in run_cfg_in_tmpdir
    run_bash(bash_template, myinputs, myoutputs, parameters)
  File "/BiO/Access/changhan/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/pypeflow/do_task.py", line 200, in run_bash
    util.system(cmd)
  File "/BiO/Access/changhan/miniconda2/envs/denovo_asm/lib/python3.7/site-packages/pypeflow/io.py", line 27, in syscall
    raise Exception(msg)
Exception: Call '/bin/bash user_script.sh' returned 256.
pwd
```
**To Reproduce**
Steps to reproduce the behavior. Providing a minimal test dataset on which we can reproduce the behavior will generally lead to quicker turnaround time!

**Expected behavior**

Can you help me why this error occurred and how to solve it? 
I already read this post (https://github.com/PacificBiosciences/FALCON/issues/687) and try ```conda update --all```, but it didn't work well.

**Comment by pb-cdunn** [comment]
The **networkx** upgrade broke some things. You have:
```py
  File ".../falcon_kit/mains/ovlp_to_graph.py", line 1207, in identify_spurs
    for s, t, v in ug2.out_edges(v1, keys=True):
```
But we have:
```py
1206             v1 = s_path[0]
1207             for v2 in s_path[1:]:
1208                 for s, t, v in list(ug2.out_edges(v1, keys=True)):
```
I'm not 100% certain that fix for the latest **networkx** is in Bioconda yet, but first try `conda update --all`. `conda list` shows your conda packages, but at runtime you should see your `falcon_kit` and `falcon_unzip` versions. We are currently on `1.7.0`, but earlier should be ok since we fixed that several months ago:
```diff
commit 10ab8d810dbec8c7e3735240ebe1d88d2fc59f1e
Author: Christopher Dunn <cdunn@pacificbiosciences.com>
Date:   Tue May 7 12:07:42 2019

    Fix for networkx update

diff --git falcon_kit/mains/ovlp_to_graph.py falcon_kit/mains/ovlp_to_graph.py
index 4099645..7a70a1a 100644
--- falcon_kit/mains/ovlp_to_graph.py
+++ falcon_kit/mains/ovlp_to_graph.py
@@ -1204,7 +1204,7 @@ def identify_spurs(ug, u_edge_data, spur_len):

             v1 = s_path[0]
             for v2 in s_path[1:]:
-                for s, t, v in ug2.out_edges(v1, keys=True):
+                for s, t, v in list(ug2.out_edges(v1, keys=True)):
```
