### ISSUE TITLE
falcon_unzip3 getting exception from empty phasing results

### ISSUE THREAD

**Issue by flowers9** [PacificBiosciences/pbbioconda#196]
**Operating system**
Linux Ubuntu

**Package name**
falcon_unzip 1.3.1
falcon-kit 1.4.2
pypeflow 2.3.0

I just installed and updated them, as best I could.  Some related packages didn't support python3, and it wasn't obvious exactly which should be installed in which environment.

**Conda environment**
```
# packages in environment at /home/raid2/LINUXOPT/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
asn1crypto                0.24.0                py36_1003    conda-forge
bcftools                  1.9                  h68d8f2e_7    bioconda
bedtools                  2.29.0               h6ed99ea_1    bioconda
blasr                     5.3.3                h018d624_1    bioconda
blasr_libcpp              5.3.3                h018d624_1    bioconda
bwa                       0.7.17               hed695b0_6    bioconda
bzip2                     1.0.8                h516909a_1    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
certifi                   2019.9.11                py36_0    conda-forge
cffi                      1.12.3           py36h8022711_0    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
conda                     4.7.12                   py36_0    conda-forge
conda-package-handling    1.4.1                    py36_0    conda-forge
cryptography              2.7              py36h72c5cf5_0    conda-forge
curl                      7.65.3               hf8cf82a_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
falcon-kit                1.4.2                    pypi_0    pypi
falcon-phase              1.1.0                    pypi_0    pypi
falcon-unzip              1.3.1                    pypi_0    pypi
future                    0.17.1                py36_1000    conda-forge
gsl                       2.5                  h294904e_1    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1103    conda-forge
htslib                    1.9                  h4da6232_3    bioconda
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.8                   py36_1000    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
libarchive                3.3.3             hb44662c_1005    conda-forge
libblas                   3.8.0               12_openblas    conda-forge
libcblas                  3.8.0               12_openblas    conda-forge
libcurl                   7.65.3               hda55be3_0    conda-forge
libdeflate                1.2                  h516909a_1    bioconda
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libiconv                  1.15              h516909a_1005    conda-forge
liblapack                 3.8.0               12_openblas    conda-forge
libopenblas               0.3.7                h6e990d7_1    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
libxml2                   2.9.9                hee79883_5    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
lzo                       2.10              h14c3975_1000    conda-forge
minimap2                  2.17                 h84994c4_0    bioconda
mummer4                   4.0.0beta2      pl526hf484d3e_4    bioconda
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.3                        py_0    conda-forge
nim-falcon                0.0.1                h2f8a211_0    bioconda
numpy                     1.17.2           py36h95a1406_0    conda-forge
openssl                   1.1.1c               h516909a_0    conda-forge
pb-assembly               0.0.6                    py36_5    bioconda
pb-dazzler                0.0.1                h516909a_0    bioconda
pb-falcon                 0.3.1            py36hc0aa232_0    bioconda
pbbam                     1.0.6                hc16d5b3_1    bioconda
pbcopper                  1.3.0                h3e4de3e_0    bioconda
pbgcpp                    1.0.0                         0    bioconda
pbmm2                     1.1.0                hfb76ee0_0    bioconda
pcre                      8.41              hf484d3e_1003    conda-forge
perl                      5.26.2            h516909a_1006    conda-forge
pip                       19.2.3                   py36_0    conda-forge
pycosat                   0.6.3           py36h14c3975_1001    conda-forge
pycparser                 2.19                     py36_1    conda-forge
pyopenssl                 19.0.0                   py36_0    conda-forge
pysam                     0.11.2.2                 py36_1    bioconda
pysocks                   1.7.0                    py36_0    conda-forge
python                    3.6.7             h357f687_1005    conda-forge
python-edlib              1.3.4            py36hc9558a2_0    bioconda
python-intervaltree       3.0.2                      py_0    bioconda
python-libarchive-c       2.8                   py36_1004    conda-forge
python-msgpack            0.6.1            py36h6bb024c_0    bioconda
python-sortedcontainers   2.1.0                      py_0    bioconda
racon                     1.4.3                he513fc3_0    bioconda
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.22.0                   py36_1    conda-forge
ruamel_yaml               0.15.71         py36h14c3975_1000    conda-forge
samtools                  1.9                 h10a08f8_12    bioconda
setuptools                41.2.0                   py36_0    conda-forge
six                       1.12.0                py36_1000    conda-forge
sqlite                    3.29.0               hcee41ef_1    conda-forge
tk                        8.6.9             hed695b0_1003    conda-forge
tqdm                      4.7.2                    py36_0    bioconda
urllib3                   1.25.3                   py36_0    conda-forge
wheel                     0.33.6                   py36_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.1.7             h14c3975_1001    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.0                h3b9ef0a_0    conda-forge
```

**Describe the bug**
When running 0-phase, some tasks fail when a grep fails to match.  Judging from the code, this is not supposed to happen (match failures are meant to pass through).  From tasks/ccs.py:

```
        #grabs the names of all the CCS reads that associate with this primary contig.
        (
        set -vx +e
        grep -w {params.ctg} {input.RID_TO_CTG} >| rid_to_ctg.txt
        )
```

**Error message**
```
2019-09-19 04:06:53,063 - root - CRITICAL - Error in /home/raid2/LINUXOPT/miniconda3/lib/python3.6/site-packages/pypeflow/do_task.py with args="{'json_fn': '/home/f2p1/flowers/ccs.test/falcon_bean/3-unzip/0-phasing/001465F/uow-fake/task.json',\n 'timeout': 30,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/home/raid2/LINUXOPT/miniconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/raid2/LINUXOPT/miniconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/raid2/LINUXOPT/miniconda3/lib/python3.6/site-packages/pypeflow/do_task.py", line 280, in <module>
    main()
  File "/home/raid2/LINUXOPT/miniconda3/lib/python3.6/site-packages/pypeflow/do_task.py", line 272, in main
    run(**vars(parsed_args))
  File "/home/raid2/LINUXOPT/miniconda3/lib/python3.6/site-packages/pypeflow/do_task.py", line 266, in run
    run_cfg_in_tmpdir(cfg, tmpdir, '.')
  File "/home/raid2/LINUXOPT/miniconda3/lib/python3.6/site-packages/pypeflow/do_task.py", line 241, in run_cfg_in_tmpdir
    run_bash(bash_template, myinputs, myoutputs, parameters)
  File "/home/raid2/LINUXOPT/miniconda3/lib/python3.6/site-packages/pypeflow/do_task.py", line 200, in run_bash
    util.system(cmd)
  File "/home/raid2/LINUXOPT/miniconda3/lib/python3.6/site-packages/pypeflow/io.py", line 27, in syscall
    raise Exception(msg)
Exception: Call '/bin/bash user_script.sh' returned 256.
```

**To Reproduce**
Steps to reproduce the behavior. Providing a minimal test dataset on which we can reproduce the behavior will generally lead to quicker turnaround time!

**Expected behavior**
Given the "set +e", a failure to match should probably not cause an exception.  The work-around I'm using is to append

`|| /bin/true`

to the grep command

**Comment by dbrowneup** [comment]
Hi @flowers9 this issue tracker is intended for our software developers, but you can submit your problem to support@pacb.com and we will work with you to resolve the problem!

**Comment by flowers9** [comment]
Right, I found what looked like a bug in your code and offered a fix for
it.  That sounds like something that should go to software developers.

**Comment by pb-dseifert** [comment]
@flowers9 feel free to attach your suggested patch here

**Comment by flowers9** [comment]
Whoops, I accidentally quoted your code above with the patch in place.  I'll edit that in a sec.  But here's the patch I used:

```
--- falcon_unzip/tasks/ccs.py.orig      2019-09-19 12:23:57.418136453 -0500
+++ falcon_unzip/tasks/ccs.py   2019-09-19 12:22:57.474997870 -0500
@@ -176,7 +176,7 @@
         #grabs the names of all the CCS reads that associate with this primary contig.
         (
         set -vx +e
-        grep -w {params.ctg} {input.RID_TO_CTG} >| rid_to_ctg.txt
+        grep -w {params.ctg} {input.RID_TO_CTG} >| rid_to_ctg.txt || /bin/true
         )
 
         #converts the CCS read names into DAZDB read ids.
```

**Comment by pb-cdunn** [comment]
Why does `set +e` not work? Could you help us debug that on your system? ... Oh, I remember. The sub-process (in parens) needs to exit with a `0`.

Locally, we have this already:
```
        (
        set -vx +e
        grep -w {params.ctg} {input.RID_TO_CTG} >| rid_to_ctg.txt
        true
        )
```
So I think you don't have the latest code....

```
pb-falcon                 0.3.1            py36hc0aa232_0    bioconda
...
python                    3.6.7             h357f687_1005    conda-forge
```
Aha. That's the problem. You have to use a python-3.7 environment.
