### ISSUE TITLE
Pbalign: error occurs during Blasr run

### ISSUE THREAD

**Issue by fantin-mesny** [PacificBiosciences/pbbioconda#202]
Dear PacBio developers,

I am polishing a large number of genomes using Arrow, after aligning PacBio subreads on assembly using Pbalign.
It worked very well for 60 genomes, but there are a few genomes I cannot polish. An error occurs during Blasr alignment.

I thought at first that my server ran out of memory, as I got the following error:

```
[INFO] 2019-09-25 08:58:26,987Z [root run 227] pbalign version: 0.4.1
[INFO] 2019-09-25 08:58:27,068Z [root run 178] BlasrService: Align reads to references using blasr.
[INFO] 2019-09-25 08:58:27,069Z [root Execute 63] BlasrService: Call "blasr m54124_190908_025312.subreads.bam contigs.fasta --out tmp/tmppgaWhx/yaw8rX.bam  --bam  --bestn 10 --minMatch 12  --maxMatch 30  --nproc 40  --minSubreadLength 50 --minAlnLength 50  --minPctSimilarity 70 --minPctAccuracy 70 --hitPolicy randombest  --randomSeed 1 "
[ERROR] 2019-09-26 05:13:02,404Z [root Execute 68] BlasrService returned a non-zero exit status 134
CMD: 'blasr m54124_190908_025312.subreads.bam contigs.fasta --out tmp/tmppgaWhx/yaw8rX.bam  --bam  --bestn 10 --minMatch 12  --maxMatch 30  --nproc 40  --minSubreadLength 50 --minAlnLength 50  --minPctSimilarity 70 --minPctAccuracy 70 --hitPolicy randombest  --randomSeed 1 '
ERROR: [INFO] 2019-09-25T10:58:27 [blasr] started.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted
Output:[]
[ERROR] 2019-09-26 05:13:02,575Z [pbalign.pbalignrunner _pacbio_main_runner 143] BlasrService returned a non-zero exit status 134
CMD: 'blasr m54124_190908_025312.subreads.bam contigs.fasta --out tmp/tmppgaWhx/yaw8rX.bam  --bam  --bestn 10 --minMatch 12  --maxMatch 30  --nproc 40  --minSubreadLength 50 --minAlnLength 50  --minPctSimilarity 70 --minPctAccuracy 70 --hitPolicy randombest  --randomSeed 1 '
ERROR: [INFO] 2019-09-25T10:58:27 [blasr] started.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted
Output:[]
Traceback (most recent call last):
  File "anaconda3/lib/python2.7/site-packages/pbcommand/cli/core.py", line 138, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "anaconda3/lib/python2.7/site-packages/pbalign/pbalignrunner.py", line 284, in args_runner
    return PBAlignRunner(args, output_dataset_type=output_dataset_type).start()
  File "anaconda3/lib/python2.7/site-packages/pbcore/util/ToolRunner.py", line 85, in start
    return self.run()
  File "anaconda3/lib/python2.7/site-packages/pbalign/pbalignrunner.py", line 240, in run
    self._alnService.run()
  File "anaconda3/lib/python2.7/site-packages/pbalign/alignservice/align.py", line 198, in run
    raise RuntimeError(str(e))
RuntimeError: BlasrService returned a non-zero exit status 134
CMD: 'blasr m54124_190908_025312.subreads.bam contigs.fasta --out tmp/tmppgaWhx/yaw8rX.bam  --bam  --bestn 10 --minMatch 12  --maxMatch 30  --nproc 40  --minSubreadLength 50 --minAlnLength 50  --minPctSimilarity 70 --minPctAccuracy 70 --hitPolicy randombest  --randomSeed 1 '
ERROR: [INFO] 2019-09-25T10:58:27 [blasr] started.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted
Output:[]
[INFO] 2019-09-26 05:13:03,076Z [pbalign.pbalignrunner _pacbio_main_runner 155] exiting with return code 2 in 72875.59 sec.
```

But then, I re-run it with lower nproc, and then the error changed. I got:

`std::length_error
`

Do you have any idea where the problem might come from ?

Thanks!

**Comment by armintoepfer** [comment]
Hi!

BLASR is actually EOL and even if we were to find the problem, we wouldn't fix it. I advise you to switch to `pbmm2`, our BLASR successor. It's not only much faster, but also more robust.

Armin
