### ISSUE TITLE
FALCON-Phase TypeError: gen_parallel_tasks() got multiple values for keyword argument 'run_dict'

### ISSUE THREAD

**Issue by bgbrink** [PacificBiosciences/pbbioconda#214]
**Operating system**
CentOS Linux release 7.3.1611 (Core)

**Package name**
falcon-phase 1.0.0
falcon-kit 1.3.0
pypeflow 2.2.0

**Conda environment**
```
# packages in environment at /home/bbrink/.conda/envs/falcon_assembler:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
asn1crypto                1.0.1                    py27_0    conda-forge
avro-python2              1.9.0                      py_0    bioconda
bcftools                  1.9                  h68d8f2e_7    bioconda
bedtools                  2.29.0               h6ed99ea_1    bioconda
blasr                     5.3.3                h018d624_1    bioconda
blasr_libcpp              5.3.3                h018d624_1    bioconda
bwa                       0.7.17               hed695b0_6    bioconda
bzip2                     1.0.8                h516909a_1    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
certifi                   2019.9.11                py27_0    conda-forge
cffi                      1.12.3           py27h8022711_0    conda-forge
chardet                   3.0.4                 py27_1003    conda-forge
cryptography              2.7              py27h72c5cf5_0    conda-forge
curl                      7.65.3               hf8cf82a_0    conda-forge
cython                    0.29.13          py27he1b5a44_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
enum34                    1.1.6                 py27_1001    conda-forge
falcon-kit                1.3.0                    pypi_0    pypi
falcon-phase              1.0.0                    pypi_0    pypi
falcon-unzip              1.2.0                    pypi_0    pypi
future                    0.17.1                py27_1000    conda-forge
gsl                       2.5                  h294904e_1    conda-forge
h5py                      2.10.0          nompi_py27h513d04c_100    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1103    conda-forge
htslib                    1.9                  h4da6232_3    bioconda
idna                      2.8                   py27_1000    conda-forge
ipaddress                 1.0.22                     py_1    conda-forge
iso8601                   0.1.12                     py_1    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
libblas                   3.8.0               13_openblas    conda-forge
libcblas                  3.8.0               13_openblas    conda-forge
libcurl                   7.65.3               hda55be3_0    conda-forge
libdeflate                1.3                  h516909a_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
liblapack                 3.8.0               13_openblas    conda-forge
libopenblas               0.3.7                h6e990d7_1    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
linecache2                1.0.0                      py_1    conda-forge
minimap2                  2.17                 h84994c4_0    bioconda
mummer4                   4.0.0beta2      pl526hf484d3e_4    bioconda
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.2                        py_1    conda-forge
nim-falcon                0.0.1                h2f8a211_0    bioconda
numpy                     1.16.4           py27h95a1406_0    conda-forge
openssl                   1.1.1c               h516909a_0    conda-forge
pb-assembly               0.0.5                    py27_2    bioconda
pb-dazzler                0.0.1                h516909a_0    bioconda
pb-falcon                 0.2.7            py27hc0aa232_1    bioconda
pbalign                   0.3.1                    py27_2    bioconda
pbbam                     1.0.6                hc16d5b3_1    bioconda
pbcommand                 1.1.1                    py27_2    bioconda
pbcopper                  1.3.0                h3e4de3e_0    bioconda
pbcore                    1.6.5                    py27_0    bioconda
pbgcpp                    1.0.0                         0    bioconda
pbmm2                     1.1.0                hfb76ee0_0    bioconda
pcre                      8.41              hf484d3e_1003    conda-forge
perl                      5.26.2            h516909a_1006    conda-forge
pip                       19.2.3                   py27_0    conda-forge
pycparser                 2.19                     py27_1    conda-forge
pyopenssl                 19.0.0                   py27_0    conda-forge
pysam                     0.15.0.1         py27hdfb72b2_1    bioconda
pysocks                   1.7.1                    py27_0    conda-forge
python                    2.7.15            h5a48372_1009    conda-forge
python-edlib              1.3.4            py27hc9558a2_0    bioconda
python-intervaltree       3.0.2                      py_0    bioconda
python-msgpack            0.6.1            py27h6bb024c_0    bioconda
python-sortedcontainers   2.1.0                      py_0    bioconda
pytz                      2019.3                     py_0    conda-forge
racon                     1.4.7                he513fc3_0    bioconda
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.22.0                   py27_1    conda-forge
samtools                  1.9                 h10a08f8_12    bioconda
setuptools                41.4.0                   py27_0    conda-forge
six                       1.12.0                py27_1000    conda-forge
sqlite                    3.30.0               hcee41ef_0    conda-forge
tk                        8.6.9             hed695b0_1003    conda-forge
traceback2                1.4.0                    py27_0    conda-forge
unittest2                 1.1.0                      py_0    conda-forge
urllib3                   1.25.6                   py27_0    conda-forge
wheel                     0.33.6                   py27_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
```

**Describe the bug**
FALCON-Phase typeError during initialization.

**Error message**
```
falcon-phase 1.0.0
falcon-kit 1.3.0
pypeflow 2.2.0
[INFO]Setup logging from file "None".
[INFO]Using config=
{'General': {},
 'Phase': {'cns_h_ctg_fasta': './4-polish/cns-output/cns_h_ctg.fasta',
           'cns_p_ctg_fasta': './4-polish/cns-output/cns_p_ctg.fasta',
           'enzyme': '"GATC"',
           'iterations': '10000000',
           'min_aln_len': '3000',
           'output_format': 'pseudohap',
           'reads_1': '/work/project/ladsie_002/analyses/data/HiC_data/SM/SM_Lib1_R1.fq.gz',
           'reads_2': '/work/project/ladsie_002/analyses/data/HiC_data/SM/SM_Lib1_R2.fq.gz'},
 'job.defaults': {'JOB_QUEUE': 'fat',
                  'MB': '32768',
                  'NPROC': '6',
                  'job_type': 'slurm',
                  'njobs': '12',
                  'pwatcher_type': 'fs_based',
                  'submit': 'sbatch -p ${JOB_QUEUE} -J ${JOB_NAME} -o ${JOB_STDOUT} -e ${JOB_STDERR} --mem-per-cpu=${MB}M --cpus-per-task=${NPROC} --time=96:00:00 ${JOB_SCRIPT}',
                  'use_tmpdir': False},
 'job.step.phase.alignment': {},
 'job.step.phase.placement': {}}
[INFO]PATH=/home/bbrink/.conda/envs/falcon_assembler/bin:/opt/software/Anaconda3-2019.03/bin:/opt/software/python-3.6/bin:/home/bbrink/perl5/bin:/opt/xcat/bin:/opt/xcat/sbin:/opt/xcat/share/xcat/tools:/home/bbrink/perl5/bin:/opt/software/Anaconda3-4.3.1/condabin:/opt/xcat/bin:/opt/xcat/sbin:/opt/xcat/share/xcat/tools:/usr/local/bin:/usr/bin:/work/project/ladsie_002/homer/bin:/work/project/ladsie_002/juicer/scripts:/usr/sbin:/work/project/ladsie_002/homer/bin:/work/project/ladsie_002/juicer/scripts:/usr/sbin
[INFO]$('which which')
/usr/bin/which
[INFO]$('which samtools')
/home/bbrink/.conda/envs/falcon_assembler/bin/samtools
[INFO]$('which nucmer')
/home/bbrink/.conda/envs/falcon_assembler/bin/nucmer
[INFO]$('which show-coords')
/home/bbrink/.conda/envs/falcon_assembler/bin/show-coords
[INFO]$('which delta-filter')
/home/bbrink/.conda/envs/falcon_assembler/bin/delta-filter
[INFO]$('which bwa')
/home/bbrink/.conda/envs/falcon_assembler/bin/bwa
[INFO]$('which bedtools')
/home/bbrink/.conda/envs/falcon_assembler/bin/bedtools
[INFO]$ nucmer --version >
[INFO]nucmer ['4', '0', '0beta2'] is >= 4.0.0
[INFO]$ bwa mem >
[INFO]$ show-coords -h >
[INFO]$ delta-filter -h >
[INFO]$('bedtools --version')
bedtools v2.29.0
[INFO]$ samtools >
[INFO]samtools ['1', '9'] is >= 1.3
[INFO]In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.fs_based' from '/home/bbrink/.conda/envs/falcon_assembler/lib/python2.7/site-packages/pwatcher/fs_based.pyc'>
[INFO]job_type='slurm', (default)job_defaults={'JOB_QUEUE': 'fat', 'pwatcher_type': 'fs_based', 'use_tmpdir': False, 'MB': '32768', 'job_type': 'slurm', 'submit': 'sbatch -p ${JOB_QUEUE} -J ${JOB_NAME} -o ${JOB_STDOUT} -e ${JOB_STDERR} --mem-per-cpu=${MB}M --cpus-per-task=${NPROC} --time=96:00:00 ${JOB_SCRIPT}', 'NPROC': '6', 'njobs': '12'}, use_tmpdir=False, squash=False, job_name_style=0
[INFO]Setting max_jobs to 12; was None
[INFO]This is where FALCON-Phase workflow should be initialized and run.
Traceback (most recent call last):
  File "/home/bbrink/.conda/envs/falcon_assembler/bin/fc_phase.py", line 11, in <module>
    load_entry_point('falcon-phase==1.0.0', 'console_scripts', 'fc_phase.py')()
  File "/home/bbrink/.conda/envs/falcon_assembler/lib/python2.7/site-packages/falcon_phase/mains/start_falcon_phase.py", line 26, in main
    falcon_phase.run(**vars(args))
  File "/home/bbrink/.conda/envs/falcon_assembler/lib/python2.7/site-packages/falcon_phase/falcon_phase.py", line 70, in run
    falcon_phase_all(config)
  File "/home/bbrink/.conda/envs/falcon_assembler/lib/python2.7/site-packages/falcon_phase/falcon_phase.py", line 21, in falcon_phase_all
    tasks_falcon_phase.run_workflow(wf, config, rule_writer)
  File "/home/bbrink/.conda/envs/falcon_assembler/lib/python2.7/site-packages/falcon_phase/tasks/tasks_falcon_phase.py", line 322, in run_workflow
    min_aln_len, default_nproc, config, rule_writer)
  File "/home/bbrink/.conda/envs/falcon_assembler/lib/python2.7/site-packages/falcon_phase/tasks/tasks_falcon_phase.py", line 267, in add_placement_as_parallel_tasks
    job_dict=config['job.step.phase.placement'],
TypeError: gen_parallel_tasks() got multiple values for keyword argument 'run_dict'

```

Related to https://github.com/PacificBiosciences/pbbioconda/issues/153, but I just installed pb-assembly into a brand new environment so this doesn't help. `conda update --all ` shows no updates.

**Comment by bgbrink** [comment]
Actually, I just realized there is a newer version if I create a new environment with python3 instead of python2.7. Somehow I had in the back of my mind that FALCON requires 2.7.

However, when installing FALCON in a python3 environment, I get a different error, for which I will open a new issue.
