### ISSUE TITLE
fc_run on SLURM system, crashing at daligner-split step

### ISSUE THREAD

**Issue by smg283** [PacificBiosciences/pbbioconda#224]
**Operating system**
Which operating system and version are you using?
CentOS Linux 7 kernel 3.10.0-957.21.2.el7.x86_64
Slurm scheduler

**Package name**
PB-Assembly 0.0.6

**Conda environment**
What is the result of `conda list`? (Try to paste that between [triple backticks](https://help.github.com/articles/creating-and-highlighting-code-blocks/).)
```
# packages in environment at miniconda3:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py37_0
blas                      1.0                         mkl
bzip2                     1.0.6                h470a237_2    conda-forge/label/cf201901
ca-certificates           2019.5.15                     0    anaconda
certifi                   2019.3.9                 py37_0    anaconda
cffi                      1.12.2           py37h2e261b9_1
chardet                   3.0.4                    py37_1
conda                     4.6.14                   py37_0    anaconda
cryptography              2.7              py37h1ba5d50_0    anaconda
cudatoolkit               10.0.130                      0
cudnn                     7.6.0                cuda10.0_0
cycler                    0.10.0                     py_1    conda-forge/label/cf201901
dbus                      1.13.2               h714fa37_1    anaconda
expat                     2.2.5                hfc679d8_2    conda-forge/label/cf201901
fontconfig                2.13.1               h65d0f4c_0    conda-forge/label/cf201901
freetype                  2.9.1                h6debe1e_4    conda-forge/label/cf201901
gettext                   0.19.8.1             h5e8e0c9_1    conda-forge/label/cf201901
glib                      2.56.2               h464dc38_1    conda-forge/label/cf201901
gst-plugins-base          1.14.0               hbbd80ab_1    anaconda
gstreamer                 1.14.0               hb453b48_1    anaconda
icu                       58.2                 hfc679d8_0    conda-forge/label/cf201901
idna                      2.8                      py37_0
intel-openmp              2019.4                      243
jpeg                      9c                   h470a237_1    conda-forge/label/cf201901
kiwisolver                1.0.1            py37h2d50403_2    conda-forge/label/cf201901
libedit                   3.1.20181209         hc058e9b_0
libffi                    3.2.1                hd88cf55_4
libgcc-ng                 8.2.0                hdf63c60_1
libgfortran-ng            7.3.0                hdf63c60_0
libiconv                  1.15                 h470a237_4    conda-forge/label/cf201901
libpng                    1.6.36               ha92aebf_0    conda-forge/label/cf201901
libstdcxx-ng              8.2.0                hdf63c60_1
libtiff                   4.0.10               h2733197_2
libuuid                   2.32.1               h470a237_2    conda-forge/label/cf201901
libxcb                    1.13                 h470a237_2    conda-forge/label/cf201901
libxml2                   2.9.8                h422b904_5    conda-forge/label/cf201901
matplotlib                3.0.2            py37h8a2030e_1    conda-forge/label/cf201901
matplotlib-base           3.0.2            py37h20b835b_1    conda-forge/label/cf201901
mkl                       2019.4                      243
mkl_fft                   1.0.12           py37ha843d7b_0
mkl_random                1.0.2            py37hd81dba3_0
ncurses                   6.1                  he6710b0_1
ninja                     1.9.0            py37hfd86e86_0
numpy                     1.16.4           py37h7e9f1db_0
numpy-base                1.16.4           py37hde5b4d6_0
olefile                   0.46                     py37_0
openssl                   1.1.1                h7b6447c_0    anaconda
pandas                    0.24.2           py37he6710b0_0    anaconda
pcre                      8.43                 he6710b0_0    anaconda
pillow                    6.0.0            py37h34e0f95_0
pip                       19.0.3                   py37_0
pthread-stubs             0.4                  h470a237_1    conda-forge/label/cf201901
pycosat                   0.6.3            py37h14c3975_0
pycparser                 2.19                     py37_0
pyopenssl                 19.0.0                   py37_0
pyparsing                 2.3.0                      py_0    conda-forge/label/cf201901
pyqt                      5.6.0            py37h8210e8a_8    conda-forge/label/cf201901
pysocks                   1.6.8                    py37_0
python                    3.7.3                h0371630_0    anaconda
python-dateutil           2.7.5                      py_0    conda-forge/label/cf201901
pytorch                   1.1.0           py3.7_cuda10.0.130_cudnn7.5.1_0    pytorch
pytz                      2019.1                     py_0    anaconda
qt                        5.6.3                h8bf5577_3    anaconda
readline                  7.0                  h7b6447c_5
requests                  2.21.0                   py37_0
ruamel_yaml               0.15.46          py37h14c3975_0
setuptools                41.0.0                   py37_0
sip                       4.18.1           py37hfc679d8_0    conda-forge/label/cf201901
six                       1.12.0                   py37_0
sqlite                    3.27.2               h7b6447c_0
tk                        8.6.8                hbc83047_0
torchvision               0.3.0           py37_cu10.0.130_1    pytorch
tornado                   5.1.1            py37h470a237_0    conda-forge/label/cf201901
urllib3                   1.24.1                   py37_0
wheel                     0.33.1                   py37_0
xorg-libxau               1.0.8                h470a237_6    conda-forge/label/cf201901
xorg-libxdmcp             1.1.2                h470a237_7    conda-forge/label/cf201901
xz                        5.2.4                h14c3975_4
yaml                      0.1.7                had09818_2
zlib                      1.2.11               h7b6447c_3
zstd                      1.3.7                h0b5b093_0
```
**Describe the bug**
I am running falcon assembler via fc_run.  Job is crashing at 0-rawreads/dalinger-split step
My fc.cfg file is:
```ini
#### Input
[General]
input_fofn=input.fofn
input_type=raw
pa_DBdust_option=
pa_fasta_filter_option=streamed-median
target=assembly
skip_checks=false
LA4Falcon_preload=false
use_tmpdir=false

#### Data Partitioning
pa_DBsplit_option=-x500 -s200
ovlp_DBsplit_option=-x500 -s200

#### Repeat Masking
pa_HPCTANmask_option=
pa_REPmask_code=0,300;0,300;0,300

####Pre-assembly
genome_size = 800000000
seed_coverage = 40
length_cutoff = -1
pa_HPCdaligner_option=-v -B128 -M24
pa_daligner_option= -k18 -e0.75 -l1200 -h256 -w8 -s100
falcon_sense_option=--output-multi --min-idt 0.70 --min-cov 4 --max-n-read 200
falcon_sense_greedy=False

####Pread overlapping
ovlp_HPCdaligner_option=-v -B128 -M24
ovlp_daligner_option=-k24 -e.92 -l1800 -h600 -s100

####Final Assembly
length_cutoff_pr=1000
overlap_filtering_setting=--max-diff 100 --max-cov 100 --min-cov 2
fc_ovlp_to_graph_option=
length_cutoff_pr=10000

[job.defaults]
job_type=slurm
pwatcher_type=blocking
JOB_QUEUE =short
NPROC = 6
njobs = 10
submit = sbatch -p ${JOB_QUEUE} -J ${JOB_NAME} -o ${JOB_STDOUT} -e ${JOB_STDERR} --cpus-per-task=${NPROC} --wait ${JOB_SCRIPT}

[job.step.da]
NPROC=4
njobs=10
[job.step.la]
NPROC=4
njobs=10
[job.step.cns]
NPROC=8
njobs=10
[job.step.pda]
NPROC=4
njobs=10
[job.step.pla]
NPROC=4
njobs=10
[job.step.asm]
NPROC=24
njobs=1
```
**Error message**

Paste the error message / stack.
The last few lines of stderr are, the key is SyntaxError:more than 255 arguments :
```py
[INFO]Num satisfied in this iteration: 6
[INFO]Num still unsatisfied: 1
[INFO]About to submit: Node(0-rawreads/repc/rep-gathered)
[INFO]Popen: '/bin/bash -C /software/7/apps/pb-assembly/0.0.6/lib/python3.6/site-packages/pwatcher/mains/job_start.sh >| /project/ag100pest/Scal/Falcon/0-rawreads/repc/rep-gathered/run-P6dfaabcd965906.bash.stdout 2>| /project/ag100pest/Scal/Falcon/0-rawreads/repc/rep-gathered/run-P6dfaabcd965906.bash.stderr'
[INFO]recently_satisfied:
{Node(0-rawreads/repc/rep-gathered)}
[INFO]Num satisfied in this iteration: 1
[INFO]Num still unsatisfied: 0
[INFO]Num unsatisfied: 2, graph: 3014
[INFO]About to submit: Node(0-rawreads/repc/rep-combine)
[INFO]Popen: '/bin/bash -C /software/7/apps/pb-assembly/0.0.6/lib/python3.6/site-packages/pwatcher/mains/job_start.sh >| /project/ag100pest/Scal/Falcon/0-rawreads/repc/rep-combine/run-P165057521ca462.bash.stdout 2>| /project/ag100pest/Scal/Falcon/0-rawreads/repc/rep-combine/run-P165057521ca462.bash.stderr'
[INFO](slept for another 0.0s -- another 1 loop iterations)
[INFO](slept for another 0.30000000000000004s -- another 2 loop iterations)
[INFO](slept for another 1.2000000000000002s -- another 3 loop iterations)
[INFO]recently_satisfied:
{Node(0-rawreads/repc/rep-combine)}
[INFO]Num satisfied in this iteration: 1
[INFO]Num still unsatisfied: 1
[INFO]About to submit: Node(0-rawreads/daligner-split)
[INFO]Popen: '/bin/bash -C /software/7/apps/pb-assembly/0.0.6/lib/python3.6/site-packages/pwatcher/mains/job_start.sh >| /project/ag100pest/Scal/Falcon/0-rawreads/daligner-split/run-P2f034f6e535eee.bash.stdout 2>| /project/ag100pest/Scal/Falcon/0-rawreads/daligner-split/run-P2f034f6e535eee.bash.stderr'
[INFO](slept for another 1.4s -- another 4 loop iterations)
[INFO](slept for another 2.0s -- another 5 loop iterations)
[INFO](slept for another 5.7s -- another 6 loop iterations)
[INFO]recently_satisfied:
{Node(0-rawreads/daligner-split)}
[INFO]Num satisfied in this iteration: 1
[INFO]Num still unsatisfied: 0
Traceback (most recent call last):
  File "/software/7/apps/pb-assembly/0.0.6/bin/fc_run", line 11, in <module>
    load_entry_point('falcon-kit==1.4.4', 'console_scripts', 'fc_run')()
  File "/software/7/apps/pb-assembly/0.0.6/lib/python3.6/site-packages/falcon_kit/mains/run1.py", line 706, in main
    main1(argv[0], args.config, args.logger)
  File "/software/7/apps/pb-assembly/0.0.6/lib/python3.6/site-packages/falcon_kit/mains/run1.py", line 73, in main1
    input_fofn_fn=input_fofn_fn,
  File "/software/7/apps/pb-assembly/0.0.6/lib/python3.6/site-packages/falcon_kit/mains/run1.py", line 293, in run
    daligner_split_script=pype_tasks.TASK_DB_DALIGNER_SPLIT_SCRIPT,
  File "/software/7/apps/pb-assembly/0.0.6/lib/python3.6/site-packages/falcon_kit/mains/run1.py", line 524, in add_daligner_and_merge_tasks
    dist=Dist(NPROC=4, MB=4000, job_dict=daligner_job_config),
  File "/software/7/apps/pb-assembly/0.0.6/lib/python3.6/site-packages/falcon_kit/pype.py", line 194, in gen_parallel_tasks
    dist=Dist(local=True, use_tmpdir=False),
  File "/software/7/apps/pb-assembly/0.0.6/lib/python3.6/site-packages/pypeflow/tasks.py", line 60, in gen_task
    validate_dict(inputs)
  File "/software/7/apps/pb-assembly/0.0.6/lib/python3.6/site-packages/pypeflow/tasks.py", line 56, in validate_dict
    collections.namedtuple('validate', list(mydict.keys()))
  File "/software/7/apps/pb-assembly/0.0.6/lib/python3.6/collections/__init__.py", line 429, in namedtuple
    exec(class_definition, namespace)
  File "<string>", line 12
SyntaxError: more than 255 arguments
```

**To Reproduce**
Steps to reproduce the behavior. Providing a minimal test dataset on which we can reproduce the behavior will generally lead to quicker turnaround time!

**Expected behavior**

**Comment by pb-cdunn** [comment]
The conda-env that you've listed does not include any `pb-*` packages, leaving open the possibility that you are out-of-date.

`python3.6` -- We support only python3.7. But I see `python 3.7.3` in your conda-env. So I think you are running Falcon from elsewhere, not from your conda-environment.

That means this is not a "Slurm" problem at all. You should always run locally (on a small dataset) before wasting any time at all with job-distribution. If there is still a bug, feel free to re-open this.
