### ISSUE TITLE
Exit status 256

### ISSUE THREAD

**Issue by nsgarcia27** [PacificBiosciences/pbbioconda#226]
Hello, 

I am encountering a problem I haven't seen before. I am not sure if this is due to our PBS system or the software itself. It seems to be stuck at the 0-rawreads stage - it stops working almost immediately after I run the PBS job.  I also tried deleting the "mypwatcher" folder but it didn't help either.

Below is the config specs:

```
{
  "General": {
    "LA4Falcon_preload": false,
    "avoid_text_file_busy": true,
    "bestn": 12,
    "dazcon": false,
    "falcon_sense_greedy": false,
    "falcon_sense_option": "--output-multi --min-idt 0.70 --min-cov 3 --max-n-read 200",
    "falcon_sense_skip_contained": false,
    "fc_ovlp_to_graph_option": " --min-len 1000",
    "genome_size": "1800000000",
    "input_fofn": "input.fofn",
    "input_type": "raw",
    "length_cutoff": "-1",
    "length_cutoff_pr": "1000",
    "overlap_filtering_setting": "--max-diff 100 --max-cov 200 --min-cov 2",
    "ovlp_DBsplit_option": "-a -x500 -s400",
    "ovlp_HPCdaligner_option": "-v -B128 -M24",
    "ovlp_daligner_option": "-h600 -e.92 -l1800 -s100 -k24",
    "pa_DBdust_option": "",
    "pa_DBsplit_option": "-a -x500 -s400",
    "pa_HPCTANmask_option": "",
    "pa_HPCdaligner_option": "-v -B128 -M32",
    "pa_REPmask_code": "1,20;10,15;50,10",
    "pa_daligner_option": "-e.75 -l2000 -s100 -k18 -h256 -w8",
    "pa_dazcon_option": "-j 4 -x -l 500",
    "pa_fasta_filter_option": "streamed-median",
    "seed_coverage": "30",
    "skip_checks": false,
    "target": "assembly"
```

And this is the last lines from the error outputfile. It seems to print this same error file everytime I run the PBS job.

```
ERROR]Task Node(0-rawreads/repb/daligner-runs/rep_0795) failed with exit-code=256
[ERROR]Some tasks are recently_done but not satisfied: set([Node(0-rawreads/repb/daligner-runs/rep_0795)])
[ERROR]ready: set([])
submitted: set([Node(0-rawreads/repb/daligner-runs/rep_0794), Node(0-rawreads/repb/daligner-runs/rep_0724), Node(0-rawreads/repb/daligner-runs/rep_0802), Node(0-rawreads/repb/daligner-runs/rep_0912), Node(0-rawreads/repb/daligner-runs/rep_0800), Node(0-rawreads/repb/daligner-runs/rep_0788), Node(0-rawreads/repb/daligner-runs/rep_0812), Node(0-rawreads/repb/daligner-runs/rep_0813), Node(0-rawreads/repb/daligner-runs/rep_0807), Node(0-rawreads/repb/daligner-runs/rep_0785), Node(0-rawreads/repb/daligner-runs/rep_0796), Node(0-rawreads/repb/daligner-runs/rep_0910), Node(0-rawreads/repb/daligner-runs/rep_0814), Node(0-rawreads/repb/daligner-runs/rep_0809), Node(0-rawreads/repb/daligner-runs/rep_0805), Node(0-rawreads/repb/daligner-runs/rep_0808), Node(0-rawreads/repb/daligner-runs/rep_0723), Node(0-rawreads/repb/daligner-runs/rep_0726), Node(0-rawreads/repb/daligner-runs/rep_0911), Node(0-rawreads/repb/daligner-runs/rep_0793), Node(0-rawreads/repb/daligner-runs/rep_0804), Node(0-rawreads/repb/daligner-runs/rep_0791), Node(0-rawreads/repb/daligner-runs/rep_0884), Node(0-rawreads/repb/daligner-runs/rep_0798), Node(0-rawreads/repb/daligner-runs/rep_0815)])
[INFO]CALL:
 qdel P6199c88866cc9d
qdel: illegally formed job identifier: P6199c88866cc9d
[INFO]CALL:
 qdel Peee3940212cea9
qdel: illegally formed job identifier: Peee3940212cea9
[INFO]CALL:
 qdel P0adb509f2d1e6c
qdel: illegally formed job identifier: P0adb509f2d1e6c
[INFO]CALL:
 qdel P5f255c3c6e7e3c
qdel: illegally formed job identifier: P5f255c3c6e7e3c
[INFO]CALL:
 qdel P3baa7adbf76388
qdel: illegally formed job identifier: P3baa7adbf76388
[INFO]CALL:
 qdel P2ad9216b1a383e
qdel: illegally formed job identifier: P2ad9216b1a383e
[INFO]CALL:
 qdel P6fe7029f2d0bbf
qdel: illegally formed job identifier: P6fe7029f2d0bbf
[INFO]CALL:
 qdel P20d6217f2af172
qdel: illegally formed job identifier: P20d6217f2af172
[INFO]CALL:
 qdel P00d74dc69e4e5f
qdel: illegally formed job identifier: P00d74dc69e4e5f
[INFO]CALL:
 qdel P514245c1a3cc22
qdel: illegally formed job identifier: P514245c1a3cc22
[INFO]CALL:
 qdel Pf48cc47ace9e04
qdel: illegally formed job identifier: Pf48cc47ace9e04
[INFO]CALL:
 qdel Pc878a107e4a277
qdel: illegally formed job identifier: Pc878a107e4a277
[INFO]CALL:
 qdel Pe762a623462736
qdel: illegally formed job identifier: Pe762a623462736
[INFO]CALL:
 qdel P9625f0cee9c81b
qdel: illegally formed job identifier: P9625f0cee9c81b
[INFO]CALL:
 qdel Pb9fbc0613438d9
qdel: illegally formed job identifier: Pb9fbc0613438d9
[INFO]CALL:
 qdel P73455a33605b2a
qdel: illegally formed job identifier: P73455a33605b2a
[INFO]CALL:
 qdel P904946fc83ad13
qdel: illegally formed job identifier: P904946fc83ad13
[INFO]CALL:
 qdel Pe62c8d03d6e77c
qdel: illegally formed job identifier: Pe62c8d03d6e77c
[INFO]CALL:
 qdel P9c7b8a28ceadcb
qdel: illegally formed job identifier: P9c7b8a28ceadcb
[INFO]CALL:
 qdel Pab8e3e32104ccb
qdel: illegally formed job identifier: Pab8e3e32104ccb
[INFO]CALL:
 qdel Pb7828915d69dcf
qdel: illegally formed job identifier: Pb7828915d69dcf
[INFO]CALL:
 qdel P6b43ee87744b03
qdel: illegally formed job identifier: P6b43ee87744b03
[INFO]CALL:
 qdel P05c3dd1d59de56
qdel: illegally formed job identifier: P05c3dd1d59de56
[INFO]CALL:
 qdel P4789e4cd55a294
qdel: illegally formed job identifier: P4789e4cd55a294
[INFO]CALL:
 qdel Pa851ed96a3848e
qdel: illegally formed job identifier: Pa851ed96a3848e
[INFO]CALL:
 qdel P1fb7d07eafa943
qdel: illegally formed job identifier: P1fb7d07eafa943
Traceback (most recent call last):
  File "/home/chenc1/garci191/.conda/envs/denovo_asm_2.7/bin/fc_run", line 11, in <module>
    load_entry_point('falcon-kit==1.2.4', 'console_scripts', 'fc_run')()
  File "/home/chenc1/garci191/.conda/envs/denovo_asm_2.7/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 726, in main
    main1(argv[0], args.config, args.logger)
  File "/home/chenc1/garci191/.conda/envs/denovo_asm_2.7/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 76, in main1
    input_fofn_fn=input_fofn_fn,
  File "/home/chenc1/garci191/.conda/envs/denovo_asm_2.7/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 277, in run
    letter, group_size, coverage_limit)
  File "/home/chenc1/garci191/.conda/envs/denovo_asm_2.7/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 645, in add_rep_tasks
    daligner_split_script=pype_tasks.TASK_DB_REP_DALIGNER_SPLIT_SCRIPT,
  File "/home/chenc1/garci191/.conda/envs/denovo_asm_2.7/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 539, in add_daligner_and_merge_tasks
    dist=Dist(NPROC=4, MB=4000, job_dict=daligner_job_config),
  File "/home/chenc1/garci191/.conda/envs/denovo_asm_2.7/lib/python2.7/site-packages/falcon_kit/pype.py", line 194, in gen_parallel_tasks
    wf.refreshTargets()
  File "/home/chenc1/garci191/.conda/envs/denovo_asm_2.7/lib/python2.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 278, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/home/chenc1/garci191/.conda/envs/denovo_asm_2.7/lib/python2.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 362, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: set([Node(0-rawreads/repb/daligner-runs/rep_0795)])
```

At the first ERROR line I noticed "exit-code=256". What does this mean?

Thank you very much,
Nelson

**Comment by pb-cdunn** [comment]
`ERROR]Task Node(0-rawreads/repb/daligner-runs/rep_0795) failed`

First, if you look into that directory, you can probably find `stderr` that will tell you what actually went wrong.

Second, you are having problems with `qdel`, unrelated to the crash. I suggest using [the `blocking` "pwatcher"](https://github.com/PacificBiosciences/pypeFLOW/wiki/Configuration) instead of `fs_based`. Then you can configure qdel or whatever should be called on your system to kill jobs early.

Please re-open if you need more help.
