### ISSUE TITLE
pbmm2 align error

### ISSUE THREAD

**Issue by KeleyKeley** [PacificBiosciences/pbbioconda#228]
Hi,

quiver-run error issue.
I found uow*** folder under 4-polish/quiver-run/000**/, because aligned bam file was not generated. 
I re-ran user_script.sh under uow***, but execution stopped with pbmm2 align error with comments below

`Could not determine read input type(s). Please do not mix data types, such as BAM+FASTQ. File of files may only contain BAMs or datasets.`

I do not understand why only this sample gives me an error.
(Actually, this sample was sequenced by Sequel II and I do not think this occurs an error.)

Do you have any Solutions??

Thank you

**Comment by KeleyKeley** [comment]
I updated `pbmm2` and `genomicConsensus`. These are the latest.
`pbmm2` works well, but variantCaller does not work... 😢

[Error Message]
Arrow: unsupported chemistries found: (S/P4-C2/5.0-8M)
Arrow: unsupported chemistries found: (S/P4-C2/5.0-8M)
Traceback (most recent call last):
  File "/home/denovo/miniconda2/envs/pbasm/lib/python2.7/site-packages/pbcommand/cli/core.py", line 138, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/home/denovo/miniconda2/envs/pbasm/lib/python2.7/site-packages/GenomicConsensus/main.py", line 340, in args_runner
    return tr.main()
  File "/home/denovo/miniconda2/envs/pbasm/lib/python2.7/site-packages/GenomicConsensus/main.py", line 270, in main
    self._configureAlgorithm(options, peekFile)
  File "/home/denovo/miniconda2/envs/pbasm/lib/python2.7/site-packages/GenomicConsensus/main.py", line 164, in _configureAlgorithm
    self._algorithmConfiguration = self._algorithm.configure(options, alnFile)
  File "/home/denovo/miniconda2/envs/pbasm/lib/python2.7/site-packages/GenomicConsensus/arrow/arrow.py", line 233, in configure
    die("Arrow: unsupported chemistries found: ({0})".format(", ".join(sorted(unsupp))))
  File "/home/denovo/miniconda2/envs/pbasm/lib/python2.7/site-packages/GenomicConsensus/utils.py", line 16, in die
    raise DieException(msg)
DieException: Arrow: unsupported chemistries found: (S/P4-C2/5.0-8M)
[ERROR] Arrow: unsupported chemistries found: (S/P4-C2/5.0-8M)
Traceback (most recent call last):
  File "/home/denovo/miniconda2/envs/pbasm/lib/python2.7/site-packages/pbcommand/cli/core.py", line 138, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/home/denovo/miniconda2/envs/pbasm/lib/python2.7/site-packages/GenomicConsensus/main.py", line 340, in args_runner
    return tr.main()
  File "/home/denovo/miniconda2/envs/pbasm/lib/python2.7/site-packages/GenomicConsensus/main.py", line 270, in main
    self._configureAlgorithm(options, peekFile)
  File "/home/denovo/miniconda2/envs/pbasm/lib/python2.7/site-packages/GenomicConsensus/main.py", line 164, in _configureAlgorithm
    self._algorithmConfiguration = self._algorithm.configure(options, alnFile)
  File "/home/denovo/miniconda2/envs/pbasm/lib/python2.7/site-packages/GenomicConsensus/arrow/arrow.py", line 233, in configure
    die("Arrow: unsupported chemistries found: ({0})".format(", ".join(sorted(unsupp))))
  File "/home/denovo/miniconda2/envs/pbasm/lib/python2.7/site-packages/GenomicConsensus/utils.py", line 16, in die
    raise DieException(msg)
DieException: Arrow: unsupported chemistries found: (S/P4-C2/5.0-8M)

Arrow does not support Seqeul II reads??

Thank you

**Comment by pb-cdunn** [comment]
You need to use `gcpp` instead of **GenomicConsensus**. You'll have that automatically if you use a python3.7 environment. We no longer support python2.7 in Bioconda. Sorry!

**Comment by rozaimirazali** [comment]
Hi.

I am having the same issue - _"Could not determine read input type(s). Please do not mix data types, such as BAM+FASTQ. File of files may only contain BAMs or datasets."_

The version of pbmm2 1.1.0

The command: 

`pbmm2 align --log-level DEBUG --sort --alignment-threads 32 --preset SUBREAD --sample MNDY0206 --unmapped ../../input/ref/GRCh38.p12.genome.fa bam.fofn output.bam`

The bam.fofn only contains bam files

> m54106_180305_090504.subreads.bam
> m54106_180305_191055.subreads.bam
> m54106_180306_095808.subreads.bam
> m54106_180306_200343.subreads.bam
> m54106_180704_064123.subreads.bam
> m54106_180704_165029.subreads.bam
> m54106_180710_082246.subreads.bam
> m54106_180710_183350.subreads.bam
> m54107_180305_090413.subreads.bam
> m54107_180305_191001.subreads.bam
> m54107_180306_095813.subreads.bam
> m54107_180306_200409.subreads.bam
> m54107_180430_173338.subreads.bam
> m54107_180502_045750.subreads.bam
> m54107_180626_073517.subreads.bam
> m54107_180626_174914.subreads.bam
> m54107_180627_102459.subreads.bam
> m54107_180627_203329.subreads.bam
> m54107_180702_065016.subreads.bam
> m54107_180702_170553.subreads.bam
> m54107_180703_080930.subreads.bam
> m54107_180703_182453.subreads.bam
> m54107_180704_044013.subreads.bam
> m54107_180704_145613.subreads.bam
> m54107_180705_011214.subreads.bam
> m54107_180705_112915.subreads.bam
> m54107_180709_070406.subreads.bam
> m54107_180709_172201.subreads.bam
> m54107_180710_082455.subreads.bam
> m54107_180710_184412.subreads.bam
> m54107_180711_050825.subreads.bam
> m54107_180711_152740.subreads.bam
> m54107_180712_014716.subreads.bam
> m54107_180712_120227.subreads.bam

Any idea how to solve this?
