### ISSUE TITLE
Problem using FALCON-Unzip with example data set

### ISSUE THREAD

**Issue by KaparaNewbie** [PacificBiosciences/pbbioconda#229]
**Operating system**
Which operating system and version are you using?
```
NAME="CentOS Linux"
VERSION="7 (Core)"
```

**Package name**
Using ```falconc --version``` I get:
```
version=0.2.1+git.SL-release-8.0.0-80-g64395b9, nim-version=1.0.99
```
My environment is completely updated, and channel priorities are set in my condarc file (in my home directory) as follows:
```
channels:
  - conda-forge
  - bioconda
  - defaults
```

**Conda environment**
```
_libgcc_mutex             0.1                        main
asn1crypto                1.2.0                    py27_0    conda-forge
avro-python2              1.9.0                      py_0    bioconda
bedtools                  2.29.0               hc088bd4_3    bioconda
blas                      2.14                   openblas    conda-forge
blasr                     5.3.3                h018d624_1    bioconda
blasr_libcpp              5.3.3                h018d624_1    bioconda
bwa                       0.7.17               hed695b0_6    bioconda
bzip2                     1.0.8                h516909a_1    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
certifi                   2019.9.11                py27_0    conda-forge
cffi                      1.13.2           py27h8022711_0    conda-forge
chardet                   3.0.4                 py27_1003    conda-forge
cryptography              2.7              py27h72c5cf5_0    conda-forge
curl                      7.65.3               hf8cf82a_0    conda-forge
cython                    0.29.14          py27he1b5a44_0    conda-forge
decorator                 4.4.1                      py_0    conda-forge
enum34                    1.1.6                 py27_1001    conda-forge
future                    0.18.2                   py27_0    conda-forge
h5py                      2.10.0          nompi_py27h513d04c_100    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
htslib                    1.9                  h244ad75_9    bioconda
idna                      2.8                   py27_1000    conda-forge
intel-openmp              2019.4                      243
ipaddress                 1.0.23                     py_0    conda-forge
iso8601                   0.1.12                     py_1    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libcurl                   7.65.3               hda55be3_0    conda-forge
libdeflate                1.3                  h516909a_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0
libgfortran-ng            7.3.0                hdf63c60_2    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
liblapacke                3.8.0               14_openblas    conda-forge
libopenblas               0.3.7                h6e990d7_3    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0
linecache2                1.0.0                      py_1    conda-forge
minimap2                  2.17                 h8b12597_1    bioconda
mkl                       2019.4                      243
mkl-service               2.3.0            py27h516909a_0    conda-forge
mkl_fft                   1.0.15           py27h516909a_1    conda-forge
mkl_random                1.1.0            py27hb3f55d8_0    conda-forge
mummer4                   4.0.0beta2      pl526hf484d3e_4    bioconda
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.2                        py_1    conda-forge
nim-falcon                1.0.0                h2f8a211_0    bioconda
numpy                     1.16.5           py27h95a1406_0    conda-forge
numpy-base                1.16.5           py27h2f8d375_0
openssl                   1.1.1c               h516909a_0    conda-forge
pb-assembly               0.0.5                    py27_2    bioconda
pb-dazzler                0.0.1                h516909a_0    bioconda
pb-falcon                 0.2.7            py27hc0aa232_1    bioconda
pbalign                   0.3.2                      py_1    bioconda
pbbam                     1.0.6                hc16d5b3_1    bioconda
pbcommand                 1.1.1                      py_3    bioconda
pbcopper                  1.3.0                h3e4de3e_0    bioconda
pbcore                    1.7.1                    py27_0    bioconda
pbgcpp                    1.0.0                         0    bioconda
pbmm2                     1.1.0                hfb76ee0_0    bioconda
pcre                      8.43                 he1b5a44_0    conda-forge
perl                      5.26.2            h516909a_1006    conda-forge
pip                       19.3.1                   py27_0    conda-forge
pycparser                 2.19                     py27_1    conda-forge
pyopenssl                 19.0.0                   py27_0    conda-forge
pysam                     0.15.3           py27hbcae180_3    bioconda
pysocks                   1.7.1                    py27_0    conda-forge
python                    2.7.15            h5a48372_1009    conda-forge
python-edlib              1.3.4            py27hc9558a2_0    bioconda
python-intervaltree       3.0.2                      py_0    bioconda
python-msgpack            0.6.1            py27hc9558a2_1    bioconda
python-sortedcontainers   2.1.0                      py_0    bioconda
pytz                      2019.3                     py_0    conda-forge
racon                     1.4.7                he513fc3_0    bioconda
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.22.0                   py27_1    conda-forge
samtools                  1.9                 h10a08f8_12    bioconda
setuptools                41.6.0                   py27_1    conda-forge
six                       1.13.0                   py27_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tk                        8.6.9             hed695b0_1003    conda-forge
traceback2                1.4.0                    py27_0    conda-forge
unittest2                 1.1.0                      py_0    conda-forge
urllib3                   1.25.6                   py27_0    conda-forge
wheel                     0.33.6                   py27_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
```

**Describe the bug**
I'm testing my installation using the example data set.
FALCON command ```fc_run fc_run.cfg``` works well (as for as I understand), but the FALCON-Unzip command ```fc_unzip.py fc_unzip.cfg``` fails.

**Error message**
```
falcon-unzip 1.2.0 (pip thinks "falcon-unzip 1.2.0")
falcon-kit 1.3.0
pypeflow 2.2.0
[INFO]Setup logging from file "None".
[INFO]Using config=
{'General': {'max_n_open_files': '1000'},
 'Unzip': {'input_bam_fofn': 'input_bam.fofn',
           'input_fofn': 'input.fofn',
           'polish_include_zmw_all_subreads': False,
           'polish_use_blasr': False,
           'polish_vc_ignore_error': False},
 'job.defaults': {'NPROC': '4',
                  'job_type': 'string',
                  'njobs': '8',
                  'pwatcher_type': 'blocking',
                  'submit': 'bash -C ${CMD} >| ${STDOUT_FILE} 2>| ${STDERR_FILE}',
                  'use_tmpdir': False},
 'job.step.unzip.blasr_aln': {'NPROC': '16', 'njobs': '2'},
 'job.step.unzip.hasm': {'NPROC': '48', 'njobs': '1'},
 'job.step.unzip.phasing': {'NPROC': '2', 'njobs': '16'},
 'job.step.unzip.quiver': {'NPROC': '12', 'njobs': '2'},
 'job.step.unzip.track_reads': {'NPROC': '48', 'njobs': '1'},
 'max_n_open_files': '1000'}
[INFO]PATH=/home/alu/kobish/.conda/envs/denovo_asm/bin:/home/alu/kobish/PrecedencePaths:/private/apps/bin/Centos7:/home/alu/kobish/PrecedencePaths:/private/apps/bin/Centos7:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/alu/kobish/bin:/home/alu/kobish/bin
[INFO]$('which which')
/usr/bin/which
[INFO]$('which blasr')
/home/alu/kobish/.conda/envs/denovo_asm/bin/blasr
[INFO]$('which samtools')
/home/alu/kobish/.conda/envs/denovo_asm/bin/samtools
[INFO]$('which pbalign')
/home/alu/kobish/.conda/envs/denovo_asm/bin/pbalign
[INFO]$('which gcpp')
/home/alu/kobish/.conda/envs/denovo_asm/bin/gcpp
[INFO]$('which minimap2')
/home/alu/kobish/.conda/envs/denovo_asm/bin/minimap2
[INFO]$('which nucmer')
/home/alu/kobish/.conda/envs/denovo_asm/bin/nucmer
[INFO]$('which show-coords')
/home/alu/kobish/.conda/envs/denovo_asm/bin/show-coords
[INFO]$('which fc_rr_hctg_track2.exe')
which: no fc_rr_hctg_track2.exe in (/home/alu/kobish/.conda/envs/denovo_asm/bin:/home/alu/kobish/PrecedencePaths:/private/apps/bin/Centos7:/home/alu/kobish/PrecedencePaths:/private/apps/bin/Centos7:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/alu/kobish/bin:/home/alu/kobish/bin)
[WARNING]Call 'which fc_rr_hctg_track2.exe' returned 256.
Traceback (most recent call last):
  File "/home/alu/kobish/.conda/envs/denovo_asm/bin/fc_unzip.py", line 11, in <module>
    load_entry_point('falcon-unzip==1.2.0', 'console_scripts', 'fc_unzip.py')()
  File "/home/alu/kobish/.conda/envs/denovo_asm/lib/python2.7/site-packages/falcon_unzip/mains/start_unzip.py", line 33, in main
    unzip.run(**vars(args))
  File "/home/alu/kobish/.conda/envs/denovo_asm/lib/python2.7/site-packages/falcon_unzip/unzip.py", line 167, in run
    config = parse_config(config_fn)
  File "/home/alu/kobish/.conda/envs/denovo_asm/lib/python2.7/site-packages/falcon_unzip/unzip.py", line 128, in parse_config
    io.validate_config(config)
  File "/home/alu/kobish/.conda/envs/denovo_asm/lib/python2.7/site-packages/falcon_unzip/io.py", line 76, in validate_config
    syscall('which ' + cmd)
  File "/home/alu/kobish/.conda/envs/denovo_asm/lib/python2.7/site-packages/pypeflow/io.py", line 29, in syscall
    raise Exception(msg)
Exception: Call 'which fc_rr_hctg_track2.exe' returned 256.
```

Thanks in advance,
Kobi

**Comment by pb-cdunn** [comment]
We support only python3.7 in Bioconda.
