### ISSUE TITLE
fc_phase.py - ImportError: cannot import name quote

### ISSUE THREAD

**Issue by bgbrink** [PacificBiosciences/pbbioconda#238]
**Operating system**
SUSE Linux Enterprise Server 12 (x86_64)

**Package name**
pb-assembly

**Conda environment**
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
avro-python2              1.9.0                      py_0    bioconda
bedtools                  2.29.0               hc088bd4_3    bioconda
blasr                     5.3.3                h018d624_1    bioconda
blasr_libcpp              5.3.3                h018d624_1    bioconda
bwa                       0.7.17               hed695b0_6    bioconda
bzip2                     1.0.8                h516909a_1    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
certifi                   2019.9.11                py27_0    conda-forge
cffi                      1.13.2           py27h8022711_0    conda-forge
chardet                   3.0.4                 py27_1003    conda-forge
cryptography              2.8              py27h72c5cf5_0    conda-forge
curl                      7.65.3               hf8cf82a_0    conda-forge
cython                    0.29.14          py27he1b5a44_0    conda-forge
decorator                 4.4.1                      py_0    conda-forge
enum34                    1.1.6                 py27_1002    conda-forge
falcon-kit                1.3.0                    pypi_0    pypi
falcon-phase              1.0.0                    pypi_0    pypi
falcon-unzip              1.2.0                    pypi_0    pypi
future                    0.18.2                   py27_0    conda-forge
h5py                      2.10.0          nompi_py27h513d04c_100    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
htslib                    1.9                  h244ad75_9    bioconda
idna                      2.8                   py27_1000    conda-forge
ipaddress                 1.0.23                     py_0    conda-forge
iso8601                   0.1.12                     py_1    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libcurl                   7.65.3               hda55be3_0    conda-forge
libdeflate                1.3                  h516909a_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_2    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libopenblas               0.3.7                h6e990d7_3    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
linecache2                1.0.0                      py_1    conda-forge
minimap2                  2.17                 h8b12597_1    bioconda
mummer4                   4.0.0beta2      pl526hf484d3e_4    bioconda
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  1.11                     py27_0    conda-forge
nim-falcon                1.0.1                h2f8a211_0    bioconda
numpy                     1.16.5           py27h95a1406_0    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
pb-assembly               0.0.5                    py27_2    bioconda
pb-dazzler                0.0.1                h516909a_0    bioconda
pb-falcon                 0.2.7            py27hc0aa232_1    bioconda
pbalign                   0.3.2                      py_1    bioconda
pbbam                     1.0.6                hc16d5b3_1    bioconda
pbcommand                 1.1.1                      py_3    bioconda
pbcopper                  1.3.0                h3e4de3e_0    bioconda
pbcore                    1.7.1                    py27_0    bioconda
pbgcpp                    1.0.0                         0    bioconda
pbmm2                     1.1.0                hfb76ee0_0    bioconda
pcre                      8.43                 he1b5a44_0    conda-forge
perl                      5.26.2            h516909a_1006    conda-forge
pip                       19.3.1                   py27_0    conda-forge
pycparser                 2.19                     py27_1    conda-forge
pyopenssl                 19.0.0                   py27_0    conda-forge
pypeflow                  2.2.0                    py27_0    bioconda
pysam                     0.15.3           py27hbcae180_3    bioconda
pysocks                   1.7.1                    py27_0    conda-forge
python                    2.7.15            h5a48372_1009    conda-forge
python-edlib              1.3.6            py27hc9558a2_0    bioconda
python-intervaltree       3.0.2                      py_0    bioconda
python-msgpack            0.6.1            py27hc9558a2_1    bioconda
python-sortedcontainers   2.1.0                      py_0    bioconda
pytz                      2019.3                     py_0    conda-forge
racon                     1.4.10               he513fc3_0    bioconda
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.22.0                   py27_1    conda-forge
samtools                  1.9                 h10a08f8_12    bioconda
setuptools                41.6.0                   py27_1    conda-forge
six                       1.13.0                   py27_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tk                        8.6.9             hed695b0_1003    conda-forge
traceback2                1.4.0                    py27_0    conda-forge
unittest2                 1.1.0                      py_0    conda-forge
urllib3                   1.25.7                   py27_0    conda-forge
wheel                     0.33.6                   py27_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
```

**Describe the bug**
falcon-phase fails immediately and throws the error below. falcon and falcon-unzip ran just fine.

**Error message**
```
falcon-phase 1.0.0
falcon-kit 1.3.0
pypeflow 2.3.0
Traceback (most recent call last):
  File "/dss/dssfs02/lwp-dss-0001/u8c12/u8c12-dss-0000/2019-11-06_EATRO1125/.snakemake/conda/157cd06d/bin/fc_phase.py", line 11, in <module>
    load_entry_point('falcon-phase==1.0.0', 'console_scripts', 'fc_phase.py')()
  File "/dss/dssfs02/lwp-dss-0001/u8c12/u8c12-dss-0000/2019-11-06_EATRO1125/.snakemake/conda/157cd06d/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/dss/dssfs02/lwp-dss-0001/u8c12/u8c12-dss-0000/2019-11-06_EATRO1125/.snakemake/conda/157cd06d/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/dss/dssfs02/lwp-dss-0001/u8c12/u8c12-dss-0000/2019-11-06_EATRO1125/.snakemake/conda/157cd06d/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/dss/dssfs02/lwp-dss-0001/u8c12/u8c12-dss-0000/2019-11-06_EATRO1125/.snakemake/conda/157cd06d/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/dss/dssfs02/lwp-dss-0001/u8c12/u8c12-dss-0000/2019-11-06_EATRO1125/.snakemake/conda/157cd06d/lib/python2.7/site-packages/falcon_phase/mains/start_falcon_phase.py", line 3, in <module>
    from .. import falcon_phase
  File "/dss/dssfs02/lwp-dss-0001/u8c12/u8c12-dss-0000/2019-11-06_EATRO1125/.snakemake/conda/157cd06d/lib/python2.7/site-packages/falcon_phase/falcon_phase.py", line 6, in <module>
    from .tasks import tasks_falcon_phase as tasks_falcon_phase
  File "/dss/dssfs02/lwp-dss-0001/u8c12/u8c12-dss-0000/2019-11-06_EATRO1125/.snakemake/conda/157cd06d/lib/python2.7/site-packages/falcon_phase/tasks/tasks_falcon_phase.py", line 2, in <module>
    from falcon_kit.pype import Dist
  File "/dss/dssfs02/lwp-dss-0001/u8c12/u8c12-dss-0000/2019-11-06_EATRO1125/.snakemake/conda/157cd06d/lib/python2.7/site-packages/falcon_kit/pype.py", line 11, in <module>
    from pypeflow.do_task import wait_for
  File "/dss/dssfs02/lwp-dss-0001/u8c12/u8c12-dss-0000/2019-11-06_EATRO1125/.snakemake/conda/157cd06d/lib/python2.7/site-packages/pypeflow/do_task.py", line 15, in <module>
    from shlex import quote
ImportError: cannot import name quote
```

**Comment by isovic** [comment]
Hi @bgbrink,
It looks like you're using Python2.7, but we upgraded the codebase to Python3.
Can you try to install Python3.7 and use that for your run?
Best regards,
Ivan.

**Comment by armintoepfer** [comment]
Closing due to lack of activity.
