### ISSUE TITLE
pb-assembly fails at 2-asm-falcon after running smoothly at first stages. 

### ISSUE THREAD

**Issue by charlesfeigin** [PacificBiosciences/pbbioconda#240]
Running pb-assembly locally using settings in cfg file in the attachment. Run went smoothly until 2-asm-falcon stage, but failed with an error that I don't really understand. End of the stderr file (also attached) says: 

time python -m falcon_kit.mains.collect_pread_gfa --add-string-graph >| sg.gfa.json
+ python -m falcon_kit.mains.collect_pread_gfa --add-string-graph
falcon-kit 1.3.0
pypeflow 2.2.0
Traceback (most recent call last):
  File "/home/myusername/.conda/envs/denovo_asm/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/myusername/.conda/envs/denovo_asm/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/myusername/.conda/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/mains/collect_pread_gfa.py", line 243, in <module>
    main()
  File "/home/myusername/.conda/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/mains/collect_pread_gfa.py", line 240, in main
    run(sys.stdout, **vars(args))
  File "/home/myusername/.conda/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/mains/collect_pread_gfa.py", line 196, in run
    add_string_graph_to_gfa(gfa_graph, sg_edges_list, utg_data, ctg_paths, preads_dict, preads_overlap_dict, sg_edges_dict)
  File "/home/myusername/.conda/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/mains/collect_pread_gfa.py", line 129, in add_string_graph_to_gfa
    asm_graph = AsmGraph(sg_edges_list, utg_data, ctg_paths)
  File "/home/myusername/.conda/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/fc_asm_graph.py", line 33, in __init__
    self.build_node_map()
  File "/home/myusername/.conda/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/fc_asm_graph.py", line 169, in build_node_map
    sg = self.get_sg_for_ctg(ctg_id)
  File "/home/myusername/.conda/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/fc_asm_graph.py", line 156, in get_sg_for_ctg
    nx.add_path(sg, one_path)
AttributeError: 'module' object has no attribute 'add_path'
2019-11-21 08:21:02,683 - root - WARNING - Call '/bin/bash user_script.sh' returned 256.
2019-11-21 08:21:02,683 - root - INFO - CD: '/home/myusername/data/genomes/my_species/2-asm-falcon' -> '/home/myusername/data/genomes/my_species/2-asm-falcon'
2019-11-21 08:21:02,683 - root - INFO - CD: '/home/myusername/data/genomes/my_species/2-asm-falcon' -> '/home/myusername/data/genomes/my_species/2-asm-falcon'
2019-11-21 08:21:02,684 - root - CRITICAL - Error in /home/myusername/.conda/envs/denovo_asm/lib/python2.7/site-packages/pypeflow/do_task.py with args="{'json_fn': '/home/myusername/data/genomes/my_species/2-asm-falcon/task.json',\n 'timeout': 30,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/home/myusername/.conda/envs/denovo_asm/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/myusername/.conda/envs/denovo_asm/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/myusername/.conda/envs/denovo_asm/lib/python2.7/site-packages/pypeflow/do_task.py", line 281, in <module>
    main()  File "/home/myusername/.conda/envs/denovo_asm/lib/python2.7/site-packages/pypeflow/do_task.py", line 273, in main
    run(**vars(parsed_args))
  File "/home/myusername/.conda/envs/denovo_asm/lib/python2.7/site-packages/pypeflow/do_task.py", line 267, in run
    run_cfg_in_tmpdir(cfg, tmpdir, '.')
  File "/home/myusername/.conda/envs/denovo_asm/lib/python2.7/site-packages/pypeflow/do_task.py", line 242, in run_cfg_in_tmpdir
    run_bash(bash_template, myinputs, myoutputs, parameters)
  File "/home/myusername/.conda/envs/denovo_asm/lib/python2.7/site-packages/pypeflow/do_task.py", line 201, in run_bash
    util.system(cmd)
  File "/home/myusername/.conda/envs/denovo_asm/lib/python2.7/site-packages/pypeflow/io.py", line 29, in syscall
    raise Exception(msg)
Exception: Call '/bin/bash user_script.sh' returned 256.
+++ pwd
++ echo 'FAILURE. Running top in /home/myusername/data/genomes/my_species/2-asm-falcon (If you see -terminal database is inaccessible- you are using the python bin-wrapper, so you will not get diagnostic info. No big deal. This process is crashing anyway.)'
++ rm -f top.txt
++ which python
++ which top
++ env -u LD_LIBRARY_PATH top -b -n 1
++ env -u LD_LIBRARY_PATH top -b -n 1
++ pstree -apl

real    25m15.321s
user    51m59.876s
sys     4m7.425s
+ finish
+ echo 'finish code: 1'

Is this because of a missing python module? It seems like python can't find something it should be able to but I don't really know the language. Is it possible to resume this run without starting from the beginning? Thanks so much for your help, I'm happy to provide any other information that may be helpful.

[my_pb-assembly_run.zip](https://github.com/PacificBiosciences/pbbioconda/files/3876720/my_pb-assembly_run.zip)

**Comment by charlesfeigin** [comment]
Any help would be greatly appreciated

**Comment by isovic** [comment]
Hi @charlesfeigin,
It looks like this might be due to the changes in the NetworkX package, they changed the underlying API between versions.
Can you please pull the latest version of the `pb-assembly` and update all the Conda packages, then try resuming the workflow?

Best regards,
Ivan.

**Comment by armintoepfer** [comment]
Closing due to lack of activity.
