### ISSUE TITLE
falcon_unzip.py failing at 4-polish/track-reads

### ISSUE THREAD

**Issue by duncanberger** [PacificBiosciences/pbbioconda#243]
**Operating system**
Linux version 3.2.0-105-generic
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04 LTS
Release:	12.04
Codename:	precise

**Package name**
fc_unzip.py --version
falcon-unzip 1.3.7 (pip thinks "falcon-unzip 1.3.7")
falcon-kit 1.8.0 (pip thinks "falcon-kit 1.8.0")
pypeflow 2.3.0

**Conda environment**
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
bam2fastx                 1.3.0                he1c1bb9_8    bioconda
bedtools                  2.29.0               hc088bd4_3    bioconda
blasr                     5.3.3                h018d624_1    bioconda
blasr_libcpp              5.3.3                h018d624_1    bioconda
bwa                       0.7.17               hed695b0_6    bioconda
bzip2                     1.0.8                h516909a_1    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
certifi                   2019.9.11                py37_0    conda-forge
cffi                      1.13.2           py37h8022711_0    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
conda                     4.7.12                   py37_0    conda-forge
conda-package-handling    1.6.0            py37h516909a_1    conda-forge
cryptography              2.8              py37h72c5cf5_0    conda-forge
curl                      7.65.3               hf8cf82a_0    conda-forge
decorator                 4.4.1                      py_0    conda-forge
falcon-kit                1.8.0                    pypi_0    pypi
falcon-phase              1.2.0                    pypi_0    pypi
falcon-unzip              1.3.7                    pypi_0    pypi
future                    0.18.2                   py37_0    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
htslib                    1.9                  h244ad75_9    bioconda
idna                      2.8                   py37_1000    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libcurl                   7.65.3               hda55be3_0    conda-forge
libdeflate                1.3                  h516909a_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_2    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libopenblas               0.3.7                h6e990d7_3    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
minimap2                  2.17                 h8b12597_1    bioconda
mummer4                   4.0.0beta2      pl526hf484d3e_4    bioconda
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.4                        py_0    conda-forge
nim-falcon                1.0.1                h2f8a211_0    bioconda
numpy                     1.17.3           py37h95a1406_0    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
pb-assembly               0.0.8                         0    bioconda
pb-dazzler                0.0.1                h516909a_0    bioconda
pb-falcon                 2.2.3            py37hed50d52_0    bioconda
pb-falcon-phase           0.1.0                h3889886_0    bioconda
pbbam                     1.0.6                hc16d5b3_1    bioconda
pbcopper                  1.3.0                h3e4de3e_0    bioconda
pbgcpp                    1.0.0                         0    bioconda
pbmm2                     1.1.0                hfb76ee0_0    bioconda
pcre                      8.43                 he1b5a44_0    conda-forge
perl                      5.26.2            h516909a_1006    conda-forge
pip                       19.3.1                   py37_0    conda-forge
pycosat                   0.6.3           py37h516909a_1002    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pysam                     0.15.3           py37hbcae180_3    bioconda
pysocks                   1.7.1                    py37_0    conda-forge
python                    3.7.3                h33d41f4_1    conda-forge
python-edlib              1.3.6            py37hc9558a2_0    bioconda
python-intervaltree       3.0.2                      py_0    bioconda
python-msgpack            0.6.1            py37hc9558a2_1    bioconda
python-sortedcontainers   2.1.0                      py_0    bioconda
racon                     1.4.10               he513fc3_0    bioconda
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.22.0                   py37_1    conda-forge
ruamel_yaml               0.15.71         py37h14c3975_1000    conda-forge
samtools                  1.9                 h10a08f8_12    bioconda
setuptools                42.0.1                   py37_0    conda-forge
six                       1.13.0                   py37_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
tqdm                      4.39.0                     py_0    conda-forge
urllib3                   1.25.7                   py37_0    conda-forge
wheel                     0.33.6                   py37_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.1.7             h14c3975_1001    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
```

**Describe the bug**
fc_unzip.py fails at the 4-polish/track-reads stage. Looking in the track-reads directory 'job_start.sh' failed. Run files attached:
cfg for unzip
stderr & stdout for 'job_start.sh' (from 4-polish/track-reads stage)

[falcon_unzip.cfg.txt](https://github.com/PacificBiosciences/pbbioconda/files/3894565/falcon_unzip.cfg.txt)
[run-P0b586600618475.bash.stderr.txt](https://github.com/PacificBiosciences/pbbioconda/files/3894566/run-P0b586600618475.bash.stderr.txt)
[run-P0b586600618475.bash.stdout.txt](https://github.com/PacificBiosciences/pbbioconda/files/3894567/run-P0b586600618475.bash.stdout.txt)

I've attempted to remove, reinstall and update pb-assembly multiple times with no change in the error. Up until this stage the assembly process worked fine. 

**Error message**
Partial output from run-P0b586600618475.bash.stderr:
```
[67159]finished run_tr_stage1('../../0-rawreads/build/raw_reads.db', /lustre/scratch118/infgen/team133/db22/assemblies/stest/2227STDY8166692/falcon/0-rawreads/las...(143), 2500, 30)
# That writes a msgpack partial for each raw_reads.*.las file.
# Default n_core is n_cpu/2. TODO: Configure --n-core
# (We also use a proc for LA4Falcon, so this is half.)
# It is actually limited by number of files, but in theory we could use whole machine if we have enough blocks.

abs_rawread_to_contigs=$(readlink -f rawread_to_contigs) #TODO: No readlink
readlink -f rawread_to_contigs)
readlink -f rawread_to_contigs
++ readlink -f rawread_to_contigs
+ abs_rawread_to_contigs=/lustre/scratch118/infgen/team133/db22/assemblies/stest/2227STDY8166692/falcon/4-polish/track-reads/rawread_to_contigs
cwd=$(pwd)
pwd)
pwd
++ pwd
+ cwd=/lustre/scratch118/infgen/team133/db22/assemblies/stest/2227STDY8166692/falcon/4-polish/track-reads
cd ../..
+ cd ../..
falconc rr-hctg-track2 --read-to-contig-map=${cwd}/read_to_contig_map --output=${abs_rawread_to_contigs} --partials-fn=${cwd}/partials.json
+ falconc rr-hctg-track2 --read-to-contig-map=/lustre/scratch118/infgen/team133/db22/assemblies/stest/2227STDY8166692/falcon/4-polish/track-reads/read_to_contig_map --output=/lustre/scratch118/infgen/team133/db22/assemblies/stest/2227STDY8166692/falcon/4-polish/track-reads/rawread_to_contigs --partials-fn=/lustre/scratch118/infgen/team133/db22/assemblies/stest/2227STDY8166692/falcon/4-polish/track-reads/partials.json
could not import: pcre_free_study
2019-11-26 22:10:28,679 - root - WARNING - Call '/bin/bash user_script.sh' returned 256.
2019-11-26 22:10:28,679 - root - INFO - CD: '/lustre/scratch118/infgen/team133/db22/assemblies/stest/2227STDY8166692/falcon/4-polish/track-reads' -> '/lustre/scratch118/infgen/team133/db22/assemblies/stest/2227STDY8166692/falcon/4-polish/track-reads'
2019-11-26 22:10:28,679 - root - INFO - CD: '/lustre/scratch118/infgen/team133/db22/assemblies/stest/2227STDY8166692/falcon/4-polish/track-reads' -> '/lustre/scratch118/infgen/team133/db22/assemblies/stest/2227STDY8166692/falcon/4-polish/track-reads'
2019-11-26 22:10:28,680 - root - CRITICAL - Error in /lustre/scratch118/infgen/team133/db22/software/miniconda3/lib/python3.7/site-packages/pypeflow/do_task.py with args="{'json_fn': '/lustre/scratch118/infgen/team133/db22/assemblies/stest/2227STDY8166692/falcon/4-polish/track-reads/task.json',\n 'timeout': 30,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/lustre/scratch118/infgen/team133/db22/software/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/lustre/scratch118/infgen/team133/db22/software/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/lustre/scratch118/infgen/team133/db22/software/miniconda3/lib/python3.7/site-packages/pypeflow/do_task.py", line 280, in <module>
    main()
  File "/lustre/scratch118/infgen/team133/db22/software/miniconda3/lib/python3.7/site-packages/pypeflow/do_task.py", line 272, in main
    run(**vars(parsed_args))
  File "/lustre/scratch118/infgen/team133/db22/software/miniconda3/lib/python3.7/site-packages/pypeflow/do_task.py", line 266, in run
    run_cfg_in_tmpdir(cfg, tmpdir, '.')
  File "/lustre/scratch118/infgen/team133/db22/software/miniconda3/lib/python3.7/site-packages/pypeflow/do_task.py", line 241, in run_cfg_in_tmpdir
    run_bash(bash_template, myinputs, myoutputs, parameters)
  File "/lustre/scratch118/infgen/team133/db22/software/miniconda3/lib/python3.7/site-packages/pypeflow/do_task.py", line 200, in run_bash
    util.system(cmd)
  File "/lustre/scratch118/infgen/team133/db22/software/miniconda3/lib/python3.7/site-packages/pypeflow/io.py", line 27, in syscall
    raise Exception(msg)
Exception: Call '/bin/bash user_script.sh' returned 256.
pwd) (If you see -terminal database is inaccessible- you are using the python bin-wrapper, so you will not get diagnostic info. No big deal. This process is crashing anyway.)"
pwd) (If you see -terminal database is inaccessible- you are using the python bin-wrapper, so you will not get diagnostic info. No big deal. This process is crashing anyway.)
pwd
+++ pwd
++ echo 'FAILURE. Running top in /lustre/scratch118/infgen/team133/db22/assemblies/stest/2227STDY8166692/falcon/4-polish/track-reads (If you see -terminal database is inaccessible- you are using the python bin-wrapper, so you will not get diagnostic info. No big deal. This process is crashing anyway.)'
++ rm -f top.txt
++ which python
++ which top
++ env -u LD_LIBRARY_PATH top -b -n 1
++ env -u LD_LIBRARY_PATH top -b -n 1
++ pstree -apl

real	9m9.363s
user	196m5.877s
sys	28m1.909s
+ finish
+ echo 'finish code: 1'
```

**To Reproduce**

**Expected behavior**
falcon_unzip.py would finish entire run. 

Thanks.

**Comment by duncanberger** [comment]
I'm assuming this is the issue:
```
falconc rr-hctg-track2 --read-to-contig-map=${cwd}/read_to_contig_map --output=${abs_rawread_to_contigs} --partials-fn=${cwd}/partials.json
+ falconc rr-hctg-track2 --read-to-contig-map=/lustre/scratch118/infgen/team133/db22/assemblies/stest/2227STDY8166692/falcon/4-polish/track-reads/read_to_contig_map --output=/lustre/scratch118/infgen/team133/db22/assemblies/stest/2227STDY8166692/falcon/4-polish/track-reads/rawread_to_contigs --partials-fn=/lustre/scratch118/infgen/team133/db22/assemblies/stest/2227STDY8166692/falcon/4-polish/track-reads/partials.json
could not import: pcre_free_study
```

But so far I've been unable to find a solution. Similar problems for other tools, e.g.:
https://github.com/bioconda/bioconda-recipes/issues/8548
https://github.com/docopt/docopt.nim/issues/13

Would suggest that the pcre version is out of date. Not entirely sure which exact file it's looking for but 'which libpcre.so' find only the assembly conda env. So it's not finding an out of date version. (as far as I can tell).

**Comment by duncanberger** [comment]
And running falconc on it's own (within the environment):

$ falconc --version
could not import: pcre_free_study

$ falconc
could not import: pcre_free_study

**Comment by duncanberger** [comment]
I've now found that the error seems to vary depending on which cluster I use (even though the environments are meant to be identical). So, it seems to be a problem on our end. I'll close this issue.
