### ISSUE TITLE
Arrow: unsupported chemistries found: (unknown)

### ISSUE THREAD

**Issue by ptrebert** [PacificBiosciences/pbbioconda#257]
Hi,
I want to run Arrow polishing on a Sequel-2 CLR dataset (system is `Linux 3.10.0-862.14.4.el7.x86_64 GNU/Linux / CentOS Linux release 7.7.1908`). The Conda env is set up via Snakemake as part of a larger pipeline using the following yaml:
```yaml
name: pbtools
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=2.7.*
  - python-consensuscore2=3.4.1
  - genomicconsensus=2.3.3
  - pbccs=3.4.1
  - pbbam=1.0.6
  - pbmm2=1.1.0
  - pbcoretools=0.2.4
  - bam2fastx=1.3.0
  - hap.py=0.3.10
```
Arrow dies with the following exception:
```
[INFO] Using pbcommand v1.1.1
[INFO] completed setting up logger with <functools.partial object at 0x2b41851968e8>
[INFO] log opts {'file_name': 'log/OMIT_PATH/NA19239_hgsvc_pbsq2-clr_1000-flye.h1.cluster1.arrow-p1.log', 'level': 20}
[INFO] ConsensusCore version: 1.0.2
[INFO] ConsensusCore2 version: 3.4.1
[INFO] Starting.
[INFO] Peeking at file /OMIT_PATH/polishing/alignments/NA19239_hgsvc_pbsq2-clr_1000_map-to_NA19239_hgsvc_pbsq2-clr_1000-flye.h1.cluster1.arrow-p1.psort.pbn.bam
[INFO] Input data: numAlnHits=212422
[INFO] Loading reference
[INFO] Loaded 33 of 33 reference groups from /OMIT_PATH/NA19239_hgsvc_pbsq2-clr_1000-flye.h1.cluster1.fasta 
[INFO] Will use arrow algorithm
[INFO] Found consensus models for: (P6-C4, S/P1-C1.1, S/P1-C1.2, S/P1-C1.3, S/P1-C1/beta, S/P2-C2, S/P2-C2/5.0, S/P3-C1/5.0-8M, S/P3-C3/5.0)
[ERROR] Arrow: unsupported chemistries found: (unknown)
Traceback (most recent call last):
  File "/OMIT_PATH/.snakemake/conda/0150e93d/lib/python2.7/site-packages/pbcommand/cli/core.py", line 138, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/OMIT_PATH/.snakemake/conda/0150e93d/lib/python2.7/site-packages/GenomicConsensus/main.py", line 340, in args_runner
    return tr.main()
  File "/OMIT_PATH/.snakemake/conda/0150e93d/lib/python2.7/site-packages/GenomicConsensus/main.py", line 270, in main
    self._configureAlgorithm(options, peekFile)
  File "/OMIT_PATH/.snakemake/conda/0150e93d/lib/python2.7/site-packages/GenomicConsensus/main.py", line 164, in _configureAlgorithm
    self._algorithmConfiguration = self._algorithm.configure(options, alnFile)
  File "/OMIT_PATH/.snakemake/conda/0150e93d/lib/python2.7/site-packages/GenomicConsensus/arrow/arrow.py", line 233, in configure
    die("Arrow: unsupported chemistries found: ({0})".format(", ".join(sorted(unsupp))))
  File "/OMIT_PATH/.snakemake/conda/0150e93d/lib/python2.7/site-packages/GenomicConsensus/utils.py", line 16, in die
    raise DieException(msg)
DieException: Arrow: unsupported chemistries found: (unknown)
[INFO] exiting with return code 2 in 0.86 sec.
```
The header of the respective BAM files looks as follows:
```
@HD     VN:1.5  SO:coordinate   pb:3.0.7
[@SG OMITTED]
@RG     ID:2fd380fa     PL:PACBIO       DS:READTYPE=SUBREAD;Ipd:CodecV1=ip;PulseWidth:CodecV1=pw;BINDINGKIT=101-789-500;SEQUENCINGKIT=101-826-100;BASECALLERVERSION=5.0.0;FRAMERATEHZ=100.000000        PU:m54336U_191222_173559        SM:NA19239      PM:SEQUELII
@RG     ID:9c35e496     PL:PACBIO       DS:READTYPE=SUBREAD;Ipd:CodecV1=ip;PulseWidth:CodecV1=pw;BINDINGKIT=101-789-500;SEQUENCINGKIT=101-826-100;BASECALLERVERSION=5.0.0;FRAMERATEHZ=100.000000        PU:m54336U_191225_235049        SM:NA19239      PM:SEQUELII
@PG     ID:baz2bam      PN:baz2bam      VN:8.0.0.78867  CL:/opt/pacbio/ppa-8.0.0/bin/baz2bam /data/pa/m54336U_191222_173559.baz -o /data/pa/m54336U_191222_173559 --metadata /data/pa/.m54336U_191222_173559.metadata.xml -j 32 -b 8 --inlinePbi --progress --silent --minSubLength 50 --minSnr 2.000000 --adapters /data/pa/m54336U_191222_173559.adapters.fasta --controlAdapters /data/pa/m54336U_191222_173559.controls.adapters.fasta --controls /data/pa/m54336U_191222_173559.controls.fasta --maxInputQueueZMW 300000 --zmwBatchSize 75000 --zmwHeaderBatchSize 1000000 
@PG     ID:bazFormat    PN:bazformat    VN:1.6.0
@PG     ID:bazwriter    PN:bazwriter    VN:8.0.0
@PG     ID:pbmm2        PN:pbmm2        VN:1.1.0 (commit 1.1.0) CL:pbmm2 align --log-level INFO --sort --sort-memory 682M --no-bai --alignment-threads 22 --sort-threads 2 --preset SUBREAD --sample NA19239 OMIT_PATH/NA19239_hgsvc_pbsq2-clr_1000-flye.h1.cluster1.fasta OMIT_PATH/polishing/alignments/NA19239_hgsvc_pbsq2-clr_1000_map-to_NA19239_hgsvc_pbsq2-clr_1000-flye.h1.cluster1.arrow-p1.psort.pbn.bam
```

I just saw yesterday that Arrow/genomicConsensus has actually reached EOL - will the above be "fixed" by simply upgrading to `pbgcpp=1.9.0`? If so, where can I find more info regarding the QV computation mentioned in the release notes (here: github.com/PacificBiosciences/gcpp)?
Thanks for your help.

Best,
Peter

**Comment by ptrebert** [comment]
Answered via mail: `pbgcpp=1.9.0` should solve the issue.
