### ISSUE TITLE
Error at fc_unzip 3-unzip/2-htigs/chunk_000000F

### ISSUE THREAD

**Issue by audreystott** [PacificBiosciences/pbbioconda#263]
**Operating system**
Linux SLES

**Package name**
pb-assembly 0.0.8

**Describe the bug**
Unable to complete Falcon-unzip step

**Error message**
[ERROR 2020-03-05 14:38:10] Failure in generate_haplotigs_for_ctg(('000000F', '../../0-phasing/000000F/uow-00/proto', './uow-000000F', '../../..', False, 100, 100))
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/falcon_unzip/mains/graphs_to_h_tigs_2.py", line 85, in run_generate_haplotigs_for_ctg
    out_dir, proto_dir, min_query_span, min_target_span, logger)
  File "/usr/local/lib/python3.7/site-packages/falcon_unzip/mains/graphs_to_h_tigs_2.py", line 310, in generate_haplotigs_for_ctg
    nx_to_gfa(ctg_id, haplotig_graph, fp_out)
  File "/usr/local/lib/python3.7/site-packages/falcon_unzip/proto/graphs_to_h_tigs_2_utils.py", line 185, in nx_to_gfa
    node = haplotig_graph.node[v]
AttributeError: 'DiGraph' object has no attribute 'node'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/falcon_unzip/mains/graphs_to_h_tigs_2.py", line 1707, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/falcon_unzip/mains/graphs_to_h_tigs_2.py", line 1703, in main
    args.func(args)
  File "/usr/local/lib/python3.7/site-packages/falcon_unzip/mains/graphs_to_h_tigs_2.py", line 1490, in cmd_apply
    result = run_generate_haplotigs_for_ctg(exe)
  File "/usr/local/lib/python3.7/site-packages/falcon_unzip/mains/graphs_to_h_tigs_2.py", line 85, in run_generate_haplotigs_for_ctg
    out_dir, proto_dir, min_query_span, min_target_span, logger)
  File "/usr/local/lib/python3.7/site-packages/falcon_unzip/mains/graphs_to_h_tigs_2.py", line 310, in generate_haplotigs_for_ctg
    nx_to_gfa(ctg_id, haplotig_graph, fp_out)
  File "/usr/local/lib/python3.7/site-packages/falcon_unzip/proto/graphs_to_h_tigs_2_utils.py", line 185, in nx_to_gfa
    node = haplotig_graph.node[v]
AttributeError: 'DiGraph' object has no attribute 'node'

**To Reproduce**
fc_unzip.py fc_unzip.cfg

**Expected behavior**
Error in the run, and incomplete set of results

**Comment by audreystott** [comment]
Hi guys

Just wanting to give the exact commands I ran that has brought about the above error.

`srun singularity exec pb-assembly_0.0.8--0.sif fc_run fc_run.cfg `
followed by
`srun singularity exec pb-assembly_0.0.8--0.sif fc_unzip.py fc_unzip.cfg &> run1.std`

The pb-assembly container was pulled from [here](https://quay.io/repository/biocontainers/pb-assembly).

**Comment by audreystott** [comment]
[all0.log](https://github.com/PacificBiosciences/pbbioconda/files/4347499/all0.log)
Attached is my log file from fc_unzip.

**Comment by audreystott** [comment]
[fc_run.cfg.txt](https://github.com/PacificBiosciences/pbbioconda/files/4347607/fc_run.cfg.txt)
[fc_unzip.cfg.txt](https://github.com/PacificBiosciences/pbbioconda/files/4347608/fc_unzip.cfg.txt)
Attached are the cfg files for fc_run and fc_unzip, respectively

**Comment by armintoepfer** [comment]
Closing due to lack of activity.
