### ISSUE TITLE
Arrow: unsupported chemistries found: (unknown) even with pbgcpp=1.9.0

### ISSUE THREAD

**Issue by cbplott** [PacificBiosciences/pbbioconda#264]
I am running  Arrow polishing on a Sequel-2 CLR data set on a Linux system (`Linux 4.12.14-150.47-default`) and I am getting an unknown chemistry error:
```Arrow: unsupported chemistries found: (unknown)
Arrow: unsupported chemistries found: (unknown)
Traceback (most recent call last):
  File "/global/homes/c/cplott/.conda/envs/DIST_PACBIO_POLISHING/lib/python2.7/site-packages/pbcommand/cli/core.py", line 138, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/global/homes/c/cplott/.conda/envs/DIST_PACBIO_POLISHING/lib/python2.7/site-packages/GenomicConsensus/main.py", line 340, in args_runner
    return tr.main()
  File "/global/homes/c/cplott/.conda/envs/DIST_PACBIO_POLISHING/lib/python2.7/site-packages/GenomicConsensus/main.py", line 270, in main
    self._configureAlgorithm(options, peekFile)
  File "/global/homes/c/cplott/.conda/envs/DIST_PACBIO_POLISHING/lib/python2.7/site-packages/GenomicConsensus/main.py", line 164, in _configureAlgorithm
    self._algorithmConfiguration = self._algorithm.configure(options, alnFile)
  File "/global/homes/c/cplott/.conda/envs/DIST_PACBIO_POLISHING/lib/python2.7/site-packages/GenomicConsensus/arrow/arrow.py", line 233, in configure
    die("Arrow: unsupported chemistries found: ({0})".format(", ".join(sorted(unsupp))))
  File "/global/homes/c/cplott/.conda/envs/DIST_PACBIO_POLISHING/lib/python2.7/site-packages/GenomicConsensus/utils.py", line 16, in die
    raise DieException(msg)
DieException: Arrow: unsupported chemistries found: (unknown)
[ERROR] Arrow: unsupported chemistries found: (unknown)
Traceback (most recent call last):
  File "/global/homes/c/cplott/.conda/envs/DIST_PACBIO_POLISHING/lib/python2.7/site-packages/pbcommand/cli/core.py", line 138, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/global/homes/c/cplott/.conda/envs/DIST_PACBIO_POLISHING/lib/python2.7/site-packages/GenomicConsensus/main.py", line 340, in args_runner
    return tr.main()
  File "/global/homes/c/cplott/.conda/envs/DIST_PACBIO_POLISHING/lib/python2.7/site-packages/GenomicConsensus/main.py", line 270, in main
    self._configureAlgorithm(options, peekFile)
  File "/global/homes/c/cplott/.conda/envs/DIST_PACBIO_POLISHING/lib/python2.7/site-packages/GenomicConsensus/main.py", line 164, in _configureAlgorithm
    self._algorithmConfiguration = self._algorithm.configure(options, alnFile)
  File "/global/homes/c/cplott/.conda/envs/DIST_PACBIO_POLISHING/lib/python2.7/site-packages/GenomicConsensus/arrow/arrow.py", line 233, in configure
    die("Arrow: unsupported chemistries found: ({0})".format(", ".join(sorted(unsupp))))
  File "/global/homes/c/cplott/.conda/envs/DIST_PACBIO_POLISHING/lib/python2.7/site-packages/GenomicConsensus/utils.py", line 16, in die
    raise DieException(msg)
DieException: Arrow: unsupported chemistries found: (unknown)
```
I have checked to make sure all of my conda packages are up to date:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
asn1crypto                1.3.0                    py27_0
avro-python2              1.9.0                      py_0    bioconda
blas                      1.0                         mkl
blasr                     5.3.3                h707fff8_0    bioconda
blasr_libcpp              5.3.3                h707fff8_0    bioconda
bzip2                     1.0.8                h7b6447c_0
ca-certificates           2020.1.1                      0
certifi                   2019.11.28               py27_0
cffi                      1.13.2           py27h2e261b9_0
chardet                   3.0.4                 py27_1003
cryptography              2.8              py27h1ba5d50_0
curl                      7.68.0               hbc83047_0
cython                    0.29.14          py27he6710b0_0
enum34                    1.1.6                    py27_1
genomicconsensus          2.3.3                      py_1    bioconda
h5py                      2.9.0            py27h7918eee_0
hdf5                      1.10.4               hb1b8bf9_0
htslib                    1.9                  ha228f0b_7    bioconda
idna                      2.8                      py27_0
intel-openmp              2020.0                      166
ipaddress                 1.0.23                     py_0
iso8601                   0.1.12                   py27_1
krb5                      1.17.1               h173b8e3_0
libcurl                   7.68.0               h20c2e04_0
libdeflate                1.0                  h14c3975_1    bioconda
libedit                   3.1.20181209         hc058e9b_0
libffi                    3.2.1                hd88cf55_4
libgcc-ng                 9.1.0                hdf63c60_0
libgfortran-ng            7.3.0                hdf63c60_0
libssh2                   1.8.2                h1ba5d50_0
libstdcxx-ng              9.1.0                hdf63c60_0
linecache2                1.0.0                    py27_0
mkl                       2020.0                      166
mkl-service               2.3.0            py27he904b0f_0
mkl_fft                   1.0.15           py27ha843d7b_0
mkl_random                1.1.0            py27hd6b4f25_0
ncurses                   6.1                  he6710b0_1
numpy                     1.16.5           py27h7e9f1db_0
numpy-base                1.16.5           py27hde5b4d6_0
openssl                   1.1.1d               h7b6447c_4
pbbam                     0.23.0               h88345a9_0    bioconda
pbcommand                 1.1.1                      py_3    bioconda
pbcopper                  0.4.2                h3f2a3d2_1    bioconda
pbcore                    1.7.1                    py27_0    bioconda
pbgcpp                    1.9.0                         0    bioconda
pbmm2                     1.0.0                ha888412_0    bioconda
pip                       19.3.1                   py27_0
pycparser                 2.19                     py27_0
pyopenssl                 19.1.0                   py27_0
pysam                     0.15.3           py27hda2845c_1    bioconda
pysocks                   1.7.1                    py27_0
python                    2.7.17               h9bab390_0
python-consensuscore      1.1.1            py27h3f2a3d2_3    bioconda
python-consensuscore2     3.4.1                    py27_0    bioconda
pytz                      2019.3                     py_0
readline                  7.0                  h7b6447c_5
requests                  2.22.0                   py27_1
samtools                  1.9                 h10a08f8_12    bioconda
setuptools                42.0.2                   py27_0
six                       1.13.0                   py27_0
sqlite                    3.31.1               h7b6447c_0
tk                        8.6.8                hbc83047_0
traceback2                1.4.0                    py27_0
unittest2                 1.1.0                    py27_0
urllib3                   1.25.7                   py27_0
wheel                     0.33.6                   py27_0
xz                        5.2.4                h14c3975_4
zlib                      1.2.11               h7b6447c_3
```
I do not see any reason for me to be getting this error. Any guidence would be greatly appreciated.

**Comment by pb-dseifert** [comment]
`genomicconsensus` is EOL and will not be supported. Try running `gcpp` from the `pbgcpp` (which you have installed as I can see).
