### ISSUE TITLE
preads error

### ISSUE THREAD

**Issue by rob123king** [PacificBiosciences/pbbioconda#270]
I have got to the preads stage by running the cns scripts across the cluster independently then launching the main job again to do cns_gather and carry on. I did this fro the daligner jobs too which worked fine but I seem to have an error which I can't work out why? I should be using the latest bioconda version of Falcon. 

```
executable=${PYPEFLOW_JOB_START_SCRIPT}
+ executable=/home/data/pest_genomics/Falcon2/0-rawreads/preads/run-P245490cce74e2a.bash
timeout=${PYPEFLOW_JOB_START_TIMEOUT:-60} # wait 60s by default
+ timeout=60

# Wait up to timeout seconds for the executable to become "executable",
# then exec.
#timeleft = int(timeout)
while [[ ! -x "${executable}" ]]; do
    if [[ "${timeout}" == "0" ]]; then
        echo "timed out waiting for (${executable})"
        exit 77
    fi
    echo "not executable: '${executable}', waiting ${timeout}s"
    sleep 1
    timeout=$((timeout-1))
done
+ [[ ! -x /home/data/pest_genomics/Falcon2/0-rawreads/preads/run-P245490cce74e2a.bash ]]

/bin/bash ${executable}
+ /bin/bash /home/data/pest_genomics/Falcon2/0-rawreads/preads/run-P245490cce74e2a.bash
+ '[' '!' -d /home/data/pest_genomics/Falcon2/0-rawreads/preads ']'
+ cd /home/data/pest_genomics/Falcon2/0-rawreads/preads
+ eval '/bin/bash run.sh'
++ /bin/bash run.sh
export PATH=$PATH:/bin
+ export PATH=/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/bin:/home/data/pest_genomics/anaconda3a/condabin:/home/data/pest_genomics/anaconda3/bin:/usr/java/jdk1.8.0_60/jre/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/apps/bin:/home/apps/scripts:/home/data/rking/mirdeep2_0_0_7:/home/data/rking/mirdeep2_0_0_7/essentials/ViennaRNA-1.8.4/install_dir/bin:/home/data/rking/mirdeep2_0_0_7/essentials/randfold-2.0:/bin
+ PATH=/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/bin:/home/data/pest_genomics/anaconda3a/condabin:/home/data/pest_genomics/anaconda3/bin:/usr/java/jdk1.8.0_60/jre/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/apps/bin:/home/apps/scripts:/home/data/rking/mirdeep2_0_0_7:/home/data/rking/mirdeep2_0_0_7/essentials/ViennaRNA-1.8.4/install_dir/bin:/home/data/rking/mirdeep2_0_0_7/essentials/randfold-2.0:/bin
cd /home/data/pest_genomics/Falcon2/0-rawreads/preads
+ cd /home/data/pest_genomics/Nezara_viridula/Falcon2/0-rawreads/preads
/bin/bash task.sh
+ /bin/bash task.sh
pypeflow 2.2.0
2020-03-13 19:53:51,365 - root - DEBUG - Running "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/site-packages/pypeflow/do_task.py /home/data/pest_genomics/Falcon2/0-rawreads/preads/task.json"
2020-03-13 19:53:51,391 - root - DEBUG - Checking existence of '/home/data/pest_genomics/Falcon2/0-rawreads/preads/task.json' with timeout=30
2020-03-13 19:53:51,395 - root - DEBUG - Loading JSON from '/home/data/pest_genomics/Falcon2/0-rawreads/preads/task.json'
2020-03-13 19:53:51,397 - root - DEBUG - {u'bash_template_fn': u'template.sh',
 u'inputs': {u'config': u'../../General_config.json',
             u'gathered': u'../cns-gather/gathered.json',
             u'raw_reads_db': u'../repc/rep-combine/raw_reads.db'},
 u'outputs': {u'preads_fofn': u'input_preads.fofn'},
 u'parameters': {u'pypeflow_mb': 4000,
                 u'pypeflow_nproc': 1,
                 u'topdir': u'../..'}}
2020-03-13 19:53:51,398 - root - INFO - CD: '/home/data/pest_genomics/Falcon2/0-rawreads/preads' <- '/home/data/pest_genomics/Falcon2/0-rawreads/preads'
2020-03-13 19:53:51,400 - root - DEBUG - Checking existence of u'../repc/rep-combine/raw_reads.db' with timeout=30
2020-03-13 19:53:51,408 - root - DEBUG - Checking existence of u'../cns-gather/gathered.json' with timeout=30
2020-03-13 19:53:51,409 - root - DEBUG - Checking existence of u'../../General_config.json' with timeout=30
2020-03-13 19:53:51,410 - root - DEBUG - Checking existence of u'template.sh' with timeout=30
2020-03-13 19:53:51,411 - root - INFO - CD: '/home/data/pest_genomics/Falcon2/0-rawreads/preads' <- '/home/data/pest_genomics/Falcon2/0-rawreads/preads'
2020-03-13 19:53:51,416 - root - INFO - $('/bin/bash user_script.sh')
hostname
+ hostname
pwd
+ pwd
date
+ date
# Substitution will be similar to snakemake "shell".
python -m falcon_kit.mains.consensus_gather_fasta_fofn --gathered-fn=../cns-gather/gathered.json --db-fn=../repc/rep-combine/raw_reads.db --config-fn=../../General_config.json --preads-fofn-fn=input_preads.fofn
+ python -m falcon_kit.mains.consensus_gather_fasta_fofn --gathered-fn=../cns-gather/gathered.json --db-fn=../repc/rep-combine/raw_reads.db --config-fn=../../General_config.json --preads-fofn-fn=input_preads.fofn
falcon-kit 1.3.0
pypeflow 2.2.0
Traceback (most recent call last):
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/site-packages/falcon_kit/mains/consensus_gather_fasta_fofn.py", line 90, in <module>
    main()
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/site-packages/falcon_kit/mains/consensus_gather_fasta_fofn.py", line 86, in main
    run(**vars(args))
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/site-packages/falcon_kit/mains/consensus_gather_fasta_fofn.py", line 44, in run
    if 0 == io.filesize(fn):
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/site-packages/falcon_kit/util/io.py", line 235, in filesize
    statinfo = os.stat(fn)
OSError: [Errno 2] No such file or directory: '/home/data/pest_genomics/Falcon2/0-rawreads/cns-gather/../cns-runs/cns_00044/uow-00/consensus.cns_00044.fasta'
2020-03-13 19:53:58,092 - root - WARNING - Call '/bin/bash user_script.sh' returned 256.
2020-03-13 19:53:58,093 - root - INFO - CD: '/home/data/pest_genomics/Falcon2/0-rawreads/preads' -> '/home/data/pest_genomics/Falcon2/0-rawreads/preads'
2020-03-13 19:53:58,094 - root - INFO - CD: '/home/data/pest_genomics/Falcon2/0-rawreads/preads' -> '/home/data/pest_genomics/Falcon2/0-rawreads/preads'
2020-03-13 19:53:58,096 - root - CRITICAL - Error in /home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/site-packages/pypeflow/do_task.py with args="{'json_fn': '/home/data/pest_genomics/Falcon2/0-rawreads/preads/task.json',\n 'timeout': 30,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/site-packages/pypeflow/do_task.py", line 281, in <module>
    main()
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/site-packages/pypeflow/do_task.py", line 273, in main
    run(**vars(parsed_args))
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/site-packages/pypeflow/do_task.py", line 267, in run
    run_cfg_in_tmpdir(cfg, tmpdir, '.')
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/site-packages/pypeflow/do_task.py", line 242, in run_cfg_in_tmpdir
    run_bash(bash_template, myinputs, myoutputs, parameters)
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/site-packages/pypeflow/do_task.py", line 201, in run_bash
    util.system(cmd)
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/site-packages/pypeflow/io.py", line 29, in syscall
    raise Exception(msg)
Exception: Call '/bin/bash user_script.sh' returned 256.
+++ pwd
++ echo 'FAILURE. Running top in /home/data/pest_genomics/Falcon2/0-rawreads/preads (If you see -terminal database is inaccessible- you are using the python bin-wrapper, so you will not get diagnostic info. No big deal. This process is crashing anyway.)'
++ rm -f top.txt
++ which python
++ which top
++ env -u LD_LIBRARY_PATH top -b -n 1
++ env -u LD_LIBRARY_PATH top -b -n 1
++ pstree -apl

real	0m12.521s
user	0m1.449s
sys	0m2.397s
+ finish
+ echo 'finish code: 1'


```

**Comment by rob123king** [comment]
I see missing a file 044
