### ISSUE TITLE
gcpp failing

### ISSUE THREAD

**Issue by marcodelapierre** [PacificBiosciences/pbbioconda#271]
**Operating system**
Ubuntu 18.04

**Package name**
pb-assembly 0.0.8

**Conda environment**
Built a container on 18 March 2020 with the following Dockerfile:
```
FROM continuumio/miniconda3:4.8.2

RUN apt update && apt install -y psmisc

RUN conda install -y -c bioconda pb-assembly=0.0.8
```
Note that I had to build a container rather than use the biocontainer, as currently this one is missing the package `psmisc`, which provides the required tool `pstree`

**Describe the bug**
I try and run the sample pipeline you provide at https://github.com/PacificBiosciences/pb-assembly#example-data-set
The pipeline fails with an error.

**Error message**
Screen error:
```
[ERROR]Task Node(4-polish/quiver-run/000000F) failed with exit-code=1
[ERROR]Task Node(4-polish/quiver-run/000000F_001) failed with exit-code=1
[ERROR]Some tasks are recently_done but not satisfied: {Node(4-polish/quiver-run/000000F_001), Node(4-polish/quiver-run/000000F)}
[ERROR]ready: set()
	submitted: set()
[ERROR]Noop. We cannot kill blocked threads. Hopefully, everything will die on SIGTERM.
[ERROR]Error for run(target=clr, config_fn=fc_unzip.cfg, logging_config_fn=None)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/falcon_unzip/unzip.py", line 195, in run
    run_logged(target, config_fn)
  File "/opt/conda/lib/python3.7/site-packages/falcon_unzip/unzip.py", line 184, in run_logged
    unzip_all(config, unzip_config_fn)
  File "/opt/conda/lib/python3.7/site-packages/falcon_unzip/unzip.py", line 27, in unzip_all
    tasks_unzip.run_workflow(wf, config, unzip_config_fn)
  File "/opt/conda/lib/python3.7/site-packages/falcon_unzip/tasks/unzip.py", line 739, in run_workflow
    job_dict=config['job.step.unzip.quiver'],
  File "/opt/conda/lib/python3.7/site-packages/falcon_kit/pype.py", line 195, in gen_parallel_tasks
    wf.refreshTargets()
  File "/opt/conda/lib/python3.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 278, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/opt/conda/lib/python3.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 362, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: {Node(4-polish/quiver-run/000000F_001), Node(4-polish/quiver-run/000000F)}
Traceback (most recent call last):
  File "/opt/conda/bin/fc_unzip.py", line 11, in <module>
    load_entry_point('falcon-unzip==1.3.7', 'console_scripts', 'fc_unzip.py')()
  File "/opt/conda/lib/python3.7/site-packages/falcon_unzip/mains/start_unzip.py", line 33, in main
    unzip.run(**vars(args))
  File "/opt/conda/lib/python3.7/site-packages/falcon_unzip/unzip.py", line 195, in run
    run_logged(target, config_fn)
  File "/opt/conda/lib/python3.7/site-packages/falcon_unzip/unzip.py", line 184, in run_logged
    unzip_all(config, unzip_config_fn)
  File "/opt/conda/lib/python3.7/site-packages/falcon_unzip/unzip.py", line 27, in unzip_all
    tasks_unzip.run_workflow(wf, config, unzip_config_fn)
  File "/opt/conda/lib/python3.7/site-packages/falcon_unzip/tasks/unzip.py", line 739, in run_workflow
    job_dict=config['job.step.unzip.quiver'],
  File "/opt/conda/lib/python3.7/site-packages/falcon_kit/pype.py", line 195, in gen_parallel_tasks
    wf.refreshTargets()
  File "/opt/conda/lib/python3.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 278, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/opt/conda/lib/python3.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 362, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: {Node(4-polish/quiver-run/000000F_001), Node(4-polish/quiver-run/000000F)}
```

First error inside `4-polish/quiver-run/000000F/run-P8ee12899d659aa.bash.stderr`:
```
gcpp --algorithm=arrow -x 5 -X 120 -q 0 -j $nproc -r ../../../quiver-split/refs/000000F/ref.fasta aln-000000F.bam            -o ${fasta_fn},${fastq_fn},cns.vcf
+ gcpp --algorithm=arrow -x 5 -X 120 -q 0 -j 1 -r ../../../quiver-split/refs/000000F/ref.fasta aln-000000F.bam -o cns.fasta,cns.fastq,cns.vcf
rc=$?
+ rc=1
if [[ $rc != 0 ]]; then
    if [[ $VC_IGNORE_ERROR != 1 ]]; then
        echo ERROR gcpp failed. Maybe no reads for this block?
        exit 1
    else
        echo WARNING gcpp failed. Maybe no reads for this block.
        # We expect gcpp to write files even on error, so we do not need to "touch" them.
    fi
fi
+ [[ 1 != 0 ]]
+ [[ 0 != 1 ]]
+ echo ERROR gcpp failed. Maybe no reads for this 'block?'
+ exit 1
touch quiver_done.exit
+ touch quiver_done.exit
WARNING:root:Call '/bin/bash user_script.sh' returned 256.
```

There's a similar error in `4-polish/quiver-run/000000F_001/run-P483c9b764f6a24.bash.stderr`

**To Reproduce**
I followed the steps you provide in the example mentioned above. I have only edited the runtime commands to use the container I have built:

```
mkdir -p /data/work/falcon/docker
cd /data/work/falcon/docker

cat << EOF >Dockerfile
FROM continuumio/miniconda3:4.8.2

RUN apt update && apt install -y psmisc

RUN conda install -y -c bioconda pb-assembly=0.0.8
EOF

docker build -t mycontainer .

cd ..
mkdir test_pb_official
cd test_pb_official

git clone https://github.com/cdunn2001/git-sym.git
git clone https://github.com/pb-cdunn/FALCON-examples.git
cd FALCON-examples
../git-sym/git-sym update run/greg200k-sv2

cd run/greg200k-sv2
docker run -u $(id -u):$(id -g) -v /data/work:/data/work -w $(pwd) --rm  mycontainer fc_run fc_run.cfg
docker run -u $(id -u):$(id -g) -v /data/work:/data/work -w $(pwd) --rm  mycontainer fc_unzip.py fc_unzip.cfg
```

**Expected behavior**
As you state: "If everything was installed properly the test case will exit cleanly and you should find fasta files with a
size greater than 0 in the 4-polish/cns-output directory."

**Comment by pb-dseifert** [comment]
Hi @marcodelapierre  
thanks for reporting this. Would you be willing to share your data? All data shared with PacBio is treated strictly confidentially, and this makes debugging (and fixing) a lot easier for us.

**Comment by AntoineHo** [comment]
Hello, I have exactly the same error on the same dataset. Any idea on how to solve this ?

Ubuntu 18.10

```
# packages in environment at /home/lege/anaconda3/envs/pbasm:           
#                                                                       
# Name                    Version                   Build  Channel      
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
aioeasywebdav             2.4.0                 py37_1000    conda-forge
aiohttp                   3.6.2            py37h516909a_0    conda-forge
appdirs                   1.4.3                      py_1    conda-forge
async-timeout             3.0.1                   py_1000    conda-forge
attrs                     19.3.0                     py_0    conda-forge  
bamtools                  2.5.1                he513fc3_6    bioconda     
bax2bam                   0.0.9                h018d624_7    bioconda     
bcrypt                    3.1.7            py37h8f50634_1    conda-forge  
bedtools                  2.29.2               hc088bd4_0    bioconda     
blasr                     5.3.3                h018d624_2    bioconda     
blasr_libcpp              5.3.3                h018d624_1    bioconda     
boto3                     1.14.20            pyh9f0ad1d_0    conda-forge  
botocore                  1.17.20            pyh9f0ad1d_0    conda-forge  
brotlipy                  0.7.0           py37h8f50634_1000    conda-forge
bwa                       0.7.17               hed695b0_7    bioconda     
bzip2                     1.0.8                h516909a_2    conda-forge  
ca-certificates           2020.6.20            hecda079_0    conda-forge  
cachetools                4.1.1                      py_0    conda-forge  
cairo                     1.16.0            h3fc0475_1005    conda-forge  
certifi                   2020.6.20        py37hc8dfbb8_0    conda-forge  
cffi                      1.14.0           py37hd463f26_0    conda-forge  
chardet                   3.0.4           py37hc8dfbb8_1006    conda-forge
configargparse            1.2.3              pyh9f0ad1d_0    conda-forge  
crc32c                    2.0              py37h516909a_0    conda-forge  
cryptography              2.9.2            py37hb09aad4_0    conda-forge  
curl                      7.71.1               he644dc0_1    conda-forge  
datrie                    0.8.2            py37h8f50634_0    conda-forge  
decorator                 4.4.2                      py_0    conda-forge  
docutils                  0.15.2                   py37_0    conda-forge  
dropbox                   10.1.1             pyh9f0ad1d_0    conda-forge  
expat                     2.2.9                he1b5a44_2    conda-forge  
falcon-kit                1.8.1                    pypi_0    pypi         
falcon-phase              1.2.0                    pypi_0    pypi         
falcon-unzip              1.3.7                    pypi_0    pypi               
fftw                      3.3.8           mpi_mpich_h3f9e1be_1011    conda-forge
filechunkio               1.8                        py_2    conda-forge        
fontconfig                2.13.1            h1056068_1002    conda-forge        
freetype                  2.10.2               he06d7ca_0    conda-forge        
ftputil                   4.0.0                      py_0    conda-forge        
future                    0.18.2           py37hc8dfbb8_1    conda-forge        
gdk-pixbuf                2.36.12           h3f25603_1005    conda-forge        
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge        
ghostscript               9.22              hf484d3e_1001    conda-forge        
giflib                    5.1.7                h516909a_1    conda-forge        
gitdb                     4.0.5                      py_0    conda-forge        
gitpython                 3.1.3                      py_0    conda-forge        
glib                      2.65.0               h6f030ca_0    conda-forge        
gobject-introspection     1.64.1           py37h619baee_1    conda-forge        
google-api-core           1.17.0           py37hc8dfbb8_0    conda-forge        
google-api-python-client  1.9.1              pyh9f0ad1d_1    conda-forge        
google-auth               1.19.0                     py_0    conda-forge        
google-auth-httplib2      0.0.3                      py_3    conda-forge        
google-cloud-core         1.3.0                      py_0    conda-forge        
google-cloud-storage      1.28.1             pyh9f0ad1d_0    conda-forge        
google-resumable-media    0.5.1              pyh9f0ad1d_0    conda-forge        
googleapis-common-protos  1.51.0           py37hc8dfbb8_2    conda-forge        
graphite2                 1.3.13            he1b5a44_1001    conda-forge        
graphviz                  2.38.0            hf68f40c_1011    conda-forge        
harfbuzz                  2.4.0                hee91db6_5    conda-forge        
hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge    
htslib                    1.9                  h4da6232_3    bioconda           
httplib2                  0.18.1             pyh9f0ad1d_0    conda-forge        
icu                       67.1                 he1b5a44_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
imagemagick               7.0.8_54        pl526h39023e4_0    conda-forge
importlib-metadata        1.7.0            py37hc8dfbb8_0    conda-forge
importlib_metadata        1.7.0                         0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jbig                      2.1               h516909a_2002    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
jmespath                  0.10.0             pyh9f0ad1d_0    conda-forge
jpeg                      9d                   h516909a_0    conda-forge
jsonschema                3.2.0            py37hc8dfbb8_1    conda-forge
jupyter_core              4.6.3            py37hc8dfbb8_1    conda-forge
k8                        0.2.5                he513fc3_0    bioconda   
krb5                      1.17.1               hfafb76e_1    conda-forge
ld_impl_linux-64          2.34                 h53a641e_7    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libcroco                  0.6.13               h8d621e5_1    conda-forge
libcurl                   7.71.1               hcdd3856_1    conda-forge
libdeflate                1.6                  h516909a_0    conda-forge
libedit                   3.1.20191231         h46ee950_1    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran-ng            7.5.0                hdf63c60_6    conda-forge
libiconv                  1.15              h516909a_1006    conda-forge
liblapack                 3.8.0               17_openblas    conda-forge
libopenblas               0.3.10               h5ec1e0e_0    conda-forge
libpng                    1.6.37               hed695b0_1    conda-forge
libprotobuf               3.12.3               h8b12597_1    conda-forge
librsvg                   2.44.14              h11c8777_0    conda-forge
libssh2                   1.9.0                hab1572f_3    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libtiff                   4.1.0                hc3755c2_3    conda-forge
libtool                   2.4.6             h14c3975_1002    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp                   1.0.2                hf4e8a37_4    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.10               h72b56ed_1    conda-forge
llvm-openmp               10.0.0               hc9558a2_0    conda-forge
lz4-c                     1.9.2                he1b5a44_1    conda-forge
markupsafe                1.1.1            py37h8f50634_1    conda-forge
minimap2                  2.17                 hed695b0_2    bioconda   
mpi                       1.0                       mpich    conda-forge
mpich                     3.3.2                hc856adb_0    conda-forge
multidict                 4.7.5            py37h8f50634_1    conda-forge
mummer4                   4.0.0beta2      pl526he1b5a44_5    bioconda   
nbformat                  5.0.7                      py_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.4                        py_1    conda-forge
nim-falcon                1.5.1                h1341992_0    bioconda   
numpy                     1.18.5           py37h8960a57_0    conda-forge
oauth2client              4.1.3                      py_0    conda-forge
openjpeg                  2.3.1                h981e76c_3    conda-forge
openssl                   1.1.1g               h516909a_1    conda-forge
pandas                    1.0.5            py37h0da4684_0    conda-forge
pango                     1.40.14           he7ab937_1005    conda-forge
paramiko                  2.7.1                    py37_0    conda-forge
pb-assembly               0.0.8                         0    bioconda   
pb-dazzler                0.0.1                h516909a_0    bioconda   
pb-falcon                 2.2.4            py37hed50d52_0    bioconda      
pb-falcon-phase           0.1.0                h3889886_0    bioconda      
pbbam                     1.0.6                hc16d5b3_0    bioconda      
pbcopper                  1.3.0                h3e4de3e_0    bioconda      
pbgcpp                    1.9.0                         0    bioconda      
pbmm2                     1.3.0                h56fc30b_0    bioconda      
pcre                      8.44                 he1b5a44_0    conda-forge   
perl                      5.26.2            h516909a_1006    conda-forge   
pip                       20.1.1                     py_1    conda-forge   
pixman                    0.38.0            h516909a_1003    conda-forge   
pkg-config                0.29.2            h516909a_1006    conda-forge   
prettytable               0.7.2                      py_3    conda-forge   
protobuf                  3.12.3           py37h3340039_0    conda-forge   
psutil                    5.7.0            py37h8f50634_1    conda-forge   
pthread-stubs             0.4               h14c3975_1001    conda-forge   
pyasn1                    0.4.8                      py_0    conda-forge   
pyasn1-modules            0.2.7                      py_0    conda-forge   
pycparser                 2.20               pyh9f0ad1d_2    conda-forge   
pygments                  2.6.1                      py_0    conda-forge   
pygraphviz                1.5             py37h8f50634_1002    conda-forge 
pynacl                    1.3.0           py37h516909a_1001    conda-forge 
pyopenssl                 19.1.0                     py_1    conda-forge   
pyrsistent                0.16.0           py37h8f50634_0    conda-forge   
pysam                     0.16.0.1         py37hc334e0b_1    bioconda      
pysftp                    0.2.9                      py_1    conda-forge   
pysocks                   1.7.1            py37hc8dfbb8_1    conda-forge   
python                    3.7.6           cpython_h8356626_6    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge   
python-edlib              1.3.8.post1      py37h9a982cc_2    bioconda      
python-intervaltree       3.0.2                      py_0    bioconda      
python-irodsclient        0.8.2                      py_0    conda-forge  
python-msgpack            0.6.1            py37h9a982cc_3    bioconda     
python-sortedcontainers   2.2.2              pyh9f0ad1d_0    bioconda     
python_abi                3.7                     1_cp37m    conda-forge  
pytz                      2020.1             pyh9f0ad1d_0    conda-forge  
pyyaml                    5.3.1            py37h8f50634_0    conda-forge  
racon                     1.4.13               he513fc3_0    bioconda     
ratelimiter               1.2.0           py37hc8dfbb8_1001    conda-forge
readline                  8.0                  h46ee950_1    conda-forge  
requests                  2.24.0             pyh9f0ad1d_0    conda-forge  
rsa                       4.6                pyh9f0ad1d_0    conda-forge  
s3transfer                0.3.3            py37hc8dfbb8_1    conda-forge  
samtools                  1.9                 h10a08f8_12    bioconda     
setuptools                49.2.0           py37hc8dfbb8_0    conda-forge  
simplejson                3.17.0           py37h8f50634_1    conda-forge  
six                       1.15.0             pyh9f0ad1d_0    conda-forge  
slacker                   0.14.0                     py_0    conda-forge  
smmap                     3.0.4              pyh9f0ad1d_0    conda-forge  
snakemake                 5.20.1                        0    bioconda     
snakemake-minimal         5.20.1                     py_0    bioconda     
sqlite                    3.32.3               hcee41ef_1    conda-forge  
tk                        8.6.10               hed695b0_0    conda-forge  
toposort                  1.5                        py_3    conda-forge  
traitlets                 4.3.3            py37hc8dfbb8_1    conda-forge  
uritemplate               3.0.1                      py_0    conda-forge  
urllib3                   1.25.9                     py_0    conda-forge  
wheel                     0.34.2                     py_1    conda-forge  
wrapt                     1.12.1           py37h8f50634_1    conda-forge  
xmlrunner                 1.7.7                      py_0    conda-forge  
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge  
xorg-libice               1.0.10               h516909a_0    conda-forge  
xorg-libsm                1.2.3             h84519dc_1000    conda-forge  
xorg-libx11               1.6.9                h516909a_0    conda-forge  
xorg-libxau               1.0.9                h14c3975_0    conda-forge  
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge  
xorg-libxext              1.3.4                h516909a_0    conda-forge  
xorg-libxpm               3.5.13               h516909a_0    conda-forge  
xorg-libxrender           0.9.10            h516909a_1002    conda-forge  
xorg-libxt                1.1.5             h516909a_1003    conda-forge  
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge  
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge  
xorg-xproto               7.0.31            h14c3975_1007    conda-forge  
xz                        5.2.5                h516909a_1    conda-forge  
yaml                      0.2.5                h516909a_0    conda-forge  
yarl                      1.3.0           py37h516909a_1000    conda-forge
zipp                      3.1.0                      py_0    conda-forge  
zlib                      1.2.11            h516909a_1006    conda-forge  
zstd                      1.4.4                h6597ccf_3    conda-forge  
```

File `run-P3f542ff9b584b7.bash.stderr`
```
set +e
+ set +e
gcpp --algorithm=arrow -x 5 -X 120 -q 0 -j $nproc -r ../../../quiver-split/refs/000000F/ref.fasta aln-000000F.bam            -o ${fasta_fn},${fastq_fn},cns.vcf
+ gcpp --algorithm=arrow -x 5 -X 120 -q 0 -j 1 -r ../../../quiver-split/refs/000000F/ref.fasta aln-000000F.bam -o cns.fasta,cns.fastq,cns.vcf
rc=$?
+ rc=1
if [[ $rc != 0 ]]; then
    if [[ $VC_IGNORE_ERROR != 1 ]]; then
        echo ERROR gcpp failed. Maybe no reads for this block?
        exit 1
    else
        echo WARNING gcpp failed. Maybe no reads for this block.
        # We expect gcpp to write files even on error, so we do not need to "touch" them.
    fi
fi
+ [[ 1 != 0 ]]
+ [[ 0 != 1 ]]
+ echo ERROR gcpp failed. Maybe no reads for this 'block?'
+ exit 1
touch quiver_done.exit
+ touch quiver_done.exit
WARNING:root:Call '/bin/bash user_script.sh' returned 256.
INFO:root:CD: 'uow-00' -> '/mnt/sda1/Antoine/22-06-20_HiCHomologs/TEST/pb-asm/FALCON-examples/run/greg200k-sv2/4-polish/quiver-run/000000F'
ERROR:root:failed multiprocessing
multiprocessing.pool.RemoteTraceback: 
...
```

I looked into the folder `uow-00` and I cannot find the output of `gcpp`. I am guessing that it should contain these files: `cns.fasta`, `cns.fastq`, `cns.vcf`.

When I try to send manually the command found in `run-P3f542ff9b584b7.bash.stderr`, the shell is freed immediately without any error message but no output files either. It does not seem to run at all.

```
$ time gcpp --algorithm=arrow -x 5 -X 120 -q 0 -j 1 -r ../../../quiver-split/refs/000000F/ref.fasta aln-000000F.bam -o cns.fasta,cns.fastq,cns.vcf
gcpp --algorithm=arrow -x 5 -X 120 -q 0 -j 1 -r  aln-000000F.bam -o   0.00s user 0.00s system 93% cpu 0.006 total
$ ls
aln-000000F.bam  aln-000000F.bam.bai  aln-000000F.bam.pbi  quiver_done.exit  user_script.sh
```

Any idea how to solve this?

Cheers,
AH

**Comment by pb-cdunn** [comment]
First, because of changes in conda or bioconda, I needed this:

    conda install samtools=1.9

Second, I think it works without `pstree`, except the error message at the end won't show the process-tree, so I don't think you need **psmisc**.

Third,
```sh
+ pbmm2 align --sort ../../../quiver-split/refs/000000F/ref.fasta /localdisk/scratch/cdunn/bioc/bioconda-recipes/recipes/pbipa/FALCON-examples/run/greg200k-sv2/4-polish/segregate-run/segr000/segregated/000000F/000000F.bam aln-000000F.bam
+ pbindex aln-000000F.bam
user_script.sh: line 22: pbindex: command not found
```
That means `pbindex` is missing. That is in **pbbam**, so simply run this:

    conda install pbbam
    which pbindex

But I guess you got through all those parts.

Finally, the bug.
```
+ gcpp --algorithm=arrow -x 5 -X 120 -q 0 -j 1 -r ../../../quiver-split/refs/000000F/ref.fasta     aln-000000F.bam -o cns.fasta,cns.fastq,cns.vcf
...
+ echo ERROR gcpp failed. Maybe no reads for this 'block?'
```

I've pushed a new tarball -- based on newer chemistry -- into pacbcloud. If you update `FALCON-examples` and re-run your `git-sym` command, you'll have it. You should then `cd run/greg-200k-sv2; rm -rf 3-* 4-*; make unzip`. Or just clean and re-run the whole thing. It works for me now.
