### ISSUE TITLE
DieException: Arrow: unsupported chemistries found: (unknown)

### ISSUE THREAD

**Issue by forrwill** [PacificBiosciences/pbbioconda#276]
software， smrtlink7.00
when I running arrow process，the problem comes out，and the log information is as below, and I do not know the reason, 
![image](https://user-images.githubusercontent.com/41096851/77977597-b32f4500-7332-11ea-9264-13e76de45cee.png)

**Comment by forrwill** [comment]
[ERROR] Arrow: unsupported chemistries found: (unknown)
Traceback (most recent call last):
  File "/public2/Bio/Project/jzliu/software/smrtlink/install/smrtlink-release_7.0.0.63985/bundles/smrttools/install/smrttools-release_7.0.0.63823/private/thirdparty/python/python_2.7.9/site-packages/pbcommand/cli/core.py", line 138, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/public2/Bio/Project/jzliu/software/smrtlink/install/smrtlink-release_7.0.0.63985/bundles/smrttools/install/smrttools-release_7.0.0.63823/private/thirdparty/python/python_2.7.9/site-packages/GenomicConsensus/main.py", line 340, in args_runner
    return tr.main()
  File "/public2/Bio/Project/jzliu/software/smrtlink/install/smrtlink-release_7.0.0.63985/bundles/smrttools/install/smrttools-release_7.0.0.63823/private/thirdparty/python/python_2.7.9/site-packages/GenomicConsensus/main.py", line 270, in main
    self._configureAlgorithm(options, peekFile)
  File "/public2/Bio/Project/jzliu/software/smrtlink/install/smrtlink-release_7.0.0.63985/bundles/smrttools/install/smrttools-release_7.0.0.63823/private/thirdparty/python/python_2.7.9/site-packages/GenomicConsensus/main.py", line 164, in _configureAlgorithm
    self._algorithmConfiguration = self._algorithm.configure(options, alnFile)
  File "/public2/Bio/Project/jzliu/software/smrtlink/install/smrtlink-release_7.0.0.63985/bundles/smrttools/install/smrttools-release_7.0.0.63823/private/thirdparty/python/python_2.7.9/site-packages/GenomicConsensus/arrow/arrow.py", line 233, in configure
    die("Arrow: unsupported chemistries found: ({0})".format(", ".join(sorted(unsupp))))
  File "/public2/Bio/Project/jzliu/software/smrtlink/install/smrtlink-release_7.0.0.63985/bundles/smrttools/install/smrttools-release_7.0.0.63823/private/thirdparty/python/python_2.7.9/site-packages/GenomicConsensus/utils.py", line 16, in die
    raise DieException(msg)
DieException: Arrow: unsupported chemistries found: (unknown)

**Comment by forrwill** [comment]
when I changed the chemistry mapping.xml file with the latest version, the task died with the log "[ERROR] Arrow: unsupported chemistries found: (S/P4-C2/5.0-8M)"

**Comment by forrwill** [comment]
and another question is that is there arrow in smrtlink8.0? thank you

**Comment by pb-dseifert** [comment]
`GenomicConsensus` is an EOL software and unsupported. `gcpp` is the spiritual successor. SL 8.0 does not include `GenomicConsensus` anymore, hence you'll find no `arrow` command.
