### ISSUE TITLE
Arrow: unsupported chemistries found: (unknown)

### ISSUE THREAD

**Issue by MMengrui** [PacificBiosciences/pbbioconda#289]
**Operating system**
I am using the conda to install the packages

**Package name**
genomicconsensus

**Conda environment**
What is the result of `conda list`? (Try to paste that between [triple backticks](https://help.github.com/articles/creating-and-highlighting-code-blocks/).)

**Describe the bug**
Arrow: unsupported chemistries found: (unknown)
Arrow: unsupported chemistries found: (unknown)
Traceback (most recent call last):
  File "/home/sugon/miniconda3/envs/pb-assembly/lib/python2.7/site-packages/pbcommand/cli/core.py", line 138, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/home/sugon/miniconda3/envs/pb-assembly/lib/python2.7/site-packages/GenomicConsensus/main.py", line 340, in args_runner
    return tr.main()
  File "/home/sugon/miniconda3/envs/pb-assembly/lib/python2.7/site-packages/GenomicConsensus/main.py", line 270, in main
    self._configureAlgorithm(options, peekFile)
  File "/home/sugon/miniconda3/envs/pb-assembly/lib/python2.7/site-packages/GenomicConsensus/main.py", line 164, in _configureAlgorithm
    self._algorithmConfiguration = self._algorithm.configure(options, alnFile)
  File "/home/sugon/miniconda3/envs/pb-assembly/lib/python2.7/site-packages/GenomicConsensus/arrow/arrow.py", line 233, in configure
    die("Arrow: unsupported chemistries found: ({0})".format(", ".join(sorted(unsupp))))
  File "/home/sugon/miniconda3/envs/pb-assembly/lib/python2.7/site-packages/GenomicConsensus/utils.py", line 16, in die
    raise DieException(msg)
DieException: Arrow: unsupported chemistries found: (unknown)
[ERROR] Arrow: unsupported chemistries found: (unknown)
Traceback (most recent call last):
  File "/home/sugon/miniconda3/envs/pb-assembly/lib/python2.7/site-packages/pbcommand/cli/core.py", line 138, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/home/sugon/miniconda3/envs/pb-assembly/lib/python2.7/site-packages/GenomicConsensus/main.py", line 340, in args_runner
    return tr.main()
  File "/home/sugon/miniconda3/envs/pb-assembly/lib/python2.7/site-packages/GenomicConsensus/main.py", line 270, in main
    self._configureAlgorithm(options, peekFile)
  File "/home/sugon/miniconda3/envs/pb-assembly/lib/python2.7/site-packages/GenomicConsensus/main.py", line 164, in _configureAlgorithm
    self._algorithmConfiguration = self._algorithm.configure(options, alnFile)
  File "/home/sugon/miniconda3/envs/pb-assembly/lib/python2.7/site-packages/GenomicConsensus/arrow/arrow.py", line 233, in configure
    die("Arrow: unsupported chemistries found: ({0})".format(", ".join(sorted(unsupp))))
  File "/home/sugon/miniconda3/envs/pb-assembly/lib/python2.7/site-packages/GenomicConsensus/utils.py", line 16, in die
    raise DieException(msg)
DieException: Arrow: unsupported chemistries found: (unknown)

**To Reproduce**
~/miniconda3/envs/pb-assembly/bin/arrow --referenceFilename hui-assemble.contigs.fasta hui-pbalign.bam -o hui-arrow.fasta

**Comment by pb-dseifert** [comment]
`GenomicConsensus` is EOL and any problems found with it will not fixed. Please try `pbgcpp` instead.

**Comment by MMengrui** [comment]
Thanks very much, but how to polish the contigs with pbgcpp?
