### ISSUE TITLE
Arrow: unsupported chemistries found: (unknown) smrtlink 7.0.0

### ISSUE THREAD

**Issue by XuewenWangUGA** [PacificBiosciences/pbbioconda#291]
I am using Linux system which installed smrtlink 7.0.0

I am calling variance using squeal II CLR reads against assembly.
command: 
 variantCaller  --algorithm  arrow -j $nthrd --minCoverage 5 --coverage 100 --referenceFilename $gassembly -o $polsseq.fa -o $polsseq.vcf $alnrefbam

where $alnrefbam was generated from pbmm2 via command
pbmm2 align $gassembly subreadsBamsets.fofn $alnrefbam --sort -j $nthrd -J $sortnthrd 

**Error message**
Paste the error message / stack.
Arrow: unsupported chemistries found: (unknown)
Arrow: unsupported chemistries found: (unknown)
Traceback (most recent call last):
  File "/lustre/software/smrtanalysis/smrtlink/install/smrtlink-release_7.0.0.63985/bundles/smrttools/install/smrttools-release_7.0.0.63823/private/thirdparty/python/python_2.7.9/site-packages/pbcommand/cli/core.py", line 138, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/lustre/software/smrtanalysis/smrtlink/install/smrtlink-release_7.0.0.63985/bundles/smrttools/install/smrttools-release_7.0.0.63823/private/thirdparty/python/python_2.7.9/site-packages/GenomicConsensus/main.py", line 340, in args_runner
    return tr.main()
  File "/lustre/software/smrtanalysis/smrtlink/install/smrtlink-release_7.0.0.63985/bundles/smrttools/install/smrttools-release_7.0.0.63823/private/thirdparty/python/python_2.7.9/site-packages/GenomicConsensus/main.py", line 270, in main
    self._configureAlgorithm(options, peekFile)
  File "/lustre/software/smrtanalysis/smrtlink/install/smrtlink-release_7.0.0.63985/bundles/smrttools/install/smrttools-release_7.0.0.63823/private/thirdparty/python/python_2.7.9/site-packages/GenomicConsensus/main.py", line 164, in _configureAlgorithm
    self._algorithmConfiguration = self._algorithm.configure(options, alnFile)
  File "/lustre/software/smrtanalysis/smrtlink/install/smrtlink-release_7.0.0.63985/bundles/smrttools/install/smrttools-release_7.0.0.63823/private/thirdparty/python/python_2.7.9/site-packages/GenomicConsensus/arrow/arrow.py", line 233, in configure
    die("Arrow: unsupported chemistries found: ({0})".format(", ".join(sorted(unsupp))))
  File "/lustre/software/smrtanalysis/smrtlink/install/smrtlink-release_7.0.0.63985/bundles/smrttools/install/smrttools-release_7.0.0.63823/private/thirdparty/python/python_2.7.9/site-packages/GenomicConsensus/utils.py", line 16, in die
    raise DieException(msg)
DieException: Arrow: unsupported chemistries found: (unknown)

Question:
Any help or suggestion on this error? Thanks.

**Comment by armintoepfer** [comment]
As this is a SMRTLink and not a bioconda related question, please report your problem to PacBio's tech support.
