### ISSUE TITLE
Error with FALCON: Task Node(2-asm-falcon) failed with exit-code=1

### ISSUE THREAD

**Issue by jialei0701** [PacificBiosciences/pbbioconda#294]
Hi, guys.

My pb-assembly was installed with following commands:
```
conda create -n pb-assembly
conda activate pb-assembly
conda install pb-assembly
```  

when I run with example data, the following error message appears:
```
[ERROR]Task Node(2-asm-falcon) failed with exit-code=1
[ERROR]Some tasks are recently_done but not satisfied: {Node(2-asm-falcon)}
[ERROR]ready: set()
        submitted: set()
[ERROR]Noop. We cannot kill blocked threads. Hopefully, everything will die on SIGTERM.
Traceback (most recent call last):
  File "***/software/miniconda3/envs/pb-assembly/bin/fc_run.py", line 11, in <module>
    load_entry_point('falcon-kit==1.8.1', 'console_scripts', 'fc_run.py')()
  File "***/software/miniconda3/envs/pb-assembly/lib/python3.7/site-packages/falcon_kit/mains/run1.py", line 706, in main
    main1(argv[0], args.config, args.logger)
  File "***/software/miniconda3/envs/pb-assembly/lib/python3.7/site-packages/falcon_kit/mai
ns/run1.py", line 73, in main1
    input_fofn_fn=input_fofn_fn,
  File "***/software/miniconda3/envs/pb-assembly/lib/python3.7/site-packages/falcon_kit/mai
ns/run1.py", line 460, in run
    wf.refreshTargets()
  File "***/software/miniconda3/envs/pb-assembly/lib/python3.7/site-packages/pypeflow/simpl
e_pwatcher_bridge.py", line 278, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "***/software/miniconda3/envs/pb-assembly/lib/python3.7/site-packages/pypeflow/simpl
e_pwatcher_bridge.py", line 362, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: {Node(2-asm-falcon)}
```
After check 'run-Paf09d75706fc2e.bash.stderr' within 2-asm-falcon dir, I got error message like this:
```
Error: unhandled exception: overlapParser.nim(75, 20) `iSpace != -1` Bad input line '---'.
```
I try to run command within file **user_script.sh** separately, I got the command (`time python3 -m falcon_kit.mains.ovlp_to_graph  --min-len 1 --overlap-file preads.filtered.m4 >| fc_ovlp_to_graph.log`) where this error occurred.
Based on error message, I found file preads.m4 end with `---`. When I remove the last line of preads.m4, error message disappeared.
So I just add a command(`sed -i '$d' preads.m4`) after the command(`time python3 -m falcon_kit.mains.ovlp_filter --db ../1-preads_ovl/build/preads.db --las-fofn ../1-preads_ovl/las-merge-combine/las_fofn.json --max-diff 120 --max-cov 120 --min-cov 2 --n-core 8 --min-len 1 --out-fn preads.m4`) which generate filepreads.m4 file within user_script.sh. Then the scripts user_script.sh can be run successfully.

But when I run `fc_run fc_run.cfg`，this error occurred again. So I modified the python scripts(`/public/software/lib/miniconda3/envs/pb-assembly/lib/python3.7/site-packages/falcon_kit/mains/ovlp_filter.py`) and comment out lines which print "---". After that, when I run `fc_run fc_run.cfg`, the error message disappeared.

Are there any problems with my modification?

**Comment by elfore** [comment]
I am having the same error here, but there is no ```---``` at the end of my file ```1-preads_ovl/db2falcon/preads4falcon.fasta```, anything tips for me would be really appreciated.

**Comment by SarahBeecroft** [comment]
Hi Jialei0701, 
I just wanted to say that your fix worked for me as well. thanks heaps! 

elfore- sorry if i've misunderstood your issue, but the file jialei mentioned with the '---' is 2-asm_falcon/preads.m4 not the one you mentioned.

**Comment by jialei0701** [comment]
> I am having the same error here, but there is no `---` at the end of my file `1-preads_ovl/db2falcon/preads4falcon.fasta`, anything tips for me would be really appreciated.

@elfore , file contains '---' is 2-asm_falcon/preads.m4 but not preads4falcon.fasta. Maybe you can just comment out lines which print "---" within file /public/software/lib/miniconda3/envs/pb-assembly/lib/python3.7/site-packages/falcon_kit/mains/ovlp_filter.py and try again.

**Comment by jialei0701** [comment]
@elfore , file contains '---' is 2-asm_falcon/preads.m4 but not preads4falcon.fasta. Maybe you can just comment out lines which print "---" within file /public/software/lib/miniconda3/envs/pb-assembly/lib/python3.7/site-packages/falcon_kit/mains/ovlp_filter.py and try again.

**Comment by elfore** [comment]
> Hi Jialei0701,
> I just wanted to say that your fix worked for me as well. thanks heaps!
> 
> elfore- sorry if i've misunderstood your issue, but the file jialei mentioned with the '---' is 2-asm_falcon/preads.m4 not the one you mentioned.

Thanks for your reply, I changed my filter requirements and ended up a m4 file with ---

**Comment by elfore** [comment]
> > I am having the same error here, but there is no `---` at the end of my file `1-preads_ovl/db2falcon/preads4falcon.fasta`, anything tips for me would be really appreciated.
> 
> @elfore , file contains '---' is 2-asm_falcon/preads.m4 but not preads4falcon.fasta. Maybe you can just comment out lines which print "---" within file /public/software/lib/miniconda3/envs/pb-assembly/lib/python3.7/site-packages/falcon_kit/mains/ovlp_filter.py and try again.

Thank you, I tried your method and it works well.

**Comment by armintoepfer** [comment]
Closing due to lack of activity.

**Comment by pb-cdunn** [comment]
```
conda create -n pba pb-assembly nim-falcon==3.0.2
```
If you do not specify `nim-falcon==3.0.2`, you may end up with the wrong nim-falcon/htslib versions because of intricacies of how conda works. We're trying not to update **pb-assembly** and **nim-falcon** at all anymore, now that there is a working combination.

If at all possibly, use hifi reads and switch to **pbipa**, which explicitly requires `htslib>=1.10` and `samtools>=1.10` (both of which are necessary because of those conda intricacies).

**Comment by QiushiLi** [comment]
Hi guys,

If you are still suffering from the env related issue of falcon, maybe you would like to try this frozen environment of mine, which works well through 2-asm stage.

Simply unzip "pb-assembly.yml.zip", then
conda env create -f pb-assembly.yml

The order of the channel is very important. Please do not change the order unless you have a clear reason.
My conda version is 4.9.2

Qiushi
[pb-assembly.yml.zip](https://github.com/PacificBiosciences/pbbioconda/files/5902875/pb-assembly.yml.zip)
