### ISSUE TITLE
`pa_DBdust_option`  will not pass the option to DBdust

### ISSUE THREAD

**Issue by xuzhougeng** [PacificBiosciences/pbbioconda#30]
**Operating system**

CentOS Linux release 7.5.1804 (Core)

**Package name**

pb-assembly

**Conda environment**

my conda environment is 

```bash
# packages in environment at /opt/biosoft/pb-assembly:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py27_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
avro-python2              1.8.2                      py_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
bcftools                  1.9                  h4da6232_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
bedtools                  2.27.1               he941832_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
blasr                     5.3.2                hac9d22c_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
blasr_libcpp              5.3.1                hac9d22c_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
bwa                       0.7.17               ha92aebf_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
bzip2                     1.0.6                h470a237_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
ca-certificates           2018.8.24            ha4d7672_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
certifi                   2018.8.24             py27_1001    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
cffi                      1.11.5           py27h5e8e0c9_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
chardet                   3.0.4                    py27_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
cryptography              2.3.1            py27hdffb7b8_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
cryptography-vectors      2.3.1                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
curl                      7.61.0               h93b3f91_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
cython                    0.28.5           py27hfc679d8_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
decorator                 4.3.0                      py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
enum34                    1.1.6                    py27_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
future                    0.16.0                   py27_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
genomicconsensus          2.3.2                    py27_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
h5py                      2.8.0            py27hb794570_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
hdf5                      1.10.2               hc401514_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
htslib                    1.7                           0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
idna                      2.7                      py27_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
intel-openmp              2019.0                      118    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ipaddress                 1.0.22                     py_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
iso8601                   0.1.12                     py_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
krb5                      1.14.6                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libdeflate                1.0                  h470a237_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
libffi                    3.2.1                hfc679d8_5    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libgcc                    7.2.0                h69d50b8_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libgcc-ng                 7.2.0                hdf63c60_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libgfortran               3.0.0                         1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libssh2                   1.8.0                h5b517e9_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
linecache2                1.0.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
minimap2                  2.12                 ha92aebf_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
mkl                       2019.0                      118    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl_fft                   1.0.6                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
mkl_random                1.0.1                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
mummer4                   4.0.0beta2      pl526hfc679d8_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
ncurses                   6.1                  hfc679d8_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
networkx                  2.2                        py_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
nim-falcon                0.0.0                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
numpy                     1.15.0           py27h1b885b7_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
numpy-base                1.15.0           py27h3dfced4_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
openssl                   1.0.2p               h470a237_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pb-assembly               0.0.1                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
pb-dazzler                0.0.0                h470a237_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
pb-falcon                 0.2.3            py27ha92aebf_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
pbalign                   0.3.1                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
pbbam                     0.18.0               h1310cd9_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
pbcommand                 1.1.1                    py27_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
pbcore                    1.5.1                    py27_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl                      5.26.2               h470a237_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pip                       18.0                     py27_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pycparser                 2.19                       py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pyopenssl                 18.0.0                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pysam                     0.14.1           py27hae42fb6_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
pysocks                   1.6.8                    py27_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
python                    2.7.15               h9fef7bc_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
python-consensuscore      1.1.1            py27h02d93b8_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
python-consensuscore2     3.1.0                    py27_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
python-edlib              1.2.3            py27h470a237_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
python-intervaltree       2.1.0                      py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
python-msgpack            0.5.6            py27h470a237_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
python-sortedcontainers   2.0.4                      py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
pytz                      2018.5                     py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
readline                  7.0                  haf1bffa_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
requests                  2.19.1                   py27_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
samtools                  1.9                  h8ee4bcc_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
setuptools                40.4.0                py27_1000    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
six                       1.11.0                   py27_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
sqlite                    3.25.1               hb1c47c0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
tk                        8.6.8                ha92aebf_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
traceback2                1.4.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
unittest2                 1.1.0                      py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
urllib3                   1.23                     py27_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
wheel                     0.31.1                py27_1001    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xz                        5.2.4                h470a237_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
zlib                      1.2.11               h470a237_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
```

**Describe the bug**

`pa_DBdust_option`  will not use the options I set. I use the E.coli data from https://pb-falcon.readthedocs.io/en/latest/tutorial.html , and I set this option to `pa_DBdust_option=-w66 -m12`, and keep other options same as https://github.com/PacificBiosciences/pb-assembly/blob/master/cfgs/fc_run_200kb.cfg.

And this is General_config.json

```bash
cat General_config.json 
{
  "ovlp_HPCTANmask_option": "-l500",
  "falcon_sense_greedy": false,
  "pa_fasta_filter_option": "pass",
  "seed_coverage": "20",
  "overlap_filtering_setting": "--max-diff 100 --max-cov 100 --min-cov 2",
  "length_cutoff_pr": "1000",
  "input_fofn": "input.fofn",
  "pa_HPCdaligner_option": "-v -B128 -M24",
  "ovlp_daligner_option": "-e.9 -l2500 -k24 -h1024 -w6 -s100",
  "bestn": 12,
  "pa_HPCTANmask_option": "",
  "input_type": "raw",
  "pa_REPmask_code": "0,300;0,300;0,300",
  "pa_DBsplit_option": "-x500 -s200",
  "fc_ovlp_to_graph_option": " --min-len 1000",
  "genome_size": "0",
  "avoid_text_file_busy": true,
  "pa_dazcon_option": "-j 4 -x -l 500",
  "skip_checks": false,
  "ver": "100",
  "target": "assembly",
  "falcon_sense_skip_contained": false,
  "pa_daligner_option": "-e.8 -l2000 -k18 -h480  -w8 -s100",
  "length_cutoff": "3000",
  "pa_DBdust_option": "-w66 -m12",
  "ovlp_HPCdaligner_option": "-v -B128 -M24",
  "LA4Falcon_preload": false,
  "dazcon": false,
  "falcon_sense_option": "--output-multi --min-idt 0.70 --min-cov 2 --max-n-read 1800",
  "ovlp_DBsplit_option": "-x500 -s200"
}
```

and I use `ps aux | grep DBdust` to check whether the options is passed to DBdust.

![dubst](http://oex750gzt.bkt.clouddn.com/18-9-29/2515515.jpg)

**Expected behavior**

I think the behavior should be  same as daligner, which I use `ps aux | grep daligner` get the following information.  Which is in line with the options `pa_HPCdaligner_option=-v -B128 -M24` and
`pa_daligner_option=-e.8 -l2000 -k18 -h480  -w8 -s100`

```bash
daligner -v -k18 -w8 -h480 -H3000 -e0.8 -l2000 -M24 -P. -mdust -mtan -mrep0 raw_reads.5 raw_reads.1 raw_reads.2 raw_reads.3 raw_reads.4 raw_reads.5
```

**Comment by pb-cdunn** [comment]
Oops. This will be fixed soon, in the next pb-falcon bioconda update. (It's already fixed in our local code.)

**Comment by xuzhougeng** [comment]
@pb-cdunn Thanks

**Comment by nat2bee** [comment]
Hi, I may be having the same error... I'm currently using versions falcon-kit 1.2.4 and pypeflow 2.1.1 is this bug fixed on it?

I'm running it on the cluster (3.10.0-862.2.3.el7.x86_64 GNU/Linux)

My 0-rawreads/build/run-*.bash.stderr file error is:
```
INFO:root:  #803,657 count=  6,613,531,648 
INFO:root:#1,612,062 count= 13,226,917,959 
+ read fn
#cat fc.fofn | xargs rm -f
DBdust true raw_reads
+ DBdust true raw_reads
Usage: DBdust [-b] [-w<int(64)>] [-t<double(2.)>] [-m<int(10)>] <path:db|dam>

      -w: DUST algorithm window size.
      -t: DUST algorithm threshold.
      -m: Record only low-complexity intervals >= this size.
      -b: Take into account base composition bias.
[WARNING]Call 'bash -vex build_db.sh' returned 256.
Traceback (most recent call last):
  File "/scratch/7077691/.conda/envs/denovo_asm/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/scratch/7077691/.conda/envs/denovo_asm/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/cephfs/scratch/7077691/.conda/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/mains/dazzler.py", line 1368, in <module>
    main()
  File "/cephfs/scratch/7077691/.conda/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/mains/dazzler.py", line 1364, in main
    args.func(args)
  File "/cephfs/scratch/7077691/.conda/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/mains/dazzler.py", line 928, in cmd_build
    build_db(ours, args.input_fofn_fn, args.db_fn, args.length_cutoff_fn)
  File "/cephfs/scratch/7077691/.conda/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/mains/dazzler.py", line 143, in build_db
    io.syscall('bash -vex {}'.format(script_fn))
  File "/scratch/7077691/.conda/envs/denovo_asm/lib/python2.7/site-packages/pypeflow/io.py", line 29, in syscall
    raise Exception(msg)
Exception: Call 'bash -vex build_db.sh' returned 256.
2019-01-18 10:33:20,837 - root - WARNING - Call '/bin/bash user_script.sh' returned 256.
2019-01-18 10:33:20,838 - root - WARNING - CD: '/cephfs/scratch/7077691/Teste_Novo_Cluster/FALCON_test/0-rawreads/build' -> '/cephfs/scratch/7077691/Teste_Novo_Cluster/FALCON_test/0-rawreads/build'
2019-01-18 10:33:20,930 - root - WARNING - CD: '/cephfs/scratch/7077691/Teste_Novo_Cluster/FALCON_test/0-rawreads/build' -> '/cephfs/scratch/7077691/Teste_Novo_Cluster/FALCON_test/0-rawreads/build'
2019-01-18 10:33:20,931 - root - CRITICAL - Error in /cephfs/scratch/7077691/.conda/envs/denovo_asm/lib/python2.7/site-packages/pypeflow/do_task.py with args="{'json_fn': '/cephfs/scratch/7077691/Teste_Novo_Cluster/FALCON_test/0-rawreads/build/task.json',\n 'timeout': 30,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/scratch/7077691/.conda/envs/denovo_asm/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/scratch/7077691/.conda/envs/denovo_asm/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/cephfs/scratch/7077691/.conda/envs/denovo_asm/lib/python2.7/site-packages/pypeflow/do_task.py", line 267, in <module>
    main()
  File "/cephfs/scratch/7077691/.conda/envs/denovo_asm/lib/python2.7/site-packages/pypeflow/do_task.py", line 259, in main
    run(**vars(parsed_args))
  File "/cephfs/scratch/7077691/.conda/envs/denovo_asm/lib/python2.7/site-packages/pypeflow/do_task.py", line 253, in run
    run_cfg_in_tmpdir(cfg, tmpdir, '.')
  File "/cephfs/scratch/7077691/.conda/envs/denovo_asm/lib/python2.7/site-packages/pypeflow/do_task.py", line 228, in run_cfg_in_tmpdir
    run_bash(bash_template, myinputs, myoutputs, parameters)
  File "/cephfs/scratch/7077691/.conda/envs/denovo_asm/lib/python2.7/site-packages/pypeflow/do_task.py", line 187, in run_bash
    util.system(cmd)
  File "/scratch/7077691/.conda/envs/denovo_asm/lib/python2.7/site-packages/pypeflow/io.py", line 29, in syscall
    raise Exception(msg)
Exception: Call '/bin/bash user_script.sh' returned 256.
+++ pwd
++ echo 'FAILURE. Running top in /cephfs/scratch/7077691/Teste_Novo_Cluster/FALCON_test/0-rawreads/build (If you see -terminal database is inaccessible- you are using the python bin-wrapper, so you will not get diagnostic info. No big deal. This process is crashing anyway.)'
++ rm -f top.txt
++ which python
++ which top
++ env -u LD_LIBRARY_PATH top -b -n 1
++ env -u LD_LIBRARY_PATH top -b -n 1
++ pstree -apl

real	19m54.210s
user	16m49.347s
sys	1m51.247s
+ finish
+ echo 'finish code: 1'
```


And my config file:
```
#### Input for FALCON 14/1/19
[General]
input_fofn=/scratch/7077691/Teste_Novo_Cluster/FALCON_test/input.fofn
input_type=raw
pa_DBdust_option=true
pa_fasta_filter_option=streamed-median
target=assembly
skip_checks=False
LA4Falcon_preload=false


#### Data Partitioning
pa_DBsplit_option=-x500 -s50
ovlp_DBsplit_option=-x500 -s50

#### Repeat Masking
pa_HPCTANmask_option=
pa_REPmask_code=0,300;0,300;0,300

####Pre-assembly
genome_size=0
seed_coverage=30
length_cutoff=1000    
pa_HPCdaligner_option=-v -B128 -M24
pa_daligner_option=-e.8 -l2000 -k18 -h480 -w8 -s100
falcon_sense_option=--output-multi --min-idt 0.70 --min-cov 3 --max-n-read 400
falcon_sense_greedy=False

####Pread overlapping
ovlp_daligner_option=-e.9 -l2500 -k24 -h1024 -w6 -s100 
ovlp_HPCdaligner_option=-v -B128 -M24

####Final Assembly
overlap_filtering_setting=--max-diff 100 --max-cov 100 --min-cov 2
fc_ovlp_to_graph_option=
length_cutoff_pr=1000



[job.defaults]
job_type=slurm
pwatcher_type=blocking
JOB_QUEUE=default
MB=32768
NPROC=6
njobs=32
submit = srun --wait=0 -p SP2 -J ${JOB_NAME} -o ${JOB_STDOUT} -e ${JOB_STDERR} --mem=${MB}M --cpus-per-task=${NPROC} --time=20-00:00:0 ${JOB_SCRIPT}
```

I did my config file based on the examples/ documentation but it is the first time I'm running Falcon so I might have messed up something....

**Comment by pb-cdunn** [comment]
@nat2bee ,

```cfg
pa_DBdust_option=true
```
Drop `true`. If you want, you can provide options to **DBdust** via that parameter.

(I think "true" might have caused it to run in the past, but not anymore. [Available options are here](https://github.com/PacificBiosciences/FALCON/wiki/Options-Available).)

**Comment by nat2bee** [comment]
Thanks! 
It's running now =)
