### ISSUE TITLE
pb-assembly - Exception: Some tasks are recently_done but not satisfied: {Node(2-asm-falcon)} - TypeError: '>' not supported between instances of 'int' and 'NoneType'

### ISSUE THREAD

**Issue by AntoineHo** [PacificBiosciences/pbbioconda#314]
Hello,

**Operating system**
Distributor ID: Ubuntu
Description:    Ubuntu 18.10
Release:        18.10
Codename:       cosmic

**Package name**
pb-assembly 0.0.8 0 bioconda

**Conda environment**

**Describe the bug**
Falcon assembly fails at the 2-asm-falcon step:

**Error message**
```bash
[INFO](slept for another 2.8s -- another 7 loop iterations)
[ERROR]Task Node(2-asm-falcon) failed with exit-code=1
[ERROR]Some tasks are recently_done but not satisfied: {Node(2-asm-falcon)}
[ERROR]ready: set()
        submitted: set()
[ERROR]Noop. We cannot kill blocked threads. Hopefully, everything will die on SIGTERM.
Traceback (most recent call last):
  File "/home/lege/anaconda3/envs/pbasm/bin/fc_run", line 11, in <module>
    load_entry_point('falcon-kit==1.8.1', 'console_scripts', 'fc_run')()
  File "/home/lege/anaconda3/envs/pbasm/lib/python3.7/site-packages/falcon_kit/mains/run1.py", line 706, in main
    main1(argv[0], args.config, args.logger)
  File "/home/lege/anaconda3/envs/pbasm/lib/python3.7/site-packages/falcon_kit/mains/run1.py", line 73, in main1
    input_fofn_fn=input_fofn_fn,
  File "/home/lege/anaconda3/envs/pbasm/lib/python3.7/site-packages/falcon_kit/mains/run1.py", line 460, in run
    wf.refreshTargets()
  File "/home/lege/anaconda3/envs/pbasm/lib/python3.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 278, in refreshTargets 
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/home/lege/anaconda3/envs/pbasm/lib/python3.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 362, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: {Node(2-asm-falcon)}
```
When I look in the logs, this is the first error I find: (file = `2-asm-falcon/run-Pa4b2ed561e360f.bash.stderr`)
```bash
completed loop record j = 1434122 out of 1434122 at /mnt/sda1/Antoine/22-06-20_HiCHomologs/1_FalconAssembly/1-preads_ovl/las-merge-gathered/../las-merge-runs/m_00000/uow-00/preads.1.las Fri Jul 17 10:45:17 2020
completed loop record j = 1389498 out of 1389498 at /mnt/sda1/Antoine/22-06-20_HiCHomologs/1_FalconAssembly/1-preads_ovl/las-merge-gathered/../las-merge-runs/m_00009/uow-00/preads.18.las Fri Jul 17 10:45:17 2020

[DALIGNER Info] No mapping coordinates will be written for FALCON consensus. The consensus will have to re-map.
[15589]preparing filter_stage1
[15589]maxrss:    21572
[15589]terminating ovlp_filter workers...
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/lege/anaconda3/envs/pbasm/lib/python3.7/site-packages/falcon_kit/util/io.py", line 68, in run_func
    ret = func(*args)
  File "/home/lege/anaconda3/envs/pbasm/lib/python3.7/site-packages/falcon_kit/mains/ovlp_filter.py", line 14, in run_filter_stage1
    return fn, filter_stage1(reader.readlines, max_diff, max_ovlp, min_ovlp, min_len, min_idt)
  File "/home/lege/anaconda3/envs/pbasm/lib/python3.7/site-packages/falcon_kit/mains/ovlp_filter.py", line 38, in filter_stage1
    if ignore(overlap_data):
  File "/home/lege/anaconda3/envs/pbasm/lib/python3.7/site-packages/falcon_kit/mains/ovlp_filter.py", line 21, in ignore
    if (abs(left_count - right_count) > max_diff) or \
TypeError: '>' not supported between instances of 'int' and 'NoneType'
```

My configuration file (I have tried with and without the [job.defaults] part and the script seem to fail in the same part but the reported error code is 256:
```bash
[job.defaults]
pwatcher_type = blocking
submit = /bin/bash -c "${JOB_SCRIPT}" > "${JOB_STDOUT}" 2> "${JOB_STDERR}"

[General]                                                                 
job_type = local
input_fofn = input.fofn
input_type = raw

length_cutoff = 5000

length_cutoff_pr = 5000                                                   

genome_size = 100000000
seed_coverage = 200

default_concurrent_jobs = 12
pa_concurrent_jobs = 12
cns_concurrent_jobs = 12
ovlp_concurrent_jobs = 12

pa_daligner_option = -v -e0.70 -l5000 -k18 -h1250 -w8 -s100
ovlp_daligner_option = -v -k24 -h1250 -e.96 -l2500 -s100 
pa_HPCdaligner_option = -B4 -M48
ovlp_HPCdaligner_option = -B4

pa_DBsplit_option = -a -x500 -s200
ovlp_DBsplit_option = -s200

falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 10 --max_n_read 400 --n_core 12
falcon_sense_skip_contained = False

overlap_filtering_setting = --max_cov 400 --min_cov 20 --n_core 12
```

**To Reproduce**
I do not really know how to provide data to reproduce this. I tried to run the example 200k and it works for the assembly part `fc_run` but not for the unzip part `fc_unzip.py` which has the same kind of exceptions: `[ERROR]Noop. We cannot kill blocked threads. Hopefully, everything will die on SIGTERM` and `WARNING:root:Call '/bin/bash user_script.sh' returned 256.` and `ERROR:root:failed multiprocessing`

**Expected behavior**
/

Any idea what may cause these errors and solve them? It seems to me that it occurs somewhere at the end of the `1-preads_ovl/` step.

Thanks.
Cheers,

AH

**Comment by AntoineHo** [comment]
Hello, I found out that the config file is wrong: missing step process, MB and jobs info.
