### ISSUE TITLE
HiFi Falcon pypeflow.simple_pwatcher_bridge:94 - ERROR - Task Node(1-preads_ovl/daligner-runs/j_0027) failed with exit-code=1

### ISSUE THREAD

**Issue by B10inform** [PacificBiosciences/pbbioconda#316]
Hi, I am having issues with FalconHiFi

Falcon was installed as : https://github.com/PacificBiosciences/pb-assembly
conda create -n pb-assembly
source activate pb-assembly
conda install pb-assembly

module load conda3
source activate pb-assembly

conda update --all

my fc_run_HiFi.cfg file:

[General]
input_fofn = ccs.fasta.fofn
input_type = preads
pa_DBdust_option=
pa_fasta_filter_option=streamed-median

pa_DBsplit_option=-x500 -s400
ovlp_DBsplit_option=-s400

pa_HPCTANmask_option = -k18 -h480 -w8 -e.8 -s100
pa_HPCREPmask_option = -k18 -h480 -w8 -e.8 -s100

length_cutoff = -1
genome_size = 200000
seed_coverage = 30
pa_HPCdaligner_option = -v -B128 -M24
pa_daligner_option = -e.8 -l1000 -k18 -h70  -w8 -s100
falcon_sense_option = --output-multi --min-cov-aln 4 --min-idt 0.70 --min-cov 4 --max-n-read 200 --n-core 14
falcon_sense_greedy=False

ovlp_HPCdaligner_option = -v -B128 -M24
ovlp_daligner_option = -e.99 -l3000 -k24 -h1024 -s100

length_cutoff_pr = 10000
overlap_filtering_setting = --max-diff 400 --max-cov 400 --min-cov 2 --n-core 24 --min-idt 99.9 --ignore-indels
fc_ovlp_to_graph_option=

[job.defaults]
job_type = local
MB = 48000
NPROC = 12
njobs = 200
pwatcher_type = blocking
submit = bash -C ${CMD} >| ${STDOUT_FILE} 2>| ${STDERR_FILE}

[job.step.da]
NPROC=4
MB=32000
njobs=200
[job.step.la]
NPROC=8
MB=64000
njobs=200
[job.step.cns]
NPROC=8
MB=64000
njobs=200
[job.step.pda]
NPROC=8
MB=64000
njobs=200
[job.step.pla]
NPROC=4
MB=32000
njobs=200
[job.step.asm]
NPROC=24
MB=192000
njobs=1

fc_run fc_run_HiFi.cfg

Error starts from here:
2020-07-17 21:18:29,671 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(P4d02f4582190b7->254).
2020-07-17 21:18:29,003 - pypeflow.simple_pwatcher_bridge:94 - ERROR - Task Node(1-preads_ovl/daligner-runs/j_0027) failed with exit-code=1
2020-07-17 21:18:29,683 - pypeflow.simple_pwatcher_bridge:94 - ERROR - Task Node(1-preads_ovl/daligner-runs/j_0044) failed with exit-code=1
2020-07-17 21:18:29,683 - pypeflow.simple_pwatcher_bridge:94 - ERROR - Task Node(1-preads_ovl/daligner-runs/j_0017) failed with exit-code=1
2020-07-17 21:18:29,683 - pypeflow.simple_pwatcher_bridge:94 - ERROR - Task Node(1-preads_ovl/daligner-runs/j_0000) failed with exit-code=1
2020-07-17 21:18:29,684 - pypeflow.simple_pwatcher_bridge:94 - ERROR - Task Node(1-preads_ovl/daligner-runs/j_0012) failed with exit-code=1
2020-07-17 21:18:29,684 - pypeflow.simple_pwatcher_bridge:94 - ERROR - Task Node(1-preads_ovl/daligner-runs/j_0037) failed with exit-code=1
2020-07-17 21:18:29,684 - pypeflow.simple_pwatcher_bridge:94 - ERROR - Task Node(1-preads_ovl/daligner-runs/j_0036) failed with exit-code=1
2020-07-17 21:18:29,684 - pypeflow.simple_pwatcher_bridge:343 - DEBUG - recently_done: [(Node(1-preads_ovl/daligner-runs/j_0036), False), (Node(1-preads_ovl/daligner-runs/j_0000), False), (Node(1-preads_ovl/daligner-runs/j_0037), False), (Node(1-preads_ovl/daligner-runs/j_0044), False), (Node(1-preads_ovl/daligner-runs/j_0012), False), (Node(1-preads_ovl/daligner-runs/j_0017), False), (Node(1-preads_ovl/daligner-runs/j_0027), False)]
2020-07-17 21:18:29,684 - pypeflow.simple_pwatcher_bridge:344 - DEBUG - Num done in this iteration: 7
2020-07-17 21:18:29,685 - pypeflow.simple_pwatcher_bridge:358 - ERROR - Some tasks are recently_done but not satisfied: {Node(1-preads_ovl/daligner-runs/j_0036), Node(1-preads_ovl/daligner-runs/j_0000), Node(1-preads_ovl/daligner-runs/j_0037), Node(1-preads_ovl/daligner-runs/j_0044), Node(1-preads_ovl/daligner-runs/j_0012), Node(1-preads_ovl/daligner-runs/j_0017), Node(1-preads_ovl/daligner-runs/j_0027)}
2020-07-17 21:18:29,685 - pypeflow.simple_pwatcher_bridge:359 - ERROR - ready: set()
	submitted: {Node(1-preads_ovl/daligner-runs/j_0051), Node(1-preads_ovl/daligner-runs/j_0028), Node(1-preads_ovl/daligner-runs/j_0047), Node(1-preads_ovl/daligner-runs/j_0046), Node(1-preads_ovl/daligner-runs/j_0054), Node(1-preads_ovl/daligner-runs/j_0029), Node(1-preads_ovl/daligner-runs/j_0025), Node(1-preads_ovl/daligner-runs/j_0052), Node(1-preads_ovl/daligner-runs/j_0024), Node(1-preads_ovl/daligner-runs/j_0026), Node(1-preads_ovl/daligner-runs/j_0035), Node(1-preads_ovl/daligner-runs/j_0049), Node(1-preads_ovl/daligner-runs/j_0034), Node(1-preads_ovl/daligner-runs/j_0010), Node(1-preads_ovl/daligner-runs/j_0004), Node(1-preads_ovl/daligner-runs/j_0040), Node(1-preads_ovl/daligner-runs/j_0039), Node(1-preads_ovl/daligner-runs/j_0007), Node(1-preads_ovl/daligner-runs/j_0038), Node(1-preads_ovl/daligner-runs/j_0042), Node(1-preads_ovl/daligner-runs/j_0021), Node(1-preads_ovl/daligner-runs/j_0032), Node(1-preads_ovl/daligner-runs/j_0006), Node(1-preads_ovl/daligner-runs/j_0043), Node(1-preads_ovl/daligner-runs/j_0018), Node(1-preads_ovl/daligner-runs/j_0009), Node(1-preads_ovl/daligner-runs/j_0022), Node(1-preads_ovl/daligner-runs/j_0055), Node(1-preads_ovl/daligner-runs/j_0050), Node(1-preads_ovl/daligner-runs/j_0053), Node(1-preads_ovl/daligner-runs/j_0016), Node(1-preads_ovl/daligner-runs/j_0011), Node(1-preads_ovl/daligner-runs/j_0031), Node(1-preads_ovl/daligner-runs/j_0001), Node(1-preads_ovl/daligner-runs/j_0056), Node(1-preads_ovl/daligner-runs/j_0008), Node(1-preads_ovl/daligner-runs/j_0015), Node(1-preads_ovl/daligner-runs/j_0019), Node(1-preads_ovl/daligner-runs/j_0002), Node(1-preads_ovl/daligner-runs/j_0023), Node(1-preads_ovl/daligner-runs/j_0003), Node(1-preads_ovl/daligner-runs/j_0030), Node(1-preads_ovl/daligner-runs/j_0005), Node(1-preads_ovl/daligner-runs/j_0045), Node(1-preads_ovl/daligner-runs/j_0041), Node(1-preads_ovl/daligner-runs/j_0014), Node(1-preads_ovl/daligner-runs/j_0048), Node(1-preads_ovl/daligner-runs/j_0013), Node(1-preads_ovl/daligner-runs/j_0033), Node(1-preads_ovl/daligner-runs/j_0020)}
2020-07-17 21:18:29,685 - pwatcher.blocking:466 - DEBUG - delete(which='known', jobids=<50>)
2020-07-17 21:18:29,685 - pwatcher.blocking:430 - ERROR - Noop. We cannot kill blocked threads. Hopefully, everything will die on SIGTERM.
2020-07-17 21:18:29,685 - pypeflow.simple_pwatcher_bridge:189 - DEBUG - In notifyTerminate(), result of delete:None
2020-07-17 21:18:35,818 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:35,819 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(P1676d3e75dfbe8->1).
2020-07-17 21:18:35,937 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:35,938 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(Pfba2e0b762ef43->1).
2020-07-17 21:18:35,984 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:35,985 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(P154a6336c2c2eb->1).
2020-07-17 21:18:36,172 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:36,172 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(Pa0f62a46f8c5fd->1).
2020-07-17 21:18:36,585 - pwatcher.blocking:234 - DEBUG - rc: 254
2020-07-17 21:18:36,587 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(P71df2115f8ee6c->254).
2020-07-17 21:18:36,647 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:36,647 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(P8d2b4c9638bd43->1).
2020-07-17 21:18:36,663 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:36,664 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(Pb42e3ae536c492->1).
2020-07-17 21:18:37,353 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:37,353 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(P429a23e1300841->1).
2020-07-17 21:18:39,333 - pwatcher.blocking:234 - DEBUG - rc: 254
2020-07-17 21:18:39,334 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(Pe76b7cb574f36d->254).
2020-07-17 21:18:39,334 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:39,334 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(P0003b10abfdd31->1).
2020-07-17 21:18:40,037 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:40,130 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(Pef56615d869299->1).
2020-07-17 21:18:40,268 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:40,341 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(P87ac923b38bf25->1).
2020-07-17 21:18:41,217 - pwatcher.blocking:234 - DEBUG - rc: 254
2020-07-17 21:18:41,222 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(P8bda7bab695cf4->254).
2020-07-17 21:18:42,462 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:42,494 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(P69ab3d969c03d4->1).
2020-07-17 21:18:42,747 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:42,791 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(Pe3274f9e867770->1).
2020-07-17 21:18:43,330 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:43,330 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(P31aa497310c558->1).
2020-07-17 21:18:43,371 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:43,372 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(Pc621492f7ba0fd->1).
2020-07-17 21:18:43,703 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:43,703 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(P80365d58241232->1).
2020-07-17 21:18:44,832 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:44,837 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(Pe4bfe8e24f77bf->1).
2020-07-17 21:18:44,883 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:44,883 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(P2c145de53a2e55->1).
2020-07-17 21:18:46,012 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:46,013 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(Pd6ed2be856607b->1).
2020-07-17 21:18:46,507 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:46,507 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(Pbac6482d4f398c->1).
2020-07-17 21:18:46,614 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:46,650 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(Pcd1867b4c3dbcb->1).
2020-07-17 21:18:46,622 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:46,654 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(Pac439d84c98853->1).
2020-07-17 21:18:46,683 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:46,684 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(P177b7e382d3b23->1).
2020-07-17 21:18:46,733 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:46,748 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(P8345a608399ae7->1).
2020-07-17 21:18:47,329 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:47,329 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(Pb659c739cb4c55->1).
2020-07-17 21:18:47,308 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:47,329 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(P3810b1b1e2a180->1).
2020-07-17 21:18:47,419 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:47,420 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(Pa318f0ca67e1a2->1).
2020-07-17 21:18:47,420 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:47,420 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(Paa036dfc1fb000->1).
2020-07-17 21:18:47,746 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:47,750 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(P286aafcc65405e->1).
2020-07-17 21:18:47,803 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:47,804 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(Pfb83f0a4033f1d->1).
2020-07-17 21:18:47,931 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:47,932 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(P2ec134932e20ef->1).
2020-07-17 21:18:47,958 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:47,958 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(Pfb22ea2a43e243->1).
2020-07-17 21:18:47,961 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:47,961 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(P9c09bd3ad3712d->1).
2020-07-17 21:18:49,576 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:49,577 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(P11ed310521e08b->1).
2020-07-17 21:18:49,577 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:49,577 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(P4d4cb493dfc911->1).
2020-07-17 21:18:50,426 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:50,428 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(Pc340cd4c0d7e6b->1).
2020-07-17 21:18:51,057 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:51,057 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(Pd5f16a0d261fc2->1).
2020-07-17 21:18:51,342 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:51,343 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(Pcc96ca41536e40->1).
2020-07-17 21:18:51,695 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:51,695 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(P987e32c08c99c3->1).
2020-07-17 21:18:51,801 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:51,801 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(Pb3d3a81393f42e->1).
2020-07-17 21:18:51,973 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:51,973 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(Pfd9224d9fd9040->1).
2020-07-17 21:18:52,930 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:52,930 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(P4bba0906e0bf88->1).
2020-07-17 21:18:54,763 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:54,763 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(Pcb2b6381a4dd72->1).
2020-07-17 21:18:58,026 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:18:58,026 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(Pee97cf6bb0a1da->1).
2020-07-17 21:19:28,048 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:19:28,049 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(P15ab24eb210449->1).
2020-07-17 21:20:02,749 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:20:02,749 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(P2a9962a85ce579->1).
2020-07-17 21:20:16,400 - pwatcher.blocking:234 - DEBUG - rc: 1
2020-07-17 21:20:16,400 - pwatcher.blocking:86 - DEBUG - Thread notify_exited(Pda071aeb77e734->1).

Than i check **Task Node(1-preads_ovl/daligner-runs/j_0027)**

In the run-Pe51e88700be78b.bash.stderr ;

.# restore shell debugging options if disabled
if [ -n "${_mlshdbg:-}" ]; then
   set -$_mlshdbg;
   unset _mlshdbg;
fi;
+ '[' -n '' ']'
daligner_p -v -k24 -h1024 -H10000 -e0.99 -l3000 -M24 -P. -mdust preads.28 preads.1 preads.2 preads.3 preads.4 preads.5 preads.6 preads.7 preads.8 preads.9 preads.10 preads.11 preads.12 preads.13 preads.14 preads.15 preads.16 preads.17 preads.18 preads.19 preads.20 preads.21 preads.22 preads.23 preads.24 preads.25 preads.26 preads.27 preads.28
+ daligner_p -v -k24 -h1024 -H10000 -e0.99 -l3000 -M24 -P. -mdust preads.28 preads.1 preads.2 preads.3 preads.4 preads.5 preads.6 preads.7 preads.8 preads.9 preads.10 preads.11 preads.12 preads.13 preads.14 preads.15 preads.16 preads.17 preads.18 preads.19 preads.20 preads.21 preads.22 preads.23 preads.24 preads.25 preads.26 preads.27 preads.28
run_daligner.sh: line 1: 12555 Killed                  daligner_p -v -k24 -h1024 -H10000 -e0.99 -l3000 -M24 -P. -mdust preads.28 preads.1 preads.2 preads.3 preads.4 preads.5 preads.6 preads.7 preads.8 preads.9 preads.10 preads.11 preads.12 preads.13 preads.14 preads.15 preads.16 preads.17 preads.18 preads.19 preads.20 preads.21 preads.22 preads.23 preads.24 preads.25 preads.26 preads.27 preads.28
[WARNING]Call 'bash -vex run_daligner.sh' returned 35072.
Traceback (most recent call last):
  File "/home/.conda/envs/pb-assembly/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/.conda/envs/pb-assembly/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/.conda/envs/pb-assembly/lib/python3.7/site-packages/falcon_kit/mains/dazzler.py", line 1532, in <module>
    main()
  File "/home/.conda/envs/pb-assembly/lib/python3.7/site-packages/falcon_kit/mains/dazzler.py", line 1528, in main
    args.func(args)
  File "/home/.conda/envs/pb-assembly/lib/python3.7/site-packages/falcon_kit/mains/dazzler.py", line 1087, in cmd_daligner_apply
    daligner_apply(args.db_fn, args.script_fn, args.job_done_fn)
  File "/home/.conda/envs/pb-assembly/lib/python3.7/site-packages/falcon_kit/mains/dazzler.py", line 810, in daligner_apply
    io.syscall('bash -vex {}'.format(os.path.basename(script_fn)))
  File "/home/.conda/envs/pb-assembly/lib/python3.7/site-packages/pypeflow/io.py", line 27, in syscall
    raise Exception(msg)
Exception: Call 'bash -vex run_daligner.sh' returned 35072.
WARNING:root:Call '/bin/bash user_script.sh' returned 256.
INFO:root:CD: 'uow-00' -> '/home/HiFi/FALCON/1-preads_ovl/daligner-runs/j_0027'
ERROR:root:failed multiprocessing
multiprocessing.pool.RemoteTraceback: 

In the previous post  #59 similar (https://github.com/PacificBiosciences/pbbioconda/issues/59) error was mentioned
**run_daligner.sh: line 1: 12555 Killed    daligner_p -v -k24 -h1024 -H10000 -e0.99 -l3000 -M24 -P. -mdust preads.28 preads.1 preads.2 preads.3 preads.4 preads.5 preads.6 preads.7 preads.8 preads.9 preads.10 preads.11 preads.12 preads.13 preads.14 preads.15 preads.16 preads.17 preads.18 preads.19 preads.20 preads.21 preads.22 preads.23 preads.24 preads.25 preads.26 preads.27 preads.28**

Tried pa_HPCdaligner_option = -v -B128 -M300. Still same error. Any help would be really great.

Stay safe.

**Comment by armintoepfer** [comment]
Please use our latest HiFi assembler from bioconda `pbipa`

**Comment by pb-cdunn** [comment]
```
Killed daligner_p
```
It looks like your HPC scheduler killed the job, probably because it exceeded a resource limit like excess memory. That's very difficult for us to help you with remotely.

Issue 59 did have this problem, but also solved it. "I think I have no longer problem with my scheduler, but I have another." You could post there to ask the other user what she did.

```
input_fofn = ccs.fasta.fofn
```
It looks like you have ccs reads. As Armin said, we recommend using **pbipa** if possible. It's much simpler and faster.
