### ISSUE TITLE
pbalign break, due to blasr missing shared library

### ISSUE THREAD

**Issue by elcortegano** [PacificBiosciences/pbbioconda#371]
**Operating system**
Scientific Linux 7.8 (Nitrogen)

**Package name**
Bioconda installed `pbalign` results in error (see below). Version used is 0.3.2 (latest from bioconda). Environment is updated.

**Conda environment**

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
alsa-lib                  1.2.3                h516909a_0    conda-forge
atk-1.0                   2.36.0               h3371d22_4    conda-forge
avro-python2              1.9.0                      py_0    bioconda
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
backports_abc             0.5                        py_1    conda-forge
bedtools                  2.30.0               hc088bd4_0    bioconda
blasr                     5.3.2                h4ef8376_2    bioconda
blasr_libcpp              5.3.4                h6479705_1    bioconda
blast                     2.10.1          pl526he19e7b1_3    bioconda
boost                     1.67.0           py27h3e44d54_0    conda-forge
boost-cpp                 1.67.0               h3a22d5f_0    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.11.0               h470a237_1    bioconda
ca-certificates           2020.12.5            ha878542_0    conda-forge
cairo                     1.16.0            h18b612c_1001    conda-forge
canu                      2.1.1                he1b5a44_0    bioconda
certifi                   2019.11.28       py27h8c360ce_1    conda-forge
chrpath                   0.16              h14c3975_1001    conda-forge
circos                    0.69.8                        0    bioconda
curl                      7.71.1               he644dc0_8    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.15          py27haf22ab1_1    conda-forge
dbus                      1.13.6               hfdff14a_1    conda-forge
entrez-direct             13.9            pl526h375a9b1_0    bioconda
expat                     2.2.10               h9c3ff4c_0    conda-forge
flye                      2.8.2            py27h4bd9754_0    bioconda
fontconfig                2.13.1            hba837de_1004    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
functools32               3.2.3.2                    py_3    conda-forge
futures                   3.3.0            py27h8c360ce_1    conda-forge
gdk-pixbuf                2.42.2               h0c95a7a_2    conda-forge
GenomicConsensus          2.3.3                     <pip>
genomicconsensus          2.3.3                      py_1    bioconda
gettext                   0.19.8.1          h0b5b191_1005    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
glib                      2.66.4               hc4f0c31_2    conda-forge
glib-tools                2.66.4               hc4f0c31_2    conda-forge
glimmerhmm                3.0.4           pl526hf484d3e_3    bioconda
gnuplot                   5.2.7                he39d25e_2    conda-forge
graphite2                 1.3.13            h58526e2_1001    conda-forge
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               h28cd5cc_2  
gtk2                      2.24.33              hab0c2f8_0    conda-forge
h5py                      2.10.0          nompi_py27h513d04c_102    conda-forge
harfbuzz                  2.4.0                h37c48d4_1    conda-forge
hdf5                      1.10.5          nompi_h5b725eb_1114    conda-forge
htslib                    1.10.2               hd3b49d5_1    bioconda
icu                       58.2              hf484d3e_1000    conda-forge
iso8601                   0.1.13             pyh9f0ad1d_0    conda-forge
java-jdk                  8.0.92                        1    bioconda
joblib                    0.14.1             pyh9f0ad1d_0    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
k8                        0.2.5                he513fc3_0    bioconda
kiwisolver                1.1.0            py27h9e3301b_1    conda-forge
krb5                      1.17.2               h926e7f8_0    conda-forge
lcms2                     2.11                 hcbb858e_1    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_1    conda-forge
libblas                   3.9.0                7_openblas    conda-forge
libcblas                  3.9.0                7_openblas    conda-forge
libclang                  11.0.1          default_ha53f305_1    conda-forge
libcurl                   7.71.1               hcdd3856_8    conda-forge
libdeflate                1.6                  h516909a_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               hcdb4288_3    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_18    conda-forge
libgd                     2.2.5             h0d07dcb_1005    conda-forge
libgfortran-ng            9.3.0               hff62375_18    conda-forge
libgfortran5              9.3.0               hff62375_18    conda-forge
libglib                   2.66.4               h748fe8e_2    conda-forge
libgomp                   9.3.0               h2828fa1_18    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0                7_openblas    conda-forge
libllvm11                 11.0.1               hf817b99_0    conda-forge
libnghttp2                1.41.0               hab1572f_1    conda-forge
libopenblas               0.3.12          pthreads_h4812303_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libpq                     12.3                 h255efa7_3    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.3.0               h6de172a_18    conda-forge
libtiff                   4.1.0                hc3755c2_3    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp                   1.0.2                h56121f0_5    conda-forge
libxcb                    1.13              h7f98852_1003    conda-forge
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.9.10               hb55368b_3  
linecache2                1.0.0                      py_1    conda-forge
lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
matplotlib-base           2.2.4            py27hfd891ef_0    conda-forge
minimap2                  2.17                 hed695b0_3    bioconda
mysql-common              8.0.22               ha770c72_3    conda-forge
mysql-libs                8.0.22               h935591d_3    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
nspr                      4.29                 h9c3ff4c_1    conda-forge
nss                       3.61                 hb5efdd6_0    conda-forge
numpy                     1.16.5           py27h95a1406_0    conda-forge
openjdk                   11.0.8               hacce0ff_0    conda-forge
openssl                   1.1.1i               h7f98852_0    conda-forge
pango                     1.42.4               h7062337_4    conda-forge
pbalign                   0.3.2                      py_1    bioconda
pbbam                     1.6.0                h5b7e6e0_0    bioconda
pbcommand                 1.1.1                      py_3    bioconda
pbcore                    1.7.1                    py27_0    bioconda
pcre                      8.44                 he1b5a44_0    conda-forge
perl                      5.26.2            h36c2ea0_1008    conda-forge
perl-app-cpanminus        1.7044                  pl526_1    bioconda
perl-archive-tar          2.32                    pl526_0    bioconda
perl-autoloader           5.74                    pl526_2    bioconda
perl-base                 2.23                    pl526_1    bioconda
perl-business-isbn        3.004                   pl526_0    bioconda
perl-business-isbn-data   20140910.003            pl526_0    bioconda
perl-carp                 1.38                    pl526_3    bioconda
perl-clone                0.42            pl526h516909a_0    bioconda
perl-common-sense         3.74                    pl526_2    bioconda
perl-compress-raw-bzip2   2.087           pl526he1b5a44_0    bioconda
perl-compress-raw-zlib    2.087           pl526hc9558a2_0    bioconda
perl-config-general       2.63                    pl526_0    bioconda
perl-constant             1.33                    pl526_1    bioconda
perl-data-dumper          2.173                   pl526_0    bioconda
perl-digest-hmac          1.03                    pl526_3    bioconda
perl-digest-md5           2.55                    pl526_0    bioconda
perl-digest-perl-md5      1.9                     pl526_1    bioconda
perl-dynaloader           1.25                    pl526_1    bioconda
perl-encode               2.88                    pl526_1    bioconda
perl-encode-locale        1.05                    pl526_6    bioconda
perl-exporter             5.72                    pl526_1    bioconda
perl-exporter-tiny        1.002001                pl526_0    bioconda
perl-extutils-makemaker   7.36                    pl526_1    bioconda
perl-file-listing         6.04                    pl526_1    bioconda
perl-file-path            2.16                    pl526_0    bioconda
perl-file-temp            0.2304                  pl526_2    bioconda
perl-filesys-df           0.92                          1    bioconda
perl-font-ttf             1.06                    pl526_0    bioconda
perl-gd                   2.71            pl526he860b03_0    bioconda
perl-html-parser          3.72            pl526h6bb024c_5    bioconda
perl-html-tagset          3.20                    pl526_3    bioconda
perl-html-tree            5.07                    pl526_1    bioconda
perl-http-cookies         6.04                    pl526_0    bioconda
perl-http-daemon          6.01                    pl526_1    bioconda
perl-http-date            6.02                    pl526_3    bioconda
perl-http-message         6.18                    pl526_0    bioconda
perl-http-negotiate       6.01                    pl526_3    bioconda
perl-io-compress          2.087           pl526he1b5a44_0    bioconda
perl-io-html              1.001                   pl526_2    bioconda
perl-io-socket-ssl        2.066                   pl526_0    bioconda
perl-io-string            1.08                    pl526_3    bioconda
perl-io-zlib              1.10                    pl526_2    bioconda
perl-json                 4.02                    pl526_0    bioconda
perl-json-xs              2.34            pl526h6bb024c_3    bioconda
perl-libwww-perl          6.39                    pl526_0    bioconda
perl-list-moreutils       0.428                   pl526_1    bioconda
perl-list-moreutils-xs    0.428                   pl526_0    bioconda
perl-lwp-mediatypes       6.04                    pl526_0    bioconda
perl-lwp-protocol-https   6.07                    pl526_4    bioconda
perl-math-bezier          0.01                    pl526_1    bioconda
perl-math-round           0.07                    pl526_1    bioconda
perl-math-vecstat         0.08                    pl526_1    bioconda
perl-mime-base64          3.15                    pl526_1    bioconda
perl-module-implementation 0.09                    pl526_2    bioconda
perl-module-runtime       0.016                   pl526_1    bioconda
perl-mozilla-ca           20180117                pl526_1    bioconda
perl-net-http             6.19                    pl526_0    bioconda
perl-net-ssleay           1.88            pl526h90d6eec_0    bioconda
perl-ntlm                 1.09                    pl526_4    bioconda
perl-number-format        1.75                    pl526_3    bioconda
perl-params-validate      1.29            pl526h14c3975_1    bioconda
perl-parent               0.236                   pl526_1    bioconda
perl-pathtools            3.75            pl526h14c3975_1    bioconda
perl-readonly             2.05                    pl526_0    bioconda
perl-regexp-common        2017060201              pl526_0    bioconda
perl-scalar-list-utils    1.52            pl526h516909a_0    bioconda
perl-set-intspan          1.19                    pl526_1    bioconda
perl-socket               2.027                   pl526_1    bioconda
perl-statistics-basic     1.6611                  pl526_2    bioconda
perl-storable             3.15            pl526h14c3975_0    bioconda
perl-svg                  2.84                    pl526_0    bioconda
perl-test-requiresinternet 0.05                    pl526_0    bioconda
perl-text-format          0.59                    pl526_2    bioconda
perl-threaded             5.26.0                        0    bioconda
perl-time-hires           1.9760          pl526h14c3975_1    bioconda
perl-time-local           1.28                    pl526_1    bioconda
perl-try-tiny             0.30                    pl526_1    bioconda
perl-types-serialiser     1.0                     pl526_2    bioconda
perl-uri                  1.76                    pl526_0    bioconda
perl-www-robotrules       6.02                    pl526_3    bioconda
perl-xml-namespacesupport 1.12                    pl526_0    bioconda
perl-xml-parser           2.44            pl526h4e0c4b3_7    bioconda
perl-xml-sax              1.02                    pl526_0    bioconda
perl-xml-sax-base         1.09                    pl526_0    bioconda
perl-xml-sax-expat        0.51                    pl526_3    bioconda
perl-xml-simple           2.25                    pl526_1    bioconda
perl-xsloader             0.24                    pl526_0    bioconda
pip                       20.1.1             pyh9f0ad1d_0    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pysam                     0.16.0.1         py27ha863e18_1    bioconda
python                    2.7.18               h15b4118_1  
python-consensuscore      1.1.1            py27h55c140c_4    bioconda
python-consensuscore2     3.4.1                    py27_0    bioconda
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                2.7                    1_cp27mu    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
qt                        5.9.7                h5867ecd_1  
quast                     5.0.2           py27pl526h53fee03_2    bioconda
readline                  8.0                  he28a2e2_2    conda-forge
requests                  2.13.0                   py27_0    conda-forge
samtools                  1.10                 h2e538c0_3    bioconda
setuptools                44.0.0                   py27_0    conda-forge
simplejson                3.8.1                    py27_0    bioconda
singledispatch            3.4.0.3         pyh9f0ad1d_1001    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.34.0               h74cdb3f_0    conda-forge
subprocess32              3.5.4            py27h516909a_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
tornado                   5.1.1           py27h14c3975_1000    conda-forge
traceback2                1.4.0                    py27_0    conda-forge
unittest2                 1.1.0                      py_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xorg-fixesproto           5.0               h14c3975_1002    conda-forge
xorg-inputproto           2.3.2             h7f98852_1002    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.12               h516909a_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxfixes            5.0.3             h516909a_1004    conda-forge
xorg-libxi                1.7.10               h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-libxt                1.2.1                h7f98852_0    conda-forge
xorg-libxtst              1.2.3             h516909a_1002    conda-forge
xorg-recordproto          1.14.2            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.8                ha95c52a_1    conda-forge
```

**Describe the bug**

**Error message**
```
[INFO] 2021-02-11 00:28:37,937Z [pbalign.pbalignrunner _pacbio_main_runner 130] Using pbcommand v1.1.1
[INFO] 2021-02-11 00:28:37,937Z [pbalign.pbalignrunner _pacbio_main_runner 131] completed setting up logger with <function setup_log at 0x7f7364eaf5d0>
[INFO] 2021-02-11 00:28:37,937Z [pbalign.pbalignrunner _pacbio_main_runner 132] log opts {'file_name': None, 'level': 20}
[INFO] 2021-02-11 00:28:37,939Z [root run 227] pbalign version: 0.4.1
[INFO] 2021-02-11 00:28:37,945Z [root run 178] BlasrService: Align reads to references using blasr.
[INFO] 2021-02-11 00:28:37,946Z [root Execute 63] BlasrService: Call "blasr /localdisk/data/chlamydomonas/cc_2931_pacbio/assemblies/flye/Anc.bam /localdisk/data/chlamydomonas/cc_2931_pacbio/assemblies/flye/CC2931.fasta --out /tmp/tmpHIvKNv/YSB6ZV.bam  --bam  --bestn 10 --minMatch 12  --maxMatch 30  --nproc 64  --minSubreadLength 50 --minAlnLength 50  --minPctSimilarity 70 --minPctAccuracy 70 --hitPolicy randombest  --randomSeed 1 "
BlasrService returned a non-zero exit status 127
CMD: 'blasr /localdisk/data/chlamydomonas/cc_2931_pacbio/assemblies/flye/Anc.bam /localdisk/data/chlamydomonas/cc_2931_pacbio/assemblies/flye/CC2931.fasta --out /tmp/tmpHIvKNv/YSB6ZV.bam  --bam  --bestn 10 --minMatch 12  --maxMatch 30  --nproc 64  --minSubreadLength 50 --minAlnLength 50  --minPctSimilarity 70 --minPctAccuracy 70 --hitPolicy randombest  --randomSeed 1 '
ERROR: blasr: error while loading shared libraries: libhdf5_cpp.so.12: cannot open shared object file: No such file or directory
Output:[]
[ERROR] 2021-02-11 00:28:37,951Z [root Execute 68] BlasrService returned a non-zero exit status 127
CMD: 'blasr /localdisk/data/chlamydomonas/cc_2931_pacbio/assemblies/flye/Anc.bam /localdisk/data/chlamydomonas/cc_2931_pacbio/assemblies/flye/CC2931.fasta --out /tmp/tmpHIvKNv/YSB6ZV.bam  --bam  --bestn 10 --minMatch 12  --maxMatch 30  --nproc 64  --minSubreadLength 50 --minAlnLength 50  --minPctSimilarity 70 --minPctAccuracy 70 --hitPolicy randombest  --randomSeed 1 '
ERROR: blasr: error while loading shared libraries: libhdf5_cpp.so.12: cannot open shared object file: No such file or directory
Output:[]
BlasrService returned a non-zero exit status 127
CMD: 'blasr /localdisk/data/chlamydomonas/cc_2931_pacbio/assemblies/flye/Anc.bam /localdisk/data/chlamydomonas/cc_2931_pacbio/assemblies/flye/CC2931.fasta --out /tmp/tmpHIvKNv/YSB6ZV.bam  --bam  --bestn 10 --minMatch 12  --maxMatch 30  --nproc 64  --minSubreadLength 50 --minAlnLength 50  --minPctSimilarity 70 --minPctAccuracy 70 --hitPolicy randombest  --randomSeed 1 '
ERROR: blasr: error while loading shared libraries: libhdf5_cpp.so.12: cannot open shared object file: No such file or directory
Output:[]
Traceback (most recent call last):
  File "/localdisk/home/elopezc/.conda/envs/elopezc/lib/python2.7/site-packages/pbcommand/cli/core.py", line 138, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/localdisk/home/elopezc/.conda/envs/elopezc/lib/python2.7/site-packages/pbalign/pbalignrunner.py", line 284, in args_runner
    return PBAlignRunner(args, output_dataset_type=output_dataset_type).start()
  File "/localdisk/home/elopezc/.conda/envs/elopezc/lib/python2.7/site-packages/pbcore/util/ToolRunner.py", line 85, in start
    return self.run()
  File "/localdisk/home/elopezc/.conda/envs/elopezc/lib/python2.7/site-packages/pbalign/pbalignrunner.py", line 240, in run
    self._alnService.run()
  File "/localdisk/home/elopezc/.conda/envs/elopezc/lib/python2.7/site-packages/pbalign/alignservice/align.py", line 198, in run
    raise RuntimeError(str(e))
RuntimeError: BlasrService returned a non-zero exit status 127
CMD: 'blasr /localdisk/data/chlamydomonas/cc_2931_pacbio/assemblies/flye/Anc.bam /localdisk/data/chlamydomonas/cc_2931_pacbio/assemblies/flye/CC2931.fasta --out /tmp/tmpHIvKNv/YSB6ZV.bam  --bam  --bestn 10 --minMatch 12  --maxMatch 30  --nproc 64  --minSubreadLength 50 --minAlnLength 50  --minPctSimilarity 70 --minPctAccuracy 70 --hitPolicy randombest  --randomSeed 1 '
ERROR: blasr: error while loading shared libraries: libhdf5_cpp.so.12: cannot open shared object file: No such file or directory
Output:[]
[ERROR] 2021-02-11 00:28:37,952Z [pbalign.pbalignrunner _pacbio_main_runner 143] BlasrService returned a non-zero exit status 127
CMD: 'blasr /localdisk/data/chlamydomonas/cc_2931_pacbio/assemblies/flye/Anc.bam /localdisk/data/chlamydomonas/cc_2931_pacbio/assemblies/flye/CC2931.fasta --out /tmp/tmpHIvKNv/YSB6ZV.bam  --bam  --bestn 10 --minMatch 12  --maxMatch 30  --nproc 64  --minSubreadLength 50 --minAlnLength 50  --minPctSimilarity 70 --minPctAccuracy 70 --hitPolicy randombest  --randomSeed 1 '
ERROR: blasr: error while loading shared libraries: libhdf5_cpp.so.12: cannot open shared object file: No such file or directory
Output:[]
Traceback (most recent call last):
  File "/localdisk/home/elopezc/.conda/envs/elopezc/lib/python2.7/site-packages/pbcommand/cli/core.py", line 138, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/localdisk/home/elopezc/.conda/envs/elopezc/lib/python2.7/site-packages/pbalign/pbalignrunner.py", line 284, in args_runner
    return PBAlignRunner(args, output_dataset_type=output_dataset_type).start()
  File "/localdisk/home/elopezc/.conda/envs/elopezc/lib/python2.7/site-packages/pbcore/util/ToolRunner.py", line 85, in start
    return self.run()
  File "/localdisk/home/elopezc/.conda/envs/elopezc/lib/python2.7/site-packages/pbalign/pbalignrunner.py", line 240, in run
    self._alnService.run()
  File "/localdisk/home/elopezc/.conda/envs/elopezc/lib/python2.7/site-packages/pbalign/alignservice/align.py", line 198, in run
    raise RuntimeError(str(e))
RuntimeError: BlasrService returned a non-zero exit status 127
CMD: 'blasr /localdisk/data/chlamydomonas/cc_2931_pacbio/assemblies/flye/Anc.bam /localdisk/data/chlamydomonas/cc_2931_pacbio/assemblies/flye/CC2931.fasta --out /tmp/tmpHIvKNv/YSB6ZV.bam  --bam  --bestn 10 --minMatch 12  --maxMatch 30  --nproc 64  --minSubreadLength 50 --minAlnLength 50  --minPctSimilarity 70 --minPctAccuracy 70 --hitPolicy randombest  --randomSeed 1 '
ERROR: blasr: error while loading shared libraries: libhdf5_cpp.so.12: cannot open shared object file: No such file or directory
Output:[]
[INFO] 2021-02-11 00:28:37,953Z [pbalign.pbalignrunner _pacbio_main_runner 155] exiting with return code 2 in 0.02 sec.
```

**To Reproduce**
The command used was:

```
pbalign --nproc 64 <file.bam> <reference.fa> <output>
```

**Comment by pb-cdunn** [comment]
I think the `hdf5` in your env is too old. You have `1.10`, but [the latest in Anaconda is `1.12`](https://anaconda.org/anaconda/hdf5). I guess **blasr** was built against the latest, though I'm not 100% certain.

Hopefully, there is not a conflict that requires `1.10`.

**Comment by elcortegano** [comment]
In the end it made it to use `pbmm2 align` instead. I was unable to get a consistent conda environment with the packages in the right version so that either blasr or samtools did not break.

**Comment by pb-dseifert** [comment]
`pbalign` is EOL and will not be supported anymore. We will make one last binary release of `blasr`, which is EOL too, but we recognize that some in the community are attached to it. Please only use `pbmm2` going forward.
