### ISSUE TITLE
gcpp ERROR: [pbbam] chemistry compatibility

### ISSUE THREAD

**Issue by lemene** [PacificBiosciences/pbbioconda#392]
Hi, 
When I ran unzip, I met the following error in the polishing step:
```
	gcpp --algorithm=arrow -x 5 -X 120 -q 0 -j 1 -r ../../../quiver-split/refs/000003F_006/ref.fasta aln-000003F_006.bam -o cns.fasta,cns.fastq,cns.vcf
	>|> 20210406 03:24:06.961 -|- FATAL -|- Run -|- 0x2b45cc74cc40|| -|- gcpp ERROR: [pbbam] chemistry compatibility ERROR: unsupported sequencing chemistry combination:
	    binding kit:        100372700
	    sequencing kit:     100356200
	    basecaller version: 2.3.0.0.140640
See SMRT Link release documentation for details about consumables compatibility or contact PacBio Technical Support.
```

The version of gcpp is 2.0.2-2.0.2. I tried  gcpp(0.0.1) and variantCaller(2.2.2).  The former reported the same error, while the latter reported the following error.

```
	variantCaller --algorithm=arrow -x 5 -X 120 -q 0 -j 1 -r ../../../quiver-split/refs/000003F_006/ref.fasta aln-000003F_006.bam -o cns.fasta,cns.fastq,cns.vcf
	
	Arrow: unsupported chemistries found: (P4-C2)
	Arrow: unsupported chemistries found: (P4-C2)
	Traceback (most recent call last):
	  File "./fc_env_210331/lib/python2.7/site-packages/pbcommand/cli/core.py", line 137, in _pacbio_main_runner
	    return_code = exe_main_func(*args, **kwargs)
	  File "./fc_env_210331/lib/python2.7/site-packages/GenomicConsensus-2.2.2-py2.7.egg/GenomicConsensus/main.py", line 351, in args_runner
	    return tr.main()
	  File "./fc_env_210331/lib/python2.7/site-packages/GenomicConsensus-2.2.2-py2.7.egg/GenomicConsensus/main.py", line 277, in main
	    self._configureAlgorithm(options, peekFile)
	  File "./fc_env_210331/lib/python2.7/site-packages/GenomicConsensus-2.2.2-py2.7.egg/GenomicConsensus/main.py", line 164, in _configureAlgorithm
	    self._algorithmConfiguration = self._algorithm.configure(options, alnFile)
	  File "./fc_env_210331/lib/python2.7/site-packages/GenomicConsensus-2.2.2-py2.7.egg/GenomicConsensus/arrow/arrow.py", line 260, in configure
	    die("Arrow: unsupported chemistries found: ({0})".format(", ".join(sorted(unsupp))))
	  File "./fc_env_210331/lib/python2.7/site-packages/GenomicConsensus-2.2.2-py2.7.egg/GenomicConsensus/utils.py", line 16, in die
	    raise DieException(msg)
	DieException: Arrow: unsupported chemistries found: (P4-C2)
	[ERROR] Arrow: unsupported chemistries found: (P4-C2)

```

Is there any idea to fix it? 

Thanks.

**Comment by armintoepfer** [comment]
This chemistry is from the RSII instrument and no longer supported. If you need software to work with RSII data, please install SMRT Analysis v2.3.0 at the bottom of https://www.pacb.com/support/software-downloads/

**Comment by lemene** [comment]
Thank you so much for the reply. I have installed SMRT Analysis v2.3.0.  The parameters of variantCaller.py in SMRT Analysis v2.3.0 seem to be incompatible with those of gcpp(0.0.1) and variantCaller(2.2.2).  Do you have any suggestions on how to use SMRT analysis v2.3.0 to finish the unzip's polishing step?
