### ISSUE TITLE
Bug in restarting falcon_unzip/unzip.pl

### ISSUE THREAD

**Issue by bruc** [PacificBiosciences/pbbioconda#41]
When restarting fc_unzip.py at an early stage, I get the following error traceback:

    [INFO] ln -s 4-polish 4-quiver
    Traceback (most recent call last):
      File "/db/congenomics/local6/binaries/conda/bin/fc_unzip.py", line 11, in <module>
        load_entry_point('falcon-unzip==1.1.3', 'console_scripts', 'fc_unzip.py')()
      File "/db/congenomics/local6/binaries/conda/lib/python2.7/site-packages/falcon_unzip/mains/start_unzip.py", line 29, in main
        unzip.run(**vars(args))
      File "/db/congenomics/local6/binaries/conda/lib/python2.7/site-packages/falcon_unzip/unzip.py", line 145, in run
        backward_compatible_dirs()
      File "/db/congenomics/local6/binaries/conda/lib/python2.7/site-packages/falcon_unzip/unzip.py", line 137, in backward_compatible_dirs
        symlink_if_missing(polish_dn, quiver_dn)
      File "/db/congenomics/local6/binaries/conda/lib/python2.7/site-packages/falcon_unzip/unzip.py", line 107, in symlink_if_missing
        os.symlink(src, name)
    OSError: [Errno 17] File exists

The problem is that the "4-polish" folder doesn't exist yet. Thus, in the symlink_if_missing function, the test for 4-quiver fails, and then the code tries to recreate the symbolic link, and that already exists.

The solution is to change the test from "exists" to "lexists". Here's the updated code snippet:

```
def symlink_if_missing(src, name):
    if not os.path.lexists(name):
        LOG.info(' ln -s {} {}'.format(src, name))
        os.symlink(src, name)
```

**Comment by pb-cdunn** [comment]
`70425993 falcon_unzip/unzip.py (Christopher Dunn   2018-09-21 133)     if not os.path.lexists(name)`

That's in the released version now.
