### ISSUE TITLE
pbindex not found

### ISSUE THREAD

**Issue by spz1st** [PacificBiosciences/pbbioconda#412]
**Operating system**
RedHat linux 7

**Package name**
pb-assembly (pb_unzip.py)

**Conda environment**
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             4.5                       1_gnu
bedtools                  2.30.0               h7d7f7ad_1    bioconda
blas                      1.0                         mkl
blasr                     5.3.5                         0    bioconda
bwa                       0.7.17               h5bf99c6_8    bioconda
bzip2                     1.0.8                h7b6447c_0
ca-certificates           2021.5.25            h06a4308_1
certifi                   2021.5.30        py37h06a4308_0
curl                      7.71.1               hbc83047_1
decorator                 5.0.9              pyhd3eb1b0_0
falcon-kit                1.8.1                    pypi_0    pypi
falcon-phase              1.2.0                    pypi_0    pypi
falcon-unzip              1.3.7                    pypi_0    pypi
future                    0.18.2                   py37_1
htslib                    1.9                  ha228f0b_7    bioconda
intel-openmp              2021.2.0           h06a4308_610
k8                        0.2.5                h9a82719_1    bioconda
krb5                      1.18.2               h173b8e3_0
ld_impl_linux-64          2.35.1               h7274673_9
libcurl                   7.71.1               h20c2e04_1
libdeflate                1.0                  h14c3975_1    bioconda
libedit                   3.1.20210216         h27cfd23_1
libffi                    3.3                  he6710b0_2
libgcc                    7.2.0                h69d50b8_2
libgcc-ng                 9.3.0               h5101ec6_17
libgomp                   9.3.0               h5101ec6_17
libssh2                   1.9.0                h1ba5d50_1
libstdcxx-ng              9.3.0               hd4cf53a_17
minimap2                  2.20                 h5bf99c6_0    bioconda
mkl                       2021.2.0           h06a4308_296
mkl-service               2.3.0            py37h27cfd23_1
mkl_fft                   1.3.0            py37h42c9631_2
mkl_random                1.2.1            py37ha9443f7_2
mummer4                   4.0.0rc1        pl5262h1b792b2_1    bioconda
ncurses                   6.2                  he6710b0_1
networkx                  2.2                      py37_1
nim-falcon                3.0.1                h1341992_0    bioconda
numpy                     1.20.2           py37h2d18471_0
numpy-base                1.20.2           py37hfae3a4d_0
openssl                   1.1.1k               h27cfd23_0
pb-assembly               0.0.8                hdfd78af_1    bioconda
pb-dazzler                0.0.1                h779adbc_1    bioconda
pb-falcon                 2.2.4            py37hed50d52_0    bioconda
pb-falcon-phase           0.1.0                h3889886_0    bioconda
pb-falconc                0.1.2                hc9558a2_1    bioconda
pbgcpp                    2.0.2                h9ee0642_1    bioconda
pbmm2                     1.3.0                h56fc30b_0    bioconda
pcre                      8.44                 he6710b0_0
perl                      5.26.2               h14c3975_0
pip                       21.1.2           py37h06a4308_0
pysam                     0.15.3           py37hda2845c_1    bioconda
python                    3.7.10               h12debd9_4
python-edlib              1.3.8.post2      py37h22450f8_1    bioconda
python-intervaltree       3.1.0              pyh864c0ab_0    bioconda
python-msgpack            0.6.1            py37h22450f8_4    bioconda
python-sortedcontainers   2.3.0              pyh3252c3a_0    bioconda
python_abi                3.7                     1_cp37m    conda-forge
racon                     1.4.20               h9a82719_1    bioconda
readline                  8.1                  h27cfd23_0
samtools                  1.7                           1    bioconda
setuptools                52.0.0           py37h06a4308_0
six                       1.15.0           py37h06a4308_0
sqlite                    3.35.4               hdfb4753_0
tk                        8.6.10               hbc83047_0
wheel                     0.36.2             pyhd3eb1b0_0
xz                        5.2.5                h7b6447c_0
zlib                      1.2.11               h7b6447c_3
```

**Describe the bug**
Not sure if it's a bug or simply something's lacking in the installed env.
I just installed pb-assembly with conda in a new env  and downloaded the test data according to the instruction in pb-assembly READM.md.  When I tried fc_run and succeeded (after updated pb-falconc separately).  But when I tried fc_unzip.py, I got errors about pbindex not found (see below).

**Error message**
```
[INFO]Popen: 'bash -C /usr/local/miniconda_py37/envs/pb-assembly/lib/python3.7/site-packages/pwatcher/mains/job_start.sh >| /data/test_pb/FALCON-examples/run/greg200k-sv2/4-polish/quiver-run/000000F_001/run-Pa79ce46875bf1f.bash.stdout 2>| /data/test_pb/FALCON-examples/run/greg200k-sv2/4-polish/quiver-run/000000F_001/run-Pa79ce46875bf1f.bash.stderr'
[INFO](slept for another 1.4s -- another 4 loop iterations)
[INFO](slept for another 2.0s -- another 5 loop iterations)
[ERROR]Task Node(4-polish/quiver-run/000000F_001) failed with exit-code=1
[ERROR]Task Node(4-polish/quiver-run/000000F) failed with exit-code=1
[ERROR]Some tasks are recently_done but not satisfied: {Node(4-polish/quiver-run/000000F), Node(4-polish/quiver-run/000000F_001)}
[ERROR]ready: set()
        submitted: set()
[ERROR]Noop. We cannot kill blocked threads. Hopefully, everything will die on SIGTERM.
[ERROR]Error for run(target=clr, config_fn=fc_unzip.cfg, logging_config_fn=None)
Traceback (most recent call last):
  File "/usr/local/miniconda_py37/envs/pb-assembly/lib/python3.7/site-packages/falcon_unzip/unzip.py", line 195, in run
    run_logged(target, config_fn)
  File "/usr/local/miniconda_py37/envs/pb-assembly/lib/python3.7/site-packages/falcon_unzip/unzip.py", line 184, in run_logged
    unzip_all(config, unzip_config_fn)
  File "/usr/local/miniconda_py37/envs/pb-assembly/lib/python3.7/site-packages/falcon_unzip/unzip.py", line 27, in unzip_all
    tasks_unzip.run_workflow(wf, config, unzip_config_fn)
  File "/usr/local/miniconda_py37/envs/pb-assembly/lib/python3.7/site-packages/falcon_unzip/tasks/unzip.py", line 739, in run_workflow
    job_dict=config['job.step.unzip.quiver'],
  File "/usr/local/miniconda_py37/envs/pb-assembly/lib/python3.7/site-packages/falcon_kit/pype.py", line 195, in gen_parallel_tasks
    wf.refreshTargets()
  File "/usr/local/miniconda_py37/envs/pb-assembly/lib/python3.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 278, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/usr/local/miniconda_py37/envs/pb-assembly/lib/python3.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 362, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: {Node(4-polish/quiver-run/000000F), Node(4-polish/quiver-run/000000F_001)}
Traceback (most recent call last):
  File "/usr/local/miniconda_py37/envs/pb-assembly/bin/fc_unzip.py", line 11, in <module>
    load_entry_point('falcon-unzip==1.3.7', 'console_scripts', 'fc_unzip.py')()
  File "/usr/local/miniconda_py37/envs/pb-assembly/lib/python3.7/site-packages/falcon_unzip/mains/start_unzip.py", line 33, in main
    unzip.run(**vars(args))
  File "/usr/local/miniconda_py37/envs/pb-assembly/lib/python3.7/site-packages/falcon_unzip/unzip.py", line 195, in run
    run_logged(target, config_fn)
  File "/usr/local/miniconda_py37/envs/pb-assembly/lib/python3.7/site-packages/falcon_unzip/unzip.py", line 184, in run_logged
    unzip_all(config, unzip_config_fn)
  File "/usr/local/miniconda_py37/envs/pb-assembly/lib/python3.7/site-packages/falcon_unzip/unzip.py", line 27, in unzip_all
    tasks_unzip.run_workflow(wf, config, unzip_config_fn)
  File "/usr/local/miniconda_py37/envs/pb-assembly/lib/python3.7/site-packages/falcon_unzip/tasks/unzip.py", line 739, in run_workflow
    job_dict=config['job.step.unzip.quiver'],
  File "/usr/local/miniconda_py37/envs/pb-assembly/lib/python3.7/site-packages/falcon_kit/pype.py", line 195, in gen_parallel_tasks
    wf.refreshTargets()
  File "/usr/local/miniconda_py37/envs/pb-assembly/lib/python3.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 278, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/usr/local/miniconda_py37/envs/pb-assembly/lib/python3.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 362, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: {Node(4-polish/quiver-run/000000F), Node(4-polish/quiver-run/000000F_001)}

```

The following are lines from the file /data/test_pb/FALCON-examples/run/greg200k-sv2/4-polish/quiver-run/000000F_001/run-Pa79ce46875bf1f.bash.stderr.

```
+ pbmm2 align --sort ../../../quiver-split/refs/000000F_001/ref.fasta /data/test_pb/FALCON-examples/run/greg200k-sv2/4-polish/segregate-run/segr001/segregated/000000F_001/000000F_001.bam aln-000000F_001.bam
+ pbindex aln-000000F_001.bam
user_script.sh: line 22: pbindex: command not found
touch quiver_done.exit
+ touch quiver_done.exit
WARNING:root:Call '/bin/bash user_script.sh' returned 32512.
INFO:root:CD: 'uow-00' -> '/data/test_pb/FALCON-examples/run/greg200k-sv2/4-polish/quiver-run/000000F_001'
ERROR:root:failed multiprocessing
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/miniconda_py37/envs/pb-assembly/lib/python3.7/site-packages/falcon_kit/util/io.py", line 68, in run_func
    ret = func(*args)
  File "/usr/local/miniconda_py37/envs/pb-assembly/lib/python3.7/site-packages/falcon_kit/mains/generic_run_units_of_work.py", line 45, in run_uow
    pypeflow.do_task.run_bash(script, inputs, outputs, params)
  File "/usr/local/miniconda_py37/envs/pb-assembly/lib/python3.7/site-packages/pypeflow/do_task.py", line 200, in run_bash
    util.system(cmd)
  File "/usr/local/miniconda_py37/envs/pb-assembly/lib/python3.7/site-packages/pypeflow/io.py", line 27, in syscall
    raise Exception(msg)
Exception: Call '/bin/bash user_script.sh' returned 32512.
```

**To Reproduce**
followed steps descript in https://github.com/gconcepcion/pb-assembly
```
$ conda create -n pb-assembly
$ conda activate pb-assembly
$ conda install pb-assembly
$ conda update --all
$ conda install -c bioconda pb-falconc
$ mkdir test_pb
$ cd test_pb
$ git clone https://github.com/cdunn2001/git-sym.git
$ git clone https://github.com/pb-cdunn/FALCON-examples.git
$ cd FALCON-examples/
$ ../git-sym/git-sym update run/greg200k-sv2
$ cd run/greg200k-sv2/
$ fc_run fc_run.cfg
$ fc_unzip.py fc_unzip.cfg # got errors with exit code 1
```

**Expected behavior**
Expected fc_unzip.py to finish with exit code 0

**Comment by spz1st** [comment]
I resolved the issue.  pbbam was not installed.  After I installed pbbam (conda install -c bioconda pbbam),  pbindex is available.  Wondering why pbbam is not included in pb-assembly installation (at least in my case).
