### ISSUE TITLE
FALCON cannot run sample data set: Exception: Call '/bin/bash user_script.sh' returned 256.

### ISSUE THREAD

**Issue by Mpersicae** [PacificBiosciences/pbbioconda#477]
Hello,

I am trying to get FALCON-UNZIP set up on an SGE grid, and I am running into a persistent error while running the example E. coli data set. 

I installed pb-assembly into a conda environment as indicated here https://github.com/PacificBiosciences/pb-assembly. I updated all the packages in the environment. Here is the environment:

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
bedtools                  2.30.0               h468198e_3    bioconda
blasr                     5.3.5                         0    bioconda
bwa                       0.7.17               h7132678_9    bioconda
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
curl                      7.82.0               h2283fc2_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
falcon-kit                1.8.1                    pypi_0    pypi
falcon-phase              1.2.0                    pypi_0    pypi
falcon-unzip              1.3.7                    pypi_0    pypi
future                    0.18.2           py37h89c1867_4    conda-forge
htslib                    1.9                  ha228f0b_7    bioconda
k8                        0.2.5                hd03093a_2    bioconda
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.19.2               h08a2579_4    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libblas                   3.9.0           13_linux64_openblas    conda-forge
libcblas                  3.9.0           13_linux64_openblas    conda-forge
libcurl                   7.82.0               h2283fc2_0    conda-forge
libdeflate                1.0                  h14c3975_1    bioconda
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 11.2.0              h1d223b6_13    conda-forge
libgfortran-ng            11.2.0              h69a702a_13    conda-forge
libgfortran5              11.2.0              h5c6108e_13    conda-forge
libgomp                   11.2.0              h1d223b6_13    conda-forge
liblapack                 3.9.0           13_linux64_openblas    conda-forge
libnghttp2                1.47.0               he49606f_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.18          pthreads_h8fe5266_0    conda-forge
libssh2                   1.10.0               ha35d2d1_2    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_13    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
minimap2                  2.24                 h7132678_1    bioconda
mummer4                   4.0.0rc1        pl5321h87f3376_3    bioconda
ncurses                   6.3                  h9c3ff4c_0    conda-forge
networkx                  2.5                        py_0    conda-forge
nim-falcon                3.0.1                h1341992_0    bioconda
numpy                     1.21.5           py37hf2998dd_0    conda-forge
openssl                   3.0.0                h7f98852_2    conda-forge
pb-assembly               0.0.8                hdfd78af_1    bioconda
pb-dazzler                0.0.1                hec16e2b_2    bioconda
pb-falcon                 2.2.4            py37hed50d52_0    bioconda
pb-falcon-phase           0.1.0                h3889886_0    bioconda
pbgcpp                    2.0.2                h9ee0642_1    bioconda
pbmm2                     1.8.0                h87f3376_1    bioconda
pcre                      8.45                 h9c3ff4c_0    conda-forge
perl                      5.32.1          2_h7f98852_perl5    conda-forge
pip                       22.0.4             pyhd8ed1ab_0    conda-forge
pysam                     0.15.3           py37hda2845c_1    bioconda
python                    3.7.12          hf930737_100_cpython    conda-forge
python-edlib              1.3.9            py37h96cfd12_1    bioconda
python-intervaltree       3.1.0              pyh864c0ab_0    bioconda
python-msgpack            0.6.1            py37h96cfd12_5    bioconda
python-sortedcontainers   2.4.0              pyh5e36f6f_0    bioconda
python_abi                3.7                     2_cp37m    conda-forge
racon                     1.4.20               hd03093a_2    bioconda
readline                  8.1                  h46c0cb4_0    conda-forge
samtools                  1.7                           1    bioconda
setuptools                60.9.3           py37h89c1867_0    conda-forge
sqlite                    3.37.0               h9cd32fc_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
```

When I run `fc_run fc_run.cfg` in the greg200k-sv2 directory, the process gets stuck at 2-asm-falcon. Here are the last few lines in the output:

```
{Node(1-preads_ovl/db2falcon)}
[INFO]Num satisfied in this iteration: 1
[INFO]Num still unsatisfied: 1
[INFO]About to submit: Node(2-asm-falcon)
[INFO]Popen: 'bash -C /home/miniconda3/envs/FALCON/lib/python3.7/site-packages/pwatcher/mains/job_start.sh >| /My_path/FALCON-examples/run/greg200k-sv2/2-asm-falcon/run-Pa91aa0405aba7f.bash.stdout 2>| /My_path/FALCON-examples/run/greg200k-sv2/2-asm-falcon/run-Pa91aa0405aba7f.bash.stderr'
[INFO](slept for another 0.6000000000000001s -- another 4 loop iterations)
[INFO](slept for another 1.5s -- another 5 loop iterations)
[ERROR]Task Node(2-asm-falcon) failed with exit-code=1
[ERROR]Some tasks are recently_done but not satisfied: {Node(2-asm-falcon)}
[ERROR]ready: set()
        submitted: set()
[ERROR]Noop. We cannot kill blocked threads. Hopefully, everything will die on SIGTERM.
Traceback (most recent call last):
  File "/home/miniconda3/envs/FALCON/bin/fc_run", line 11, in <module>
    load_entry_point('falcon-kit==1.8.1', 'console_scripts', 'fc_run')()
  File "/home/miniconda3/envs/FALCON/lib/python3.7/site-packages/falcon_kit/mains/run1.py", line 706, in main
    main1(argv[0], args.config, args.logger)
  File "/home/miniconda3/envs/FALCON/lib/python3.7/site-packages/falcon_kit/mains/run1.py", line 73, in main1
    input_fofn_fn=input_fofn_fn,
  File "/home/miniconda3/envs/FALCON/lib/python3.7/site-packages/falcon_kit/mains/run1.py", line 460, in run
    wf.refreshTargets()
  File "/home/miniconda3/envs/FALCON/lib/python3.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 278, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/home/miniconda3/envs/FALCON/lib/python3.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 362, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: {Node(2-asm-falcon)}
```

Based on other issues I found, I looked at the stderr file in the `2-asm-falcon` directory. Here are the last few lines of that file (some file paths edited for brevity):

```
# Given preads.m4,
# write sg_edges_list, c_path, utg_data, ctg_paths.
falconc m4filt-contained --in preads.m4 --out preads.filtered.m4 --min-len 1
+ falconc m4filt-contained --in preads.m4 --out preads.filtered.m4 --min-len 1
    0.0s version=0.0.0, nim-version=0.20.2
Unknown subcommand "m4filt-contained".  It is not similar to defined subcommands.

Run again with subcommand "help" to get detailed usage.
2022-03-10 15:50:25,576 - root - WARNING - Call '/bin/bash user_script.sh' returned 256.
2022-03-10 15:50:25,576 - root - INFO - CD: '/My_path/FALCON-examples/run/greg200k-sv2/2-asm-falcon' -> $
2022-03-10 15:50:25,576 - root - INFO - CD: '/My_path/FALCON-examples/run/greg200k-sv2/2-asm-falcon' -> $
2022-03-10 15:50:25,577 - root - CRITICAL - Error in /home/miniconda3/envs/FALCON/lib/python3.7/site-packages/pypeflow/do_task.py with args=$
Traceback (most recent call last):
  File "/home/miniconda3/envs/FALCON/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/miniconda3/envs/FALCON/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/miniconda3/envs/FALCON/lib/python3.7/site-packages/pypeflow/do_task.py", line 280, in <module>
    main()
  File "/home/miniconda3/envs/FALCON/lib/python3.7/site-packages/pypeflow/do_task.py", line 272, in main
    run(**vars(parsed_args))
  File "/home/miniconda3/envs/FALCON/lib/python3.7/site-packages/pypeflow/do_task.py", line 266, in run
    run_cfg_in_tmpdir(cfg, tmpdir, '.')
  File "/home/miniconda3/envs/FALCON/lib/python3.7/site-packages/pypeflow/do_task.py", line 241, in run_cfg_in_tmpdir
    run_bash(bash_template, myinputs, myoutputs, parameters)
  File "/home/miniconda3/envs/FALCON/lib/python3.7/site-packages/pypeflow/do_task.py", line 200, in run_bash
    util.system(cmd)
  File "/home/miniconda3/envs/FALCON/lib/python3.7/site-packages/pypeflow/io.py", line 27, in syscall
    raise Exception(msg)
Exception: Call '/bin/bash user_script.sh' returned 256.
+++ pwd
++ echo 'FAILURE. Running top in /My_path/FALCON-examples/run/greg200k-sv2/2-asm-falcon (If you see -terminal database is inaccessible- you are using the python bin-wrapper, so you will not get diagnostic info. No big deal. This process is crashing anyway.)'
++ rm -f top.txt
++ which python
++ which top
++ env -u LD_LIBRARY_PATH top -b -n 1
++ env -u LD_LIBRARY_PATH top -b -n 1
++ pstree -apl

real    0m1.539s
user    0m1.032s
sys     0m0.484s
+ finish
+ echo 'finish code: 1'
```

I am not experienced with python, and could not glean anything from examining the `io.py` file, so I am now stuck. Any help or advice you could provide would be much appreciated, please let me know if you need additional information. 

Thanks,
Yonathan

**Comment by gconcepcion** [comment]
Hello, It looks like your nim-falcon is out of date.


See here: https://github.com/PacificBiosciences/pbbioconda/issues/307

**Comment by Mpersicae** [comment]
Hi,

Thanks for the quick response. This was indeed the issue. 
For some reason, simply running `conda update --all` would not update nim-falcon, I had to force the update using using `conda install -n my_env nim-falcon==3.0.2`. After that, `fc_run fc_run.cfg` finished properly.

I'm having a follow-up issue where `fc_unzip.py fc_unzip.cfg` is failing during quiver polishing. I'm getting identical warnings to those posted here https://github.com/PacificBiosciences/FALCON_unzip/issues/159, so I think I can just run quiver manually if this happens with my data.

Thanks,
Yonathan
