### ISSUE TITLE
Daligner illegal option -D

### ISSUE THREAD

**Issue by gbdias** [PacificBiosciences/pbbioconda#55]
tool: pb-assembly
command: fc_run

Hi,

I am using Falcon (v0.2.3) from pb-assembly. Although I did not specify the -D option in the `pa_hpcdaligner` or `ovlp_hpcdaligner` steps, I keep getting this error regarding this being an illegal option.

```
+ which HPC.daligner
HPC.daligner -P. -e.75 -l1000 -k18 -h70 -s100 -v -D24 -mtan -mrep0 -mdust -H$CUTOFF -fdaligner-jobs raw_reads >| run_jobs.sh
+ HPC.daligner -P. -e.75 -l1000 -k18 -h70 -s100 -v -D24 -mtan -mrep0 -mdust -H31694 -fdaligner-jobs raw_reads
HPC.daligner: -D is an illegal option
[WARNING]Call 'bash -vex split_db.sh' returned 256.
```

- Here is the tail of the log file:
```
[INFO](slept for another 0.4s -- another 3 loop iterations)
[ERROR]Task Node(0-rawreads/daligner-split) failed with exit-code=1
[ERROR]Some tasks are recently_done but not satisfied: set([Node(0-rawreads/daligner-split)])
[ERROR]ready: set([])
	submitted: set([])
[ERROR]Noop. We cannot kill blocked threads. Hopefully, everything will die on SIGTERM.
Traceback (most recent call last):
  File "/home/gd98309/.conda/envs/falconda/bin/fc_run", line 11, in <module>
    load_entry_point('falcon-kit==1.2.3', 'console_scripts', 'fc_run')()
  File "/home/gd98309/.conda/envs/falconda/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 726, in main
    main1(argv[0], args.config, args.logger)
  File "/home/gd98309/.conda/envs/falconda/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 76, in main1
    input_fofn_fn=input_fofn_fn,
  File "/home/gd98309/.conda/envs/falconda/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 301, in run
    daligner_split_script=pype_tasks.TASK_DB_DALIGNER_SPLIT_SCRIPT,
  File "/home/gd98309/.conda/envs/falconda/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 539, in add_daligner_and_merge_tasks
    dist=Dist(NPROC=4, MB=4000, job_dict=daligner_job_config),
  File "/home/gd98309/.conda/envs/falconda/lib/python2.7/site-packages/falcon_kit/pype.py", line 106, in gen_parallel_tasks
    wf.refreshTargets()
  File "/home/gd98309/.conda/envs/falconda/lib/python2.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 277, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/home/gd98309/.conda/envs/falconda/lib/python2.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 361, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: set([Node(0-rawreads/daligner-split)])
```

- Any thoughts on why is that happening?

Here is my full config file:

```
[General]
# list of files of the initial bas.h5 files
input_fofn = input.fofn

input_type = raw

genome_size = 14200000
seed_coverage = 30.0
length_cutoff = -1

falcon_sense_greedy = False

pa_dbsplit_option = -x500 -s200 -a
falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 6
overlap_filtering_setting = --max_diff 60 --max_cov 100 --min_cov 4 --bestn 10 --n_core 4
length_cutoff_pr = 500
ovlp_dbsplit_option = -x500 -s200 -a

pa_daligner_option   = -e.75 -l1000 -k18 -h70 -s100
pa_hpcdaligner_option = -v -B128 -M24

ovlp_daligner_option = -h35 -e.93 -l1000 -s100 -k25
ovlp_hpcdaligner_option = -v -B128 -M24

[job.defaults]
job_type = local

# use_tmpdir = /lscratch
pwatcher_type = blocking
job_type = string
submit = bash -C ${CMD} >| ${STDOUT_FILE} 2>| ${STDERR_FILE}

NPROC = 28
njobs = 1
MB = 8000
[job.step.da]
[job.step.pda]
[job.step.la]
[job.step.pla]
[job.step.cns]
[job.step.asm]
```

**Comment by gconcepcion** [comment]
Did you install FALCON and it's associated dependencies each manually in Bioconda? There is a newer version - 0.2.4 available but I don't think that's the issue here.

Or did you install the `pb-assembly` recipe to ensure all of your dependency versions resolve correctly?
<code>
$ conda install pb-falcon
</code>

I suspect you need to update your daligner/dazzler binaries

**Comment by gbdias** [comment]
- Hi greg, I installed the pb-assembly recipe through Bioconda
- The weird thing is that I have used this installations successfully before. But after I modified my config file I get this -D error.
- I could try to do a new installation but I agree that that is probably not the issue.

**Comment by dbtara** [comment]
What i noticed is the config file config.json and General.json are the ones with the line
`"ovlp_HPCdaligner_option": "-v -D24 -l500"`

Does this help?

**Comment by gbdias** [comment]
- Hi @dbtara, I noticed that too. However, these files are generated from my config file (plus hardcoded defaults I imagine). So this -D option must somehow be implicit in my config settings.
- I have since changed my config file substantially and I no longer see this error, I don't know exactly what change did the trick though.
