### ISSUE TITLE
Error when run fc_run

### ISSUE THREAD

**Issue by thinkerle** [PacificBiosciences/pbbioconda#572]
I installed pb-assembly via conda, then i run human assembly but i get error
**fc_run.py config fc_run_HiFi_Human.cfg**
falcon-kit 1.8.1 (pip thinks "falcon-kit 1.8.1")
pypeflow 2.3.0
ERROR:root:Failed to setup logging from file "fc_run_HiFi_Human.cfg". Using basicConfig().
Traceback (most recent call last):
  File "/home/minhlong/miniconda3/lib/python3.7/site-packages/falcon_kit/run_support.py", line 547, in setup_logger
    _setup_logging(logging_config_fn)
  File "/home/minhlong/miniconda3/lib/python3.7/site-packages/falcon_kit/run_support.py", line 541, in _setup_logging
    logger_fileobj, defaults=defaults, disable_existing_loggers=False)
  File "/home/minhlong/miniconda3/lib/python3.7/logging/config.py", line 71, in fileConfig
    formatters = _create_formatters(cp)
  File "/home/minhlong/miniconda3/lib/python3.7/logging/config.py", line 104, in _create_formatters
    flist = cp["formatters"]["keys"]
  File "/home/minhlong/miniconda3/lib/python3.7/configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'formatters'
ERROR:root:Failed to parse config "config".
Traceback (most recent call last):
  File "/home/minhlong/miniconda3/lib/python3.7/site-packages/falcon_kit/mains/run1.py", line 52, in main1
    config = run_support.parse_cfg_file(input_config_fn)
  File "/home/minhlong/miniconda3/lib/python3.7/site-packages/falcon_kit/run_support.py", line 144, in parse_cfg_file
    with open(config_fn) as stream:
FileNotFoundError: [Errno 2] No such file or directory: 'config'
Traceback (most recent call last):
  File "/home/minhlong/miniconda3/bin/fc_run.py", line 11, in <module>
    load_entry_point('falcon-kit==1.8.1', 'console_scripts', 'fc_run.py')()
  File "/home/minhlong/miniconda3/lib/python3.7/site-packages/falcon_kit/mains/run1.py", line 706, in main
    main1(argv[0], args.config, args.logger)
  File "/home/minhlong/miniconda3/lib/python3.7/site-packages/falcon_kit/mains/run1.py", line 52, in main1
    config = run_support.parse_cfg_file(input_config_fn)
  File "/home/minhlong/miniconda3/lib/python3.7/site-packages/falcon_kit/run_support.py", line 144, in parse_cfg_file
    with open(config_fn) as stream:
FileNotFoundError: [Errno 2] No such file or directory: 'config'

**Comment by gconcepcion** [comment]
Before we troubleshoot FALCON, what kind of data are you running? CLR or HiFi data? It seems your config is setup for HiFi data, not CLR so I would highly recommend running [hifiasm](https://github.com/chhylp123/hifiasm) instead of FALCON

**Comment by thinkerle** [comment]
> Before we troubleshoot FALCON, what kind of data are you running? CLR or HiFi data? It seems your config is setup for HiFi data, not CLR so I would highly recommend running [hifiasm](https://github.com/chhylp123/hifiasm) instead of FALCON

yes. it Hifi data. I want to try many tools. I ran hifiasm, canu.

**Comment by gconcepcion** [comment]
We ran a hifiasm vs FALCON vs HiCanu comparison on a human genome for the [Hifiasm paper](https://www.nature.com/articles/s41592-020-01056-5) when it came out, I suggest you refer to the paper for the comparison. The overwhelming recommendation these days is to run hifiasm on your dataset, in part because it is faster, contiguity and completeness tend to be better, but also, and I can't stress this enough, because it's much easier to run than many of the alternative assemblers.
