### ISSUE TITLE
variantCaller Error

### ISSUE THREAD

**Issue by francicco** [PacificBiosciences/pbbioconda#6]
I receive this error while using Arrow.

```
Arrow: unsupported chemistries found: (unknown)
Arrow: unsupported chemistries found: (unknown)
Traceback (most recent call last):
  File "/home/fc464/lib/python2.7/site-packages/pbcommand-0.6.12-py2.7.egg/pbcommand/cli/core.py", line 137, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/home/fc464/.local/lib/python2.7/site-packages/GenomicConsensus-2.3.2-py2.7.egg/GenomicConsensus/main.py", line 340, in args_runner
    return tr.main()
  File "/home/fc464/.local/lib/python2.7/site-packages/GenomicConsensus-2.3.2-py2.7.egg/GenomicConsensus/main.py", line 270, in main
    self._configureAlgorithm(options, peekFile)
  File "/home/fc464/.local/lib/python2.7/site-packages/GenomicConsensus-2.3.2-py2.7.egg/GenomicConsensus/main.py", line 164, in _configureAlgorithm
    self._algorithmConfiguration = self._algorithm.configure(options, alnFile)
  File "/home/fc464/.local/lib/python2.7/site-packages/GenomicConsensus-2.3.2-py2.7.egg/GenomicConsensus/arrow/arrow.py", line 236, in configure
    die("Arrow: unsupported chemistries found: ({0})".format(", ".join(sorted(unsupp))))
  File "/home/fc464/.local/lib/python2.7/site-packages/GenomicConsensus-2.3.2-py2.7.egg/GenomicConsensus/utils.py", line 16, in die
    raise DieException(msg)
DieException: Arrow: unsupported chemistries found: (unknown)
[ERROR] Arrow: unsupported chemistries found: (unknown)
Traceback (most recent call last):
  File "/home/fc464/lib/python2.7/site-packages/pbcommand-0.6.12-py2.7.egg/pbcommand/cli/core.py", line 137, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/home/fc464/.local/lib/python2.7/site-packages/GenomicConsensus-2.3.2-py2.7.egg/GenomicConsensus/main.py", line 340, in args_runner
    return tr.main()
  File "/home/fc464/.local/lib/python2.7/site-packages/GenomicConsensus-2.3.2-py2.7.egg/GenomicConsensus/main.py", line 270, in main
    self._configureAlgorithm(options, peekFile)
  File "/home/fc464/.local/lib/python2.7/site-packages/GenomicConsensus-2.3.2-py2.7.egg/GenomicConsensus/main.py", line 164, in _configureAlgorithm
    self._algorithmConfiguration = self._algorithm.configure(options, alnFile)
  File "/home/fc464/.local/lib/python2.7/site-packages/GenomicConsensus-2.3.2-py2.7.egg/GenomicConsensus/arrow/arrow.py", line 236, in configure
    die("Arrow: unsupported chemistries found: ({0})".format(", ".join(sorted(unsupp))))
  File "/home/fc464/.local/lib/python2.7/site-packages/GenomicConsensus-2.3.2-py2.7.egg/GenomicConsensus/utils.py", line 16, in die
    raise DieException(msg)
DieException: Arrow: unsupported chemistries found: (unknown)
```

**Comment by pb-dseifert** [comment]
This is not a bioconda installation. We do not support GenomicConsensus installed via distribution methods other than bioconda.

**Comment by francicco** [comment]
It is a miniconda installation.

```
[fc464@login-e-16 HeliconiiniProg]$ source activate $HOME/miniconda3
(/home/fc464/miniconda3) which arrow
~/miniconda3/bin/arrow
(/home/fc464/miniconda3) which variantCaller
~/miniconda3/bin/variantCaller
(/home/fc464/miniconda3) variantCaller --algorithm=arrow --diploid -o /rds/user/fc464/hpc-work/HeliconiiniProg/Djun.Assembly-36.41x-erate-0.045/DjunPacBio.contigs.Arrow.It.1.fasta -j 32 --referenceFilename /rds/user/fc464/hpc-work/HeliconiiniProg/Djun.Assembly-36.41x-erate-0.045/DjunPacBio.contigs.fasta --reportEffectiveCoverage /rds/user/fc464/hpc-work/HeliconiiniProg/Djun.Assembly-36.41x-erate-0.045/DjunPacBio.pbmm2.PacBio.sorted.bam
Arrow: unsupported chemistries found: (unknown)
Arrow: unsupported chemistries found: (unknown)
Traceback (most recent call last):
  File "/home/fc464/miniconda3/lib/python2.7/site-packages/pbcommand/cli/core.py", line 138, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/home/fc464/.local/lib/python2.7/site-packages/GenomicConsensus-2.3.2-py2.7.egg/GenomicConsensus/main.py", line 340, in args_runner
    return tr.main()
  File "/home/fc464/.local/lib/python2.7/site-packages/GenomicConsensus-2.3.2-py2.7.egg/GenomicConsensus/main.py", line 270, in main
    self._configureAlgorithm(options, peekFile)
  File "/home/fc464/.local/lib/python2.7/site-packages/GenomicConsensus-2.3.2-py2.7.egg/GenomicConsensus/main.py", line 164, in _configureAlgorithm
    self._algorithmConfiguration = self._algorithm.configure(options, alnFile)
  File "/home/fc464/.local/lib/python2.7/site-packages/GenomicConsensus-2.3.2-py2.7.egg/GenomicConsensus/arrow/arrow.py", line 236, in configure
    die("Arrow: unsupported chemistries found: ({0})".format(", ".join(sorted(unsupp))))
  File "/home/fc464/.local/lib/python2.7/site-packages/GenomicConsensus-2.3.2-py2.7.egg/GenomicConsensus/utils.py", line 16, in die
    raise DieException(msg)
DieException: Arrow: unsupported chemistries found: (unknown)
[ERROR] Arrow: unsupported chemistries found: (unknown)
Traceback (most recent call last):
  File "/home/fc464/miniconda3/lib/python2.7/site-packages/pbcommand/cli/core.py", line 138, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/home/fc464/.local/lib/python2.7/site-packages/GenomicConsensus-2.3.2-py2.7.egg/GenomicConsensus/main.py", line 340, in args_runner
    return tr.main()
  File "/home/fc464/.local/lib/python2.7/site-packages/GenomicConsensus-2.3.2-py2.7.egg/GenomicConsensus/main.py", line 270, in main
    self._configureAlgorithm(options, peekFile)
  File "/home/fc464/.local/lib/python2.7/site-packages/GenomicConsensus-2.3.2-py2.7.egg/GenomicConsensus/main.py", line 164, in _configureAlgorithm
    self._algorithmConfiguration = self._algorithm.configure(options, alnFile)
  File "/home/fc464/.local/lib/python2.7/site-packages/GenomicConsensus-2.3.2-py2.7.egg/GenomicConsensus/arrow/arrow.py", line 236, in configure
    die("Arrow: unsupported chemistries found: ({0})".format(", ".join(sorted(unsupp))))
  File "/home/fc464/.local/lib/python2.7/site-packages/GenomicConsensus-2.3.2-py2.7.egg/GenomicConsensus/utils.py", line 16, in die
    raise DieException(msg)
DieException: Arrow: unsupported chemistries found: (unknown)
```

**Comment by francicco** [comment]
I reinstall it

```
(/home/fc464/miniconda3) conda install -c bioconda genomicconsensus
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.4
  latest version: 4.5.11

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /home/fc464/miniconda3

  added / updated specs: 
    - genomicconsensus


The following NEW packages will be INSTALLED:

    genomicconsensus: 2.3.2-py27_1 bioconda

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: - 
##############################################################################
#                                                                            #
# PacBio(R) tools distributed via Bioconda are: pre-release versions, not    #
# necessarily ISO compliant, intended for Research Use Only and not for use  #
# in diagnostic procedures, intended only for command-line users, and        #
# possibly newer than the currently available SMRT(R) Analysis builds. While #
# efforts have been made to ensure that releases on Bioconda live up to the  #
# quality that PacBio strives for, we make no warranty regarding any         #
# Bioconda release.                                                          #
#                                                                            #
# As PacBio tools distributed via Bioconda are not covered by any service    #
# level agreement or the like, please *do not* contact a PacBio Field        #
# Applications Scientist or PacBio Customer Service for assistance with any  #
# Bioconda release. We instead provide an issue tracker for you to report    #
# issues to us at:                                                           #
#                                                                            #
#   https://github.com/PacificBiosciences/pbbioconda                         #
#                                                                            #
# We make no warranty that any such issue will be addressed,                 #
# to any extent or within any time frame.                                    #
#                                                                            #
# BSD 3-Clause Clear License                                                 #
#                                                                            #
# Please see https://github.com/PacificBiosciences/pbbioconda for            #
# information on License, Copyright and Disclaimer                           #
#                                                                            #
##############################################################################

done
(/home/fc464/miniconda3) variantCaller --algorithm=arrow --diploid -o /rds/user/fc464/hpc-work/HeliconiiniProg/Djun.Assembly-36.41x-erate-0.045/DjunPacBio.contigs.Arrow.It.1.fasta -j 32 --referenceFilename /rds/user/fc464/hpc-work/HeliconiiniProg/Djun.Assembly-36.41x-erate-0.045/DjunPacBio.contigs.fasta --reportEffectiveCoverage /rds/user/fc464/hpc-work/HeliconiiniProg/Djun.Assembly-36.41x-erate-0.045/DjunPacBio.pbmm2.PacBio.sorted.bam
Arrow: unsupported chemistries found: (unknown)
Arrow: unsupported chemistries found: (unknown)
Traceback (most recent call last):
  File "/home/fc464/miniconda3/lib/python2.7/site-packages/pbcommand/cli/core.py", line 138, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/home/fc464/.local/lib/python2.7/site-packages/GenomicConsensus-2.3.2-py2.7.egg/GenomicConsensus/main.py", line 340, in args_runner
    return tr.main()
  File "/home/fc464/.local/lib/python2.7/site-packages/GenomicConsensus-2.3.2-py2.7.egg/GenomicConsensus/main.py", line 270, in main
    self._configureAlgorithm(options, peekFile)
  File "/home/fc464/.local/lib/python2.7/site-packages/GenomicConsensus-2.3.2-py2.7.egg/GenomicConsensus/main.py", line 164, in _configureAlgorithm
    self._algorithmConfiguration = self._algorithm.configure(options, alnFile)
  File "/home/fc464/.local/lib/python2.7/site-packages/GenomicConsensus-2.3.2-py2.7.egg/GenomicConsensus/arrow/arrow.py", line 236, in configure
    die("Arrow: unsupported chemistries found: ({0})".format(", ".join(sorted(unsupp))))
  File "/home/fc464/.local/lib/python2.7/site-packages/GenomicConsensus-2.3.2-py2.7.egg/GenomicConsensus/utils.py", line 16, in die
    raise DieException(msg)
DieException: Arrow: unsupported chemistries found: (unknown)
[ERROR] Arrow: unsupported chemistries found: (unknown)
Traceback (most recent call last):
  File "/home/fc464/miniconda3/lib/python2.7/site-packages/pbcommand/cli/core.py", line 138, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/home/fc464/.local/lib/python2.7/site-packages/GenomicConsensus-2.3.2-py2.7.egg/GenomicConsensus/main.py", line 340, in args_runner
    return tr.main()
  File "/home/fc464/.local/lib/python2.7/site-packages/GenomicConsensus-2.3.2-py2.7.egg/GenomicConsensus/main.py", line 270, in main
    self._configureAlgorithm(options, peekFile)
  File "/home/fc464/.local/lib/python2.7/site-packages/GenomicConsensus-2.3.2-py2.7.egg/GenomicConsensus/main.py", line 164, in _configureAlgorithm
    self._algorithmConfiguration = self._algorithm.configure(options, alnFile)
  File "/home/fc464/.local/lib/python2.7/site-packages/GenomicConsensus-2.3.2-py2.7.egg/GenomicConsensus/arrow/arrow.py", line 236, in configure
    die("Arrow: unsupported chemistries found: ({0})".format(", ".join(sorted(unsupp))))
  File "/home/fc464/.local/lib/python2.7/site-packages/GenomicConsensus-2.3.2-py2.7.egg/GenomicConsensus/utils.py", line 16, in die
    raise DieException(msg)
DieException: Arrow: unsupported chemistries found: (unknown)
```

**Comment by pb-dseifert** [comment]
Look at your import stack:
```
File "/home/fc464/miniconda3/lib/python2.7/site-packages/pbcommand/cli/core.py", line 138, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/home/fc464/.local/lib/python2.7/site-packages/GenomicConsensus-2.3.2-py2.7.egg/GenomicConsensus/main.py", line 340, in args_runner
    return tr.main()
```
The fact that you have a file

     File "/home/fc464/.local/lib/python2.7/site-packages/GenomicConsensus-2.3.2-py2.7.egg/GenomicConsensus/main.py"

in there is a strong indication that you tried to install GC in a user site-packages dir. See https://github.com/conda/conda/issues/448#issuecomment-54212275 for suggestions. In general I prefer the first point - user site-packages are brittle and tend to infest every invocation and import lookup order, which is why they should be avoided for venvs. The quickest hack you can try is: https://github.com/conda/conda/issues/448#issuecomment-195848539

    export PYTHONNOUSERSITE=True

**Comment by francicco** [comment]
I see the point. the local library was conflicting with conda. I removed it and it's now running. Thanks a lot!
F
