### ISSUE TITLE
Falcon unzip 0-phasing jobs failing at the last step

### ISSUE THREAD

**Issue by rob123king** [PacificBiosciences/pbbioconda#70]
I run unzip and creates the reads folder then the 0-phasing folder. But only one of the jobs completed. It seems to progress to the very last step for each job in 0-phasing. for instance 000045F creates the uow-00 folder and in the proto folder I have regions.json, preads.fasta, preads.sam, ref.fa link.

Seems to be failing here:
python -m falcon_unzip.proto.main_augment_pb     --wd ./proto/     --ctg-id 000045F     --p-ctg ${falcon_asm_dir}/p_ctg.fa     --p-ctg-tiling-path ${falcon_asm_dir}/p_ctg_tiling_path     --a-ctg ${falcon_asm_dir}/a_ctg.fa     --a-ctg-tiling-path ${falcon_asm_dir}/a_ctg_tiling_path     --p-variant-fn get_phased_blocks/phased_variants     --preads-sam proto/preads.sam     --extracted-ctg-fasta ${unzip_dir}/reads/000045F/ref.fa     --rawread-bam ${ctg_aln_out}     --rid-phase-map rid_to_phase.true     --out-updated-rid-phase_map rid_to_phase.tmp
mv rid_to_phase.tmp rid_to_phase

**Comment by rob123king** [comment]
I'll try it. Some jobs did complete, just the very small jobs that is but anything sizeable failed with this error. I tried rerunning with a lot of memory but didn't seem to help so hopefully updated bioconda version will work.

**Comment by rob123king** [comment]
Still failed even when reinstalled bioconda latest version.

**Comment by rob123king** [comment]
Might be a different issue now. Getting this error. 

`Node(3-unzip/0-phasing/000064F), Node(3-unzip/0-phasing/000005F), Node(3-unzip/0-phasing/phasing-chunks/000070F), Node(3-unzip/0-phasing/phasing-chunks/000083F), Node(3-unzip/0-phasing/phasing-chunks/000098F), Node(3-unzip/0-phasing/phasing-chunks/000026F), Node(3-unzip/0-phasing/phasing-chunks/000007F), Node(3-unzip/0-phasing/000049F), Node(3-unzip/0-phasing/phasing-chunks/000142F), Node(3-unzip/0-phasing/phasing-chunks/000108F), Node(3-unzip/0-phasing/phasing-chunks/000062F), Node(3-unzip/0-phasing/phasing-chunks/000003F), Node(3-unzip/0-phasing/phasing-chunks/000004F), Node(3-unzip/0-phasing/phasing-chunks/000130F), Node(3-unzip/0-phasing/phasing-chunks/000059F), Node(3-unzip/0-phasing/phasing-chunks/000101F), Node(3-unzip/0-phasing/000001F), Node(3-unzip/0-phasing/phasing-chunks/000105F), Node(3-unzip/0-phasing/000090F), Node(3-unzip/0-phasing/phasing-chunks/000085F), Node(3-unzip/0-phasing/phasing-chunks/000120F), Node(3-unzip/0-phasing/phasing-chunks/000137F), Node(3-unzip/0-phasing/phasing-chunks/000140F), Node(3-unzip/0-phasing/phasing-chunks/000012F), Node(3-unzip/0-phasing/phasing-chunks/000096F), Node(3-unzip/0-phasing/phasing-chunks/000076F), Node(3-unzip/0-phasing/phasing-chunks/000008F), Node(3-unzip/0-phasing/phasing-chunks/000020F), Node(3-unzip/0-phasing/000127F), Node(3-unzip/0-phasing/phasing-chunks/000114F), Node(3-unzip/0-phasing/phasing-chunks/000011F), Node(3-unzip/0-phasing/phasing-chunks/000099F), Node(3-unzip/0-phasing/phasing-chunks/000146F), Node(3-unzip/0-phasing/phasing-chunks/000122F), Node(3-unzip/0-phasing/phasing-chunks/000104F), Node(3-unzip/0-phasing/phasing-chunks/000117F), Node(3-unzip/0-phasing/phasing-chunks/000034F), Node(3-unzip/0-phasing/phasing-chunks/000023F), Node(3-unzip/0-phasing/phasing-chunks/000077F), Node(3-unzip/0-phasing/phasing-chunks/000086F), Node(3-unzip/0-phasing/phasing-chunks/000116F), Node(3-unzip/0-phasing/phasing-chunks/000057F), Node(3-unzip/0-phasing/phasing-chunks/000079F), Node(3-unzip/0-phasing/phasing-chunks/000084F), Node(3-unzip/0-phasing/phasing-chunks/000095F), Node(3-unzip/0-phasing/phasing-chunks/000037F), Node(3-unzip/0-phasing/phasing-chunks/000123F)])
        submitted: set([Node(3-unzip/0-phasing/000073F), Node(3-unzip/0-phasing/000075F), Node(3-unzip/0-phasing/000002F)])
[ERROR]Noop. We cannot kill blocked threads. Hopefully, everything will die on SIGTERM.
Traceback (most recent call last):
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/bin/fc_unzip.py", line 11, in <module>
    load_entry_point('falcon-unzip==1.1.5', 'console_scripts', 'fc_unzip.py')()
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/site-packages/falcon_unzip/mains/start_unzip.py", line 29, in main
    unzip.run(**vars(args))
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/site-packages/falcon_unzip/unzip.py", line 184, in run
    unzip_all(config, unzip_config_fn)
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/site-packages/falcon_unzip/unzip.py", line 29, in unzip_all
    tasks_unzip.run_workflow(wf, config, unzip_config_fn, rule_writer)
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/site-packages/falcon_unzip/tasks/unzip.py", line 459, in run_workflow
    dist=Dist(NPROC=24, job_dict=config['job.step.unzip.blasr_aln']),
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/site-packages/falcon_kit/pype.py", line 194, in gen_parallel_tasks
    wf.refreshTargets()
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 278, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 362, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: set([Node(3-unzip/0-phasing/000131F)])
(denovo_asm3) bash-4.1$ ls ./3-unzip/0-phasing/**/*done
./3-unzip/0-phasing/000075F/run.sh.done  ./3-unzip/0-phasing/000144F/run.sh.done  ./3-unzip/0-phasing/phasing-split/run.sh.done
`

I rerun one run.sh job to see if progresses but gives error below
Traceback (most recent call last):
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/site-packages/falcon_unzip/proto/main_augment_pb.py", line 635, in <module>
    main()
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/site-packages/falcon_unzip/proto/main_augment_pb.py", line 632, in main
    run(**vars(args))
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/site-packages/falcon_unzip/proto/main_augment_pb.py", line 517, in run
    updated_rid2phase, phase_relation_graph, htig_to_phase = create_new_rid2phase(ctg_id, rid2phase, all_regions, m4, a_paths)
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/site-packages/falcon_unzip/proto/main_augment_pb.py", line 94, in create_new_rid2phase
    found_regions = tree.search(reference_start, reference_end)
AttributeError: 'IntervalTree' object has no attribute 'search'
WARNING:root:Call '/bin/bash user_script.sh' returned 256.
WARNING:root:CD: 'uow-00' -> '/home/data/pest_genomics/Spodoptera_exigua/Falcon/sp2/3-unzip/0-phasing/000131F'
Traceback (most recent call last):
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/site-packages/falcon_kit/mains/generic_run_units_of_work.py", line 116, in <module>
    main()
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/site-packages/falcon_kit/mains/generic_run_units_of_work.py", line 112, in main
    run(**vars(args))
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/site-packages/falcon_kit/mains/generic_run_units_of_work.py", line 65, in run
    pypeflow.do_task.run_bash(script, inputs, outputs, params)
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/site-packages/pypeflow/do_task.py", line 187, in run_bash
    util.system(cmd)
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/site-packages/pypeflow/io.py", line 29, in syscall
    raise Exception(msg)
Exception: Call '/bin/bash user_script.sh' returned 256.
2019-01-16 18:48:46,966 - root - WARNING - Call '/bin/bash user_script.sh' returned 256.
2019-01-16 18:48:46,967 - root - WARNING - CD: '/home/data/pest_genomics/Spodoptera_exigua/Falcon/sp2/3-unzip/0-phasing/000131F' -> '/home/data/pest_genomics/Spodoptera_exigua/Falcon/sp2/3-unzip/0-phasing/000131F'
2019-01-16 18:48:46,968 - root - WARNING - CD: '/home/data/pest_genomics/Spodoptera_exigua/Falcon/sp2/3-unzip/0-phasing/000131F' -> '/home/data/pest_genomics/Spodoptera_exigua/Falcon/sp2/3-unzip/0-phasing/000131F'
2019-01-16 18:48:46,970 - root - CRITICAL - Error in /home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/site-packages/pypeflow/do_task.py with args="{'json_fn': '/home/data/pest_genomics/Spodoptera_exigua/Falcon/sp2/3-unzip/0-phasing/000131F/task.json',\n 'timeout': 30,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/site-packages/pypeflow/do_task.py", line 267, in <module>
    main()
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/site-packages/pypeflow/do_task.py", line 259, in main
    run(**vars(parsed_args))
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/site-packages/pypeflow/do_task.py", line 253, in run
    run_cfg_in_tmpdir(cfg, tmpdir, '.')
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/site-packages/pypeflow/do_task.py", line 228, in run_cfg_in_tmpdir
    run_bash(bash_template, myinputs, myoutputs, parameters)
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/site-packages/pypeflow/do_task.py", line 187, in run_bash
    util.system(cmd)
  File "/home/data/bioinf_resources/programming_tools/miniconda3/envs/denovo_asm3/lib/python2.7/site-packages/pypeflow/io.py", line 29, in syscall
    raise Exception(msg)
Exception: Call '/bin/bash user_script.sh' returned 256.
+++ pwd
++ echo 'FAILURE. Running top in /home/data/pest_genomics/Spodoptera_exigua/Falcon/sp2/3-unzip/0-phasing/000131F (If you see -terminal database is inaccessible- you are using the python bin-wrapper, so you will not get diagnostic info. No big deal. This process is crashing anyway.)'
++ rm -f top.txt
++ which python
++ which top
++ env -u LD_LIBRARY_PATH top -b -n 1
++ env -u LD_LIBRARY_PATH top -b -n 1
++ pstree -apl

real	4m22.817s
user	3m24.654s
sys	0m22.643s
+ finish
+ echo 'finish code: 1'


I keep tweaking my config hoping it will go through but no joy
#### Input
[General]
max_n_open_files = 300

[Unzip]
input_fofn=input.fofn
input_bam_fofn=input_bam.fofn

[job.defaults]
job_type=local
pwatcher_type=blocking
#job_queue=bash -C ${CMD}
#use_tmpdir = true
MB=64384
NPROC=6
njobs=8
submit=bash -C ${CMD} >| ${STDOUT_FILE} 2>| ${STDERR_FILE}

[job.step.unzip.track_reads]
njobs=4
NPROC=4
MB=79216
# uses minimap2 now
[job.step.unzip.blasr_aln]
njobs=4
NPROC=4
MB=62384
[job.step.unzip.phasing]
njobs=4
NPROC=4
MB=62384
[job.step.unzip.hasm]
njobs=4
NPROC=4
MB=62384
# uses arrow now
[job.step.unzip.quiver]
njobs=2
NPROC=12
MB=98304

**Comment by rob123king** [comment]
What annoys me is it does work for one or two 
@isovic as you say lloks like intervaltree change but why would some work and other people should be seeing it with this bioconda installation..
https://github.com/Gallopsled/pwntools/issues/1238

**Comment by rob123king** [comment]
pip show intervaltree | grep Version
Version: 3.0.2
License: Apache License, Version 2.0

**Comment by rob123king** [comment]
new issue at quiver stage that I will post elsewhere

**Comment by pb-cdunn** [comment]
The IntervalTree problem should be solved in the latest release. `conda update --all`.
