### ISSUE TITLE
4-polish/merge-reads fails with ValueError: 10569389 exceeds max_map_len(1048576)

### ISSUE THREAD

**Issue by mp15** [PacificBiosciences/pbbioconda#74]
**Operating system**
RHEL 7.4

**Package name**
falcon-unzip 1.1.5
falcon-kit 1.2.5
pypeflow 2.1.1

**Conda environment**
```
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py27_3    conda-forge
avro                      1.8.2             h05e4be9_1000    conda-forge
avro-python2              1.8.2                      py_1    bioconda
bcftools                  1.9                  h4da6232_0    bioconda
bedtools                  2.27.1               he941832_2    bioconda
blas                      1.0                         mkl  
blasr                     5.3.2                hac9d22c_3    bioconda
blasr_libcpp              5.3.1                hac9d22c_2    bioconda
bwa                       0.7.17               ha92aebf_3    bioconda
bzip2                     1.0.6                h470a237_2    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
certifi                   2018.11.29            py27_1000    conda-forge
cffi                      1.11.5           py27h5e8e0c9_1    conda-forge
chardet                   3.0.4                    py27_3    conda-forge
conda                     4.5.12                py27_1000    conda-forge
conda-env                 2.6.0                         1  
cryptography              2.3.1            py27hdffb7b8_0    conda-forge
cryptography-vectors      2.3.1                    py27_0    conda-forge
curl                      7.61.0               h93b3f91_2    conda-forge
cython                    0.28.5           py27hfc679d8_0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
enum34                    1.1.6                 py27_1001    conda-forge
future                    0.16.0                   py27_2    conda-forge
futures                   3.2.0                 py27_1000    conda-forge
genomicconsensus          2.3.2                    py27_1    bioconda
h5py                      2.8.0           py27h3010b51_1003    conda-forge
hdf5                      1.10.2               hc401514_2    conda-forge
htslib                    1.7                           0    bioconda
idna                      2.7                      py27_2    conda-forge
intel-openmp              2019.0                      118  
ipaddress                 1.0.22                     py_1    conda-forge
iso8601                   0.1.12                     py_1    conda-forge
jansson                   2.11              h14c3975_1001    conda-forge
krb5                      1.14.6                        0    conda-forge
libdeflate                1.0                  h470a237_0    bioconda
libedit                   3.1.20170329         h6b74fdf_2  
libffi                    3.2.1                hd88cf55_4  
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libssh2                   1.8.0                h5b517e9_2    conda-forge
libstdcxx-ng              8.2.0                hdf63c60_1  
linecache2                1.0.0                    py27_0    conda-forge
minimap2                  2.12                 ha92aebf_0    bioconda
mkl                       2019.0                      118  
mkl_fft                   1.0.6                    py27_0    conda-forge
mkl_random                1.0.1                    py27_0    conda-forge
mummer4                   4.0.0beta2      pl526hfc679d8_3    bioconda
ncurses                   6.1                  hf484d3e_0  
networkx                  2.2                        py_1    conda-forge
nim-falcon                0.0.0                         0    bioconda
numpy                     1.14.2           py27hdbf6ddf_0  
numpy-base                1.15.2           py27h81de0dd_0  
openssl                   1.0.2p            h14c3975_1002    conda-forge
pb-assembly               0.0.3                    py27_1    bioconda
pb-dazzler                0.0.0                h470a237_0    bioconda
pb-falcon                 0.2.5            py27ha92aebf_1    bioconda
pbalign                   0.3.1                    py27_0    bioconda
pbbam                     0.18.0               h1310cd9_1    bioconda
pbcommand                 1.1.1            py27h24bf2e0_1    bioconda
pbcopper                  0.4.2                h02d93b8_0    bioconda
pbcore                    1.5.1                    py27_1    bioconda
pbmm2                     0.8.1                ha87ae23_0    bioconda
perl                      5.26.2               h470a237_0    conda-forge
pip                       18.0                     py27_1    conda-forge
pycosat                   0.6.3            py27h470a237_1    conda-forge
pycparser                 2.19                       py_0    conda-forge
pyopenssl                 18.0.0                   py27_0    conda-forge
pysam                     0.14.1           py27hae42fb6_1    bioconda
pysocks                   1.6.8                    py27_2    conda-forge
python                    2.7.15               h9fef7bc_0    conda-forge
python-consensuscore      1.1.1            py27h02d93b8_1    bioconda
python-consensuscore2     3.1.0                    py27_1    bioconda
python-edlib              1.2.3            py27h470a237_1    bioconda
python-intervaltree       2.1.0                      py_0    bioconda
python-msgpack            0.5.6            py27h470a237_0    bioconda
python-sortedcontainers   2.0.4                      py_0    bioconda
pytz                      2018.5                     py_0    conda-forge
readline                  7.0                  h7b6447c_5  
requests                  2.19.1                   py27_1    conda-forge
ruamel_yaml               0.15.63          py27h470a237_0    conda-forge
samtools                  1.9                  h8ee4bcc_1    bioconda
setuptools                40.4.0                py27_1000    conda-forge
six                       1.11.0                   py27_1    conda-forge
snappy                    1.1.7             hf484d3e_1002    conda-forge
sqlite                    3.24.0               h84994c4_0  
tk                        8.6.8                hbc83047_0  
traceback2                1.4.0                    py27_0    conda-forge
unittest2                 1.1.0                      py_0    conda-forge
urllib3                   1.23                     py27_1    conda-forge
wheel                     0.31.1                py27_1001    conda-forge
xz                        5.2.4                h14c3975_4  
yaml                      0.1.7                had09818_2  
zlib                      1.2.11               ha838bed_2  
```

**Describe the bug**
FALCON unzip schedules a job to perform the merge_reads step which fails with the error message below.

**Error message**
```
[INFO 2019-01-18 13:23:19,715]"SAM files will go into '/lustre/scratch106/team149/data/pacbio/draft4h_falcon/4-polish/merge-reads'"
Traceback (most recent call last):
  File "/software/team149/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/software/team149/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/software/team149/lib/python2.7/site-packages/falcon_unzip/mains/bam_partition_and_merge.py", line 281, in <module>
    main()
  File "/software/team149/lib/python2.7/site-packages/falcon_unzip/mains/bam_partition_and_merge.py", line 277, in main
    run(**vars(args))
  File "/software/team149/lib/python2.7/site-packages/falcon_unzip/mains/bam_partition_and_merge.py", line 222, in run
    read2ctg = deserialize(read2ctg_fn)
  File "/software/team149/lib/python2.7/site-packages/falcon_kit/io.py", line 142, in deserialize
    val = read_as_msgpack(ifs)
  File "/software/team149/lib/python2.7/site-packages/falcon_kit/io.py", line 112, in read_as_msgpack
    max_array_len=2**20,
  File "msgpack/_unpacker.pyx", line 200, in msgpack._unpacker.unpackb
ValueError: 10569389 exceeds max_map_len(1048576)
```

**To Reproduce**
Run FALCON unzip on my dataset

**Expected behavior**
I expected it to proceed without error

**Comment by mp15** [comment]
This seems to be down to me having too much data? Looking at ```4-polish/select-reads/read2ctg.msgpack.json``` there is 10569389 entries in this file, and I assume the same number in ```4-polish/select-reads/read2ctg.msgpack```? I could increase ```max_map_len``` in ```/software/team149/lib/python2.7/site-packages/falcon_unzip/mains/bam_partition_and_merge.py", line 222``` but I have no idea what the consequences of this will be nor why this limit was put in place.

**Comment by mp15** [comment]
Thank you, this got me past that point.

**Comment by mcshane** [comment]
Just to chime in, I ran into this too and have applied the same patch.

**Comment by mcshane** [comment]
Am already using msgpack 0.5.6 (as was @mp15 according to his conda environment above).
