### ISSUE TITLE
IntervalTree object has no attribute 'search

### ISSUE THREAD

**Issue by Lcornet** [PacificBiosciences/pbbioconda#86]
Dear Falcon team,

I have the following error while running unzip.py : 
AttributeError: 'IntervalTree' object has no attribute 'search'
WARNING:root:Call '/bin/bash user_script.sh' returned 256.
WARNING:root:CD: 'uow-00' -> '/media/vol2/scratch/lcornet/cassava/falcon-test/3-unzip/0-phasing/001666F'
Traceback (most recent call last):
  File "/media/vol2/home/lcornet/anaconda2/envs/denovo_asm/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/media/vol2/home/lcornet/anaconda2/envs/denovo_asm/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/media/vol2/home/lcornet/anaconda2/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/mains/generic_run_units_of_work.py", line 11
6, in <module>
    main()
  File "/media/vol2/home/lcornet/anaconda2/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/mains/generic_run_units_of_work.py", line 11
2, in main
    run(**vars(args))
  File "/media/vol2/home/lcornet/anaconda2/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/mains/generic_run_units_of_work.py", line 65
, in run
    pypeflow.do_task.run_bash(script, inputs, outputs, params)
  File "/media/vol2/home/lcornet/anaconda2/envs/denovo_asm/lib/python2.7/site-packages/pypeflow/do_task.py", line 187, in run_bash
    util.system(cmd)
  File "/media/vol2/home/lcornet/anaconda2/envs/denovo_asm/lib/python2.7/site-packages/pypeflow/io.py", line 29, in syscall
    raise Exception(msg)
Exception: Call '/bin/bash user_script.sh' returned 256.

i tried to install Intervaltree with pip wihout success , could you help me ?

**Comment by Lcornet** [comment]
Ok, thanks Ivan.

Could you point me to a specific version ?

Luc,

**Comment by isovic** [comment]
Sure, can you test out version 2.1.0?

Best regards,
Ivan.

**Comment by Lcornet** [comment]
i already try : 
pip install intervaltree==2.1.0
I can downgrade, but it will give the same result, no ?

**Comment by isovic** [comment]
Strange, perhaps it's picking up the `intervaltree` package from a different location?
Did you have the conda environment activated before you installed this version of `intervaltree`?

According to the docs, this version should contain the search function:
https://pypi.org/project/intervaltree/2.1.0/

Ivan

**Comment by Lcornet** [comment]
pip install intervaltree==2.1.0 wthin conda fix it,

Thanks

**Comment by pb-cdunn** [comment]
The latest pb-falcon/pb-assembly should also take care of this now. `conda update --all`
