### ISSUE TITLE
DBdustb usage error

### ISSUE THREAD

**Issue by nat2bee** [PacificBiosciences/pbbioconda#87]
**Operating system**
cluster (3.10.0-862.2.3.el7.x86_64 GNU/Linux), with slurm

**Package name**
- falcon-kit 1.2.5 
- pypeflow 2.1.1
I'm running FALCON for the assembly and this is the latest version I could get though conda install

**Conda environment**
```
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                py27_1003    conda-forge
avro-python2              1.8.2                      py_1    bioconda
bcftools                  1.9                  h47928c2_1    bioconda
bedtools                  2.27.1               he860b03_3    bioconda
blas                      1.0                         mkl  
blasr                     5.3.2                h82bacf8_5    bioconda
blasr_libcpp              5.3.1                h82bacf8_4    bioconda
bwa                       0.7.17               h84994c4_4    bioconda
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
certifi                   2018.11.29            py27_1000    conda-forge
cffi                      1.11.5          py27h9745a5d_1001    conda-forge
chardet                   3.0.4                 py27_1003    conda-forge
cryptography              2.5              py27hb7f436b_0    conda-forge
curl                      7.64.0               h646f8bb_0    conda-forge
cython                    0.29.4           py27hf484d3e_0    conda-forge
decorator                 4.3.2                      py_0    conda-forge
enum34                    1.1.6                 py27_1001    conda-forge
future                    0.17.1                py27_1000    conda-forge
genomicconsensus          2.3.2                    py27_3    bioconda
h5py                      2.8.0           py27hfb8609e_1004    conda-forge
hdf5                      1.10.3            hba1933b_1001    conda-forge
htslib                    1.9                  h47928c2_5    bioconda
idna                      2.8                   py27_1000    conda-forge
intel-openmp              2019.1                      144  
ipaddress                 1.0.22                     py_1    conda-forge
iso8601                   0.1.12                     py_1    conda-forge
krb5                      1.16.3            hc83ff2d_1000    conda-forge
libcurl                   7.64.0               h01ee5af_0    conda-forge
libdeflate                1.0                  h14c3975_1    bioconda
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             hf484d3e_1005    conda-forge
libgcc-ng                 7.3.0                hdf63c60_0    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libssh2                   1.8.0             h1ad7b7a_1003    conda-forge
libstdcxx-ng              7.3.0                hdf63c60_0    conda-forge
linecache2                1.0.0                      py_1    conda-forge
minimap2                  2.15                 ha92aebf_0    bioconda
mkl                       2019.1                      144  
mkl_fft                   1.0.10           py27h14c3975_1    conda-forge
mkl_random                1.0.2            py27h637b7d7_2    conda-forge
mummer4                   4.0.0beta2      pl526hfc679d8_3    bioconda
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.2                        py_1    conda-forge
nim-falcon                0.0.0                         0    bioconda
numpy                     1.15.4           py27h7e9f1db_0  
numpy-base                1.15.4           py27hde5b4d6_0  
openssl                   1.0.2p            h14c3975_1002    conda-forge
pb-assembly               0.0.4                    py27_3    bioconda
pb-dazzler                0.0.0                h470a237_0    bioconda
pb-falcon                 0.2.5            py27hc0aa232_3    bioconda
pbalign                   0.3.2                    py27_0    bioconda
pbbam                     0.19.0               h6678c95_1    bioconda
pbcommand                 1.1.1                    py27_2    bioconda
pbcopper                  0.4.2                h02d93b8_0    bioconda
pbcore                    1.6.5                    py27_0    bioconda
pbmm2                     0.12.0               ha87ae23_0    bioconda
perl                      5.26.2            h14c3975_1001    conda-forge
pip                       19.0.1                   py27_0    conda-forge
pycparser                 2.19                       py_0    conda-forge
pyopenssl                 19.0.0                   py27_0    conda-forge
pysam                     0.15.2           py27h1671916_1    bioconda
pysocks                   1.6.8                 py27_1002    conda-forge
python                    2.7.15            h938d71a_1006    conda-forge
python-consensuscore      1.1.1            py27h02d93b8_2    bioconda
python-consensuscore2     3.1.0                    py27_2    bioconda
python-edlib              1.2.3.post1      py27h470a237_0    bioconda
python-intervaltree       3.0.2                      py_0    bioconda
python-msgpack            0.5.6            py27h470a237_0    bioconda
python-sortedcontainers   2.1.0                      py_0    bioconda
pytz                      2018.9                     py_0    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
requests                  2.21.0                py27_1000    conda-forge
samtools                  1.9                  h57cc563_6    bioconda
setuptools                40.7.3                   py27_0    conda-forge
six                       1.12.0                py27_1000    conda-forge
sqlite                    3.26.0            h67949de_1000    conda-forge
tk                        8.6.9             h84994c4_1000    conda-forge
traceback2                1.4.0                    py27_0    conda-forge
unittest2                 1.1.0                      py_0    conda-forge
urllib3                   1.24.1                py27_1000    conda-forge
wheel                     0.32.3                   py27_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
```

**Describe the bug**
Assembly fails.

**Error message**
```
executable=${PYPEFLOW_JOB_START_SCRIPT}
+ executable=/cephfs/scratch/7077691/Teste_Novo_Cluster/FALCON_test/0-rawreads/build/run-Pb028d7db7fe754.bash
timeout=${PYPEFLOW_JOB_START_TIMEOUT:-60} # wait 60s by default
+ timeout=60

# Wait up to timeout seconds for the executable to become "executable",
# then exec.
#timeleft = int(timeout)
while [[ ! -x "${executable}" ]]; do
    if [[ "${timeout}" == "0" ]]; then
        echo "timed out waiting for (${executable})"
        exit 77
    fi
    echo "not executable: '${executable}', waiting ${timeout}s"
    sleep 1
    timeout=$((timeout-1))
done
+ [[ ! -x /cephfs/scratch/7077691/Teste_Novo_Cluster/FALCON_test/0-rawreads/build/run-Pb028d7db7fe754.bash ]]

/bin/bash ${executable}
+ /bin/bash /cephfs/scratch/7077691/Teste_Novo_Cluster/FALCON_test/0-rawreads/build/run-Pb028d7db7fe754.bash
+ '[' '!' -d /cephfs/scratch/7077691/Teste_Novo_Cluster/FALCON_test/0-rawreads/build ']'
+ cd /cephfs/scratch/7077691/Teste_Novo_Cluster/FALCON_test/0-rawreads/build
+ eval '/bin/bash run.sh'
++ /bin/bash run.sh
export PATH=$PATH:/bin
+ export PATH=/scratch/7077691/.conda/envs/denovo_asm/bin:/apps/gnu/Anaconda3-5.2.0-Linux-x86_64/bin:/opt/ohpc/pub/mpi/openmpi-gnu/1.10.7/bin:/opt/ohpc/pub/compiler/gcc/5.4.0/bin:/opt/ohpc/pub/utils/prun/1.2:/opt/ohpc/pub/utils/autotools/bin:/opt/ohpc/pub/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/pbs/bin:/scratch/7077691/.local/bin:/scratch/7077691/bin:/bin
+ PATH=/scratch/7077691/.conda/envs/denovo_asm/bin:/apps/gnu/Anaconda3-5.2.0-Linux-x86_64/bin:/opt/ohpc/pub/mpi/openmpi-gnu/1.10.7/bin:/opt/ohpc/pub/compiler/gcc/5.4.0/bin:/opt/ohpc/pub/utils/prun/1.2:/opt/ohpc/pub/utils/autotools/bin:/opt/ohpc/pub/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/pbs/bin:/scratch/7077691/.local/bin:/scratch/7077691/bin:/bin
cd /cephfs/scratch/7077691/Teste_Novo_Cluster/FALCON_test/0-rawreads/build
+ cd /cephfs/scratch/7077691/Teste_Novo_Cluster/FALCON_test/0-rawreads/build
/bin/bash task.sh
+ /bin/bash task.sh
pypeflow 2.1.1
2019-02-07 12:10:43,763 - root - DEBUG - Running "/cephfs/scratch/7077691/.conda/envs/denovo_asm/lib/python2.7/site-packages/pypeflow/do_task.py /cephfs/scratch/7077691/Teste_Novo_Cluster/FALCON_test/0-rawreads/build/task.json"
2019-02-07 12:10:44,148 - root - DEBUG - Checking existence of '/cephfs/scratch/7077691/Teste_Novo_Cluster/FALCON_test/0-rawreads/build/task.json' with timeout=30
2019-02-07 12:10:44,148 - root - DEBUG - Loading JSON from '/cephfs/scratch/7077691/Teste_Novo_Cluster/FALCON_test/0-rawreads/build/task.json'
2019-02-07 12:10:44,150 - root - DEBUG - {u'bash_template_fn': u'template.sh',
 u'inputs': {u'config': u'../../General_config.json',
             u'input_fofn': u'../../../../../../../scratch/7077691/Teste_Novo_Cluster/FALCON_test/input.fofn'},
 u'outputs': {u'db': u'raw_reads.db', u'length_cutoff': u'length_cutoff'},
 u'parameters': {u'pypeflow_mb': 4000,
                 u'pypeflow_nproc': 1,
                 u'topdir': u'../..'}}
2019-02-07 12:10:44,150 - root - WARNING - CD: '/cephfs/scratch/7077691/Teste_Novo_Cluster/FALCON_test/0-rawreads/build' <- '/cephfs/scratch/7077691/Teste_Novo_Cluster/FALCON_test/0-rawreads/build'
2019-02-07 12:10:44,150 - root - DEBUG - Checking existence of u'../../../../../../../scratch/7077691/Teste_Novo_Cluster/FALCON_test/input.fofn' with timeout=30
2019-02-07 12:10:44,243 - root - DEBUG - Checking existence of u'../../General_config.json' with timeout=30
2019-02-07 12:10:44,307 - root - DEBUG - Checking existence of u'template.sh' with timeout=30
2019-02-07 12:10:44,308 - root - WARNING - CD: '/cephfs/scratch/7077691/Teste_Novo_Cluster/FALCON_test/0-rawreads/build' <- '/cephfs/scratch/7077691/Teste_Novo_Cluster/FALCON_test/0-rawreads/build'
2019-02-07 12:10:44,469 - root - INFO - $('/bin/bash user_script.sh')
hostname
+ hostname
pwd
+ pwd
date
+ date
# Substitution will be similar to snakemake "shell".
python -m falcon_kit.mains.dazzler --config-fn=../../General_config.json --db-fn=raw_reads.db  build --input-fofn-fn=../../../../../../../scratch/7077691/Teste_Novo_Cluster/FALCON_test/input.fofn --length-cutoff-fn=length_cutoff
+ python -m falcon_kit.mains.dazzler --config-fn=../../General_config.json --db-fn=raw_reads.db build --input-fofn-fn=../../../../../../../scratch/7077691/Teste_Novo_Cluster/FALCON_test/input.fofn --length-cutoff-fn=length_cutoff
falcon-kit 1.2.5
pypeflow 2.1.1
[INFO]Log-level: INFO
[INFO]config('../../General_config.json'):
{u'falcon_sense_greedy': False, u'pa_fasta_filter_option': u'streamed-median', u'seed_coverage': u'30', u'overlap_filtering_setting': u'--max-diff 100 --max-cov 100 --min-cov 2', u'length_cutoff_pr': u'1000', u'pa_REPmask_code': u'0,300;0,300;0,300', u'pa_HPCdaligner_option': u'-v -B128 -M24', u'ver': u'100', u'bestn': 12, u'pa_HPCTANmask_option': u'', u'input_type': u'raw', u'pa_DBsplit_option': u'-x500 -s50', u'fc_ovlp_to_graph_option': u' --min-len 1000', u'input_fofn': u'/scratch/7077691/Teste_Novo_Cluster/FALCON_test/input.fofn', u'genome_size': u'0', u'avoid_text_file_busy': True, u'pa_dazcon_option': u'-j 4 -x -l 500', u'ovlp_DBdust_option': u'', u'skip_checks': False, u'ovlp_daligner_option': u'-e.9 -l2500 -k24 -h1024 -w6 -s100', u'target': u'assembly', u'falcon_sense_skip_contained': False, u'pa_daligner_option': u'-e.8 -l2000 -k18 -h480 -w8 -s100', u'length_cutoff': u'1000', u'pa_DBdust_option': u'true', u'ovlp_HPCdaligner_option': u'-v -B128 -M24', u'LA4Falcon_preload': False, u'dazcon': False, u'falcon_sense_option': u'--output-multi --min-idt 0.70 --min-cov 3 --max-n-read 400', u'ovlp_DBsplit_option': u'-x500 -s50'}
[INFO]our subset of config:
{'daligner_opt': u'-e.8 -l2000 -k18 -h480 -w8 -s100 -v -B128 -M24', 'genome_size': 0, 'TANmask_opt': u'-e.8 -l2000 -k18 -h480 -w8 -s100 ', 'DBdust_opt': u'true', 'seed_coverage': 30.0, 'user_length_cutoff': 1000, 'fasta_filter_option': u'streamed-median', 'REPmask_opt': u'-e.8 -l2000 -k18 -h480 -w8 -s100 ', 'DBsplit_opt': u'-x500 -s50'}
[INFO]Building rdb from '../../../../../../../scratch/7077691/Teste_Novo_Cluster/FALCON_test/input.fofn', to write 'raw_reads.db'
[INFO]$('bash -vex build_db.sh')
module () {  eval $($LMOD_CMD bash "$@") && eval $(${LMOD_SETTARG_CMD:-:} -s sh)
}
ml () {  eval $($LMOD_DIR/ml_cmd "$@")
}
#!/bin/bash
# -*- shell-script -*-
#
########################################################################
# Start Lmod BASHENV
########################################################################

# Remember the XTRACE and VERBOSE states so that they are restored
# at the end of this script.
[[ ${-/x} != $- ]] && XTRACE_STATE="-x"  || XTRACE_STATE="+x"
+ [[ hvB != hvxB ]]
+ XTRACE_STATE=-x
[[ ${-/v} != $- ]] && VERBOSE_STATE="-v" || VERBOSE_STATE="+v"
+ [[ hxB != hvxB ]]
+ VERBOSE_STATE=-v
set +xv     # Turn off tracing for now.
+ set +xv
unset XTRACE_STATE  VERBOSE_STATE
+ unset XTRACE_STATE VERBOSE_STATE

########################################################################
# End Lmod BASHENV
########################################################################
#
# Local Variables:
# mode: shell-script
# indent-tabs-mode: nil
# End:
#!/bin/bash
set -vex
+ set -vex
echo "PBFALCON_ERRFILE=$PBFALCON_ERRFILE"
+ echo PBFALCON_ERRFILE=
set -o pipefail
+ set -o pipefail
rm -f raw_reads.db .raw_reads.* # in case of re-run
+ rm -f raw_reads.db '.raw_reads.*'
#fc_fasta2fasta < my.input.fofn >| fc.fofn
while read fn; do  cat  ${fn} | python -m falcon_kit.mains.fasta_filter streamed-median - | fasta2DB -v raw_reads -i${fn##*/}; done < my.input.fofn
+ read fn
+ fasta2DB -v raw_reads -iMbi_all_pacbio.fasta
+ python -m falcon_kit.mains.fasta_filter streamed-median -
+ cat /scratch/7077691/Teste_Novo_Cluster/Mbi_all_pacbio.fasta
falcon-kit 1.2.5
pypeflow 2.1.1
INFO:root:Counting bytes from "None"
INFO:root:        #1 count=          4,925 
INFO:root:        #2 count=         30,153 
Adding 'Mbi_all_pacbio.fasta.fasta' ...
INFO:root:        #3 count=         58,828 
INFO:root:        #6 count=        134,264 
INFO:root:       #23 count=        240,172 
INFO:root:       #50 count=        444,055 
INFO:root:       #90 count=        852,790 
INFO:root:      #176 count=      1,664,683 
INFO:root:      #349 count=      3,282,472 
INFO:root:      #706 count=      6,515,672 
INFO:root:    #1,384 count=     12,984,066 
INFO:root:    #2,805 count=     25,903,448 
INFO:root:    #5,668 count=     51,751,504 
INFO:root:   #11,472 count=    103,424,226 
INFO:root:   #23,339 count=    206,769,381 
INFO:root:   #47,932 count=    413,457,506 
INFO:root:   #98,054 count=    826,796,745 
INFO:root:  #199,366 count=  1,653,472,757 
INFO:root:  #404,933 count=  3,306,844,426 
INFO:root:  #803,657 count=  6,613,531,648 
INFO:root:#1,612,062 count= 13,226,917,959 
+ read fn
#cat fc.fofn | xargs rm -f
DBdust true raw_reads
+ DBdust true raw_reads
Usage: DBdust [-b] [-w<int(64)>] [-t<double(2.)>] [-m<int(10)>] <path:db|dam>

      -w: DUST algorithm window size.
      -t: DUST algorithm threshold.
      -m: Record only low-complexity intervals >= this size.
      -b: Take into account base composition bias.
[WARNING]Call 'bash -vex build_db.sh' returned 256.
Traceback (most recent call last):
  File "/scratch/7077691/.conda/envs/denovo_asm/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/scratch/7077691/.conda/envs/denovo_asm/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/cephfs/scratch/7077691/.conda/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/mains/dazzler.py", line 1373, in <module>
    main()
  File "/cephfs/scratch/7077691/.conda/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/mains/dazzler.py", line 1369, in main
    args.func(args)
  File "/cephfs/scratch/7077691/.conda/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/mains/dazzler.py", line 932, in cmd_build
    build_db(ours, args.input_fofn_fn, args.db_fn, args.length_cutoff_fn)
  File "/cephfs/scratch/7077691/.conda/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/mains/dazzler.py", line 147, in build_db
    io.syscall('bash -vex {}'.format(script_fn))
  File "/scratch/7077691/.conda/envs/denovo_asm/lib/python2.7/site-packages/pypeflow/io.py", line 29, in syscall
    raise Exception(msg)
Exception: Call 'bash -vex build_db.sh' returned 256.
2019-02-07 12:22:11,076 - root - WARNING - Call '/bin/bash user_script.sh' returned 256.
2019-02-07 12:22:11,076 - root - WARNING - CD: '/cephfs/scratch/7077691/Teste_Novo_Cluster/FALCON_test/0-rawreads/build' -> '/cephfs/scratch/7077691/Teste_Novo_Cluster/FALCON_test/0-rawreads/build'
2019-02-07 12:22:11,077 - root - WARNING - CD: '/cephfs/scratch/7077691/Teste_Novo_Cluster/FALCON_test/0-rawreads/build' -> '/cephfs/scratch/7077691/Teste_Novo_Cluster/FALCON_test/0-rawreads/build'
2019-02-07 12:22:11,077 - root - CRITICAL - Error in /cephfs/scratch/7077691/.conda/envs/denovo_asm/lib/python2.7/site-packages/pypeflow/do_task.py with args="{'json_fn': '/cephfs/scratch/7077691/Teste_Novo_Cluster/FALCON_test/0-rawreads/build/task.json',\n 'timeout': 30,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/scratch/7077691/.conda/envs/denovo_asm/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/scratch/7077691/.conda/envs/denovo_asm/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/cephfs/scratch/7077691/.conda/envs/denovo_asm/lib/python2.7/site-packages/pypeflow/do_task.py", line 267, in <module>
    main()
  File "/cephfs/scratch/7077691/.conda/envs/denovo_asm/lib/python2.7/site-packages/pypeflow/do_task.py", line 259, in main
    run(**vars(parsed_args))
  File "/cephfs/scratch/7077691/.conda/envs/denovo_asm/lib/python2.7/site-packages/pypeflow/do_task.py", line 253, in run
    run_cfg_in_tmpdir(cfg, tmpdir, '.')
  File "/cephfs/scratch/7077691/.conda/envs/denovo_asm/lib/python2.7/site-packages/pypeflow/do_task.py", line 228, in run_cfg_in_tmpdir
    run_bash(bash_template, myinputs, myoutputs, parameters)
  File "/cephfs/scratch/7077691/.conda/envs/denovo_asm/lib/python2.7/site-packages/pypeflow/do_task.py", line 187, in run_bash
    util.system(cmd)
  File "/scratch/7077691/.conda/envs/denovo_asm/lib/python2.7/site-packages/pypeflow/io.py", line 29, in syscall
    raise Exception(msg)
Exception: Call '/bin/bash user_script.sh' returned 256.
+++ pwd
++ echo 'FAILURE. Running top in /cephfs/scratch/7077691/Teste_Novo_Cluster/FALCON_test/0-rawreads/build (If you see -terminal database is inaccessible- you are using the python bin-wrapper, so you will not get diagnostic info. No big deal. This process is crashing anyway.)'
++ rm -f top.txt
++ which python
++ which top
++ env -u LD_LIBRARY_PATH top -b -n 1
++ env -u LD_LIBRARY_PATH top -b -n 1
++ pstree -apl

real	13m9.138s
user	8m50.571s
sys	1m11.890s
+ finish
+ echo 'finish code: 1'
```

**To Reproduce**
My config file is:
```
#### Input for FALCON 14/1/19
[General]
input_fofn=/scratch/7077691/Teste_Novo_Cluster/FALCON_test/input.fofn
input_type=raw
pa_DBdust_option=true
pa_fasta_filter_option=streamed-median
target=assembly
skip_checks=False
LA4Falcon_preload=false


#### Data Partitioning
pa_DBsplit_option=-x500 -s50
ovlp_DBsplit_option=-x500 -s50

#### Repeat Masking
pa_HPCTANmask_option=
pa_REPmask_code=0,300;0,300;0,300

####Pre-assembly
genome_size=0
seed_coverage=30
length_cutoff=1000    
pa_HPCdaligner_option=-v -B128 -M24
pa_daligner_option=-e.8 -l2000 -k18 -h480 -w8 -s100
falcon_sense_option=--output-multi --min-idt 0.70 --min-cov 3 --max-n-read 400
falcon_sense_greedy=False

####Pread overlapping
ovlp_daligner_option=-e.9 -l2500 -k24 -h1024 -w6 -s100 
ovlp_HPCdaligner_option=-v -B128 -M24

####Final Assembly
overlap_filtering_setting=--max-diff 100 --max-cov 100 --min-cov 2
fc_ovlp_to_graph_option=
length_cutoff_pr=1000



[job.defaults]
job_type=slurm
pwatcher_type=blocking
JOB_QUEUE=default
MB=32768
NPROC=6
njobs=32
submit = srun --wait=0 -p SP2 -J ${JOB_NAME} -o ${JOB_STDOUT} -e ${JOB_STDERR} --mem=${MB}M --cpus-per-task=${NPROC} --time=20-00:00:0 ${JOB_SCRIPT}


[job.step.da]
NPROC=4
MB=32768
njobs=240
[job.step.la]
NPROC=4
MB=32768
njobs=240
[job.step.cns]
NPROC=8
MB=60000
njobs=240
[job.step.pda]
NPROC=4
MB=32768
njobs=240
[job.step.pla]
NPROC=4
MB=32768
njobs=240
[job.step.asm]
NPROC=20
MB=60000
njobs=1
```

**Comment by pb-cdunn** [comment]
Ah, this is the same as your comment in #30, I think. See reply there.
