### ISSUE TITLE
Consistent failures always with exit-code=256 

### ISSUE THREAD

**Issue by larskoenig-rtl** [PacificBiosciences/pbbioconda#89]
**Operating system**
PRETTY_NAME="CentOS Linux 7 (Core)"
3.10.0-514.6.1.el7.x86_64
conda version: 4.5.12

**Package name**
unknown

**Conda environment**
```
# packages in environment at /home/bio/miniconda2/envs/denovo_asm:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                py27_1003    conda-forge
avro-python2              1.8.2                      py_1    bioconda
bcftools                  1.9                  h47928c2_1    bioconda
bedtools                  2.27.1               he860b03_3    bioconda
blas                      1.0                         mkl
blasr                     5.3.2                h82bacf8_5    bioconda
blasr_libcpp              5.3.1                h82bacf8_4    bioconda
bwa                       0.7.17               h84994c4_4    bioconda
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
certifi                   2018.11.29            py27_1000    conda-forge
cffi                      1.11.5          py27h9745a5d_1001    conda-forge
chardet                   3.0.4                 py27_1003    conda-forge
cryptography              2.5              py27hb7f436b_0    conda-forge
curl                      7.64.0               h646f8bb_0    conda-forge
cython                    0.29.4           py27hf484d3e_0    conda-forge
decorator                 4.3.2                      py_0    conda-forge
enum34                    1.1.6                 py27_1001    conda-forge
future                    0.17.1                py27_1000    conda-forge
genomicconsensus          2.3.2                    py27_3    bioconda
h5py                      2.8.0           py27hfb8609e_1004    conda-forge
hdf5                      1.10.3            hba1933b_1001    conda-forge
htslib                    1.9                  h47928c2_5    bioconda
idna                      2.8                   py27_1000    conda-forge
intel-openmp              2019.1                      144
ipaddress                 1.0.22                     py_1    conda-forge
iso8601                   0.1.12                     py_1    conda-forge
krb5                      1.16.3            hc83ff2d_1000    conda-forge
libcurl                   7.64.0               h01ee5af_0    conda-forge
libdeflate                1.0                  h14c3975_1    bioconda
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             hf484d3e_1005    conda-forge
libgcc-ng                 7.3.0                hdf63c60_0    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libssh2                   1.8.0             h1ad7b7a_1003    conda-forge
libstdcxx-ng              7.3.0                hdf63c60_0    conda-forge
linecache2                1.0.0                      py_1    conda-forge
minimap2                  2.15                 h84994c4_1    bioconda
mkl                       2019.1                      144
mkl_fft                   1.0.10           py27h14c3975_1    conda-forge
mkl_random                1.0.2            py27h637b7d7_2    conda-forge
mummer4                   4.0.0beta2      pl526hfc679d8_3    bioconda
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.2                        py_1    conda-forge
nim-falcon                0.0.0                         0    bioconda
numpy                     1.15.4           py27h7e9f1db_0
numpy-base                1.15.4           py27hde5b4d6_0
openssl                   1.0.2p            h14c3975_1002    conda-forge
pb-assembly               0.0.4                    py27_3    bioconda
pb-dazzler                0.0.0                h470a237_0    bioconda
pb-falcon                 0.2.5            py27hc0aa232_3    bioconda
pbalign                   0.3.2                    py27_0    bioconda
pbbam                     0.19.0               h6678c95_1    bioconda
pbcommand                 1.1.1                    py27_2    bioconda
pbcopper                  0.4.2                h02d93b8_0    bioconda
pbcore                    1.6.5                    py27_0    bioconda
pbmm2                     0.12.0               ha87ae23_0    bioconda
perl                      5.26.2            h14c3975_1001    conda-forge
pip                       19.0.1                   py27_0    conda-forge
pycparser                 2.19                       py_0    conda-forge
pyopenssl                 19.0.0                   py27_0    conda-forge
pysam                     0.15.2           py27h1671916_1    bioconda
pysocks                   1.6.8                 py27_1002    conda-forge
python                    2.7.15            h938d71a_1006    conda-forge
python-consensuscore      1.1.1            py27h02d93b8_2    bioconda
python-consensuscore2     3.1.0                    py27_2    bioconda
python-edlib              1.2.3.post1      py27h470a237_0    bioconda
python-intervaltree       3.0.2                      py_0    bioconda
python-msgpack            0.5.6            py27h470a237_0    bioconda
python-sortedcontainers   2.1.0                      py_0    bioconda
pytz                      2018.9                     py_0    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
requests                  2.21.0                py27_1000    conda-forge
samtools                  1.9                  h57cc563_6    bioconda
setuptools                40.7.3                   py27_0    conda-forge
six                       1.12.0                py27_1000    conda-forge
sqlite                    3.26.0            h67949de_1000    conda-forge
tk                        8.6.9             h84994c4_1000    conda-forge
traceback2                1.4.0                    py27_0    conda-forge
unittest2                 1.1.0                      py_0    conda-forge
urllib3                   1.24.1                py27_1000    conda-forge
wheel                     0.32.3                   py27_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
```

**Describe the bug**
When trying to run assembly, inconsistent errors, initially appear to be issues with the heartbeat files. Some files complete successfully. Others fail fairly quickly during tan-split step. Total data set is 15 cells, but as part of troubleshooting, I have been breaking the set into smaller subsets of 2, 3, 4, 5 cells to test if it is system resource related. I have also tried use bam2fastx instead of SMRT Link to generate the input fasta, single cells, all cells, and nothing has worked.

**Error message**
```
[INFO]recently_satisfied:
set([Node(0-rawreads/build)])
[INFO]Num satisfied in this iteration: 1
[INFO]Num still unsatisfied: 1
[INFO]About to submit: Node(0-rawreads/tan-split)
[INFO] starting job Job(jobid='P7a76247ac20297', cmd='/bin/bash run.sh', rundir='/mnt/grid/Luce_5856/0-rawreads/tan-split', options={'pwatcher_type': 'fs_based', 'use_tmpdir': False, 'MB': 4000, 'job_type': 'local', 'submit': 'bash -C ${CMD} >| ${STDOUT_FILE} 2>| ${STDERR_FILE}', 'NPROC': 1, 'njobs': '8'}) w/ job_type=LOCAL
[INFO]dir: '/mnt/grid/Luce_5856/mypwatcher/jobs/P7a76247ac20297'
CALL:
 '/bin/bash /mnt/grid/Luce_5856/mypwatcher/wrappers/run-P7a76247ac20297.bash 1>|stdout 2>|stderr & '
[INFO]pid=21649 pgid=21649 sub-pid=22190
[INFO]Submitted backgroundjob=MetaJobLocal(MetaJob(job=Job(jobid='P7a76247ac20297', cmd='/bin/bash run.sh', rundir='/mnt/grid/Luce_5856/0-rawreads/tan-split', options={'pwatcher_type': 'fs_based', 'use_tmpdir': False, 'MB': 4000, 'job_type': 'local', 'submit': 'bash -C ${CMD} >| ${STDOUT_FILE} 2>| ${STDERR_FILE}', 'NPROC': 1, 'njobs': '8'}), lang_exe='/bin/bash'))
[ERROR]Task Node(0-rawreads/tan-split) failed with exit-code=256
[ERROR]Some tasks are recently_done but not satisfied: set([Node(0-rawreads/tan-split)])
[ERROR]ready: set([])
        submitted: set([])
[ERROR]Failed to kill job for heartbeat 'heartbeat-P8404878de35533' (which might mean it was already gone): IOError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/home/bio/miniconda2/envs/denovo_asm/lib/python2.7/site-packages/pwatcher/fs_based.py", line 612, in delete_heartbeat
    bjob.kill(state, heartbeat)
  File "/home/bio/miniconda2/envs/denovo_asm/lib/python2.7/site-packages/pwatcher/fs_based.py", line 274, in kill
    with open(heartbeat_fn) as ifs:
IOError: [Errno 2] No such file or directory: '/mnt/grid/Luce_5856/mypwatcher/heartbeats/heartbeat-P8404878de35533'
[ERROR]Failed to kill job for heartbeat 'heartbeat-P7a76247ac20297' (which might mean it was already gone): IOError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/home/bio/miniconda2/envs/denovo_asm/lib/python2.7/site-packages/pwatcher/fs_based.py", line 612, in delete_heartbeat
    bjob.kill(state, heartbeat)
  File "/home/bio/miniconda2/envs/denovo_asm/lib/python2.7/site-packages/pwatcher/fs_based.py", line 274, in kill
    with open(heartbeat_fn) as ifs:
IOError: [Errno 2] No such file or directory: '/mnt/grid/Luce_5856/mypwatcher/heartbeats/heartbeat-P7a76247ac20297'
Traceback (most recent call last):
  File "/home/bio/miniconda2/envs/denovo_asm/bin/fc_run", line 11, in <module>
    load_entry_point('falcon-kit==1.2.5', 'console_scripts', 'fc_run')()
  File "/home/bio/miniconda2/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 726, in main
    main1(argv[0], args.config, args.logger)
  File "/home/bio/miniconda2/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 76, in main1
    input_fofn_fn=input_fofn_fn,
  File "/home/bio/miniconda2/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/mains/run1.py", line 242, in run
    dist=Dist(NPROC=4, MB=4000, job_dict=config['job.step.da']),
  File "/home/bio/miniconda2/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/pype.py", line 106, in gen_parallel_tasks
    wf.refreshTargets()
  File "/home/bio/miniconda2/envs/denovo_asm/lib/python2.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 278, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/home/bio/miniconda2/envs/denovo_asm/lib/python2.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 362, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: set([Node(0-rawreads/tan-split)])
```

**To Reproduce**
I get similar behavior when running the F1_bull test set. That set crashes at 0-rawreads/build with a similar error: 
```
[ERROR]Task Node(0-rawreads/build) failed with exit-code=256
[ERROR]Some tasks are recently_done but not satisfied: set([Node(0-rawreads/build)])
[ERROR]ready: set([])
        submitted: set([])
[ERROR]Failed to kill job for heartbeat 'heartbeat-P186ecc91d79e2f' (which might mean it was already gone): IOError(2, 'No such file or directory')
```

The 200k test set assembles correctly.

**Expected behavior**
I expect the system to be able to perform the preads correctly for a subset of 2 cells, which worked with another subset earlier.

**Comment by pb-cdunn** [comment]
If there is an error in a task, you need to find the task-specific stderr (somewhere under `0-rawreads/build` e.g.). I'm not sure about that.

On the "heartbeat" problem, `fs_based` (filesystem-based process-watcher) is very difficult to support on disparate systems. Try
```
pwatcher_type = blocking
job_type = string
submit = ...
```
See https://github.com/PacificBiosciences/pypeFLOW/wiki/configuration
