### ISSUE TITLE
arrow IOError: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by Michelledemers** [PacificBiosciences/pbbioconda#90]
**Operating system**
CentOS release 6.9 (Final)

**Package name**
anaconda2 v5.0.1 / arrow

**Conda environment**
```
# packages in environment at /usr/local/anaconda2/5.0.1:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py27_0  
alabaster                 0.7.12                     py_0    conda-forge
anaconda                  custom           py27h4a00acb_0  
anaconda-client           1.7.1                      py_0    conda-forge
anaconda-navigator        1.9.6                    py27_0  
anaconda-project          0.8.2                      py_1    conda-forge
arrow                     0.12.1                py27_1002    conda-forge
asn1crypto                0.24.0                py27_1003    conda-forge
astroid                   1.6.5                    py27_0    conda-forge
astropy                   2.0.9                    py27_0    conda-forge
atk                       2.25.90           hf2eb9ee_1001    conda-forge
atomicwrites              1.2.1                      py_0    conda-forge
attrs                     18.2.0                     py_0    conda-forge
avro-python2              1.8.2                      py_1    bioconda
babel                     2.6.0                      py_1    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.5                        py_1    conda-forge
backports.os              0.1.1                 py27_1000    conda-forge
backports.shutil_get_terminal_size 1.0.0                      py_3    conda-forge
backports_abc             0.5                        py_1    conda-forge
bam2fastx                 1.3.0                h4ef8376_6    bioconda
bax2bam                   0.0.9                h82bacf8_5    bioconda
bcftools                  1.9                  h4da6232_0    bioconda
beautifulsoup4            4.7.1                 py27_1001    conda-forge
bitarray                  0.8.3           py27h14c3975_1000    conda-forge
bkcharts                  0.2                      py27_0    conda-forge
blas                      1.0                         mkl  
blasr                     5.3.2                h82bacf8_5    bioconda
blasr_libcpp              5.3.1                h82bacf8_4    bioconda
blaze                     0.11.3           py27h5f341da_0  
bleach                    3.1.0                    pypi_0    pypi
blinker                   1.4                        py_1    conda-forge
bokeh                     1.0.4                 py27_1000    conda-forge
boto                      2.49.0                     py_0    conda-forge
boto3                     1.9.86                     py_0    conda-forge
botocore                  1.12.86                    py_0    conda-forge
bottleneck                1.2.1           py27h3010b51_1001    conda-forge
bz2file                   0.98                       py_0    conda-forge
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
cairo                     1.14.12           h80bd089_1005    conda-forge
cdecimal                  2.3             py27h14c3975_1000    conda-forge
certifi                   2018.11.29            py27_1000    conda-forge
cffi                      1.11.5          py27h9745a5d_1001    conda-forge
chardet                   3.0.4                 py27_1003    conda-forge
click                     7.0                        py_0    conda-forge
cloudpickle               0.6.1                      py_0    conda-forge
clyent                    1.2.2                      py_1    conda-forge
colorama                  0.4.1                      py_0    conda-forge
conda                     4.6.1                    py27_0    conda-forge
conda-build               3.17.8                   py27_0    conda-forge
conda-env                 2.6.0                         1    conda-forge
conda-verify              3.1.1                 py27_1000    conda-forge
configparser              3.7.1                    py27_0    conda-forge
contextlib2               0.5.5                      py_2    conda-forge
cryptography              2.3.1           py27hb7f436b_1000    conda-forge
curl                      7.63.0            h646f8bb_1000    conda-forge
cycler                    0.10.0                     py_1    conda-forge
cython                    0.29.3           py27hf484d3e_0    conda-forge
cytoolz                   0.9.0.1         py27h14c3975_1001    conda-forge
dask                      1.1.0                      py_1    conda-forge
dask-core                 1.1.0                      py_0    conda-forge
datashape                 0.5.4                    py27_0    conda-forge
dbus                      1.13.0            h4e0c4b3_1000    conda-forge
decorator                 4.3.2                      py_0    conda-forge
distributed               1.25.2                py27_1000    conda-forge
docutils                  0.14                  py27_1001    conda-forge
entrypoints               0.3                   py27_1000    conda-forge
enum34                    1.1.6                 py27_1001    conda-forge
et_xmlfile                1.0.1                    py27_0    conda-forge
expat                     2.2.5             hf484d3e_1002    conda-forge
fastcache                 1.0.2           py27h14c3975_1001    conda-forge
filelock                  3.0.10                     py_0    conda-forge
flask                     1.0.2                      py_2    conda-forge
flask-cors                3.0.7                      py_0    conda-forge
fontconfig                2.13.1            h2176d3f_1000    conda-forge
freetype                  2.9.1             h94bbf69_1005    conda-forge
funcsigs                  1.0.2                      py_3    conda-forge
functools32               3.2.3.2                    py_3    conda-forge
future                    0.17.1                py27_1000    conda-forge
futures                   3.2.0                 py27_1000    conda-forge
gdk-pixbuf                2.36.12           h4f1c04b_1001    conda-forge
genomicconsensus          2.3.2                    py27_3    bioconda
gensim                    3.5.0           py27h04863e7_1000    conda-forge
get_terminal_size         1.0.0                haa9412d_0  
gettext                   0.19.8.1          h9745a5d_1001    conda-forge
gevent                    1.3.7            py27h14c3975_0    conda-forge
glib                      2.56.2            had28632_1001    conda-forge
glob2                     0.6                        py_0    conda-forge
gmp                       6.1.2             hf484d3e_1000    conda-forge
gmpy2                     2.0.8           py27hb20f59a_1002    conda-forge
gobject-introspection     1.56.1          py27h9e29830_1001    conda-forge
graphite2                 1.3.13            hf484d3e_1000    conda-forge
greenlet                  0.4.13                   py27_0    conda-forge
grin                      1.2.1                   py_1001    conda-forge
gst-plugins-base          1.12.5            h3865690_1000    conda-forge
gstreamer                 1.12.5            h0cc0488_1000    conda-forge
gtk2                      2.24.31           h5baeb44_1000    conda-forge
h5py                      2.8.0           py27hfb8609e_1004    conda-forge
harfbuzz                  1.9.0             he243708_1001    conda-forge
hdf5                      1.10.3            hba1933b_1001    conda-forge
heapdict                  1.0.0                 py27_1000    conda-forge
html5lib                  1.0.1                      py_0    conda-forge
htslib                    1.9                  hc238db4_4    bioconda
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.8                   py27_1000    conda-forge
imageio                   2.4.1                 py27_1000    conda-forge
imagesize                 1.1.0                      py_0    conda-forge
importlib_metadata        0.6                      py27_0    conda-forge
intel-openmp              2019.1                      144  
ipaddress                 1.0.22                     py_1    conda-forge
ipykernel                 4.10.0                   py27_1    conda-forge
ipython                   5.8.0                    py27_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.2                      py_0    conda-forge
iso8601                   0.1.12                     py_1    conda-forge
isort                     4.3.4                 py27_1000    conda-forge
isoseq3                   3.1.0                         0    bioconda
itsdangerous              1.1.0                      py_0    conda-forge
jbig                      2.1               h14c3975_2001    conda-forge
jdcal                     1.4                        py_1    conda-forge
jedi                      0.13.2                py27_1000    conda-forge
jinja2                    2.10                       py_1    conda-forge
jmespath                  0.9.3                      py_1    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
jsonschema                3.0.0a3               py27_1000    conda-forge
jupyter                   1.0.0                      py_1    conda-forge
jupyter_client            5.2.4                      py_1    conda-forge
jupyter_console           5.2.0                    py27_1    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyterlab                0.33.12                  py27_0    conda-forge
jupyterlab_launcher       0.11.2                     py_0    conda-forge
kiwisolver                1.0.1           py27h6bb024c_1002    conda-forge
krb5                      1.16.3            hc83ff2d_1000    conda-forge
lazy-object-proxy         1.3.1           py27h14c3975_1000    conda-forge
libarchive                3.3.3             ha149a29_1000    conda-forge
libcurl                   7.63.0            h01ee5af_1000    conda-forge
libdeflate                1.0                  h470a237_0    bioconda
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             hf484d3e_1005    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 7.3.0                hdf63c60_0    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libgpuarray               0.7.6             h14c3975_1003    conda-forge
libiconv                  1.15              h14c3975_1004    conda-forge
liblief                   0.9.0                h7725739_2  
libopenblas               0.3.3                h5a2b251_3  
libpng                    1.6.36            h84994c4_1000    conda-forge
libsodium                 1.0.16            h14c3975_1001    conda-forge
libssh2                   1.8.0             h1ad7b7a_1003    conda-forge
libstdcxx-ng              7.3.0                hdf63c60_0    conda-forge
libtiff                   4.0.10            h9022e91_1002    conda-forge
libtool                   2.4.6             h14c3975_1002    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.8             h143f9aa_1005    conda-forge
libxslt                   1.1.32            h4785a14_1002    conda-forge
lima                      1.8.0                         0    bioconda
linecache2                1.0.0                      py_1    conda-forge
llvmlite                  0.26.0          py27hdbcaa40_1000    conda-forge
locket                    0.2.0                      py_2    conda-forge
lxml                      4.3.0           py27h23eabaa_1000    conda-forge
lzo                       2.10              h14c3975_1000    conda-forge
mako                      1.0.7                      py_1    conda-forge
markupsafe                1.1.0           py27h14c3975_1000    conda-forge
matplotlib                2.2.3            py27h8e2386c_0    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
minimap2                  2.15                 ha92aebf_0    bioconda
minorseq                  1.11.0                        1    bioconda
mistune                   0.8.4           py27h14c3975_1000    conda-forge
mkl                       2019.1                      144  
mkl-service               1.1.2            py27hb2d42c5_4  
mkl_fft                   1.0.10                   py27_0    conda-forge
mkl_random                1.0.2                    py27_0    conda-forge
more-itertools            4.3.0                 py27_1000    conda-forge
mpc                       1.1.0             hb20f59a_1006    conda-forge
mpfr                      4.0.1             ha14ba45_1000    conda-forge
mpmath                    1.1.0                      py_0    conda-forge
msgpack-python            0.6.1            py27h6bb024c_0    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
navigator-updater         0.2.1                    py27_0  
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.2                        py_1    conda-forge
nltk                      3.2.5                      py_0    conda-forge
nose                      1.3.7                 py27_1002    conda-forge
notebook                  5.7.4                 py27_1000    conda-forge
numba                     0.35.0             np113py27_10  
numexpr                   2.6.2            py27h9521900_2  
numpy                     1.15.4           py27h7e9f1db_0  
numpy-base                1.15.4           py27hde5b4d6_0  
numpydoc                  0.8.0                      py_1    conda-forge
oauthlib                  2.1.0                      py_0    conda-forge
odo                       0.5.1                      py_1    conda-forge
olefile                   0.46                       py_0    conda-forge
openblas                  0.3.3             h9ac9557_1001    conda-forge
openpyxl                  2.5.12                     py_0    conda-forge
openssl                   1.0.2p            h14c3975_1002    conda-forge
packaging                 19.0                       py_0    conda-forge
pandas                    0.24.0           py27hf484d3e_0    conda-forge
pandoc                    2.5                           1    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
pango                     1.40.14           hf0c64fd_1003    conda-forge
parso                     0.3.2                      py_0    conda-forge
partd                     0.3.9                      py_0    conda-forge
patchelf                  0.9               hf484d3e_1002    conda-forge
path.py                   11.5.0                     py_0    conda-forge
pathlib2                  2.3.3                 py27_1000    conda-forge
patsy                     0.4.1            py27hd1cf8c0_0  
pb-dazzler                0.0.0                h470a237_0    bioconda
pb-falcon                 0.2.5            py27hf50d5a6_2    bioconda
pbalign                   0.3.2                    py27_0    bioconda
pbbam                     0.19.0               h6678c95_1    bioconda
pbccs                     3.3.0                         0    bioconda
pbcommand                 1.1.1                    py27_2    bioconda
pbcopper                  0.4.2                h02d93b8_0    bioconda
pbcore                    1.6.5                    py27_0    bioconda
pbcoretools               0.2.4                    py27_3    bioconda
pblaa                     2.4.2                         1    bioconda
pbmm2                     0.12.0               ha87ae23_0    bioconda
pbsv                      2.1.1                         0    bioconda
pcre                      8.41              hf484d3e_1003    conda-forge
pep8                      1.7.1                      py_0    conda-forge
pexpect                   4.6.0                 py27_1000    conda-forge
pickleshare               0.7.5                 py27_1000    conda-forge
pillow                    5.4.1           py27h00a061d_1000    conda-forge
pip                       19.0.1                   py27_0    conda-forge
pixman                    0.34.0            h14c3975_1003    conda-forge
pkginfo                   1.5.0.1                    py_0    conda-forge
pluggy                    0.8.1                      py_0    conda-forge
ply                       3.11                       py_1    conda-forge
prometheus_client         0.5.0                      py_0    conda-forge
prompt_toolkit            1.0.15                     py_1    conda-forge
psutil                    5.4.8           py27h14c3975_1000    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                 py27_1000    conda-forge
py                        1.7.0                      py_0    conda-forge
py-lief                   0.9.0            py27h7725739_2  
pycairo                   1.18.0          py27h1b9232e_1000    conda-forge
pycodestyle               2.4.0                      py_1    conda-forge
pycosat                   0.6.3           py27h14c3975_1001    conda-forge
pycparser                 2.19                       py_0    conda-forge
pycrypto                  2.6.1           py27h14c3975_1002    conda-forge
pycurl                    7.43.0.2         py27hb7f436b_0  
pyflakes                  2.1.0                      py_0    conda-forge
pygments                  2.3.1                      py_0    conda-forge
pygpu                     0.7.6           py27h3010b51_1000    conda-forge
pyjwt                     1.7.1                      py_0    conda-forge
pylint                    1.9.2                    py27_0    conda-forge
pymbar                    3.0.3            py27h7eb728f_2    conda-forge
pyodbc                    4.0.24          py27hf484d3e_1000    conda-forge
pyopenssl                 18.0.0                py27_1000    conda-forge
pyparsing                 2.3.1                      py_0    conda-forge
pyqt                      5.6.0           py27h13b7fb3_1008    conda-forge
pyrsistent                0.14.9          py27h14c3975_1000    conda-forge
pysam                     0.15.2           py27h0380709_0    bioconda
pysocks                   1.6.8                 py27_1002    conda-forge
pytables                  3.4.2            py27h1f7bffc_2  
pytest                    4.1.1                 py27_1000    conda-forge
python                    2.7.15            h938d71a_1006    conda-forge
python-consensuscore      1.1.1            py27h02d93b8_2    bioconda
python-consensuscore2     3.1.0                    py27_2    bioconda
python-crfsuite           0.9.6           py27h6bb024c_1000    conda-forge
python-dateutil           2.7.5                      py_0    conda-forge
python-edlib              1.2.3.post1      py27h470a237_0    bioconda
python-intervaltree       3.0.2                      py_0    bioconda
python-libarchive-c       2.8                   py27_1004    conda-forge
python-msgpack            0.5.6            py27h470a237_0    bioconda
python-sortedcontainers   2.1.0                      py_0    bioconda
pytz                      2018.9                     py_0    conda-forge
pywavelets                1.0.1           py27h3010b51_1000    conda-forge
pyyaml                    3.13            py27h14c3975_1001    conda-forge
pyzmq                     17.1.2          py27h6afc9c9_1001    conda-forge
qt                        5.6.2             hbe13537_1012    conda-forge
qtawesome                 0.5.5              pyh8a2030e_0    conda-forge
qtconsole                 4.4.3                      py_0    conda-forge
qtpy                      1.6.0              pyh8a2030e_0    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
requests                  2.21.0                py27_1000    conda-forge
requests-oauthlib         1.0.0                      py_1    conda-forge
rope                      0.10.7                     py_1    conda-forge
ruamel_yaml               0.15.71         py27h14c3975_1000    conda-forge
s3transfer                0.1.13                py27_1001    conda-forge
samtools                  1.9                  h8ee4bcc_1    bioconda
scandir                   1.9.0           py27h14c3975_1000    conda-forge
scikit-image              0.13.0           py27h06cb35d_1  
scikit-learn              0.20.2           py27hd81dba3_0  
scipy                     1.2.0            py27h7c811a0_0  
seaborn                   0.8.0            py27h9d2aaa1_0  
send2trash                1.5.0                      py_0    conda-forge
setuptools                40.7.0                   py27_0    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
singledispatch            3.4.0.3               py27_1000    conda-forge
sip                       4.18.1          py27hf484d3e_1000    conda-forge
six                       1.12.0                py27_1000    conda-forge
smart_open                1.8.0                      py_0    conda-forge
snowballstemmer           1.2.1                      py_1    conda-forge
sortedcollections         1.1.1                      py_0    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
soupsieve                 1.7.1                 py27_1000    conda-forge
sphinx                    1.8.3                 py27_1000    conda-forge
sphinxcontrib             1.0                      py27_1  
sphinxcontrib-websupport  1.1.0                      py_1    conda-forge
spyder                    3.3.2                 py27_1001    conda-forge
spyder-kernels            0.3.0                 py27_1001    conda-forge
sqlalchemy                1.2.16          py27h14c3975_1000    conda-forge
sqlite                    3.26.0            h67949de_1000    conda-forge
ssl_match_hostname        3.5.0.1               py27_1002    conda-forge
statsmodels               0.8.0            py27hc87d62d_0  
subprocess32              3.5.3            py27h14c3975_0    conda-forge
sympy                     1.3                   py27_1000    conda-forge
tblib                     1.3.2                      py_1    conda-forge
terminado                 0.8.1                 py27_1001    conda-forge
testpath                  0.4.2                 py27_1000    conda-forge
tk                        8.6.9             h84994c4_1000    conda-forge
toolz                     0.9.0                      py_1    conda-forge
tornado                   5.1.1           py27h14c3975_1000    conda-forge
tqdm                      4.29.1                     py_0    conda-forge
traceback2                1.4.0                    py27_0    conda-forge
traitlets                 4.3.2                 py27_1000    conda-forge
twython                   3.7.0                      py_0    conda-forge
typing                    3.6.6                 py27_1000    conda-forge
unicodecsv                0.14.1                     py_1    conda-forge
unittest2                 1.1.0                      py_0    conda-forge
unixodbc                  2.3.7             h227dcee_1000    conda-forge
urllib3                   1.24.1                py27_1000    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  0.14.1                     py_0    conda-forge
wheel                     0.32.3                   py27_0    conda-forge
widgetsnbextension        3.4.2                 py27_1000    conda-forge
wrapt                     1.11.1           py27h14c3975_0    conda-forge
wurlitzer                 1.0.2                 py27_1000    conda-forge
xlrd                      1.2.0                      py_0    conda-forge
xlsxwriter                1.1.2                      py_0    conda-forge
xlwt                      1.3.0                      py_1    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.9             h14c3975_1004    conda-forge
xorg-libsm                1.2.3             h4937e3b_1000    conda-forge
xorg-libx11               1.6.6             h14c3975_1000    conda-forge
xorg-libxau               1.0.8             h14c3975_1006    conda-forge
xorg-libxdmcp             1.1.2             h14c3975_1007    conda-forge
xorg-libxext              1.3.3             h14c3975_1004    conda-forge
xorg-libxrender           0.9.10            h14c3975_1002    conda-forge
xorg-libxt                1.1.5             h14c3975_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.1.7             h14c3975_1001    conda-forge
zeromq                    4.2.5             hf484d3e_1006    conda-forge
zict                      0.1.3                      py_0    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
zstd                      1.3.3                         1    conda-forge
```

**Describe the bug**

I am running arrow using output from pbmm2 (version C), using the *.xml output to run with arrow. I have arrow working just fine with my other genome of the same species, so this error is only specific to one of my genomes. The job aborted right around the time when I expected the program to finish computing. Here is the code I used for arrow, 

**Error message**
```
Process ResultCollectorProcess-9:
Traceback (most recent call last):
  File "/usr/local/anaconda2/5.0.1/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/local/anaconda2/5.0.1/lib/python2.7/site-packages/GenomicConsensus/ResultCollector.py", line 44, in run
    self._run()
  File "/usr/local/anaconda2/5.0.1/lib/python2.7/site-packages/GenomicConsensus/ResultCollector.py", line 34, in _run
    self.onFinish()
  File "/usr/local/anaconda2/5.0.1/lib/python2.7/site-packages/GenomicConsensus/ResultCollector.py", line 84, in onFinish
    if self.fastaWriter: self.fastaWriter.close()
  File "/usr/local/anaconda2/5.0.1/lib/python2.7/site-packages/pbcore/io/base.py", line 78, in close
    self.file.close()
IOError: [Errno 5] Input/output error
Child process exited with exitcode=1.  Aborting.
Aborting
```
**To Reproduce**
I could possibly share a BAM file if necessary.

**Expected behavior**
I expect the genome to be polished with my raw BAM reads and output a .gff file and a consensus .fasta file.

**Comment by armintoepfer** [comment]
Hey Michelle, thank you for reporting. Would be great if you can share a minimal breaking example. If you are uncomfortable posting said data here, please write me a mail atoepfer ât pacb.com

Armin

**Comment by Michelledemers** [comment]
Hi Armin,

I should close the case on GitHub, turns out it was actually a problem on our end with some fixes being made with our HPC that interfered with the running of our program. Thanks for following up though, sorry about that!

Cheers!

Michelle

Michelle Demers | PhD Candidate
Plant Breeding Institute | School of Life and Environmental Science

THE UNIVERSITY OF SYDNEY
107 Cobbitty Rd | Cobbitty | NSW | 2570
michelle.demers@sydney.edu.au<mailto:michelle.demers@sydney.edu.au>




On 13 Feb 2019, at 10:21 pm, Armin Töpfer <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey Michelle, thank you for reporting. Would be great if you can share a minimal breaking example. If you are uncomfortable posting said data here, please write me a mail atoepfer ât pacb.com<http://pacb.com>

Armin
